### ISSUE TITLE
implement view(::DataFrame, ...) to support broadcasted assignment

### ISSUE THREAD

**Issue by stevengj** [JuliaData/DataFrames.jl#1019]
In Julia 0.5, an assignment like `a[i] .= ...` gets converted by the parser to `broadcast!(identity, view(a, i), ...)`, and moreover the `broadcast!` loop is automatically merged with broadcast loops from nested "dot" calls (see JuliaLang/julia#17510 and JuliaLang/julia#17546).

It would be nice to support this if `a` is a DataFrame.  My understanding is that it will currently throw an error because `view` is not implemented for a DataFrame.

I haven't used DataFrames much, but if I understand it correctly then it sounds sufficient to define:

``` jl
Base.view(a::DataFrame, key) = a[key]
Base.view(a::DataFrame, key, indices...) = view(a[key], indices...)
```

**Comment by quinnj** [comment]
Good up for grabs issue.

**Comment by stevengj** [comment]
Actually, `.=` might work with dataframes in many cases already because `broadcast!` was updated to use a [dotview function](https://github.com/JuliaLang/julia/blob/2bdcd5f2ccd2694166c73c0f978c7cb5d60aedc0/base/broadcast.jl#L531-L539) that defaults to `getindex` (so that it works as-is with things like dictionaries of array and in general anything where `getindex` can return a mutable object).

**Comment by bkamins** [comment]
Done in 0.19.0 (+ some patching up pending in https://github.com/JuliaData/DataFrames.jl/pull/1890)
