### ISSUE TITLE
Update docstrings to new conventions

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#1093]
We should improve our docstrings by adapting them to new conventions [from the Julia manual](http://docs.julialang.org/en/latest/manual/documentation/). In particular (not all of these steps need to be done at the same time, though):
- give the signature first with a four-space indent
- merge the `Details` section with the general description (in a separate paragraph if necessary)
- only use an `# Arguments` section when there are many of them; mention the meaning of arguments in the description for simple cases
- only use a `# Result` section when really useful
- transform examples into doctests
- document return types as `::T` in the signature only when useful, and remove `# -> T` comments in the code

**Comment by bkamins** [comment]
@nalimilan - I think it is done (or I have missed something?)

**Comment by nalimilan** [comment]
Maybe some details could still be cleaned up, but I guess you did most of it, yes!
