### ISSUE TITLE
Implement a from_records constructor

### ISSUE THREAD

**Issue by grst** [JuliaData/DataFrames.jl#1191]
I am missing a way to construct a direct way to construct a DataFrame from a list of tuples, as I would do in python with [`pandas.DataFrame.from_records`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.from_records.html). 

Input data:

`records = [("A", 1), ("B", 2), ("C", `3)]`

Desired DataFrame: 
```
│ Row │ x1  │ x2 │
├─────┼─────┼────┤
│ 1   │ "A" │ 1  │
│ 2   │ "B" │ 2  │
│ 3   │ "C" │ 3  │
```

I [now know](https://stackoverflow.com/questions/44164154/how-to-create-a-dataframe-from-records-rows) that I can do something like

```
n = length(records[1])
DataFrame([[r[i] for r in records] for i=1:n],[Symbol("x$(i)") for i=1:n])
```
but this feels somehow cumbersome...

**Comment by quinnj** [comment]
I've wanted this as well.

**Comment by nalimilan** [comment]
Maybe we could implement this as `DataFrame(::AbstractArray{<:Tuple})` constructor? Or could that conflict with other meanings of this signature?

**Comment by ararslan** [comment]
If I'm not mistaken, constructing a `DataFrame` from an array of arrays treats the interior arrays as columns, whereas in this proposal the tuples would be treated as rows. That's kind of weirdly inconsistent.

**Comment by grst** [comment]
How about simply supporting a `DataFrame(::Zip)` constructor? 
Then we could do `DataFrame(zip(records...))` which would not feel too awkward for me.

**Comment by nalimilan** [comment]
Good point. Special-casing `Zip` would be weird, but accepting any iterator of columns (including `zip`) would be a nice generalization of the existing `DataTable(columns::Vector{Any}, names::Vector{Symbol})` constructor.

**Comment by nalimilan** [comment]
@quinnj How does this issue stand regarding the new Tables.jl constructors?

**Comment by bkamins** [comment]
We now allow it and generate column names with numbers as symbols due to Tabels.jl functionality.
