### ISSUE TITLE
filter doesn't work with eachrow iterator

### ISSUE THREAD

**Issue by cjprybol** [JuliaData/DataFrames.jl#1235]
```julia
julia> using DataFrames

julia> df = DataFrame(x = 1:10)
10×1 DataFrames.DataFrame
│ Row │ x  │
├─────┼────┤
│ 1   │ 1  │
│ 2   │ 2  │
│ 3   │ 3  │
│ 4   │ 4  │
│ 5   │ 5  │
│ 6   │ 6  │
│ 7   │ 7  │
│ 8   │ 8  │
│ 9   │ 9  │
│ 10  │ 10 │

julia> # I would expect this
       filter(row -> row[:x] < 5, eachrow(df))
WARNING: filter(flt, itr) is deprecated, use Iterators.filter(flt, itr) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] filter(::Function, ::DataFrames.DFRowIterator{DataFrames.DataFrame}) at ./deprecated.jl:57
 [3] eval(::Module, ::Any) at ./boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [5] macro expansion at ./REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
Base.Iterators.Filter{##1#2,DataFrames.DFRowIterator{DataFrames.DataFrame}}(#1, DataFrames.DFRowIterator{DataFrames.DataFrame}(10×1 DataFrames.DataFrame
│ Row │ x  │
├─────┼────┤
│ 1   │ 1  │
│ 2   │ 2  │
│ 3   │ 3  │
│ 4   │ 4  │
│ 5   │ 5  │
│ 6   │ 6  │
│ 7   │ 7  │
│ 8   │ 8  │
│ 9   │ 9  │
│ 10  │ 10 │))

julia> # to produce the same output as this
       df[df[:x] .< 5, :]
4×1 DataFrames.DataFrame
│ Row │ x │
├─────┼───┤
│ 1   │ 1 │
│ 2   │ 2 │
│ 3   │ 3 │
│ 4   │ 4 │
```

noticed in https://github.com/JuliaData/DataFrames.jl/issues/1234

**Comment by nalimilan** [comment]
I don't think that's how it's supposed to work. As the deprecation warning makes it clear, `filter` is a generic method on iterators which skips elements which do not match a predicate. There's absolutely no notion of merging elements into a container like a `DataFrame`.

Though once the deprecation is removed, we could imagine using `Base.filter` (as opposed to `Base.Iterators.filter` for that). Not sure how natural it would be that filtering an iterator would return a `DataFrame` rather than another iterator. Also note that Query or DataFrameMeta make this quite easy and more concise.

**Comment by cjprybol** [comment]
That makes sense. I got tripped up by how the output was being printed. I saw the full 10-row DataFrame printed as part of the eachrow iterator and thought that the filtering wasn't working at all. But I just needed to call collect

```julia
julia> collect(filter(row -> row[:x] < 5, eachrow(df)))
4-element Array{Any,1}:
 DataFrameRow (row 1)
x  1

 DataFrameRow (row 2)
x  2

 DataFrameRow (row 3)
x  3

 DataFrameRow (row 4)
x  4
```

I had expected the output to collect itself back into a DataFrame because I was used to this behavior with ranges:
```julia
julia> filter(i -> i < 5, 1:10)
4-element Array{Int64,1}:
 1
 2
 3
 4

```

but ranges are <: AbstractArray, and not iterators, so that makes sense too.

Is there a way to collect DataFrameRows back into a DataFrame? If there's a way to do that then I think we have all of the necessary bases covered here.

**Comment by nalimilan** [comment]
> Is there a way to collect DataFrameRows back into a DataFrame? If there's a way to do that then I think we have all of the necessary bases covered here.

Not that I know of, but I'm not sure where to draw the line between standard functions we should provide and more complex operations that would better be handled with Query or DataFramesMeta. A naive function converting a list of `DataFrameRow` objects into a `DataFrame` is going to be very inefficient.
