### ISSUE TITLE
how to select the mulit-row with @where  or  others?

### ISSUE THREAD

**Issue by nizhizhen** [JuliaData/DataFrames.jl#1238]
e.g. dataframe a = DataFrames.DataFrame
│ Row │ variable │ value │ Sites │
├─────┼──────────┼──────────┼──────────┤
│ 1 │ MFB_PM25 │ 1.7166 │ "x1142A" │
│ 2 │ MFB_PM25 │ -13.8486 │ "x1143A" │
│ 3 │ MFB_PM25 │ 11.2938 │ "x1144A" │
│ 4 │ MFB_PM25 │ -8.32452 │ "x1145A" │

I want to select the rows of x1143A and x1144A in Sites
how to code it .

@where(a, :Sites.== ???

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
