### ISSUE TITLE
Remove Query.jl from Query frameworks

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFrames.jl#1255]
I thought Qeury.jl doesn't use Union{T, Null} to represent null values, shouldn't that be removed from the latest doc?

**Comment by cjprybol** [comment]
@quinnj has been working to on it in https://github.com/davidanthoff/Query.jl/pull/155

**Comment by quinnj** [comment]
Query is based on IterableTables, which even now supports conversions between various table types and their own ways of representing missingness, so it's still very much relevant to DataFrame docs.
