### ISSUE TITLE
Make subDataFrame deletable and give fields to it.

### ISSUE THREAD

**Issue by alberthaoh** [JuliaData/DataFrames.jl#1263]
Trying to use unique! over subDataFrame, and failed. The problem came as no columns field in subDataFrame that is needed in delete!.  Please consider add more fields to subDataFrame.

**Comment by cjprybol** [comment]
Thanks for filing this! Copying some notes here from the Slack discussion, we need to implement a `copy` function that will make a new DataFrame from the SubDataFrame that make these functions easier to use. Something like
```julia
delete!(sdf::SubDataFrame, args...) = delete!(copy(sdf), args...)
unique!(sdf::SubDataFrame, args...) = unique!(copy(sdf), args...)
```

would probably make sense to do this for all mutating functions

**Comment by nalimilan** [comment]
Hmm, no, if you call `delete!` you don't want to modify a copy, nor to allocate one. That could be really unexpected (large memory use).

Base doesn't currently allow any mutating operations like `pop!` or `deleteat!` on `SubArray`, so there's no model to follow. But there could be two meanings:
1) remove elements from the parent and adjust the view to reflect the new state
2) only adjust the view and leave the parent as-is

1) sounds more consistent with the fact that modifying an entry in a view also modifies the parent (by definition). We could file an issue in Base to discuss the best policy in general.

**Comment by alberthaoh** [comment]
@nalimilan thx that's good realization of the problem. The only case one needs mutating operations on ```SubArray``` is really case 2, and I think one should not be able to change parent by changing its descendants. ```unique``` works for ```SubArray```, so actually no problem at all if we stick this already implied policy. But still add fields to ```SubDataFrame```, ```parent.columns``` is not giving column names. and need a way to convert it into DataFrame.

**Comment by nalimilan** [comment]
> But still add fields to SubDataFrame, parent.columns is not giving column names. and need a way to convert it into DataFrame.

Do you mean we should the `names` method to work with `SubDataFrames`?

**Comment by alberthaoh** [comment]
That's right.

**Comment by nalimilan** [comment]
`names` works now:
```julia
julia> names(view(DataFrame(x=1:2), 1))
1-element Array{Symbol,1}:
 :x

```
