### ISSUE TITLE
Allow setting ENV["LINES"] to restrict number of rows printed of DataFrames

### ISSUE THREAD

**Issue by cjprybol** [JuliaData/DataFrames.jl#1264]
So far this has only come up as an issue for writing concise doctests, but we support restricting the number of columns with `ENV["COLUMNS"]` so this seems consistent with what we already are trying to support.

See [this thread](https://github.com/JuliaData/DataFrames.jl/pull/1252/files/d0b161288ec5a0dfd3135d4336ee15e7595638af#r145217291) for more information

**Comment by nalimilan** [comment]
As I noted on the thread, I don't think that's a problem with `DataFrame` methods at all, it's due to how `displaysize(STDOUT)` works. The only solution is to use a hack to use a custom size instead of the TTY window size (which we don't care about).

**Comment by nalimilan** [comment]
Works using `displaysize` since https://github.com/JuliaData/DataFrames.jl/pull/1506.
