### ISSUE TITLE
Functions that need docstrings

### ISSUE THREAD

**Issue by cjprybol** [JuliaData/DataFrames.jl#1265]
!! No docs found for 'DataFrameRow'. [src/lib/types.md]
 !! No docs found for 'categorical!'. [src/lib/functions.md]
 !! No docs found for 'deleterows!'. [src/lib/functions.md]
 !! No docs found for 'eachcol'. [src/lib/functions.md]
 !! No docs found for 'names'. [src/lib/functions.md]
 !! No docs found for 'nullable!'. [src/lib/functions.md]
 !! No docs found for 'order'. [src/lib/functions.md]
 !! No docs found for 'show'. [src/lib/functions.md]
 !! No docs found for 'showcols'. [src/lib/functions.md]
 !! No docs found for 'size'. [src/lib/functions.md]
 !! No docs found for 'sort'. [src/lib/functions.md]
 !! No docs found for 'sort!'. [src/lib/functions.md]

**Comment by quipa** [comment]
I am willing to work on this!

**Comment by Nosferican** [comment]
Probably just write the docstring for those functions according to the standards (refer to the documentation for Julia and examples from the JuliaData ecosystem such as this one).

**Comment by Nosferican** [comment]
Related #1338.

**Comment by nalimilan** [comment]
Remaining functions to document (at least):
```
categorical!
deleterows!
eachcol
names
order
show
similar
size
```

**Comment by ajwheeler** [comment]
Still remaining:
   
    names
    order
    size
