### ISSUE TITLE
Cannot join on unordered column

### ISSUE THREAD

**Issue by cstjean** [JuliaData/DataFrames.jl#1270]
This code fails because `isless(::Complex, ::Complex)` isn't defined:
```julia
df = DataFrame(a=[1im, 2im], b=[2,3])
join(df, df, on=:a)
```

`join` is a well-defined operation even in the absence of a total order. For my use case, I have [dataframes with `StackFrame` and `Method` objects](http://nbviewer.jupyter.org/github/cstjean/FProfile.jl/blob/master/Manual.ipynb). To define an ordering on these types would be type piracy.

**Comment by nalimilan** [comment]
Funny this hadn't been reported before. It's fixed on master:
```julia
julia> using DataFrames
julia> df = DataFrame(a=[1im, 2im], b=[2,3])
2×2 DataFrames.DataFrame
│ Row │ a     │ b │
├─────┼───────┼───┤
│ 1   │ 0+1im │ 2 │
│ 2   │ 0+2im │ 3 │

julia> join(df, df, on=:a)
2×3 DataFrames.DataFrame
│ Row │ a     │ b │ b_1 │
├─────┼───────┼───┼─────┤
│ 1   │ 0+1im │ 2 │ 2   │
│ 2   │ 0+2im │ 3 │ 3   │

```
