### ISSUE TITLE
categorical! only allows AbstractString vectors

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataFrames.jl#1275]
Is it intentional not to allow making a numeric vector categorical? In my instances, numeric vectors are suppose to represent categorical variables like zip codes, ID numbers, etc. Currently one has to convert these to string vectors and then convert them to categorical vectors. Should we not allow for numeric vectors to promoted to categorical if the user requests it?

**Comment by nalimilan** [comment]
There's been a short period during which CategoricalArrays didn't completely support non-string types, but it's been fixed in master and a release should be tagged soon. So a PR to change the behavior of `categorical` would be welcome. See https://github.com/JuliaData/DataFrames.jl/pull/1254.

**Comment by Nosferican** [comment]
This seems to be addressed now.
