### ISSUE TITLE
Constructor example for DataFrame not working

### ISSUE THREAD

**Issue by kmundnic** [JuliaData/DataFrames.jl#1287]
Using Julia v0.6.1, DataFrames.jl v0.10.1. `julia>?DataFrame` gives the following example to construct a DataFrame:
``` 
v = ["x","y","z"][rand(1:3, 10)]
df1 = DataFrame(Any[[1:10], v, rand(10)], [:A, :B, :C])  # columns are Arrays
```
which fails with the following error
```ERROR: ArgumentError: All columns in a DataFrame must be the same length```

With this error, I currently cannot find a way to build a new DataFrame from a matrix and a vector containing the names of the columns.

Thanks

**Comment by ararslan** [comment]
That's since been fixed. The corrected version will appear in the next release:
```julia
v = ["x","y","z"][rand(1:3, 10)]
df1 = DataFrame(Any[collect(1:10), v, rand(10)], [:A, :B, :C])
```
`[1:10]` is an array with 1 element, the range `1:10`, whereas `collect(1:10)` is an array with 10 elements.
