### ISSUE TITLE
backport reprmime("text/latex",dt) from DataTables.jl?

### ISSUE THREAD

**Issue by floswald** [JuliaData/DataFrames.jl#1293]
I just came across this SO answer of @nalimilan : https://stackoverflow.com/a/44457515/1168848
when looking for a way to easily export a dataframe to latex. he says the `reprmime("text/latex",dt)` method is easy to backport from DataTables.jl. I think that would be  great feature! thanks.

**Comment by nalimilan** [comment]
That's already in 0.11, with all other features that have were initially developed in DataTables.
