### ISSUE TITLE
Removing pipeline API from DataFrames.jl

### ISSUE THREAD

**Issue by bicycle1885** [JuliaData/DataFrames.jl#1295]
I opened #1290 to add pipeline API to `join` dataframes. This is because I found `group_by` supports the way to combine operations with `|>`: https://github.com/JuliaData/DataFrames.jl/blob/74eb8902ebccaa5ce413ca5e4c75c00b0e296694/src/groupeddataframe/grouping.jl#L365-L366

After a while, I started to think this kind of API should not be present in DataFrames.jl because it is too opinionated to have in this basic package. It should be offered by other high-level utility packages like Query.jl or DataFramesMeta.jl as @nalimilan suggested. Please note that I don't say I dislike pipeline interfaces like dplyr, I just say it can be placed anywhere else.

**Comment by nalimilan** [comment]
I tend to agree. How many functions currently support this in the codecase?

**Comment by bicycle1885** [comment]
Only two methods I listed above. So I think the impact of removing them is limited.

**Comment by bicycle1885** [comment]
I made a quick pull request to remove the API (#1296).

**Comment by nalimilan** [comment]
I think `colwise` also has a similar method, isn't it?

**Comment by bicycle1885** [comment]
Yeah, you're right. I'll take a look more carefully.

**Comment by bicycle1885** [comment]
I've updated the pull request, which includes all pipelining interfaces I'm aware of.
