### ISSUE TITLE
BUG: Problem with string vars when subsetting large df

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#1319]
Struggling with a very strange problem:

![screen shot 2017-12-15 at 2 51 14 pm](https://user-images.githubusercontent.com/9683693/34060026-8840c41e-e1a7-11e7-9734-29b673b71510.png)

The data I'm using isn't really public, so I've been trying to come up with a MWE, but haven't had luck. The problem disappears if I take the first 10, 100, or 1000 rows. Only when I keep 10,000 rows (`head -10000 the_file.csv >> mwe.csv`) does the problem persist. It also goes away if I drop a lot of the columns. :/

Does this mean anything to anyone?

**Comment by nickeubank** [comment]
OK, while not sensitive, I'd rather not post file on github, but could share 10000 rows with an admin if it'd help.

**Comment by nickeubank** [comment]
ah, ok -- the weakrefs must be lost. Check out row 3 columns `:trans`. The letter is changing over time. It must be pointing to memory used by something else. 

![screen shot 2017-12-15 at 3 05 46 pm](https://user-images.githubusercontent.com/9683693/34060451-74c1c72e-e1a9-11e7-8f6f-2fd9f1ba075d.png)

**Comment by nalimilan** [comment]
Yes, that's a CSV/WeakRefString bug. I think it's fixed by https://github.com/quinnj/WeakRefStrings.jl/pull/17. Feel free to comment there if it persists after the fix is merged.
