### ISSUE TITLE
Selecting columns by boolean index

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1321]
Currently the following is OK:
```
df = DataFrame(rand(3,5))
df[[true, false]]
```
Usually it is expected that when using boolean selection its length should be exactly the length of the selection.
I propose to have the same strict checking in this case.

The current behavior is error prone. E.g. consider what happens when we write `df[df[:x1] .< 2]` on the above `DataFrame` (this is a mistake by the developer, but highly probable in practice) - probably the intended condition was `df[df[:x1] .< 2, :]`, but the above code will go through without any problem.

**Comment by nalimilan** [comment]
Indeed, good catch!
