### ISSUE TITLE
issorted(df, :col) does not work

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#1327]
`issorted` does not work when passed a single column, either an index or as a one-element tuple/array:
```julia
julia> df = DataFrame(x = [3, 1, 2, 1], y = ["b", "c", "a", "b"])
4×2 DataFrames.DataFrame
│ Row │ x │ y │
├─────┼───┼───┤
│ 1   │ 3 │ b │
│ 2   │ 1 │ c │
│ 3   │ 2 │ a │
│ 4   │ 1 │ b │

julia> issorted(df, :x)
ERROR: MethodError: no method matching lt(::Base.Order.Perm{Base.Order.ForwardOrdering,Array{Int64,1}}, ::DataFrames.DataFrameRow{DataFrames.DataFrame}, ::DataFrames.DataFrameRow{DataFrames.DataFrame})
Closest candidates are:
  lt(::Base.Order.ForwardOrdering, ::Any, ::Any) at ordering.jl:45
  lt(::Base.Order.ReverseOrdering, ::Any, ::Any) at ordering.jl:46
  lt(::Base.Order.By, ::Any, ::Any) at ordering.jl:47
  ...
Stacktrace:
 [1] issorted(::DataFrames.DFRowIterator{DataFrames.DataFrame}, ::Base.Order.Perm{Base.Order.ForwardOrdering,Array{Int64,1}}) at ./sort.jl:54
 [2] #issorted#185(::Array{Any,1}, ::Function, ::Function, ::Bool, ::Base.Order.ForwardOrdering, ::Function, ::DataFrames.DataFrame, ::Symbol) at /home/milan/.julia/DataFrames/src/abstractdataframe/sort.jl:275
 [3] issorted(::DataFrames.DataFrame, ::Symbol) at /home/milan/.julia/DataFrames/src/abstractdataframe/sort.jl:270
 [4] macro expansion at ./REPL.jl:97 [inlined]
 [5] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

This appears to be due to the fact that `lt` only accepts a `Perm` as first argument when the two following arguments are integers. That's not a problem for `sort` and `sortperm`, since these operate on row indices. But `issorted` operates on `DataFrameRow` objects, for which no method exists. When several columns are passed, a custom `DFPerm` object is passed as the first argument to `lt`, so a custom function is used.

I'm not sure what's the appropriate solution to fix this.

**Comment by bkamins** [comment]
How about this (a small problem is that `cols` is keyword argument so there is no way to dispatch on it)?
```
function Base.issorted(df::AbstractDataFrame; cols=Any[], lt=isless, by=identity, rev=false, order=Forward)
    cols isa Union{Real, Symbol} && return issorted(df[cols], lt=lt, by=by, rev=rev, order=order)
    length(cols) == 1 && return issorted(df[cols[1]], lt=lt, by=by, rev=rev, order=order)
    issorted(eachrow(df), ordering(df, cols, lt, by, rev, order))
end
```
This seems to give the code that will have the best performance (avoids the use `DataFrameRow` if not necessary).

BTW: the call seems to have to be `issorted(df, cols=:x)` as `cols` is a keyword argument.

**Comment by nalimilan** [comment]
`cols` is no longer a keyword argument since #1328.

Feel free to make a PR if you understand that code, I don't really know how it works.

**Comment by bkamins** [comment]
OK - but I will wait with PR itll #1328 is merged.

The general idea is that if you check only one column you can simply extract it from `DataFrame` which is cheap and then run `issorted` on it which should be faster than working with a more complex data structure consisting of `DataFrameRow`s.

**Comment by bkamins** [comment]
Additionally the following bug also needs fixing:
```
julia> x = DataFrame(a=1:3,b=3:-1:1,c=3:-1:1)
3×3 DataFrames.DataFrame
│ Row │ a │ b │ c │
├─────┼───┼───┼───┤
│ 1   │ 1 │ 3 │ 3 │
│ 2   │ 2 │ 2 │ 2 │
│ 3   │ 3 │ 1 │ 1 │

julia> issorted(x, cols=[:b,:c])
true

julia> issorted(x[2:3], cols=[:b,:c])
false
```
