### ISSUE TITLE
Add column lookup with Base.getproperty?

### ISSUE THREAD

**Issue by ararslan** [JuliaData/DataFrames.jl#1336]
Once this package requires 0.7 at a minimum, we can define column lookup in terms of `getproperty` in addition to `getindex`, so that one can access a column `x` of a `DataFrame` `df` as `df.x` in addition to `df[:x]`.

We could consider a full replacement, but continuing to allow `df[:x]` permits fetching multiple columns at a time via `df[:, [:x, :y, :z]]`. I'm not sure how that would translate to the `getproperty` syntax.

**Comment by nalimilan** [comment]
Agreed. It would make sense to couple this to a port to `NamedTuple` (#1335), in particular since `filter` would then pass a `NamedTuple` (which supports the dot syntax) to the user-provided predicate.
