### ISSUE TITLE
Docstrings aren't expanded.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaData/DataFrames.jl#1338]
A large part of docstrings found in <https://juliadata.github.io/DataFrames.jl/stable/lib/functions.html#Basics-1> is not expanded, which is annoying since function links (e.g. <https://juliadata.github.io/DataFrames.jl/stable/lib/functions.html#DataFrames.rename!>) do not go anywhere.

![image](https://user-images.githubusercontent.com/905683/34595052-1985d042-f218-11e7-94a3-bed568c85835.png)

**Comment by nalimilan** [comment]
@cjprybol Any idea why docstrings aren't expanded?

**Comment by jlapeyre** [comment]
I have run into blocks of function names that were not expanded in other packages. In one case, qualifying them, i.e. `ModuleName.func` caused them to be processed properly. These were unexported symbols.

**Comment by nalimilan** [comment]
May be due to one of these errors, as Documenter avoids expanding a block if one error happens:
```
 !! No docs found for 'DataFrameRow'. [src/lib/types.md]
 !! No docs found for 'categorical!'. [src/lib/functions.md]
 !! No docs found for 'deleterows!'. [src/lib/functions.md]
 !! No docs found for 'eachcol'. [src/lib/functions.md]
 !! No docs found for 'names'. [src/lib/functions.md]
 !! No docs found for 'order'. [src/lib/functions.md]
 !! No docs found for 'show'. [src/lib/functions.md]
 !! No docs found for 'showcols'. [src/lib/functions.md]
 !! No docs found for 'size'. [src/lib/functions.md]
Documenter: building cross-references.
 !! No doc found for reference '[`isequal`](@ref)'. [src/lib/functions.md]
```

**Comment by jlapeyre** [comment]
> May be due to one of these errors, as Documenter avoids expanding a block if one error happens:

Exactly this happened to me a couple of day ago. An undocumented function (it really had no docscrtring) prevented subsequent doc strings from being rendered. I more-or-less bisected to discover this.
