### ISSUE TITLE
Constructor `DataFrame(ds::Vector{Associative})` is missing

### ISSUE THREAD

**Issue by zhouyan** [JuliaData/DataFrames.jl#1340]
After recent update, the constructor `DataFrame(ds::Vector{Associative})` seems to be missing.

For example,
```julia
julia> x = [Dict(:x => 1, :y => 2), Dict(:x => 2, :y => 3)]
2-element Array{Dict{Symbol,Int64},1}:
 Dict(:y=>2,:x=>1)
 Dict(:y=>3,:x=>2)

julia> DataFrame(x)
1×2 DataFrames.DataFrame
│ Row │ x1                │ x2                │
├─────┼───────────────────┼───────────────────┤
│ 1   │ Dict(:y=>2,:x=>1) │ Dict(:y=>3,:x=>2) │
```
This appears to call the simple array constructor instead of a specialization like before

**Comment by nalimilan** [comment]
@bkamins Maybe an unintended consequence of our recent changes?

**Comment by zhouyan** [comment]
Just another similar problem, `vcat` also don’t work as before for a vector of DataFrames

**Comment by nalimilan** [comment]
Can you give an example of what is expected and what happens?

**Comment by zhouyan** [comment]
vcat on a vector of DataFrames used to give out a single DataFrame as if they are appended to one after another. Now it just returns the vector, the behavior of the generic vcat. I will give out examples when i got in front of a computer

**Comment by bkamins** [comment]
`Vector{Associative}` constructor was removed half a year ago in 75aa742fe246e337a4d35e45f16b31ac2e6319ec by @cjprybol if I am not mistaken.

**Comment by bkamins** [comment]
`vcat` seems to work correctly.
Probably you pass a vector to `vcat` then you should splat it with `...`. This is consistent with how `vcat` works in Base.

**Comment by nalimilan** [comment]
Good catch. Let's hear what @cjprybol says. For reference, the original PR in DataTables was https://github.com/JuliaData/DataTables.jl/pull/53.

I agree the new behavior of `vcat` makes sense. For now you can splat the arguments, but there have been discussions about adding a specific function to do that in Base (https://github.com/JuliaLang/julia/issues/21672).

**Comment by nalimilan** [comment]
@bkamins @quinnj Do you think this is something we want to support? Will Tables.jl do that automatically? Or maybe we just want to support vectors of named tuples?

**Comment by bkamins** [comment]
I would say that Tables.jl will support vectors of named tuples and this is enough.
Vector of associatives produces in general an ambiguous order of columns so I would not support it.
What users can do is implement Tables.jl trait for vector of concrete associatives if they wish.

**Comment by nalimilan** [comment]
OK, let's close this. `Dict` was used a lot in places where `NamedTuple` is now much more appropriate.
