### ISSUE TITLE
How to set row value to an array

### ISSUE THREAD

**Issue by xgdgsc** [JuliaData/DataFrames.jl#1345]
From a pandas user, the api of this package seems quite unintuitive to me. I searched and didn' t find any documentation on how to set one row of a dataframe to an array of the same size as the column length. Any advice? 

Currently, `quotes1[1, :].columns = quotes2[2, :].columns` doesn' t seem to keep the values. While `quotes1[1, :] = quotes2[2, :]` works. This doesn' t seem efficient to me, why do I have to convert that array to dataframe first?

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. A reproducible example will also likely help getting a useful reply. Thanks!

**Comment by xgdgsc** [comment]
Isn' t it related to your API design? There doesn' t seem to have a category dedicated to DataFrames.jl in forum.

**Comment by nalimilan** [comment]
You can use the `#data` category. I considered it was a request for help since you asked for advice. Anyway, better start with a Discourse post, that doesn't prevent filing a feature request here once it's clear something is more difficult to do than it should.
