### ISSUE TITLE
Implement a `eachcol` `filter` API

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFrames.jl#1351]
I see many use-cases where I want to iterate through all columns _satisfying some criterion_. E.g. all numeric columns. I think an API, where I can specify a `filter` function (or a `select` function) that returns a `Bool` would help. E.g.

```julia
# loop through only numerics columns
for (name, col) in eachcol(filter = col->eltype(col) <: Real, df)
   # do something here
end
```

**Comment by ararslan** [comment]
This is equivalent to
```julia
for (name, col) in eachcol(df)
    eltype(col) <: Real || continue
    # do something
end
```
You can also use `Iterators.filter` for this:
```julia
for (name, col) in Iterators.filter(c->eltype(c[2]) <: Real, eachcol(df))
    # do something
end
```
