### ISSUE TITLE
Deprecation of vector of vectors constructor without column names

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1361]
Recently we deprecated a constructor for `DataFrame` by vector of vectors if no column names are passed, e.g.:

```
julia> DataFrame([1:5,1:5])
WARNING: calling vector of vectors constructor without passing column names is deprecated
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] DataFrames.DataFrame(::Array{UnitRange{Int64},1}) at D:\Software\JULIA_PKG\v0.6\DataFrames\src\deprecated.jl:4
 [3] eval(::Module, ::Any) at .\boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\REPL.jl:66
 [5] macro expansion at .\REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:73
while loading no file, in expression starting on line 0
5×2 DataFrames.DataFrame
│ Row │ x1 │ x2 │
├─────┼────┼────┤
│ 1   │ 1  │ 1  │
│ 2   │ 2  │ 2  │
│ 3   │ 3  │ 3  │
│ 4   │ 4  │ 4  │
│ 5   │ 5  │ 5  │
```

Having lived with this for some time my experience is that there are cases (even some packages do this, e.g. DataFramesMeta) one creates a `DataFrame` without caring about column names in this way.

Maybe we should remove deprecation and revert to the use `gennames` in this case?

**Comment by nalimilan** [comment]
I've heard one complaint about this, but in the end IIRC a better approach was found, so that method wasn't actually needed. I'm fine with reverting this, but maybe we should wait for more input? Except if you already find it too annoying in common use cases. Maybe ask on #data for feedback.

**Comment by kescobo** [comment]
If it's being used a lot, it might be helpful to know why the deprecation was proposed in the first place. I can certainly imagine places where this type of construction is useful, but without knowing why you're planning to remove it, it's hard to think about whether retaining those use-cases is worth it. 

Eg, if you're getting a 2x performance increase by removing it, that certainly seems worth it, but if it's just to have more succinct code, less so.

**Comment by bkamins** [comment]
The reason is that this constructor was thought of as internal. There is no performance reason for the change I know of.
But I have the same experience as you in recent months - I actually use it a lot - that is why I have opened this issue 😄.

@nalimilan - maybe you have some more reasons for deprecation to add?

**Comment by nalimilan** [comment]
I think one reason was that generating arbitrary column names is weird, but if people use that constructor I guess that means they don't care anyway and that probably doesn't hurt anyone...

**Comment by bkamins** [comment]
OK. I will make a PR removing the deprecation. On #data feedback was also for removing it.

**Comment by bkamins** [comment]
Closing as the change is merged.
