### ISSUE TITLE
add useful functions like `showcols` to the documentation

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1365]
It only appears in a list and doesn't have a proper doc-string.  Suspect there might be some other great functions hiding in there as well.  Wanted to make this issue so we don't forget.

**Comment by nalimilan** [comment]
I think many functions are lacking docstrings unfortunately. Listing them would already be a useful step.

**Comment by nalimilan** [comment]
`showcols` no longer exists, and https://github.com/JuliaData/DataFrames.jl/pull/1506 added docstrings for `show`.
