### ISSUE TITLE
should `getindex` type semantics be cleaned up?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1369]
Currently `getindex` methods, particularly for `Index` accept a variety of container types and in many cases they iterate over the contents of the container to check for correctness rather than simply dispatching on the type.  For example, one can do `getindex(::Index, ::Vector{Union{Int,Missing}})`.  I have no idea what the consensus is on this (if one exists) but this issue is to open up discussion with the hope of cleaning up the methods.  The main concern here I think is programatically generated indices, i.e. from data frame operations themselves.

My own attitude toward this is that we should be fairly restrictive.  I suspect that a major concern will be that many users are probably extremely familiar with pandas, and the type situation in pandas is basically total chaos for obvious reasons.  However, as people get more familiar with Julia I have a feeling they tend to have more type-correct code, and it seems like a small ask to convert columns when they are being used for indexing.  In every case I can think of, if the conversion throws an error, so will the indexing operation.

**Comment by nalimilan** [comment]
As I noted at https://github.com/JuliaData/DataFrames.jl/pull/1364#discussion_r171851466: Yes, I think it makes sense to ignore the type of the array and look only at the actual type of the elements. Else it can be cumbersome given that Julia is a dynamic language. That's how indexing arrays works.

**Comment by bkamins** [comment]
Current implementation follows @nalimilan comment - i.e. it is fast for "clean" types like `AbstractVector{Int}`, `AbstractVector{Symbol}`, `AbstractVector{Bool}` and is slower but working for all nasty types that can be passed to `getindex` as long as the data inside those types is correct.

@ExpandingMan do I understand your proposal correctly to remove support for all those "unclean" types? As @nalimilan noted this is not how Base works, e.g.:
```
julia> x = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> x[Any[1, 3]]
2-element Array{Int64,1}:
 1
 3
```

the execption is that we handle `Union{Bool, Missing}` and base does not accept it:
```
julia> x[Union{Bool,Missing}[true, true, true]]
┌ Warning: indexing with Bool values is deprecated. Convert the index to an integer first with `Int(i)`.
│   caller = macro expansion at multidimensional.jl:657 [inlined]
└ @ Core multidimensional.jl:657
3-element Array{Int64,1}:
 1
 1
 1
```
Maybe then we should remove this support? (or change the way Base works)

**Comment by ExpandingMan** [comment]
Well, here is how I usually think about this:

It never seems like an advantage to me *not* to have to worry about this sort of thing.  Indexing only makes sense on certain types, so any input needs to at least be convertible to those types.  As a practical matter my main concern is that you wouldn't want people to inadvertently cause $O(N)$ type checks in very large arrays because a `Vector` was set to a type that it shouldn't be.  That `Base` behaves differently seems like an orthogonal issue to me (for my own purposes at least, it's usually more important to be careful here than in most uses of `Base`), but your example above shows one of the related pitfalls.  As someone who is usually mainly concerned with the end result of a dataframe (i.e. raw data that can be ingested by an algorithm) improper typing always seems like an annoyance to me and never a convenience, so my instinct is usually to forbid the people manipulating the data (usually myself) from "causing trouble".

Anyway, the only "hard" justification I have is on extremely large data frames, so if people are vehemently opposed to this I won't argue the point further.

**Comment by bkamins** [comment]
This was my initial thinking when I started DataFrames.jl cleanup some time ago.
We have here a flexibility-security trade-off. I prefer security but it seems that the majority prefers flexibility and this is how I implemented it (there was much more flexibility earlier but it was even less safer so I have removed it).

We have three options:
* leave situation as is;
* deprecate only `AbstracVector{Union{Bool, Missing}}` and leave the rest;
* allow only `AbstractVector{Union{Integer,Bool,Symbol}}`. (`Bool <: Integer` but I write it explicitly as we have different behavior for it;

When we make a decision I will patch-up `getindex` and make `setindex!` use the same rules (now it has much more holes but I would patch them in one go to reach target functionality).

**Comment by nalimilan** [comment]
I see no fundamental reason to be stricter than Base. If Base accepts heterogeneous arrays, we should accept them too. People who are concerned about performance should use `@code_warntype`, as Julia in general doesn't prevent type instabilities (or it would be a static language).

Then there's `AbstractVector{Union{Bool, Missing}}`, which we currently support but Base doesn't. I think it would be worth discussing it in Base before deprecating it here. Indeed there have been many changes related to missing values in the last development cycle, and not everything is finished yet. It could make sense to accept it given that it's going to be a more common type and that converting such arrays to `Bool` just for indexing would be a waste.

**Comment by bkamins** [comment]
@nalimilan - I guess you are the most into state and future of `Missing` in Base. Can you start the discussion in a proper issue/PR in Base (referring to this issue so that we can track it)?

**Comment by ExpandingMan** [comment]
>  I see no fundamental reason to be stricter than Base.

For me the reason is that in the vast majority of things I might be doing my types are perfectly well determined and the chances of mistakenly having a bad container are very low.  The major exception is dealing with a dataframes containing badly formatted data that came from some unpleasant source.  In those cases I have to go through the trouble of fixing it.  That becomes *slightly* easier of DataFrames itself requires reasonable typing.  Again, perhaps it's just me, but I just don't see the advantage of being reckless about types.  Indeed, this was one of the things that really annoyed me about pandas (though that's probably more the fault of Python itself than pandas).

Regardless, I agree that we definitely should discuss `Union{Bool, Missing}`.  It's far from obvious to me what the expected behavior of this should be.  (By the way, currently on master row indexing of this type throws the same error as `Base` and column indexing throws a deprecation warning, is that what's intended?)  I'm definitely perfectly happy with how `Base` behaves toward this right now.

**Comment by bkamins** [comment]
The state is:
* row indexing works 100% the same as Base
* column indexing will not allow `missing` values (after deprecation) but allows `Union{Bool,Missing}` vector with all bool values and treats it then as `Bool` vector.

And how I understand @nalimilan is that we have to decide which way to go - as I would say that Base and DataFrames.jl should be consistent here.

**Comment by bkamins** [comment]
Can we close this given #1603?
