### ISSUE TITLE
missing `lastindex` method

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1370]
`AbstractDataFrame` is missing the `lastindex(::DataFrame, ::Integer)` method.  Without it you can't do e.g. `df[1:end, 1]`.

**Comment by bkamins** [comment]
Actually also `axes` method is missing also. I will make a PR adding both.

**Comment by bkamins** [comment]
See PR #1376. @ExpandingMan tests, especially under 0.7 are welcome (it passes on my version of Julia 0.7, but the ecosystem evolves ...).

**Comment by bkamins** [comment]
close?

**Comment by ExpandingMan** [comment]
Great, thanks.
