### ISSUE TITLE
Coverage regression between 0.11.3 and 0.11.4

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#1372]
It appears that some lines are not covered by tests anymore, while they used to be in 0.11.3. For example, compare this line in 0.11.3:
https://coveralls.io/builds/14794235/source?filename=src%2Fdataframe%2Fdataframe.jl#L401
with 0.11.4:
https://coveralls.io/builds/14956234/source?filename=src%2Fdataframe%2Fdataframe.jl#L403

@bkamins I guess it could be related to your recent indexing PRs, but I couldn't identify the source of the drop in coverage (CI is green for all commits). For reference, the commits between these two versions are https://github.com/JuliaData/DataFrames.jl/compare/v0.11.3...v0.11.4

**Comment by bkamins** [comment]
There are minimal reasons from my PR (e.g. we do not test adding the same variable to data frame more than two times like `DataFrame([[1], [2], [3]], [:x, :x, :x])` or we are not testing all deprecated paths).

I will simply add tests to things that I can catch from the listing you gave:
https://coveralls.io/builds/14956234/source?filename=src%2Fdataframe%2Fdataframe.jl#L403

**Comment by bkamins** [comment]
I will split my changes into several PRs as apparently it is not only about improving test coverage :) and actually some bugs have to be fixed in the process, see #1373.

**Comment by bkamins** [comment]
Some additional tests require deciding if `setindex!`:
1. taking `AbstractVector{Bool}` should ensure that that the length of the vector is correct (it does not do that now);
2. `AbstractVector{Union{Missing, Bool}}` should be accepted if actually it contains only `Bool` values;

This is how `getindex` now works.

Additionally if we decide on any as `yes` then should it go through deprecation or simply implement new functionality (treating current different behavior as a bug).

**Comment by nalimilan** [comment]
I'd say yes to both. What currently happens in case 1? I'm not sure we need a deprecation given that it's really a weird corner case.

**Comment by bkamins** [comment]
`setindex!` does not check the length of passed `AbstractVector{Bool}` which means:
1. if it is too short it is simply accepted silently;
2. if it is too long it is simply accepted silently if all not inbounds values are `false` or throws an error if any of not inbounds values is `true`;

In general I would say that if someone passes such a vector as index it is a mistake (there is no reason to do something like this) so I would simply throw an error in such cases without deprecating the above behavior.

**Comment by nalimilan** [comment]
Agreed, I can't imagine a valid use of that behavior.

**Comment by bkamins** [comment]
Given #1380 is the last part of test coverage this can be closed I think?
