### ISSUE TITLE
functional interface for deleting columns

### ISSUE THREAD

**Issue by tpapp** [JuliaData/DataFrames.jl#1378]
We have `delete!`, but `DataFrame` is particularly nice for a functional style when subsetting/transforming columns, so it would make sense to have something like
```julia
dropcols(df::AbstractDataFrame, cols) = df[setdiff(names(df), cols)]
```

**Comment by nalimilan** [comment]
I guess we could support this via [negated indexing](https://github.com/JuliaData/DataFrames.jl/issues/182) instead of adding a new function?

**Comment by tbeason** [comment]
I define this function at the top of literally any script where I am using DataFrames (although I'll probably switch to your version because it is was more compact).

`dropcol(d,args...) = @select(d, filter(x -> !(x in args),names(d)))`

**Comment by bkamins** [comment]
We now support `Not`.
