### ISSUE TITLE
Writing to latex: omitting column with row index

### ISSUE THREAD

**Issue by davidzentlermunro** [JuliaData/DataFrames.jl#1381]
Is it possible to write a dataframe to tex without including a column that just has the row numbers?

**Comment by nalimilan** [comment]
I don't think so. I think the purpose of the `show` method for LaTeX is to provide a default representation of a `DataFrame` in LaTeX displays, but not to support any customization options (which could make the function very complex and would better be implemented in a separate package).

**Comment by korsbo** [comment]
This may be something [Latexify.jl](https://github.com/korsbo/Latexify.jl) could be helpful for. 

```julia
using DataFrames
using Latexify
df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
latexify(df; env=:table, latex=false)
```
outputs:
```
\begin{tabular}{cc}
A & B\\
1 & M\\
2 & F\\
3 & F\\
4 & M\\
\end{tabular}
```

I don't often use DataFrames myself, so I haven't spent much time on tweaking the interface between DataFrames and Latexify. But there is already some rudimentary support and  it might be rather easy to improve it if anyone is interested.

**Comment by bkamins** [comment]
Can this be closed?

**Comment by davidzentlermunro** [comment]
Yes can be closed - I'm happily writing tables using both DataFrames package and write command.
