### ISSUE TITLE
A view into a column should be a view into a vector

### ISSUE THREAD

**Issue by cstjean** [JuliaData/DataFrames.jl#1383]
```julia
df = DataFrame(x=1:100, y=201:300)
@view df[1:10, :x]
```

This returns a `SubDataFrame`. Shouldn't it be equivalent to `@view vdf[:x][1:10]`?

**Comment by nalimilan** [comment]
Probably, given that `@view x[1:10, 1]` returns a vector when `x` is a matrix.

**Comment by bkamins** [comment]
Fixed by #1603
