### ISSUE TITLE
eltypes returns Union type now?

### ISSUE THREAD

**Issue by juliohm** [JuliaData/DataFrames.jl#1386]
I have to say it is been really difficult to keep up with changes in DataFrames.jl. I have a collection of packages that is broken now because `eltypes` is returning `Union{T,Missing}`. What is the (new) correct way of accessing the column types without the missing boilerplate?

**Comment by juliohm** [comment]
Should `eltypes` return `Union` to start with?

**Comment by nalimilan** [comment]
Yes, that's expected. See https://discourse.julialang.org/t/dataframes-0-11-released/7296/. Use the `Missings.T` function to get the `T`.

BTW, please use Discourse for questions and keep GitHub for actual bug reports.

**Comment by juliohm** [comment]
Thanks, I thought it was a bug, I don't see much value in `eltypes` `Union`, but I will try to workaround with `Missings.T` as suggested.

**Comment by nalimilan** [comment]
That's not a question of "value". If a column allows for `missing`, its eltype cannot be `T`, it has to be `Union{T,Missing}`, period. The previous approach used by DataArrays was a hack.
