### ISSUE TITLE
Changes to CategoricalArrays cause test failure

### ISSUE THREAD

**Issue by spurll** [JuliaData/DataFrames.jl#1396]
DataFrames CI has been failing since CategoricalArrays was updated to v0.3.8. This seems to be a result of [this change](https://github.com/JuliaData/CategoricalArrays.jl/pull/139), which affects column ordering after `unstack`.

```julia
Test Failed
  Expression: df2 ≅ df4
   Evaluated: 2×3 DataFrames.DataFrame
│ Row │ Fish   │ Mass │ Color │
├─────┼────────┼──────┼───────┤
│ 1   │ Bob    │ 12 g │ Red   │
│ 2   │ Batman │ 18 g │ Grey  │ ≅ 2×3 DataFrames.DataFrame
│ Row │ Fish   │ Color │ Mass │
├─────┼────────┼───────┼──────┤
│ 1   │ Bob    │ Red   │ 12 g │
│ 2   │ Batman │ Grey  │ 18 g │
	FAILED: dataframe.jl
LoadError: There was an error during testing
while loading /Users/gem/.julia/v0.6/DataFrames/test/dataframe.jl, in expression starting on line 353
```

I'm not sufficiently familiar with this part of the DataFrames code offhand to know whether this is actually a problem (I don't *think* it is), so a fix may be as simple as reordering the expected columns in the affected test cases. I can take a closer look tomorrow morning.

**Comment by ararslan** [comment]
I bet the fix from https://github.com/JuliaStats/StatsModels.jl/pull/55 would be applicable here.

**Comment by nalimilan** [comment]
Good catch! `droplevels!` wasn't sufficiently tested in CategoricalArrays. See https://github.com/JuliaData/CategoricalArrays.jl/pull/140.
