### ISSUE TITLE
readtable with string separator

### ISSUE THREAD

**Issue by davidbp** [JuliaData/DataFrames.jl#1410]
Hello

Assuming the head of my data has the following format:
How can I use `readtable` to read this into a dataframe? 

```
1::1193::5::978300760
1::661::3::978302109
1::914::3::978301968
```

The `separator` needs to be `Char` and "::" is not a char.

**Comment by nalimilan** [comment]
`readtable` is deprecated. See https://github.com/JuliaData/CSV.jl/issues/126.
