### ISSUE TITLE
Columns as references concern

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#1411]
I watched @bkamins 's great talk today on YouTube, and had a question / concern about passing references and not copying into columns. I definitely applaud @bkamins 's aim of minimizing copying, but having struggled with this issue at length over on the Python pandas project, I know it's a real hard nut to crack.

My main concern is that if a library is going to make the promise that two columns are backed the the same object, I think the library needs to be able to ensure that's always the case. 

The problem one quickly runs into, however, is when one modifies a DataFrame in a way that results in copying (rather than mutating) of the DataFrame. In those situations, the promise that two columns are backed by the same object breaks down. For example:

```
julia> using DataFrames

julia> x = DataFrame(A=1:3, B=rand(3), C=randstring.([3,3,3]))
3×3 DataFrames.DataFrame
│ Row │ A │ B         │ C   │
├─────┼───┼───────────┼─────┤
│ 1   │ 1 │ 0.0660384 │ ac5 │
│ 2   │ 2 │ 0.628621  │ 2Es │
│ 3   │ 3 │ 0.344766  │ q71 │

julia> x[:A_dup] = x[:A]
3-element Array{Int64,1}:
 1
 2
 3

julia> x[:A] === x[:A_dup]
true

julia> x = x[1:2, :]
2×4 DataFrames.DataFrame
│ Row │ A │ B         │ C   │ A_dup │
├─────┼───┼───────────┼─────┼───────┤
│ 1   │ 1 │ 0.0660384 │ ac5 │ 1     │
│ 2   │ 2 │ 0.628621  │ 2Es │ 2     │

julia> x[:A] === x[:A_dup]
false

```

What's the design philosophy around this? Has it been decided this is acceptable / has it been discussed? And if not, is this something that's acceptable?

I will confess my own view is that it's a little tricky -- it's hard to keep track of which functions will mutate and which will not all the time.

**Comment by bkamins** [comment]
I would say that the design philosophy is that we are one-to-one transparent to what would Base Julia do in a similar case to an underlying vector (**if you find any cases where this contract is not met please raise an issue**).

What I mean by this is the following:
```
julia> x= [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> x_dup = x
3-element Array{Int64,1}:
 1
 2
 3

julia> x === x_dup
true

julia> x = x[1:2]
2-element Array{Int64,1}:
 1
 2

julia> x === x_dup
false
```
and you get exactly the same result as with a `DataFrame`.

Here is another example where you see that we behave just as an underlying vector would behave:
```
julia> x = DataFrame(rand(1:3, 2,2))
2×2 DataFrames.DataFrame
│ Row │ x1 │ x2 │
├─────┼────┼────┤
│ 1   │ 2  │ 2  │
│ 2   │ 3  │ 1  │

julia> y = x
2×2 DataFrames.DataFrame
│ Row │ x1 │ x2 │
├─────┼────┼────┤
│ 1   │ 2  │ 2  │
│ 2   │ 3  │ 1  │

julia> push!(x, (100, 100))
3×2 DataFrames.DataFrame
│ Row │ x1  │ x2  │
├─────┼─────┼─────┤
│ 1   │ 2   │ 2   │
│ 2   │ 3   │ 1   │
│ 3   │ 100 │ 100 │

julia> x
3×2 DataFrames.DataFrame
│ Row │ x1  │ x2  │
├─────┼─────┼─────┤
│ 1   │ 2   │ 2   │
│ 2   │ 3   │ 1   │
│ 3   │ 100 │ 100 │

julia> y
3×2 DataFrames.DataFrame
│ Row │ x1  │ x2  │
├─────┼─────┼─────┤
│ 1   │ 2   │ 2   │
│ 2   │ 3   │ 1   │
│ 3   │ 100 │ 100 │
```

I hope this helps (of course one needs to know how Base Julia works to know how `DataFrame` would behave).
