### ISSUE TITLE
Feature request for `join`

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#1412]
[ Carrying over from [Discourse](https://discourse.julialang.org/t/two-feature-requests-for-merge) ] 

I'd like to propose two added functions to the `join` function to be offered as optional keywords:

- `validate`: duplicates the functionality of `validate` keyword in the `pandas` [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) function. Accepts `"1:1"`, `"1:m"`, `"m:1"`, and `"m:m"`, and raises an exception if the merge is not 1 to 1, 1 to many, many to 1, or many to many (respectively). 
- `indicator`: duplicates functionality of `indicator` keyword in `pandas` [merge] function. If `True`, adds column to returned object which records whether resulting row has data from `both` datasets, from the `left_only`, or the `right_only` (presumably stored as categoricals? Or something else if there are performance issues.)

(Both are actually replications of behavior from [Stata](https://www.stata.com/manuals13/dmerge.pdf))

Personally, I find these exceedingly value when working with real world data, as there's no place problems become more evident than in merges, and it gets exhausting writing code the replicates these functionalities every time I merge (especially the `indicator` command). 

As noted in the Discourse discussion, there are ways of getting at these with existing tools, but (at least in my experience) they're so used I think a little syntactic sugar is warranted.

I’m an empirical social scientist, and work with data from lots of sources (census, various government agencies, other researchers, etc.). Those data sources are often supposed to relate in certain ways (Everyone in dataset A should also be in B, but there should be people in B not in A), but they almost inevitably don’t. Just doing a Left or Right join would get only the people who fit the promised relationship, but I (a) want to know how many people didn’t merge right (so I usually do an Outer join, then check the merge-state, and (b) when things go wrong, I want to look at the errors (so it’s nice to quickly query the people who are in A but not in B, in the example above).

I recognize this is not a problem that many CS people (with nice, single-source datasets) or people in the private sector (working with data from a single source, or from a SQL database that has inbuilt checks for these kinds of things) deal with much, but I think this is super common among social scientists.

**Comment by bkamins** [comment]
I do not see a problem with adding both (but maybe other people would have some objections). Please just specify the desired design.

* for `incicator` keyword argument:
    * do you want it to be `Bool` or something more general like in Pandas?
    * what should be a column name (or should there be one column or two columns - one for left and one for right)?
    * what should we do if the column name would already exist in target data frame (use standard renaming convention or something else)?
    * what values do you want to use to indicate the result (e.g. if you use two columns they could be `Bool` both; for one column there are several options, e.g. a tuple of two `Bool`)
    * what should be the default value (I guess `false`)?;
* for `validate` keyword argument:
    * what values do we want it to accept for this keyword argument; is a standard tuple of two `Bool` enough or specialized type as it was proposed on Discourse; also what they would mean, e.g. my intuition is that in `(Bool, Bool)` scenario `true` means validate (i.e. do not allow duplicates) and `false` means do not validate (i.e. allow duplcates)
    * what should be a default value (I guess `(false, false)`)
    * what should happen if validate condition is not met? - an error thrown?
    * and now we have a key question: do we want to check for duplicates only on included keys or on all keys (also those that would not show up in the result); this question is relevant for all `kind` options except `:outer` (when everything is shown); what I mean by it is the following: assume you do inner join; in the left table you have a duplicate key `"left"` which is not present in the right table; do you want to throw an error in this case (or you want to throw an error only if `"left"` would be present in the resulting joined table)

**Comment by nalimilan** [comment]
Makes sense. It would be interesting to check whether/how other software than Pandas and Stata implement this (e.g. dplyr and data.table).

**Comment by nickeubank** [comment]
Thanks all, sorry for slow response -- just had a kid, so will be kinda in and out for a while. :)

@nalimilan I don't think either `dplyr` or `data.table` offer these behaviors -- dplyr join docs don't have anything, and I don't think data.table extends join. And looks like [people aren't aware](https://stackoverflow.com/questions/40110644/is-there-a-merge-indicator-available-after-a-merge) of any in-built functionalities. The only place I've found it is the in `join` function of [statar](https://cran.r-project.org/web/packages/statar/index.html).

`Indicator`
------------

> do you want it to be Bool or something more general like in Pandas?

I'm find with two boolean columns (`_left`, `_right`) if people think that's most "julian", but the other easy option would be a categorical similar to pandas, which might be more readable. Still getting a sense of what the community thinks is "julian". :)

> what should be a column name (or should there be one column or two columns - one for left and one for right)?

If two columns, `_left` and `_right` make sense, otherwise `_merge`. 

> what should we do if the column name would already exist in target data frame (use standard renaming convention or something else)?

I'd adopt the norms of `makeunique` argument.  Most people don't prefix with underscores, so hopefully conflicts will be rare. 

> what values do you want to use to indicate the result (e.g. if you use two columns they could be Bool both; for one column there are several options, e.g. a tuple of two Bool)
what should be the default value (I guess false)?;

`_left` would be `true` if that observation's merge key appeared in left dataset, `false` otherwise. 


`validate`
----------

> what values do we want it to accept for this keyword argument; is a standard tuple of two Bool enough or specialized type as it was proposed on Discourse; also what they would mean, e.g. my intuition is that in (Bool, Bool) scenario true means validate (i.e. do not allow duplicates) and false means do not validate (i.e. allow duplcates)

If we go with a tuple of bools, I think the arg name should be something like `check_unique`. Then `true` naturally implies checking for merge-key uniqueness. 

> what should be a default value (I guess (false, false))

Yes, false, false. Don't want to add to running times in default behavior. 

> what should happen if validate condition is not met? - an error thrown?

Yes, I think an exception would be best. I was thinking the natural implementation is with `@assert`. 

> and now we have a key question: do we want to check for duplicates only on included keys or on all keys (also those that would not show up in the result); this question is relevant for all kind options except :outer (when everything is shown); what I mean by it is the following: assume you do inner join; in the left table you have a duplicate key "left" which is not present in the right table; do you want to throw an error in this case (or you want to throw an error only if "left" would be present in the resulting joined table)

I think I'd follow the Stata / pandas behavior: check on all keys

**Comment by nalimilan** [comment]
OK. Maybe instead of accepting both a Boolean or a string, we could just take a `Symbol` (or a 2-tuple of symbols) giving the name of the column(s) to create (and `nothing` by default). I don't really see the point of accepting `true`, it's less explicit than giving the name of the column.

**Comment by bkamins** [comment]
OK - all looks good to me. For indicator I would go with a single column and a `Symbol` approach. The output could be a tuple of `Bool` then.

@nickeubank do you want to make a PR?

**Comment by nalimilan** [comment]
> For indicator I would go with a single column and a Symbol approach. The output could be a tuple of Bool then.

A tuple of `Bool` wouldn't be very convenient to work with I guess. Why not create two columns?

**Comment by bkamins** [comment]
I do not have a very strong preference (that is why I proposed two column names above - and this would be my choice as then it is cheapest to work with this later and it can be more efficiently packed in memory in `BitArray`).

Then I thought (and this is what @nickeubank suggested) that maybe for the "regular" end user it would be simpler to specify one column name as it would be `Union{Symbol, Nothing}` then. Otherwise column name type should be `Union{Nothing, Tuple{Union{Symbol, Nothing},Union{Symbol, Nothing}}}` which is less obvious to use.

But as a second thought actually I think that @nalimilan is right preferring two columns. As then the user can opt in for creation of left and right column (so if only one is needed the other is not created at all). The column names should be two separate keyword arguments defaulting to `nothing` and all is clean.

**Comment by nickeubank** [comment]
> @nickeubank do you want to make a PR?

I'd be happy to, though as I mentioned, I'm afraid our first child just arrived way head of schedule, so it will take me a while to get to this. If anyone is bored and wants to take this on in the meantime they are more then welcome to do so (I would take zero offense), or I'll get to it when things slow down!

> But as a second thought actually I think that @nalimilan is right preferring two columns. As then the user can opt in for creation of left and right column (so if only one is needed the other is not created at all). The column names should be two separate keyword arguments defaulting to nothing and all is clean.

For the `indicator` option, I was actually thinking of a categorical column with levels of `left_only`, `right_only` and `both` as in `pandas`. I would think the best choice is either (a) two boolean columns, or (b) a categorical column with those values. Agnostic as to which is more julian.

**Comment by nickeubank** [comment]
ok, got bored doing morning feeding shift so did a PR after all. :) Comments appreciated.
