### ISSUE TITLE
Future of showcols and describe

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1417]
Following merge of #1409 I think that showcols is obsolete.
Especially if we added `first`, `last` or `values` optional columns to `decscibe` (apart from this column `showcols` is now a subset of `describe`).

Also a small comment for `describe`: while median is possibly ambiguous, min and max can be safely computed for ordered categorical arrays.

CC @nalimilan @pdeffebach

**Comment by pdeffebach** [comment]
#1418 Should resolve that last issue. It adds some `try...catch` blocks to get summary statistics even if we don't know what operations are allowed. This will be really useful for DataFrames with user-defined types. 

Adding `first`, `last` etc. is possible, but it's tough to make them in the default output cause it will get too wide.

**Comment by nalimilan** [comment]
Good idea, better reduce the number of exported functions and provide more options from `describe`.

**Comment by bkamins** [comment]
Thanks - I close this and move the discussion to #1418.
