### ISSUE TITLE
NamedTuples Warning Message after DataStreams update

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaData/DataFrames.jl#1419]
After Pkg.update() and subsequent update of DataStreams to v0.3.5 (#75 Switch back to using NamedTuples package). The following Warning message appears hen Precompiling the DataFrames Package.
```
WARNING: eval from module NamedTuples to DataFrames:
Expr(:type, false, Expr(:<:, Expr(:curly, :_NT_col, :T1)::Any, NamedTuples.NamedTuple)::Any, Expr(:block, Expr(:::, :col, :T1)::Any, Expr(:tuple)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **
```
So far, I did not encounter any problems with the Packages after this Warning message. 
Can I safely ignore this message? Why did this Warning appear in the first place? 
Thanks

**Comment by quinnj** [comment]
Should be fixed by https://github.com/JuliaLang/METADATA.jl/pull/15035; sorry for the temporary scary warning

**Comment by ararslan** [comment]
METADATA PR has been merged so I'll close this.
