### ISSUE TITLE
`makeunique` not respected by `join`?

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#1425]
Trouble shooting PR #1424 , and found this:

```
julia> x = DataFrame(a = [1, 2], b = [3, 4])
2×2 DataFrame
│ Row │ a │ b │
├─────┼───┼───┤
│ 1   │ 1 │ 3 │
│ 2   │ 2 │ 4 │

julia> join(x, x, on=:a, makeunique=false)
2×3 DataFrame
│ Row │ a │ b │ b_1 │
├─────┼───┼───┼─────┤
│ 1   │ 1 │ 3 │ 3   │
│ 2   │ 2 │ 4 │ 4   │
```

**Comment by bkamins** [comment]
This was intended as a temporary deprecation period.
See https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/utils.jl#L63.
After deprecation this would be an error.

@nalimilan - when do we make transition with `makeunique` to make the behavior a rule. The changes were made 6 moths ago?

**Comment by bkamins** [comment]
OK.
@nickeubank - we will have to live with this annoyance till then.
