### ISSUE TITLE
takes forever to compile on 0.7

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1427]
This was discussed a few places but I just wanted to make sure this is codified as an issue.

It takes me up to 130 seconds (timed) to compile on 0.7, which is insane.

I really have no idea what is causing this.  Method overwrite warnings from StatsBase are not helping, but it seems unlikely that's the sole cause.

**Comment by nalimilan** [comment]
Yes, that's intriguing. We should fix deprecations in the package and its dependencies, and then check whether it's still slow.

**Comment by ExpandingMan** [comment]
This was fixed by the great work being done on 0.7.  It is now at least as fast as it was on 0.6.  Closing the issue now.
