### ISSUE TITLE
Potential bug with `categorical!` with alpha

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataFrames.jl#1433]
```
julia v"0.7.0-alpha.0"
CategoricalArrays v0.3.9
DataFrames v0.11.6

data = DataFrame(a = ["a", "b", "c"])
categorical!(data)
3×1 DataFrame
│ Row │ a      │
├─────┼────────┤
│ 1   │ #undef │
│ 2   │ #undef │
│ 3   │ #undef │
```

**Comment by nalimilan** [comment]
That's a bug in CategoricalArrays, so no need to change DataFrames. If anything, we could add an upper bound on Julia 0.7 to CategoricalArrays, but we don't usually do that for any packages.

**Comment by Nosferican** [comment]
I think the explicit compatibility should be easier with the new package manager so it would be a good time to start adopting it.
