### ISSUE TITLE
Ungrouping

### ISSUE THREAD

**Issue by bogiebro** [JuliaData/DataFrames.jl#1438]
It seems that DataFrames is currently lacking a mechanism to ungroup a DataFrame once it has been grouped. This is useful because the current overload of `getindex` for `GroupedDataFrame`s allows one to filter out undesired groups. The `combine` function only works after application, and isn't particularly efficient for this use case. I'm thinking something along the following lines:

```
ungroup(g) = view(g.parent, g.idx[collect(Iterators.flatten(s:e for (s,e) in zip(g.starts, g.ends)))])
```

**Comment by nalimilan** [comment]
Makes sense. I guess we could provide a `combine` method for `GroupedDataFrame`.

**Comment by nalimilan** [comment]
https://github.com/JuliaData/DataFrames.jl/pull/1520 fixes this incidentally by allowing one to call `combine` without application. We could imagine renaming that function to `ungroup`, which is used by dplyr.

**Comment by bkamins** [comment]
Can we close this given now `combine` does what was requested?
