### ISSUE TITLE
dropmissing should not allow missing values in columns

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#1441]
It seems like `dropmissing` should change the type of columns from `Union{T, Missing}` to `T`, at least by default. That's more efficient, but also safer since missing values cannot be introduced silently in the resulting data frame.

**Comment by bonsairobo** [comment]
I agree. It's also much simpler to work with a dataframe after `dropmissing` if the types don't have `Union{Missing, T}` everywhere. I just want to assume there are no missing values.

**Comment by bkamins** [comment]
We can go forward with this, but I agree with:

> at least by default

I can imagine cases when we want to drop missings without changing `eltype` of the vectors.

**Comment by bkamins** [comment]
Apart from #1617 also `dropmissing` and `dropmissing!` should only allow `DataFrame` in a signature. I will fix it when we have this consensus.

**Comment by bkamins** [comment]
This is implemented now. Can we close the issue?
