### ISSUE TITLE
Feature Request: subset rows when boolean vector passed alone

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#1445]
Right now, subsetting rows requires a full subset notation:

```
julia> df = DataFrame(a = [1, 2, 3], b = ["a", "b", "c"])
3×2 DataFrame
│ Row │ a │ b │
├─────┼───┼───┤
│ 1   │ 1 │ a │
│ 2   │ 2 │ b │
│ 3   │ 3 │ c │

julia> df[df[:a] .> 1, :]
2×2 DataFrame
│ Row │ a │ b │
├─────┼───┼───┤
│ 1   │ 2 │ b │
│ 2   │ 3 │ c │
```

This sets it apart from R and Pandas, both of which recognize that when passed a boolean vector, they should provide a subset of rows (if the number of obs in the vector doesn't match the number or rows they throw an exception). Seems like `DataFrames.jl` could do the same thing, so instead of typing `df[df[:a] .> 1, :]`, one can just type `df[df[:a] .> 1]`. 

Given how often one subsets rows in a DataFrame, I think that'd be really nice. 

EDIT: Sorry to clarify, `df[[:a, :b]]` would still get a subset of columns (any vector of symbols would get column subsets) but `df[[true, false, false]]` would get a subset of rows.

**Comment by ararslan** [comment]
I think we'd have to change how 1D indexing into a `DataFrame` works for this to make sense; currently it selects columns.

**Comment by nickeubank** [comment]
Yes, I recognize this would be API breaking, but we're still pre-0.7 / 1.0, so I figured it was worth bringing up now. 

The good news is it wouldn't cause silent problems unless someone has a dataframe with exactly same number of rows and columns...

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/DataFrames.jl/issues/1200 and https://github.com/JuliaData/DataFrames.jl/pull/1224. Closing in favor of these issues.

> This sets it apart from R and Pandas, both of which recognize that when passed a boolean vector, they should provide a subset of rows (if the number of obs in the vector doesn't match the number or rows they throw an exception).

Actually in R this syntax indexes *columns*. That's where the design of `DataFrame` comes from.

**Comment by nickeubank** [comment]
> Actually in R this syntax indexes columns. That's where the design of DataFrame comes from.

oops, sorry -- you're right!

**Comment by pdeffebach** [comment]
> I think we'd have to change how 1D indexing into a DataFrame works for this to make sense; currently it selects columns.

I think this would be a good change, maybe a `DataFrameColumn <: AbstractDataFrame` type thing.

I am periodically rewriting random Stata cleaning files in Julia and am noticing how much of my workflow depends on arbitrary subsets of variables. If I do 

```
vars = [:x1, :x2]
one_var = [:x1]

df[:new] = f(df[vars])
dd[:one_var_new] = f(df[:one_var])
```

the way it currently stands is I have to write two methods for `f` for whether or not the input is a single symbol or more than one.

**Comment by nickeubank** [comment]
@pdeffebach I think it currently does, no?

```
julia> df = DataFrame(a = [1, 2, 3], b = ["a", "b", "c"])
3×2 DataFrame
│ Row │ a │ b │
├─────┼───┼───┤
│ 1   │ 1 │ a │
│ 2   │ 2 │ b │
│ 3   │ 3 │ c │

julia> df[[:a]]
3×1 DataFrame
│ Row │ a │
├─────┼───┤
│ 1   │ 1 │
│ 2   │ 2 │
│ 3   │ 3 │
```

**Comment by pdeffebach** [comment]
Yes it does. I was confused writing this.

**Comment by nickeubank** [comment]
@pdeffebach Did you mean to comment in #1200?

**Comment by pdeffebach** [comment]
No I think I was confused about this change in general.
