### ISSUE TITLE
Error in DataFrame function

### ISSUE THREAD

**Issue by lucasfreitas1988** [JuliaData/DataFrames.jl#1446]
Hello! I need Help!

My Code data = DataFrame(load("Lebron.xlsx","Sheet")) results in:

MethodError: no method matching get(::Float64)
Closest candidates are:
  get(::ObjectIdDict, ::ANY, :ANY) at associative.jl:434
  get(m::Base.EnvHash, ::AbstractString, ::Any) at env.jl:79
  get(::PyCall.PyObject, ::Union{Tuple{Vararg{Type,N}}, Type} where N, ::Any) at C:\Users\ACER\.julia\v0.6\PyCall\src\PyCall.jl:770
  ...
macro expansion at dataframes-missing.jl:94 [inlined]
_filldf(::Tuple{Array{Float64,1},Array{String,1},Array{Float64,1},Array{String,1},Array{Float64,1},Array{Any,1},Array{Any,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}}, ::TableTraitsUtils.TableIterator{NamedTuples._NT_Rk_Player_Home_Opp_GR_Qtr_Time_TPQ_SR_DIST_DR_CLOSEST_POINTS _POINTSOPP_DIFF_HD_WD_POINTST_POINTSM_ASSIST_PIE_OWS_WS_PER{Float64,String,Float64,String,Float64,Any,Any,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64},Tuple{Array{Float64,1},Array{String,1},Array{Float64,1},Array{String,1},Array{Float64,1},Array{Any,1},Array{Any,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}}}) at dataframes-missing.jl:81
_DataFrame(::ExcelFiles.ExcelFile) at dataframes-missing.jl:121
DataFrames.DataFrame(::ExcelFiles.ExcelFile) at dataframes-missing.jl:129
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80

What is this (MethodError: no method matching get(::Float64))?

Thank you so much,

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks! Also make sure you mention what packages you loaded apart from DataFrames.
