### ISSUE TITLE
Add column name in split-apply-combine by()

### ISSUE THREAD

**Issue by miguelmorin** [JuliaData/DataFrames.jl#1448]
I often write this kind of code:
```
aggregated_df = by(disaggregated_df, [:field1, :field2], df -> sum(df[:field3]))
rename!(categories_df, :x1 => :field3)
```

I often have bugs by forgetting the second line. Could `by()` include an optional argument to rename the aggregated column, or else to keep the name of the original column?

**Comment by nalimilan** [comment]
It's been requested many times before. We should definitely add an argument. Maybe even make it the default? I'm not sure what other software do.

**Comment by nalimilan** [comment]
R's `aggregate` isn't directly equivalent to `by` though, as it operates on columns one at a time. There's no possibility of naming conflict there. But it's interesting to note that it treats columns in `by` separately and doesn't call the summary function on them (which rarely makes sense).

**Comment by kleinschmidt** [comment]
could we add kw args to get names?

**Comment by miguelmorin** [comment]
@nalimilan If keep the same names as in the original dataframe, is there a possibility of conflict, or does it come only if we allow renaming one column to another that already exists?

**Comment by nalimilan** [comment]
Actually I think I was mistaken about what you requested in the issue description. I think we should fix it by allowing you to return a named tuple, like this:
```julia
aggregated_df = by(disaggregated_df, [:field1, :field2], df -> (new_var=sum(df[:field3])),)
```
(or maybe even a `Pair`)

There's no way to automatically find out that we should reuse the name of the column (here `:field3`) since all we see is a vector.

**Comment by miguelmorin** [comment]
Yes, absolutely. My request would require changing the syntax of `by()` to look more like `R` separating the column name `:field3` from the function `sum` in this case.

**Comment by pdeffebach** [comment]
In a similar vein, a keyword argument for suffixes in `aggregate` would be helpful, so if you pass anonimous functions you don't have all your variables with `#1` added on the end.

**Comment by bkamins** [comment]
@nalimilan - can we close this given new `by` API and new automatic naming conventions for `aggregate`?
