### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by rofinn** [JuliaData/DataFrames.jl#1451]
There have been 21 commits to master since the last release (which was in April). Looking through the diff I don't see anything breaking (that should be deprecated), but the API changes should warrant a new minor release.

**Comment by nalimilan** [comment]
Agreed, but I'm waiting for https://github.com/JuliaData/DataFrames.jl/pull/1450#discussion_r202032992 to be fixed first.

**Comment by nalimilan** [comment]
I've tagged a release at https://github.com/JuliaLang/METADATA.jl/pull/15836. We'll drop 0.6 support after that, and maybe tag another release (0.12.0) quickly.

**Comment by ararslan** [comment]
Done
