### ISSUE TITLE
Documentation of functions is broken

### ISSUE THREAD

**Issue by KristofferC** [JuliaData/DataFrames.jl#1457]
http://juliadata.github.io/DataFrames.jl/latest/lib/functions.html#Basics-1 is just a block of function names (I think this is not due to lack of docstrings but because Documenter just punts on showing anything if there is an error in an autodoc block).

Also, the docs are deployed from the 0.6 worker but that is no longer run on Travis.

**Comment by ararslan** [comment]
The issue with the docstrings is #1338. Good catch regarding Travis.

**Comment by nalimilan** [comment]
Closing in favor of the other issue.
