### ISSUE TITLE
0.6 support on 0.12

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1464]
I noticed that 0.12 is not working on 0.6 and that the `REQUIRE` file now lists 0.7.  I wasn't able to compile on 0.6 because of `using Statistics`.  Are we really dumping 0.6 so soon?  I'm not necessarily opposed to this, it just got a little bit ahead of me, I wanted to confirm that this is deliberate.

**Comment by ExpandingMan** [comment]
I just realized that this may have been a really stupid question because the next oldest release is much closer to 0.12 than I realized.  So I guess 0.12 drops 0.6, for that you'd use 0.11.7.  That seems like a good setup.

**Comment by nalimilan** [comment]
Yes, that's intended because it made porting to 0.7 simpler. 0.11.7 and 0.12.0 are very similar anyway.
