### ISSUE TITLE
Cannot `convert` an object of type DataValues.DataValue{Any} to an object of type DateTime

### ISSUE THREAD

**Issue by ianshmean** [JuliaData/DataFrames.jl#1478]
I’m stuck with new Julia 0.7/1.0 DataFrames functionality. I have dataframe `df` where column 1 is an array of `DataValues.DataValue{Any}`.

How can I convert it to DateTime, and allow for missing?

This doesn’t work:
```
datetimes = convert(Vector{Union{DateTime,Missing}}, df[1])
```

```
MethodError: Cannot `convert` an object of type DataValues.DataValue{Any} to an object of type DateTime
```

**Comment by nalimilan** [comment]
`DataValue` entries should never appear in a data frame. That's probably a bug in the Queryverse package you used to import the data.
