### ISSUE TITLE
Aggregate produces colnames with module name

### ISSUE THREAD

**Issue by jmgnve** [JuliaData/DataFrames.jl#1486]
When aggregating the data using a function from a module outside of Base, the module name is added to the column name. See example below, where "Statistics." has been inserted. Is this intentional, or should the module name be excluded?

```julia
(v0.7) jl> using DataFrames

(v0.7) jl> using Statistics

(v0.7) jl> d = DataFrame(g = [1,1,2,2], v=1:4)
4×2 DataFrame
│ Row │ g │ v │
├─────┼───┼───┤
│ 1   │ 1 │ 1 │
│ 2   │ 1 │ 2 │
│ 3   │ 2 │ 3 │
│ 4   │ 2 │ 4 │

(v0.7) jl> aggregate(d, :g, [mean, sum])
2×3 DataFrame
│ Row │ g │ v_Statistics.mean │ v_sum │
├─────┼───┼───────────────────┼───────┤
│ 1   │ 1 │ 1.5               │ 3     │
│ 2   │ 2 │ 3.5               │ 7     │
```

**Comment by pdeffebach** [comment]
Thanks for the issue report. This should be an easy fix, we can just use `nameof()` instead of the function name in the code.
