### ISSUE TITLE
Difficulty working with column names with specific characters

### ISSUE THREAD

**Issue by galaxite** [JuliaData/DataFrames.jl#1494]
I'm attempting to join several dataframes on a column called "cm-1". Attempting to do this via the command `join(df1, df2, on = :cm-1)` fails with an error suggesting that the "-" character is the problem. Replacing cm-1 in the above command with `"cm-1"`, `Symbol(cm-1)`, and `Symbol("cm-1")` fail with errors as well. Is there any way to join dataframes on a column with a name containing a dash? If not, is there a way to join based on column index? I didn't see any reference to a way to do this in the documentation.

**Comment by ararslan** [comment]
Note that `:cm-1` is not a valid symbol; it's parsed as `:cm - 1`, i.e. subtracting 1 from the symbol `:cm`. Using `Symbol("cm-1")` should work. Can you elaborate on how that fails? It works for me:
```
julia> df1 = DataFrame(Symbol("cm-1") => [1,2,3], Symbol("cm-2") => [5,6,7])
3×2 DataFrame
│ Row │ cm-1 │ cm-2 │
├─────┼──────┼──────┤
│ 1   │ 1    │ 5    │
│ 2   │ 2    │ 6    │
│ 3   │ 3    │ 7    │

julia> df2 = DataFrame(Symbol("cm-1") => [1,4,5], Symbol("cm-3") => [0,0,0])
3×2 DataFrame
│ Row │ cm-1 │ cm-3 │
├─────┼──────┼──────┤
│ 1   │ 1    │ 0    │
│ 2   │ 4    │ 0    │
│ 3   │ 5    │ 0    │

julia> join(df1, df2, on=Symbol("cm-1"))
1×3 DataFrame
│ Row │ cm-1 │ cm-2 │ cm-3 │
├─────┼──────┼──────┼──────┤
│ 1   │ 1    │ 5    │ 0    │
```

**Comment by galaxite** [comment]
As it turns out, the error was in using a colon before Symbol. Using `join(df1, df2, on = :Symbol("cm-1")` Failed with the error `MethodError: objects of type Symbol are not callable`. Using `join(df1, df2, on = Symbol("cm-1")` worked perfectly. I was under the impression that the colon was necessary due to all of the examples in the documentation using a colon when referring to column names.

**Comment by ararslan** [comment]
I see. In general a `:` prefix denotes a symbol literal, but that can only be used with things that parse as valid identifiers in Julia. For "non-standard" names, e.g. those containing dashes or other characters which don't constitute valid identifiers, the `Symbol` type constructor is required.

This may be more technical than is helpful for this scenario, but you can check out the blurb about symbols in the Julia manual: https://docs.julialang.org/en/stable/manual/metaprogramming/#Symbols-1.
