### ISSUE TITLE
Make a DataFrame not iterable

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1513]
I recently ran into the following problem doing a bunch of regressions on a DataFrame

```
regress.(Ref(df), [:y, :y1, :y2, :y3], :treat)
```

I needed the `Ref(df)` because otherwise Julia would try to iterate over a DataFrame. Since I don't think there is a way to just iterate through a DataFrame (we restrict iteration to `eachcol` and `eachrow`), we should maybe add a method for `iterate(df::DataFrame)` that makes it work like `Ref`. 

I forget what the exact solution here is to make Julia always treat a DataFrame like a scalar.

**Comment by nalimilan** [comment]
Makes sense. Though we may want to wait for a bit in case we decided to make data frames iterables over rows or columns (https://github.com/JuliaData/DataFrames.jl/issues/1514).

**Comment by nalimilan** [comment]
https://github.com/JuliaData/DataFrames.jl/pull/1840 takes a different approach, which has quite strong advantages.

**Comment by bkamins** [comment]
Yes, and with #1840 you still can do `Ref(df)` if you want to avoid broadcasting over it.

**Comment by bkamins** [comment]
Closing it as `AbstractDataFrame` is considered 2-dimensional in broadcasting. Use `Ref` to protect it against being broadcasted over.

It is not related to being iterable - `AbstractDataFrame` is not iterable.
