### ISSUE TITLE
Sync documentation with CSV.jl

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1516]
When CSV.jl is tagged we should update DataFrames.jl documentation to reflect this (e.g. use `CSV.File` instead of `CSV.read`).

CC @quinnj

**Comment by quinnj** [comment]
I'm going to switch `CSV.read` to use `CSV.File(file) |> DataFrame` internally before the release, so we shouldn't need to change those uses. The only piece left is to put in a `transform` shim for backwards compatibility.

**Comment by bkamins** [comment]
I guess after all nothing changed as `CSV.read` survived so we can close it?
