### ISSUE TITLE
In `describe` print info about the dataframe

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1518]
`describe(df)` should also print the number of columns and rows of the DataFrame it is describing. It's useful when using `describe` inside a function where your access to the DataFrame you are working with is limited.

**Comment by nalimilan** [comment]
But where could be put that information?

**Comment by pdeffebach** [comment]
I was thinking just print it, then return the dataframe of summary statistics.

**Comment by nalimilan** [comment]
That would be quite ugly. Also what does this achieve that `print(size(df))` doesn't do? The main reason to store the size of the original data frame would be to access it when you only have the result of `describe(df)`, but printing it doesn't help for that...

**Comment by pdeffebach** [comment]
That's fair. 

On a related note, can we get the `coeftable` of a GLM model to show the N? Rather than doing `nrow(m.mf.df)`.

**Comment by nalimilan** [comment]
> On a related note, can we get the `coeftable` of a GLM model to show the N? Rather than doing `nrow(m.mf.df)`.

Not sure. But that's not the place to discuss this.
