### ISSUE TITLE
sorted data frames

### ISSUE THREAD

**Issue by gdkrmr** [JuliaData/DataFrames.jl#1522]
Are there sorted data frames analogously to `data.table` in `R`? This could make some operations much faster.

**Comment by nalimilan** [comment]
Not currently. It shouldn't be too hard to improve the grouping and joining code to handle `CategoricalArray` and `PooledArray` more efficiently. But adding support for primary keys would be more work.

BTW, please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
