### ISSUE TITLE
Sorting CategoricalArray{Union{Missing, String},1,UInt32} fails.

### ISSUE THREAD

**Issue by jbrea** [JuliaData/DataFrames.jl#1524]
DataFrames v0.13.1, julia 1.0
```julia
julia> df[:x]
3-element CategoricalArray{Union{Missing, String},1,UInt32}:
 "b"
 "b"
 "a"

julia> levels(df[:x])
2-element Array{String,1}:
 "b"
 "a"

julia> sort(df)
3×1 DataFrame
│ Row │ x │
├─────┼───┤
│ 1   │ b │
│ 2   │ b │
│ 3   │ a │

julia> df[:x] = convert(Array, df[:x])
3-element Array{String,1}:
 "b"
 "b"
 "a"

julia> levels(df[:x])
2-element Array{String,1}:
 "a"
 "b"

julia> sort(df)
3×1 DataFrame
│ Row │ x │
├─────┼───┤
│ 1   │ a │
│ 2   │ b │
│ 3   │ b │
```
I ran into this when loading data with CSV (see [this issue](https://github.com/JuliaData/CSV.jl/issues/290)).

**Comment by nalimilan** [comment]
What are the `levels` of the columns in each case?

**Comment by jbrea** [comment]
I updated the example with the `levels`. I also noticed that I copied to wrong line before: I used `convert(Array, ...)` (see updated comment above).

**Comment by nalimilan** [comment]
This behavior is expected, as it follows the order of levels. What needs to be changed is that CSV.jl should sort levels in lexicographic order by default. See https://github.com/JuliaData/CSV.jl/issues/278.
