### ISSUE TITLE
Cheat sheet for R users.

### ISSUE THREAD

**Issue by gdkrmr** [JuliaData/DataFrames.jl#1530]
I had to replicate a data wrangling pipeline from R in Julia and I must say that julia has some great potential but requires a different way of thinking about some things, maybe there should be a cheat sheet for R users. Should we use this Issue to collect some things?

- in place mutation of columns simply works with built-in `map!` which is so much better, than the weird `data.table` syntax, 
- `stack`/`unstack` is performant and works great and mostly as in R.
- `filter` is much better than creating extra index vectors. At some point someone should probably create a cheat sheet for R users.

**Comment by ararslan** [comment]
I believe such a thing exists somewhere, but I can't recall who it was who made it. @piever maybe?

**Comment by nalimilan** [comment]
@Rev (on Slack) worked on that, but I'm not sure what's the status of it. I've asked for an update.

Rather than collecting ideas here, better start a PR adding a new section to the manual comparing with other software. We can always expand it progressively.

**Comment by quinnj** [comment]
https://docs.google.com/spreadsheets/d/106zpZ0YlFFOp_tcicZsqy_isE-N_1GmTMpP1AGTJUmQ/edit?usp=drive_web&ouid=108647191993543264668

**Comment by piever** [comment]
There also is a powerpoint version, not sure which is the most up to date:

[Data_Cheatsheet_DFQDFM.pptx](https://github.com/JuliaData/DataFrames.jl/files/2408865/Data_Cheatsheet_DFQDFM.pptx)

I think it's best to ask in the `#cheatsheet` channel on slack for more details  I guess transforming the excel table into a Markdown table and adding it to the docs would already be helpful?

The JuliaDB part is not very up to date ,but I guess that's not very relevant here, though in the end it'd be ideal to have a similar cheat sheet on JuliaDB as well.

**Comment by nalimilan** [comment]
Thanks. Having it in the online manual would be nice. We could imagine having a nicer-looking PDF version, but the priority is to have it available in the manual.

**Comment by tk3369** [comment]
Hi everyone 👋 

I have tried my best to put together a nice looking cheat sheet. Can you please review and let me know what you think?

Here's the link. Please look at the first two pages only. The other pages contain old copy or graphics artifacts:

https://docs.google.com/presentation/d/1mpvPyR0z3MY23sPtzQP2xICBWU8XyGBuU2M2eyf4jPM/edit?usp=sharing

Let me start with some questions:
* Do you feel the cheat sheet is complete (or is there any major function missing)?
* Do you find the organization of the content intuitive?
* Do you see any typos or other dumb mistakes?
* Is there anything you want to emphasize or add?

Thank you!

**Comment by bkamins** [comment]
Can you please give me some way to comment on this document as I would like to add some remarks in specific places. Thank you!

**Comment by tk3369** [comment]
I have just updated the permission to allow comments. Can you try again with the same link above?

**Comment by tk3369** [comment]
@bkamins Thanks for your feedback. 

I have published a PDF to my own web site:
https://ahsmart.com/assets/pdf/DataFramesCheatSheet_1.0.0.pdf

Please don't hesitate to tell me if you have any last minute requests.  Now, what would be the best place to place a link in DataFrames.jl documentation? Would you want me to submit a PR for that?

**Comment by bkamins** [comment]
I have left one small comment.

Regarding the link:
1. I would put it in DataFrames.jl/docs/src/index.md after the note on on the tutorials in Jupyter notebook (when you open that PR can you please link it with this issue so that this issue is closed then?)
2. if you can - it would be better create a separate webpage on your blog, where versions of the document can be kept (so the link would be to the page not to the document)
3. then name the document with a version of DataFrames.jl as a suffix to it

In this way we will have one link when users go (so that we do not have to update it with every version of DataFrames.jl or version of your cheat sheet) and can select an appropriate version of the tutorial depending on what version of DataFrames.jl they use (and in the long term it will be a nice account of the history of the document :smile:).

Here you have an example what I have in mind http://bogumilkaminski.pl/projects/ (the section on The Julia Express)

**Comment by bkamins** [comment]
Ah - and then on such a page you can also add the notebooks with comparisons you have created.

**Comment by tk3369** [comment]
Great idea! I also like your idea of synchronizing the version of cheat sheet with DataFrames.jl. The current file is marked as v0.21.

OK, here we go. I have just published the blog post:
https://ahsmart.com/pub/data-wrangling-with-data-frames-jl-cheat-sheet/

I will submit a PR with the link later.  

Thanks again for spending time reviewing the cheat sheet.

**Comment by bkamins** [comment]
This is looking great. So I am closing this issue as we have a cheat sheet now :smile:. And waiting for the PR with the link.

**Comment by tk3369** [comment]
@bkamins @nalimilan I have made some edits given some suggestions by several people. Please take a look the new revision if you have some spare time. Thanks again!

https://github.com/tk3369/www.ahsmart.com/pull/3

**Comment by rikhuijzer** [comment]
> @bkamins @nalimilan I have made some edits given some suggestions by several people. Please take a look the new revision if you have some spare time. Thanks again!
> 
> [tk3369/www.ahsmart.com#3](https://github.com/tk3369/www.ahsmart.com/pull/3)

Awesome! I wish that I found this cheat sheet much earlier!
