### ISSUE TITLE
Implement `repeat(df::AbstractDataFrame, kw...)`

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataFrames.jl#1541]
From the Slack#data,
```
repeat(df::AbstractDataFrame; inner::Integer = 1, outer::Integer = 1) =
    map(x -> repeat(x, inner = inner, outer = outer), eachcol(df))
```
might be nice to have in order to repeat the DataFrame's rows.

**Comment by bkamins** [comment]
Nice. Thank you. Maybe also add the version with positional parameter `repeat(df::AbstractDataFrame, count::Integer)`.

Also I think that in this method we should treat `DataFrame` as row-wise collection (which is consistent which what you poroposed above) and not a 2-D object (where `inner` and `outer` would require 2-element tuples).

Let us wait if we get any feedback on it and having this PR would be nice.

**Comment by nalimilan** [comment]
Sure, why not. That's one of the advantages of deciding that data frames are collections of rows (https://github.com/JuliaData/DataFrames.jl/issues/1514).

**Comment by Nosferican** [comment]
For the specific PR, is there anything I should be aware of from issue 1514 or should the snipped from above be good?

**Comment by nalimilan** [comment]
No, that should be enough.

**Comment by Nosferican** [comment]
Any particular in the documentation or should it be implied?

**Comment by nalimilan** [comment]
Yes, a docstring would be useful, with a small example.

**Comment by bkamins** [comment]
Close?
