### ISSUE TITLE
Remove row with missing values in a specific column?

### ISSUE THREAD

**Issue by Moelf** [JuliaData/DataFrames.jl#1544]
I'm dealing with a data set where one column is poorly documented so `dropmissing` will wipe out most of the data, I can, of course, remove that column before `dropmissing` but that required touching the raw data in some sense. Is there any easy way of dropping rows if it's missing in a column when? Also it seems `df[!isa.(df.wanted, Missing),:]` does not work for some reason.

Now the work around is
```Julia
df = df[isa.(df.wanted, String),:];
```

**Comment by ararslan** [comment]
> Also it seems `df[!isa.(df.wanted, Missing),:]` does not work for some reason.

```julia
filter!(row->!ismissing(row.wanted), df)
```

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/DataFrames.jl/pull/1546.
