### ISSUE TITLE
standardized return values for groupby

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1554]
I seem to recall that at some point we had discussed and agreed that
```julia
by(identity, df, cols)
```
where `cols` is any subset of `names(df)` should return `df` up to an ordering ambiguity.

Currently this is not the case since the key columns are appended after the group by operation.

Do we indeed agree that this should change?  Would you accept a PR?

I seem to recall that pandas does what I'm suggesting, but I don't remember for sure and haven't checked.

**Comment by nalimilan** [comment]
See also https://github.com/JuliaData/DataFrames.jl/issues/1460. I don't think we should omit the key columns by default, as they are needed most of the time (I would say). Can you check what Pandas does? But adding an argument is OK.

**Comment by bkamins** [comment]
I would say that resolving this issue is crucial before we move to 1.0 release in the "`by` world".

@nalimilan - do you have a recommendation what we should do with "duplicate columns" produced by adding key columns by default?

**Comment by nalimilan** [comment]
My latest thoughts are at https://github.com/JuliaData/DataFrames.jl/issues/1460#issuecomment-456061006. Let's close this in favor of the other issue. I've filed https://github.com/JuliaData/DataFrames.jl/pull/1938 to implement the proposed solution.
