### ISSUE TITLE
Using columns for multidimensional data

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaData/DataFrames.jl#1561]
I'm working a lot with experimental data from motion and perception experiments which has both 3D positions and rotation matrices for many points in time and "normal" data that you would usually expect in something like a DataFrame, like trial number, response codes, and so on.

I really like the way that DataFrames enable easy grouping, sorting, filtering, and plotting. But the multidimensionality of my 3D related data is always a problem. At each time point, so in each row, I have for example three position vectors and one rotation matrix. So at 1000 timepoints the rotation matrices give a 1000x3x3 array. But this is incompatible with DataFrames, which want one-dimensional columns. I don't want to make 9 columns for one "rotation matrix column", this is very unwieldy. But I do want to be able to, e.g., group by trial number, aggregate over the rotation matrices from each trial and calculate some measure, like average rotational velocity, and then plot that vs. responses. 

I have been thinking about using structs for Matrix and Vector and just make one-dimensional arrays from them, but that means I have to define things like matrix multiplication again, which is unnecessary work.

So the question is, how, if at all, can I use data like that, which in a way does fit the row-based thinking of a dataframe, because there is one row per time point, but causes confusion because of its multidimensionality, be handled together with "normal" one-dimensional data that my experiments produce. The combination could be powerful for me, but I'm not sure if a use case like this is intended or wanted.

**Comment by bkamins** [comment]
I am not sure I understand your problem 100% correct, but if I do, then please note that you can store matrices as elements of a column without a problem:
```
julia> DataFrame(matcol = [rand(3,3) for i in 1:4])
4×1 DataFrame
│ Row │ matcol                                                                               │
│     │ Array{Float64,2}                                                                     │
├─────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ 1   │ [0.0823894 0.538344 0.60286; 0.959839 0.167538 0.938625; 0.617904 0.559031 0.104505] │
│ 2   │ [0.0313417 0.812845 0.93416; 0.168691 0.0599238 0.79322; 0.654181 0.98544 0.946063]  │
│ 3   │ [0.830969 0.519575 0.617817; 0.361729 0.412819 0.124425; 0.966598 0.457171 0.212443] │
│ 4   │ [0.340811 0.0419007 0.43488; 0.463433 0.350025 0.986326; 0.923016 0.600933 0.967976] │
```
Does this solve your issue?

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
