### ISSUE TITLE
Add dimensions to HTML output

### ISSUE THREAD

**Issue by nilshg** [JuliaData/DataFrames.jl#1563]
Similar to what pandas does in jupyter: when displaying a table, print dimensions at the bottom.

This should probably just be a couple of lines at the end of this block:
https://github.com/JuliaData/DataFrames.jl/blob/4e7d4bf90c9c712d8c59e063b749c0269f65b451/src/abstractdataframe/io.jl#L75

Could try adding this unless there are objections to it?

**Comment by scls19fr** [comment]
![capture d ecran 2018-10-11 a 13 40 16](https://user-images.githubusercontent.com/109167/46801548-40579600-cd5b-11e8-850f-d59f50acead3.png)

It seems to that Jupyter only display size of Pandas DataFrame when number of rows exceed 100

![capture d ecran 2018-10-11 a 13 40 16](https://user-images.githubusercontent.com/109167/46801665-99272e80-cd5b-11e8-816b-7b9b807227fa.png)

or number of columns exceed 20

![capture d ecran 2018-10-11 a 13 42 43](https://user-images.githubusercontent.com/109167/46801678-a3e1c380-cd5b-11e8-9f2e-140a19dfd5f0.png)

**Comment by nilshg** [comment]
Yes that's a good point - clearly this is less relevant for DataFrames where all rows and columns are displayed anyway!

**Comment by nalimilan** [comment]
I think it makes sense to print the dimensions of the data frame in all cases. @bkamins?

Also, we should probably change the output (at least for IJulia) to enable scrolling with a fixed header. That's much more useful for large tables.

**Comment by bkamins** [comment]
It would be consistent to add it (we print it in REPL over the data actually).
I will investigate if we can fix the header (it should be possible with pure CSS I think).

**Comment by bkamins** [comment]
At least on my IJulia I get a horizontal scrollbar, but no vertical scrollbar and the output is truncated (and resizing the browser window does not change anything).

Do you have a different behavior?

@nilshg In summary 😄: please go ahead and push a PR with dimensions of a `DataFrame`. If you care to investigate more the following issues are also on my TO-DO:
* HTML printing `DataFrameRow` and `GroupedDataFrame` could be improved;
* the issue with number of rows printed for `AbstractDataFrame` is not perfect (maybe only on my IJulia) - could you report what you have (also @nalimilan - what do you get).
* maybe some ideas for text/plain printing of `DataFrameRow` improvement (as it is not ideal now and after changes @nalimilan and I are discussing in #1534 they will get much more common in daily usage of DataFrames.jl)

**Comment by nalimilan** [comment]
I don't use IJulia so I have no idea what it looks like there.

**Comment by nilshg** [comment]
So I've added a pull request on the first bit (will try to play around with the other bits as well if I find time!) but for some reasons the automated checks fail - not sure what's happening here as I've never done a pull request on a properly run repo that has tests and everything!

FWIW the changes work as intended on my local branch.

**Comment by bkamins** [comment]
Can we close this?
