### ISSUE TITLE
Support for construction from a named tuple?

### ISSUE THREAD

**Issue by jlperla** [JuliaData/DataFrames.jl#1573]
I think this is related to #1569 but gives a very specific suggestion.

Existing DataFrames seem to play very well with named tuples.  FOr example,
```julia
julia> df = DataFrame(a = Float64[], b = Int64[])
0×2 DataFrame

julia> push!(df, (a = 4.0, b = 2))
1×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 4.0     │ 2     │
```
What is irritating is that you cannot create the DataFrame directly from the named tuple, and instead need to specify types yourself.

There is a workaround with splatting, which can rely entirely on inference!
```julia
julia> t = (a = 4.0, b = 2)
(a = 4.0, b = 2)

julia> df = DataFrame(;t...)
1×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 4.0     │ 2     │
```
So my question is: (1) is there any real flaw in the splatting interface
and (2) would you be interested in a PR that makes this more explicit.  That is,  it would add in a constructor for named tuples and support 
```
julia> t = (a = 4.0, b = 2)
(a = 4.0, b = 2)

julia> df = DataFrame(t) # not valid, but could be
1×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 4.0     │ 2     │
```

**Comment by nalimilan** [comment]
Splatting should be OK. You can also do `DataFrame([(a = 4.0, b = 2)])`.

Whether or not constructors should allow this also depends on whether we want to allow this for Tables.jl. Cc: @quinnj

**Comment by quinnj** [comment]
I don't think Tables.jl would do something like this; _technically_, `(a = 4.0, b = 2)` is a NamedTuple of "iterables", but only because `4.0` and `2` themselves are iterable (though this has been debated a lot and most think scalars _shouldn't_ iterate). So for the time being at least, valid "tables" from Tables.jl perspective include a vector of namedtuples or a namedtuple of abstractvectors, but not plain namedtuples.

**Comment by jlperla** [comment]
OK, I didn't know that would work.  Solatting is pretty tough for new users, but:

SO you are saying that
```julia
julia>  t = (a = 4.0, b = 2)
(a = 4.0, b = 2)

julia> using DataFrames

julia> df = DataFrame([t])
1×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 4.0     │ 2     │
```
seems reasonable enough.  Should we make a PR for this in the docs?

**Comment by jlperla** [comment]
Also, it generalizes well if you want to seed a `DataFrame` from multiple named tuples.
```
julia>  t = (a = 4.0, b = 2)
(a = 4.0, b = 2)
julia>  t2 = (a = 4.0, b = 3)
(a = 4.0, b = 3)

julia> df = DataFrame([t, t2])
2×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 4.0     │ 2     │
│ 2   │ 4.0     │ 3     │
julia> using DataFrames

julia> df = DataFrame([t])
1×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 4.0     │ 2     │
```
We could add something like that to the construction section in http://juliadata.github.io/DataFrames.jl/latest/man/getting_started.html#The-DataFrame-Type-1 ?

**Comment by quinnj** [comment]
That sounds good to me.

**Comment by nalimilan** [comment]
Why not. Maybe right before the examples showing `push!`.

**Comment by quinnj** [comment]
The tricky part of supporting that would be ambiguity with `DataFrame(nt)` where `nt` is a NamedTuple of Vectors. For that case, we want it to dispatch to the catchall Tables.jl constructor. Currently it's not easy to write a method signature for the "symdiff" though.

**Comment by bkamins** [comment]
I would close this issue for the reasons given in the last two posts. Any objections?
