### ISSUE TITLE
allow vcat to widen columns

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1574]
This has been discussed before `vcat` should widen columns and replace columns that are in one column but not the other with a value of one's choosing, such as `missing`. Or there should be another name for this function. 

*or* something like this this belongs in the new [TableOperations.jl](https://github.com/JuliaData/TableOperations.jl) @quinnj  

```
function top(dfupper::AbstractDataFrame, dflower::AbstractDataFrame; widen = :all, fillval = missing)
       namesupper = names(dfupper)
       namesupper = names(dflower)
       
       nrowupper = nrow(dfupper)
       nrowlower = nrow(dflower)
       
       function _top(nrowupper, nrowlower, uppervec::AbstractVector, lowervec::AbstractVector)
              vcat(uppervec, lowervec)
       end
       
       function _top(nrowupper, nrowlower, uppervec::Nothing, lowervec::AbstractVector)
              vcat(fill(fillval, nrowupper), lowervec::AbstractVector)
       end
       
       function _top(nrowupper, nrowlower, uppervec::AbstractVector, lowervec::Nothing)
              vcat(uppervec, fill(fillval, nrowlower))
       end
       
       out = DataFrame()
       if widen == :all
              all_names = unique([namesupper; namesupper]) 
              for name in all_names
                     out[name] = _top(nrowupper, nrowlower, get(dfupper, name, nothing), get(dflower, name, nothing))
              end
       end
       # widen = :upper and widen = :lower
       return out
end
```

API issues to consider:
- [ ] What do tidyverse, Pandas, and Stata allow and what are their APIs
- [ ] How to deal with promoting types. Should we let the user `vcat` string and number columns?

**Comment by nalimilan** [comment]
See previous discussion at https://discourse.julialang.org/t/vcat-does-not-append-dataframe-rows-as-it-did-in-0-10/9823/2. tl;dr: I think we should just add a keyword argument to allow this.

Note that we already promote types in `vcat`, so I don't see the problem for the present issue.

**Comment by bkamins** [comment]
@pdeffebach can this be closed given current `vcat` implentation on master?

**Comment by pdeffebach** [comment]
Yes! please close this.
