### ISSUE TITLE
Make API more Julian

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#159]
This issue is meant to be a catch-all for cleaning up the DataFrames API. We should wait a few weeks to make changes:
- `duplicated` => `duplicates`
- `drop_duplicates!` => `delete_duplicates!`

Please copy the list of proposed changes in each response to make it easier to work through this.

**Comment by nalimilan** [comment]
This is too old to be relevant. All the `col*` functions have been removed a long time ago.
