### ISSUE TITLE
SubDataFrame is not an iterable table

### ISSUE THREAD

**Issue by mkborregaard** [JuliaData/DataFrames.jl#1597]
A SubDataFrame is not an iterabletable, making it incompatible with that framework.

cf https://github.com/queryverse/IterableTables.jl/issues/76
cf https://github.com/JuliaPlots/StatPlots.jl/issues/197

**Comment by davidanthoff** [comment]
It might be enough to change the method signatures of the three methods at the end [here](https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl#L44) to ``AbstractDataFrame``?

@quinnj, or was there a reason to not do that?

**Comment by quinnj** [comment]
Yeah, I think that would work; for those lines, I just copied the definitions from [IterableTables.jl](https://github.com/queryverse/IterableTables.jl/blob/master/src/integrations/dataframes.jl#L3)

**Comment by ErwanPiR** [comment]
Hi,
I'm sorry to ask so dumb question (I'm kind of new with Git...) but how do I know that the modifications have been made ? And if so, is it enough to update the package ?
Thanks
