### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataFrames.jl#1604]
Any chance that a new release could be tagged? It would be great if there was a version out there that has https://github.com/JuliaData/DataFrames.jl/pull/1579 included.

**Comment by nalimilan** [comment]
We're working on it but we want to merge https://github.com/JuliaData/DataFrames.jl/pull/1601 first.

**Comment by davidanthoff** [comment]
#1601 is nice, but it also is quite big and involved. If there is a chance to do a small release before that (simply just tag the current ``master``) it would be great.

**Comment by nalimilan** [comment]
The grouping API on master which hasn't been released yet is going to change slightly, so we cannot tag before #1601. Also we've introduced lots of painful deprecations, so better also offer new features to make the release more appealing.

**Comment by davidanthoff** [comment]
Ah, ok, I wasn't aware of that, then it of course makes sense to wait!

**Comment by bkamins** [comment]
Closing as the release was tagged.
