### ISSUE TITLE
Constructor from column names

### ISSUE THREAD

**Issue by ErwanPiR** [JuliaData/DataFrames.jl#1609]
Hi,

I can't find a solution to build a new DataFrame with the same columns that an existing one.
The idea would be to do if `df` is a DataFrame :
`new_df = DataFrame(names(df))`

Is that possible in a way ?

Thanks.

**Comment by pdeffebach** [comment]
```
new_df = DataFrame()
for name in names(df)
    new_df[name] = []
end
```

**Comment by ErwanPiR** [comment]
Thanks ! That's a way to do it 👍

**Comment by nalimilan** [comment]
There's also `similar`. But please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
