### ISSUE TITLE
DataFrames should be indexable by `CartesianIndex{2}`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1610]
It should be possible to do, for example
```julia
for idx ∈ CartesianIndices(size(df))
    println(df[idx])
end
```

**Comment by nalimilan** [comment]
I guess that would be consistent, but in what situations would it be useful?

**Comment by ExpandingMan** [comment]
It's just a standard way to iterate over things.  I for one use it more and more.  It's already column major so it's a good way to iterate.  If you ever are iterating over a matrix and a dataframe at the same time, it might be useful.

I'd be happy to make the PR, when I get to it.

**Comment by nalimilan** [comment]
Iterating over a data frame and a matrix at the same time is unlikely to be a good idea given how slow it's going to be compared to iterating over columns...

**Comment by ExpandingMan** [comment]
Well, they are both column major so if you have to iterate over the dataframe anyway I don't really see what harm it would do (other than typing issues of course).

Regardless, is there some reason you are opposed to making dataframes indexable by `CartesianIndex`?

**Comment by nalimilan** [comment]
Well the type-instability issue is a big problem in terms of performance. I'm not really opposed to supporting cartesian indexing, I'm just not sure it's really useful.

**Comment by bkamins** [comment]
I think it is not a problem to have it for `AbstractDataFrame` and possibly for `DataFrameRow` also if we want a complete coverage.

**Comment by bkamins** [comment]
We now allow `CartesianIndex{2}` indexing so I am closing this.

**Comment by bkamins** [comment]
(we do not provide `CartesianIndices` though. If you feel it should be added please reopen and it can be discussed.
