### ISSUE TITLE
split-apply-combine depwarns

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1623]
Currently running `by` and similar prints depwarns on first run, e.g.:
```
julia> using DataFrames

julia> df = DataFrame(rand(4,5))
4×5 DataFrame
│ Row │ x1       │ x2       │ x3       │ x4       │ x5        │
│     │ Float64  │ Float64  │ Float64  │ Float64  │ Float64   │
├─────┼──────────┼──────────┼──────────┼──────────┼───────────┤
│ 1   │ 0.507518 │ 0.343065 │ 0.250251 │ 0.925915 │ 0.685284  │
│ 2   │ 0.194043 │ 0.223878 │ 0.119892 │ 0.113459 │ 0.205621  │
│ 3   │ 0.930018 │ 0.113958 │ 0.293055 │ 0.75793  │ 0.574463  │
│ 4   │ 0.694755 │ 0.907914 │ 0.61208  │ 0.345201 │ 0.0718849 │

julia> by(df, :x1, identity)
┌ Warning: Indexing into a return value of columns on SubDataFrame will return a view of column value
│   caller = _broadcast_getindex at broadcast.jl:540 [inlined]
└ @ Core .\broadcast.jl:540
┌ Warning: Indexing into a return value of columns on SubDataFrame will return a view of column value
│   caller = copyto_nonleaf!(::Array{DataType,1}, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(eltype),Tuple{Base.Broadcast.Extruded{DataFrames.DataFrameColumns{SubDataFrame{Array{Int64,1}},AbstractArray{T,1} where T},Tuple{Bool},Tuple{Int64}}}}, ::Base.OneTo{Int64}, ::Int64, ::Int64) at broadcast.jl:540
└ @ Base.Broadcast .\broadcast.jl:540
┌ Warning: `sdf[colind]` will create a view of `parent(sdf)[colind]` in the future. Use sdf[:, colind]` to get a freshly allocated vector.
│   caller = append_rows!(::SubDataFrame{Array{Int64,1}}, ::NTuple{5,Array{Float64,1}}, ::Int64, ::NTuple{5,Symbol}) at grouping.jl:566
└ @ DataFrames C:\Users\bogum\.julia\packages\DataFrames\lsL3v\src\groupeddataframe\grouping.jl:566
4×6 DataFrame
│ Row │ x1       │ x1_1     │ x2       │ x3       │ x4       │ x5        │
│     │ Float64  │ Float64  │ Float64  │ Float64  │ Float64  │ Float64   │
├─────┼──────────┼──────────┼──────────┼──────────┼──────────┼───────────┤
│ 1   │ 0.507518 │ 0.507518 │ 0.343065 │ 0.250251 │ 0.925915 │ 0.685284  │
│ 2   │ 0.194043 │ 0.194043 │ 0.223878 │ 0.119892 │ 0.113459 │ 0.205621  │
│ 3   │ 0.930018 │ 0.930018 │ 0.113958 │ 0.293055 │ 0.75793  │ 0.574463  │
│ 4   │ 0.694755 │ 0.694755 │ 0.907914 │ 0.61208  │ 0.345201 │ 0.0718849 │
```

it could be fixed (as in e.g. in #1619).
@nalimilan - do we want to do this? It would produce another set of functions in `deprecated.jl` to be removed soon.

Also there is the following consideration:
```
julia> x = 1:10^6;

julia> y = 1:2:10^6
1:2:999999

julia> x = 1:10^6;

julia> y = 1:2:10^6;

julia> f1(x,y) = sum(view(x, y))
f1 (generic function with 1 method)

julia> f2(x,y) = sum(x[y])
f2 (generic function with 1 method)

julia> using BenchmarkTools

julia> @benchmark f1($x, $y)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.920 μs (0.00% GC)
  median time:      3.920 μs (0.00% GC)
  mean time:        4.312 μs (0.00% GC)
  maximum time:     37.205 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     8

julia> @benchmark f2($x, $y)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     22.618 ns (0.00% GC)
  median time:      23.133 ns (0.00% GC)
  mean time:        25.427 ns (0.00% GC)
  maximum time:     270.907 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```
and we see that using a view slows things down (e.g. SIMD is disabled then)

**Comment by nalimilan** [comment]
I'm not sure what can be done about this, except removing the deprecations. What methods do you think we could overload?

Regarding the benchmarks you show, they test a very specific case where both vectors are ranges, which should rarely happen in practice. If I add `collect` calls, I observe that the view is faster. That said, this reminds us that it could be useful to be able to detect when groups are already sorted so that their indices can be ranges instead of vectors, producing more efficient code.

**Comment by bkamins** [comment]
E.g. you would have to change `append_rows!` method line 566: `vals = rows[cn]` to `vals = rows[:, cn]` if `rows` is `SubDataFrame`. I have not tracked if this fixes all warnings as I thought we would leave those warnings.

Regarding timngs - I know but I give you a case when the difference is striking. Actually I think it would be good to have our own internal benchmark suite for DataFrames.jl. I can start writing it if you are OK with it (and do not have already something as then could you please share it). Then I can set-up a website tracking benchmarks as we progress with versions. The question is - what is the recommended way to do it (should it be a part of DataFrames.jl package or a separate package just for testing)? Or maybe there should be a completely different approach to it.

**Comment by nalimilan** [comment]
> E.g. you would have to change `append_rows!` method line 566: `vals = rows[cn]` to `vals = rows[:, cn]` if `rows` is `SubDataFrame`. I have not tracked if this fixes all warnings as I thought we would leave those warnings.

OK. Yeah, why not, if you're willing to do the work. I wonder whether there's an end to adding custom methods... :-)

It would be really great to have a benchmark suite! I'd use PkgBenchmark to add a `benchmark` directory to this repo, taking inspiration from existing benchmarks like H2O or [tpch-dbgen](http://github.com/electrum/tpch-dbgen) (BTW, a researcher contacted me and had ported some code to DataTables at the time, see https://gist.github.com/hannesmuehleisen/eed0f1b0cb8fdf4db56a6a852ee392bb).

**Comment by bkamins** [comment]
> I wonder whether there's an end to adding custom methods...

Probably not - and that is why I have tagged the release.

Regarding benchmarks - I will start something (but it is not clear for me from the PkgBenchmark.jl package documentation how to integrate it with CI).
