### ISSUE TITLE
Change in constructor operation / No variable allowed

### ISSUE THREAD

**Issue by patdub** [JuliaData/DataFrames.jl#1638]
Hello,
in a previous version of DataFrames (don't know exactly which it was), I was able to use variable in constructor. This code was working 
xd = DataFrame(name=String[],typ=Float64[],min=Float64[],max=Float64[],law=String[],avg=Float64[],std=Float64[])
push!(xd,(name="Voff",typ=0,min=-850e-6,max=850e-6,law="uniform",avg=(max+min)/2,std=(max-min)/8))

This was a compact solution to compute values of variables during their definition.

The same code is not working anymore.

Is it an intentional change or not ?

What could be the solution with new version (I would like to limit the number of lines because I have lot of parameter to define and don't want to increase the code length if possible). 

Thanks in advance.
Patrick.

**Comment by nalimilan** [comment]
That cannot possibly have worked, since variables are resolved by Julia before DataFrames has a chance to look at them. Maybe have a look at DataFramesMeta or Query (and please use Discourse for questions).
