### ISSUE TITLE
Export function for getting row number of DataFrameRow

### ISSUE THREAD

**Issue by kescobo** [JuliaData/DataFrames.jl#1647]
There's an internal function `DataFrames.row()` (defined [here](https://github.com/JuliaData/DataFrames.jl/blob/master/src/dataframerow/dataframerow.jl#L27)) that returns the index of a `DataFrameRow`, which I often need while iterating. It would be nice if that function were exported, though `row()` is probably too generic. Maybe `rownumber` or something? 

I'd be happy to submit a PR if others would find this useful.

**Comment by bkamins** [comment]
As indicated on https://julialang.slack.com/archives/C674VR0HH/p1545250280227000 we currently define `parentindices` which is a standard function in Base to get this information (row number is the first entry in the returned tuple).
Is this enough?

**Comment by nalimilan** [comment]
I don't really like the idea of exporting two more functions just for this. What's wrong with `enumerate(eachrow(df))`? `parentindices(r)` isn't too bad either when you need the column indices in the parent.

**Comment by bkamins** [comment]
There is one important thing here to remember. `parentindices(dfr,2)` gives you indices to `parent(dfr)`, however `parent(dfr)` does not have to be the data frame you have used to create the `DataFrameRow`. The same applies to `SubDataFrame`.

Of course in the most common case of `eachrow(df)` this does not matter, but it will matter eg. for `df[row, cols]` when `cols` is not a `Colon`.

So the decision to make is do we want to hold the true *parent* of `DataFrameRow` and `SubDataFrame` along with indices into it? It should be cheap. Actually the strategy should probably be to hold a vector of integer indices or a range (thus we will have to add an additional parameter to the types).

I was hesitant to do it, but now I see how it can be efficiently implemented so I could submit a PR if all agree (actually something like `df[1, 1:3]` should become much faster). Of course it will work as long as parent columns are not mutated (current implementation makes a copy and thus does not reflect the changes to the parent). This means that we would be mildly breaking (but I guess no one would notice it so I would go for it right away).

**Comment by kescobo** [comment]
I only understand ~60% of what you're saying, but sounds great! 😆

**Comment by bkamins** [comment]
In short - currently `parent` of `SubDataFrame` and `DataFrameRow` is a copy of the original `AbstractDataFrame` if you do column selection on it. We can avoid it and at the same time improve the performance.

**Comment by bkamins** [comment]
closing as we have implemented all that was discussed

**Comment by bkamins** [comment]
if I missed something please reopen
