### ISSUE TITLE
New contents about handing missing values in DataFrame

### ISSUE THREAD

**Issue by petershintech** [JuliaData/DataFrames.jl#1662]
When comparing the original Julia document about "Missing Values", I cannot see any additional information (except a brief introduction to coalesce() and replace()) from this document (DataFrames.jl/docs/src/man/missing.md)

How about replacing the document with new contents about the same topic but using DataFrames as examples?

**Comment by nalimilan** [comment]
Sure, help to improve the documentation is always welcome.

**Comment by bkamins** [comment]
closing as I am not sure what to add.
