### ISSUE TITLE
Failed tests for constructors

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [JuliaData/DataFrames.jl#1669]
Julia 1.0.3, MacOSX 10.14.1: Running `test DataFrames` gives following two errors:

constructors: Test Failed at .../.julia/packages/DataFrames/KUWId/test/constructors.jl:24
Expression: df == DataFrame(Any[CategoricalVector{Union{Float64, Missing}}(zeros(3)), CategoricalVector{Union{Float64, Missing}}(ones(3))])

constructors: Test Failed at .../.julia/packages/DataFrames/KUWId/test/constructors.jl:31
Expression: DataFrame([1:3, 1:3]) == DataFrame(Any[1:3, 1:3]) == DataFrame(UnitRange[1:3, 1:3]) == DataFrame(AbstractVector[1:3, 1:3]) == DataFrame([[1, 2, 3], [1, 2, 3]]) == DataFrame(Any[[1, 2, 3], [1, 2, 3]])

**Comment by nalimilan** [comment]
What version?

**Comment by marcel-goldschen-ohm** [comment]
v0.15.2
