### ISSUE TITLE
Deprecation warning for readtable premature because of slow CSV.read performance

### ISSUE THREAD

**Issue by tobiassalz** [JuliaData/DataFrames.jl#1676]
The CSV.read command is still very slow for large datasets. This means a suboptimal (and sometimes infeasible) code (using CSV.read) will be necessary to not break the code in 1.0

**Comment by nalimilan** [comment]
This has been discussed many times before. `readtable` hasn't been removed because of that, but we're not going to undeprecate it. Please file issues against CSV.jl if you experience slowdowns.
