### ISSUE TITLE
Undeprecate `DataFrameRow(df, i)`

### ISSUE THREAD

**Issue by rofinn** [JuliaData/DataFrames.jl#1696]
I'm not really clear why `DataFrameRow(df, i)` was deprecated, but that seems like a bad idea as `DataFrameRow(df, i, :)` doesn't seem like an intuitive API.

**Comment by ararslan** [comment]
To me "row" already implies that you're selecting all columns from the row, so the `:` (which I assume indicates selecting all columns) feels redundant.

**Comment by ararslan** [comment]
For reference, the deprecation was added in https://github.com/JuliaData/DataFrames.jl/pull/1648.

**Comment by nalimilan** [comment]
Fine with me (though note `df[i, :]` is shorter). @bkamins?

**Comment by rofinn** [comment]
@bkamins Thanks for the explanation. I still think that the column vs row indexing distinction could have been minimized by always indexing rows by integers and columns by symbols. 

One of our use cases is building up hash indices of our "primary key". We can then cache these hashes for future queries.

```
for i in 1:n
     r = DataFrameRow(df, i)

     # Some checks to avoid computing a hash for a row that we aren't going to need to query

     pk_hashes[i] = hash(tuple((r[c] for c in latest_key)...))
end
```

I suppose we could replace that with an `enumerate(eachrow(df))` call, but that seems a bit unnecessary if `DataFrameRow` already exists (assuming that we aren't calling `DataFrameRow(df, :, i)`).

**Comment by bkamins** [comment]
> `r = df[i, :]`

that was my point. In this way a new user does not have to learn about DataFrames.jl internals - it is enough that one knows Base.

> column vs row indexing distinction could have been minimized by always indexing rows by integers and columns by symbols.

Actually given we now treat `AbstractDataFrame` as a collection of rows by default I would prefer `df[idx]` to always perform row selection than column selection - no matter what `idx` is, but I guess it would be too breaking. This would be mostly non-problematic for users as we support `df.col` for column selection syntax via `getproperty`.

**Comment by bkamins** [comment]
But I think if the majority wants to keep `DataFrameRow(::AbstractDataFrame, ::Integer)` I will not object. I will make a PR and document this exception to the general rules we have.

**Comment by rofinn** [comment]
> For something even more efficient, see the internal hashrow_cols function.

Thanks, I'll take a look at it. I'll note that the checks for skipping the `hash` call require looking at various columns, so the `hashrows_col!` approach would require multiple passes over the dataframe (one pass for the mask and another for the colwise hashing).

**Comment by ararslan** [comment]
> Regarding using `df[i, :]` I feel like it's helpful to explicitly state that something is a `DataFrameRow` in code that's using both dataframes and regular array structures.

I'll note that this can also be accomplished with type annotations, e.g.
```julia
row = df[i,:]::DataFrameRow
```

**Comment by bkamins** [comment]
So - given the discussion - are we still willing to remove the deprecation or the patterns using `getindex` are enough?

Could I ask you to add 👍 to this post if you want to allow `DataFrameRow(df, idx)` it and 👎  if we want to keep the current design that deprecates it and finally will remove this method. Thank you.

**Comment by rofinn** [comment]
Do you see any cost with keeping it, apart from reverting a deprecation? I'd be fine with dropping the export if you'd like.

**Comment by bkamins** [comment]
The only cost is consistency, but as noted above what `DataFrameRow(df, idx)` does should be intuitively clear and I would document it. Removing deprecation is not that problematic. In summary - if even a minority found this feature useful and preferable over `df[idx, :]` we could remove the deprecation and keep it.

But I think that re-introducing `SubDataFrame(df, idx)` would be a bad idea as it would be unclear what it does (I know it was not proposed but I just want to have a completeness of discussion).
