### ISSUE TITLE
Use of copy vs colon on columns in getindex

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1699]
In `getindex` in several places we use `copy` when user wants a colon slice of columns in a `DataFrame`.
This produces inconsistent results in combination with Feather.jl (in which `copy` and `:` produce a different result).

Here is an example of the difference I am talking about:

```
julia> df = Feather.read("test.fw")
4×2 DataFrame
│ Row │ a     │ b        │
│     │ Int64 │ Float64  │
├─────┼───────┼──────────┤
│ 1   │ 1     │ 0.744287 │
│ 2   │ 2     │ 0.953696 │
│ 3   │ 3     │ 0.728511 │
│ 4   │ 4     │ 0.141408 │

julia> df[:, :a]
4-element Arrow.Primitive{Int64}:
 1
 2
 3
 4

julia> df.a[:]
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> copy(df.a)
4-element Arrow.Primitive{Int64}:
 1
 2
 3
 4
```

@ExpandingMan: we can do two things: either use slices in DataFrames.jl or make Feather.jl `copy` produce a standard vector. Do you have any opinion on what we should prefer?

**Comment by bkamins** [comment]
So we probably should switch to `:` in `getindex` in DataFrames.jl.

@nalimilan - any opinion?

**Comment by nalimilan** [comment]
> As far as I can tell, `copy` called on one of those columns should definitely _not_ return a `Vector`. That would be inconsistent with the convention of having `copy` return an object of the same type, and would be rather confusing.

Are you sure that convention exists? For example:
```julia

julia> copy(view(1:3, 1:2))
2-element Array{Int64,1}:
 1
 2
```

I'm not familiar with Feather.jl. What does it mean to return a newly-allocated `Arrow.Primitive` array? Why couldn't `getindex` allocate that kind of object too?

**Comment by ExpandingMan** [comment]
I think I might have been wrong on this.  `copy(reinterpret(T, v))` also returns an `Array`.  I can look into changing the behavior of `ArrowVector`.  It's a little dangerous in terms of causing bugs, but it's starting to look like I need to consider this.

**Comment by bkamins** [comment]
I have a pretty clear mind on this:
```
julia> p
4-element Arrow.Primitive{Float64}:
 0.4312042961382585
 0.6577706984983551
 0.7751874859987751
 0.7021373755303311

julia> p2 = copy(p)
4-element Arrow.Primitive{Float64}:
 0.4312042961382585
 0.6577706984983551
 0.7751874859987751
 0.7021373755303311

julia> p[1] = 0
0

julia> p
4-element Arrow.Primitive{Float64}:
 0.0
 0.6577706984983551
 0.7751874859987751
 0.7021373755303311

julia> p2
4-element Arrow.Primitive{Float64}:
 0.0
 0.6577706984983551
 0.7751874859987751
 0.7021373755303311
```

which shows that `p` is a view and current `copy` for sure does not do what it should. The only question is if it should return another `ArrowVector` with a fresh underlying data buffer (a new view to a new parent) or a `Vector` (simply the parent - this is what Base does with views) - here it is hard for me to say as I do not know Arrow.jl internals well enough.

No matter what you decide I guess we could switch from `copy` to `:` in DataFrames.jl as we can expect that `vector[:]` returns a fresh `Vector` "or something similar" consistently for all types in Julia (actually recently we have fixed `DataFrame` and `SubDataFrame` to follow this rule).

**Comment by nalimilan** [comment]
I guess we could use `:`, but it definitely sounds like there's a problem with `copy(::Arrow.Primitive)`.

**Comment by ExpandingMan** [comment]
Ok, you've convinced me, I'm definitely going to change the behavior of `copy`, [issue](https://github.com/ExpandingMan/Arrow.jl/issues/35).

In the future it will return a `Vector`.  There's no point in having it return an `ArrowVector` with a copied buffer.

**Comment by bkamins** [comment]
Then I will leave `copy` for now then in `getindex` as it is tad faster on small vectors than `getindex` with `:`.
So I think we can close this.
