### ISSUE TITLE
disallowmissings! on a dataframe does not actually mutate the dataframe

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/DataFrames.jl#1718]
@nickrobinson251  and I found this fun one on updating a lot of code  top v0.17.

This occurs in v17.1 and I am sure v17.0 but not tested.

Consider the following

```
julia> df =  DataFrame(;A=[1,2, missing], B=1:3)
3×2 DataFrame
│ Row │ A       │ B     │
│     │ Int64⍰  │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 1       │ 1     │
│ 2   │ 2       │ 2     │
│ 3   │ missing │ 3     │

julia> disallowmissing!(df[1:2, :])
2×2 DataFrame
│ Row │ A     │ B     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 1     │
│ 2   │ 2     │ 2     │

julia> df
3×2 DataFrame
│ Row │ A       │ B     │
│     │ Int64⍰  │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 1       │ 1     │
│ 2   │ 2       │ 2     │
│ 3   │ missing │ 3     │
```

## Actual Behavour:
So `disallowmissings!` on a `SubDataFrame` actually returns a new `DataFrame` with the columns retyped.
but **does not** mutate the the `SubDataFrame` in place , because it can't since that would break the parent.

The same happens for `dropmissings!(df; disallowmissing=true)`.

## Expected Behavour

Calling `disallowmissings!` on a `SubDataFrame` should be an error.
Optionally tere could be a non-inplace `disallowmissings` that works for both `DataFrame`s and `SubDataFrame`s and for both returns a new `DataFrame`.

`dropmissings(df; disallowmissing=true)` already exists and behaves as expcted.

## Further comment:
It would be good to test all methods that have a `!` to make sure they do actually return the same object (`objectid`-wise) as they were input.

**Comment by bkamins** [comment]
Thank you for the report (such feedback is really needed and greatly appreciated). Actually the idea of testing for object equality in tests for relevant methods is excellent and I will add such tests.

Also adding `disallowmissing` for `AbstractDataFrame` is consistend with what we have (it already works for `AbstractArrays`). @nalimilan: should we go ahead and add such a method that would create a fresh `DataFrame`?

Regarding your main question observe that `df[1:2, :]` does not create a `SubDataFrame` but `DataFrame`:
```
julia> df[1:2, :]
2×2 DataFrame
│ Row │ A      │ B     │
│     │ Int64⍰ │ Int64 │
├─────┼────────┼───────┤
│ 1   │ 1      │ 1     │
│ 2   │ 2      │ 2     │
```

which means that the following is `true` (as you have recommended to test):
```
julia> df2 = df[1:2, :]; disallowmissing!(df2) === df2
true
```

This is how you typically create a `SubDataFrame`:
```
julia> sdf = @view df[1:2, :]
2×2 SubDataFrame
│ Row │ A      │ B     │
│     │ Int64⍰ │ Int64 │
├─────┼────────┼───────┤
│ 1   │ 1      │ 1     │
│ 2   │ 2      │ 2     │
```
and `disallowmissing!` is not defined for this case:
```
julia> disallowmissing!(sdf)
ERROR: MethodError: no method matching disallowmissing!(::SubDataFrame{DataFrame,DataFrames.Index,UnitRange{Int64}})
```
as expected

**Comment by bkamins** [comment]
An additional comment is that you can expect `view`s in DataFrames.jl to behave exactly like `view`s in Base for arrays. There are two kind of views `SubDataFrame` and `DataFrameRow`.

There is, unfortunately, one exception. Call like `df[1, columns]` produces a `DataFrameRow` (a view) so it has the same effect as `@view df[1, columns]`. This is unfortunate, but it was chosen as the best from the following alternatives what `df[1, columns]` should return:
* a fresh `DataFrame` (this was breaking a rule that a single index should drop dimensionality and people wanted to be able to iterate columns of `df[1, columns]` plus it would be slow)
* a `DataFrameRow` with `df` as parent (this is what we do, and this is the fastest option; the drawback is that it is a view)
* a `NamedTuple` (the problem is that it is immutable)
* a new custom type (this is probably something we could do, but we decided that introducing yet another type is too much)

I think we could change this decision if people find it very counter-intuitive.

**Comment by nalimilan** [comment]
> Also adding `disallowmissing` for `AbstractDataFrame` is consistend with what we have (it already works for `AbstractArrays`). @nalimilan: should we go ahead and add such a method that would create a fresh `DataFrame`?

Yes, that sounds like a good idea.

But AFAICT the original issue is due to a confusion which wouldn't be fixed by changing `df[1, columns]`. And I don't see how we could avoid it as it's really consistent with Base and with our global scheme.

**Comment by oxinabox** [comment]
Ok, so this is not a subdataframes issue.
I thought it was, because most of the other issues we had during the 0.15-0.17 swap were.

My MWE clearly did not catch what the issue we hit was.
I will go digging.

**Comment by oxinabox** [comment]
I can not repoduce the original issue that that was supposed to be a MWE of.

> But AFAICT the original issue is due to a confusion which wouldn't be fixed by changing `df[1, columns]`. And I don't see how we could avoid it as it's really consistent with Base and with our global scheme.

The indexing in the example arguments was supposed to just be a standin for an operation happening else where in the code (not literally in the argument to the function).
It was confusion in how to create a SubDataFrame, but that itself was not the cause of the orignal iissue that I can not reproduce.

I am going to close this one, and open one just for  `disallow_missing(::AbstractDataFrame)`,
and open a new issue if we can workoujt what was causing the actual iissue I failed to MWE.
