### ISSUE TITLE
Wrong `sizeof` for DataFrames

### ISSUE THREAD

**Issue by mbeltagy** [JuliaData/DataFrames.jl#1719]
I was surprised that the  `DataFrame` type does not have proper `sizeof`method. 
Currently if you run `sizeof` on any `DataFrame` you will get 16 byte. 

Perhaps a custom `sizeof` needs to be defined somewhere. A very simple implementation is 

```julia
Base.sizeof(df::DataFrame)=sizeof.(@view df[1] for i=1:size(df,2)) |>sum
```

**Comment by nalimilan** [comment]
I'm not sure `sizeof` is supposed to be used to find out the amount of memory used by an object. For example, for a `Vector{String}` it doesn't take into account the size of the strings, only that of pointers.

`Base.summarysize` gives a more interesting information and it already works for data frames. I don't remember why it's not exported, though.

**Comment by bkamins** [comment]
I would close this. `sizeof` actually should be 16 as this is the size of binary representation of `DataFrame` (similar to any other `struct`) and this is the way Base defines `sizeof`.

**Comment by mbeltagy** [comment]
I was driven to try to replicate something like Python `pandas` [`info` method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) which gives you some information on  memory usage with the `'deep'` option (interestingly the default estimate works just like my `sizeof`). Didn't know about `Base.summarysize`, which is really cool. 

Closing.

**Comment by nalimilan** [comment]
Maybe you can ask why `summarize` isn't export from Base.
