### ISSUE TITLE
Support disallowmissing

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/DataFrames.jl#1720]
One of the things out of the confusion in #1718 
was that we should have a nonmutating `disallowmissing`  that applies to all abstract dataframes,
including `SubDataFrames`

**Comment by bkamins** [comment]
This is something we should definitely add, as also discussed on Slack.
My only question if we want to have:
* both `disallowmissing` (without `missing` keyword argument) and `replace` for `AbstractDataFrame`
* or only `disallowmissing` with added `missing` keyword argument

**Comment by bkamins** [comment]
My only reluctance about the third option, that is adding `replace` and `disallowmissing` with added `missing` keyword argument, is that it would be awkward as it would duplicate the functionality as @nalimilan also noted earlier.

**Comment by bkamins** [comment]
This has been stalled for some time. I would just make `disallowmissing(::AbstractDataFrame, cols)` that creates a new `DataFrame` always materializing columns (no matter what the source was) with disallowed missing in columns `cols`. OK?

CC @nalimilan

**Comment by nalimilan** [comment]
Sounds good. Basically it would create an empty `DataFrame` and fill it by calling `disallowmissing` on each column.

**Comment by bkamins** [comment]
Yes, expect that we will always do a `copy` of a column. The issue is that `disallowmissing` does not perform a copy of there is no work to be done. This is particularly problematic in our case with `SubDataFrames` where we would push `SubArrays` as columns.

**Comment by bkamins** [comment]
see https://github.com/JuliaData/DataFrames.jl/pull/1903
