### ISSUE TITLE
Defining columns of type `Union{Missings.Missing,` <:Number}` fails in Julia 1.1 but works in 0.6.4. 

### ISSUE THREAD

**Issue by mjamei19** [JuliaData/DataFrames.jl#1728]
these two lines of code both used to work in Julia 0.6 but now only the **second** one works in Julia 1.0. and the first one returns `UndefVarError`. 

1) ``DataFrame([Union{Missings.Missing,` <:Number}[missing, 1, 2]], [:col_name])``

2) ``DataFrame([Union{Missings.Missing, Int64}[missing, 1, 2]], [:col_name])``

**Comment by bkamins** [comment]
This is an issue with Base function `nonmissingtype`. DataFrames.jl only uses the standard functionality.

@nalimilan - maybe we should use `Core.Compiler.typesubtract`, but even if we do it also would need improvement for parametric types as now it does not strip `Missing` (although at least it would not fail).

**Comment by nalimilan** [comment]
We should use `Missings.T`. See https://github.com/JuliaData/DataFrames.jl/pull/1729.
