### ISSUE TITLE
When `join(..., validate=(true,true))` fails, it should include a list of non-unique joinkeyrows in the error)

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/DataFrames.jl#1732]
If you turn on the `validate` kwarg when joining, it will throw an error if they columns being joined on are have non-unique elements.
Very handy for defensive programming.

It woud be even more handy if it would include a list of which nonunique elements they were.

We might have to be a little smart about this, because we don't want to flood the user by printing 10^6 rows into the REPL. 
But we have the technology.

cc @rofinn

**Comment by rofinn** [comment]
At the very least we could probably include a `duplicates` function which returns the duplicate columns based on a key.

**Comment by oxinabox** [comment]
> `duplicates` function which returns the duplicate columns based on a key.

Hmmm... wouldn't the existing  `nonunique(df::AbstractDataFrame, cols)` do that?

**Comment by bkamins** [comment]
Currently `validate` returns the index of first offending row in each data frame. And then - as you have just noted, we can use `nonunique` to learn which rows are non-unique. I think what we have now is good enough (one function does one thing). What would be the benefit of combining `nonunique` in `join`?

**Comment by rofinn** [comment]
> Hmmm... wouldn't the existing `nonunique(df::AbstractDataFrame, cols)` do that?

`nonunique` returns a bit array of the indices that have been duplicated. It doesn't return both the original and duplicated rows of the original dataframe.

> Currently `validate` returns the index of first offending row in each data frame. And then - as you have just noted, we can use `nonunique` to learn which rows are non-unique.

Both `validate` and `nonunique` return just the index of duplicated rows, but it's often valuable to see the original and duplicated rows together.

**Comment by oxinabox** [comment]
> What would be the benefit of combining nonunique in join?


I would not think of this at all as that.

This is about giving the best error message we can.

**Comment by bkamins** [comment]
> This is about giving the best error message we can.

The idea was to print the index of the first offending row so that the user can look it up.

> Both `validate` and `nonunique` return just the index of duplicated rows, but it's often valuable to see the original and duplicated rows together.

This could be probably added to `nonunique` with something like `verbose` keyword argument. @rofinn could you specify what exactly you would like to see?

**Comment by rofinn** [comment]
I

**Comment by rofinn** [comment]
Sorry, "Close and comment" is not "Cancel" :p

It might be easiest to explain in code. Our current `safe_join` function looks like this:
```
function safe_join(index, frame, join_key)
    try
        return join(index, frame; on=join_key, kind=:left, validate=(false, true))
    catch e
        # If the validate check fails will try and be nice by showing the duplicate rows.
        # TODO: This can be removed once it is added to DataFrames.jl
        # https://github.com/JuliaData/DataFrames.jl/issues/1732
        if isa(e, ArgumentError) && occursin("are not unique", e.msg)
            # NOTE: This'll be slow for large dataframes, but hopefully this won't happen
            # very often
            duplicates = by(frame, join_key) do subdf
                n = nrow(subdf)
                # If n == 1 then don't return those indices
                # NOTE: We still need to return the empty dataframe for combining to work.
                i = n > 1 ? trues(n) : falses(n)
                subdf[i, :]
            end

            n = nrow(duplicates)
            total = nrow(frame)
            msg = string(
                "Found non-unique data rows on $join_key ($n / $total):\n",
                sprint(io -> show(io, duplicates; allcols=true)),
            )

            error(LOGGER, ArgumentError(msg))
        else
            rethrow(e)
        end
    end
end
```
In our case, we're creating a new DataFrame where all duplicate rows are next to each other. A more general solution might be to have `filter(f, grouped) -> GroupedDataFrame` and have `duplicated` be a special case of that where our filter is whether the group size is >1.

**Comment by bkamins** [comment]
The filter idea is nice. Currently you can do something like:
```
g = groupby(df, :a)
g[nrow.(g) .> 1]
```
but having the ability to `filter` `g` would be nice. Do you think having such `filter` function would work for you? (or maybe the pattern I show above is good enough for your case?)

**Comment by rofinn** [comment]
I think we'd have other use cases for the `filter` API (e.g., filter out groups my amount of missing data).

**Comment by nalimilan** [comment]
`GroupedDataFrame` isn't that complex, I think you just need to look at how `getindex` and `iterate` work.

**Comment by bkamins** [comment]
@nalimilan - I agree, but adding things like `filter` should be easy enough to do. The only question is if you are not intending to make `GroupedDataFrame <: AbstractDataFrame` which would change many things.

**Comment by bkamins** [comment]
I am starting to work on cleaning up `*join` API as this is the area we get most requests now.

Regarding this issue using:
```
[parentindices(sdf)[1] for sdf in groupby(df1, :a) if nrow(sdf) > 1]
```
gives you a vector of vectors of duplicate rows. This is efficient, but the problem is that including it in an error message will probably be to verbose (especially if there are many duplicates). Do you think it is:
1. Worth to add a function that would complement `nonunique` and implement what is proposed above?
2. Worth to give this recipe in the error message? (again I believe that printing all duplicates is problematic)

**Comment by nalimilan** [comment]
What about using `filter`?

**Comment by bkamins** [comment]
You mean to add `filter` to a `GroupedDataFrame` - yes we could add it, but I think it is orthogonal to this issue (I will open a PR for this as it should be relatively simple).

But `filter` will produce a `GroupedDataFrame` and it would be even less readable than what I propose.

**Comment by oxinabox** [comment]
Can we print out something like at most 5 duplicates,
and if there are more than 5 print `"with 154 duplicates including ...` then the first 2, and then vdots, and the last 2 or something like that?

**Comment by bkamins** [comment]
Just to be clear - is it enough for you to just print more values that are `true` in a vector returned by `nonunique` or you also want the "first duplicate" also included.

To be clearer. In the case of:
```
julia> df = DataFrame(a=[1,1,1])
3×1 DataFrame
│ Row │ a     │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │
│ 2   │ 1     │
│ 3   │ 1     │

julia> nonunique(df)
3-element Array{Bool,1}:
 0
 1
 1
```
would you want just `[2,3]` to be listed or `[1,2,3]`?

**Comment by oxinabox** [comment]
I would expect the output to include only `1`, if this is an error message.
But maybe I am misunderstanding

**Comment by bkamins** [comment]
Ah - so you want:
```
[parentindices(sdf)[1][1] for sdf in groupby(df, :a) if nrow(sdf) > 1]
```
So e.g.:
```
julia> df = DataFrame(a=[1,2,1,2,1,3,3])
7×1 DataFrame
│ Row │ a     │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │
│ 2   │ 2     │
│ 3   │ 1     │
│ 4   │ 2     │
│ 5   │ 1     │
│ 6   │ 3     │
│ 7   │ 3     │

julia> [parentindices(sdf)[1][1] for sdf in groupby(df, :a) if nrow(sdf) > 1]
3-element Array{Int64,1}:
 1
 2
 6
```
(of course it would be implemented differently, but I just want to make sure we are on the same page - you want to get the row-index of the rows that have later duplicates in the data frame)

**Comment by nalimilan** [comment]
Actually I was thinking (as mentioned above) about saying "use `filter(x -> nrow(x) > 1, groupby(df, $COLS))` to see groups with duplicate keys". Now I realize it's not really what @oxinabox wanted.

Though TBH I'm not sure printing only the index of the first row which has duplicates is very logical. Wouldn't it be more useful to be able to get a `GroupedDataFrame` showing which rows are duplicates of each other as @rofinn's code does?

**Comment by bkamins** [comment]
So maybe we could just add a hint in the error message that user can use `filter(x -> nrow(x) > 1, groupby(df, $COLS))` to see the groups with duplicates. The benefit is that it would be easy to just copy-paste the hint a get a working list. What do you think?

(I would add it in https://github.com/JuliaData/DataFrames.jl/pull/2279 if we agree to this)

**Comment by oxinabox** [comment]
Using Integers as as the values is confusing this.
Lets talk with a real example:

```julia
julia> costs = DataFrame(brand=["BurgerDuke", "BurgerDuke", "BurgerDuke", "McDannys", "McDan
nys"], product = ["burger", "fries", "drink", "burger", "drink"], price=[10.0, 5.0, 1.0, 9.5
, 0.5])
5×3 DataFrame
│ Row │ brand      │ product │ price   │
│     │ String     │ String  │ Float64 │
├─────┼────────────┼─────────┼─────────┤
│ 1   │ BurgerDuke │ burger  │ 10.0    │
│ 2   │ BurgerDuke │ fries   │ 5.0     │
│ 3   │ BurgerDuke │ drink   │ 1.0     │
│ 4   │ McDannys   │ burger  │ 9.5     │
│ 5   │ McDannys   │ drink   │ 0.5     │

julia> nutrition = DataFrame(product = ["burger", "fries", "drink"], rating = [3//5, 2//5, 1//5])
3×2 DataFrame
│ Row │ product │ rating   │
│     │ String  │ Rationa… │
├─────┼─────────┼──────────┤
│ 1   │ burger  │ 3//5     │
│ 2   │ fries   │ 2//5     │
│ 3   │ drink   │ 1//5     │

julia> innerjoin(costs, nutrition, on=:product)
5×4 DataFrame
│ Row │ brand      │ product │ price   │ rating   │
│     │ String     │ String  │ Float64 │ Rationa… │
├─────┼────────────┼─────────┼─────────┼──────────┤
│ 1   │ BurgerDuke │ burger  │ 10.0    │ 3//5     │
│ 2   │ BurgerDuke │ fries   │ 5.0     │ 2//5     │
│ 3   │ BurgerDuke │ drink   │ 1.0     │ 1//5     │
│ 4   │ McDannys   │ burger  │ 9.5     │ 3//5     │
│ 5   │ McDannys   │ drink   │ 0.5     │ 1//5     │

julia> innerjoin(costs, nutrition, on=:product, validate=(true,true))
ERROR: ArgumentError: Merge key(s) in df1 are not unique. First duplicate at row 4
```


So I want the error message to be:
```
ERROR: ArgumentError: Merge key(s) in df1 are not unique. Duplicates: "burger", "drink"
```

**Comment by bkamins** [comment]
OK - now I get it. Have a look at: https://github.com/JuliaData/DataFrames.jl/pull/2282
