### ISSUE TITLE
Add compress argument to categorical!()

### ISSUE THREAD

**Issue by harryscholes** [JuliaData/DataFrames.jl#1733]
It would be really nice to be able to compress categorical columns e.g.:

```julia
julia> import DataFrames, CategoricalArrays

julia> function DataFrames.categorical!(df::DataFrame, cname::Union{Integer, Symbol}, compress::Bool)
           df[cname] = categorical(df[cname], compress)
           df
       end

julia> df = DataFrame(a = ["A", "A", "B", "B"]);

julia> categorical!(df, :a, true);

julia> typeof(df[:a])
CategoricalArray{String,1,UInt8,String,CategoricalString{UInt8},Union{}}
```

**Comment by bkamins** [comment]
Good point, probably `compress` could be `false` by default.

@nalimilan - do you see any possible problems with this?

**Comment by nalimilan** [comment]
Makes sense. Would you make a pull request to implement this?

I agree `compress` should be `false` by default (though using `true` wouldn't be completely absurd either since we don't really care about type stability here).

**Comment by bkamins** [comment]
I recommended `false` as most people do not know what consequences `true` would have and I would avoid newcomers having to handle:
```
ERROR: cannot store level(s) 266 since reference type UInt8 can only hold 255 levels. Use the decompress function to make room for more levels.
```

And someone who is advanced enough can just consciously pass `true`.

But this is not a hugely strong preference.

**Comment by harryscholes** [comment]
Cool. I’ll take a look into the best way to implement this and put a PR together. Cheers!
