### ISSUE TITLE
Find a better API for stackdf and meltdf

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#1736]
These names really make no sense. We could use `@view` if possible or add an argument to the corresponding functions.

**Comment by bkamins** [comment]
I would add an argument. I do not see how `@view` would work if we wanted to be consistent with the standard `view` semantics.

Just to confirm - we want to retain `stackdf` and `meltdf` and how they work but just change the API. Right?

**Comment by Nosferican** [comment]
For reference, https://tidyr.tidyverse.org/dev/articles/pivot.html

**Comment by nalimilan** [comment]
Interesting. Current names aren't very explicit indeed, and there are different conventions across packages (`stack`/`melt` vs. `gather`/`spread`). That sounds quite orthogonal to the question of view vs. copy, though.
