### ISSUE TITLE
Add checks of DataFrame consistency before expensive operations

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1744]
When we run expensive operations then we could check if lengths of all columns in the data frame are consistent.

Similarly for views we could check if they did not get invalidated before expensive operations.

This might be relevant as in some places we do `@inbounds` thus core dumps can happen.

**Comment by oxinabox** [comment]
When we add this feature we should make it public,
so that users can add it to their code.
Call it `assert_consistency` or something.
If a user is worried about there code acting weird, or wanting to protech there own dataframe ops,
they can add it in.

It isn't actually all that expensive really.
It is only `O(n_cols)`

**Comment by bkamins** [comment]
Yes - for most of the operations this is relatively cheap. Only something like `getindex` and stuff that are local should not do the check. Actually the only problematic functions are `ncols`, `size` and `axes` - ideally they should do this check, but they are used in performance critical code in several places.

**Comment by oxinabox** [comment]
Some of the `getindex` should do this check.
E.g. slicing a row.
And it should be surpressed by `@inbounds`
(I am pretty sure we can extend the standard bound-check supression mechanism for this. Which feels indiomatic)

**Comment by bkamins** [comment]
So this is exactly what we should discuss where the borderline is. For instance should `df.col` or `df[:col]` perform consistency check or just return the column. Similarly - should `df[row, col]` do the check or just check if `row` is in `axes(df.col, 1)` range.

**Comment by bkamins** [comment]
#1800 shows that `push!` can silently break consistency if we use `copycols=false` (and additionally shows how good it is to have `copycols=true` by default).

CC @nalimilan

**Comment by bkamins** [comment]
Closing, as the discussion should be moved to https://github.com/JuliaData/DataFrames.jl/pull/1887.
