### ISSUE TITLE
Documentation says that a test/data/iris.csv file should exist, it doesnt.

### ISSUE THREAD

**Issue by KristofferC** [JuliaData/DataFrames.jl#1745]
http://juliadata.github.io/DataFrames.jl/stable/man/sorting.html

```jl
julia> using DataFrames, CSV

julia> iris = CSV.read(joinpath(dirname(pathof(DataFrames)), "../test/data/iris.csv"));
ERROR: ArgumentError: "C:\Users\Kristoffer\.julia\packages\DataFrames\IKMvt\src\../test/data/iris.csv" is not a valid file
Stacktrace:
 [1] #File#1(::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Nothing, ::Bool, ::Nothing, ::Bool, ::Array{String,1}, ::String, ::String, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Dict{Type,Type}, ::Symbol, ::Bool, ::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Type, ::String) at C:\Users\Kristoffer\.julia\packages\CSV\eWuJV\src\CSV.jl:135
```

**Comment by bkamins** [comment]
I will fix it.

**Comment by KristofferC** [comment]
Might be a good idea to enable the doctests?

**Comment by bkamins** [comment]
I have made the proposed change in #1746.

Regarding enabling doctests - this is a good idea (I would do it in a separate PR as probably some more tests will be failing).

Do you remember how to properly enable running doctests on CI (I will then make a PR fixing only failing doctests isssues)? Thank you.

**Comment by KristofferC** [comment]
Set 

https://github.com/JuliaData/DataFrames.jl/blob/a8904f678947e8d589a7bbe616174f1db022b3e0/docs/make.jl#L14

to `true` and add `strict = true` if you want failing doctests to fail the build. This will also fail the build if there are docstrings that are not present in the rendered documentation (which can be a bit annoying) since sometimes you have docstrings on internal stuff that you dont want to end up in the rendered documentation.

**Comment by bkamins** [comment]
This is the advice I wanted 👍  (there are always these small things you need to know I was afraid I would miss 😄).

**Comment by shivanu01** [comment]
I ma facing similar issue please help me
ArgumentError: "Iris.csv" is not a valid file

**Comment by bkamins** [comment]
The file is in docs/src/assets/iris.csv (lowercase)
