### ISSUE TITLE
`pairs` outputs warnings

### ISSUE THREAD

**Issue by cstjean** [JuliaData/DataFrames.jl#1751]
`pairs` can be nice to iterate both names and columns, but it outputs a deprecation warning:

```julia
julia> using DataFrames

julia> for (k, v) in pairs(DataFrame(x=1)) @show(k, v) end
┌ Warning: `keys(df::AbstractDataFrame)` is deprecated, use `names(df)` instead.
│   caller = pairs at abstractdict.jl:132 [inlined]
└ @ Core ./abstractdict.jl:132
┌ Warning: `values(df::AbstractDataFrame)` is deprecated, use `columns(df)` instead.
│   caller = pairs at abstractdict.jl:132 [inlined]
└ @ Core ./abstractdict.jl:132
k = :x
v = [1]
```

**Comment by bkamins** [comment]
I think we should rather define:

```
pairs(df::AbstractDataFrame) = eachcol(df, true)
```

CC @nalimilan

**Comment by nalimilan** [comment]
We've decided that data frames are collections of rows, so (if we support it) `pairs` should iterate over rows, not columns.

**Comment by bkamins** [comment]
But this would mean that it should return a collection of `Pair`s: row_number=>DataFrameRow. Right?

**Comment by nalimilan** [comment]
Yes. It should probably be equivalent to `Generator(=>, axes(df, 1), eachrow(df))`, a bit like the fallback definition. Though it would be a bit inconsistent not to also define `keys` and `values` accordingly (which isn't possible obviously as long as `df[i]` returns a column).

**Comment by bkamins** [comment]
OK - so essentially `pairs` should get another level of deprecation explaining target functionality when we deprecate `df[i]` (which should probably happen soon anyway). And later we change the functionality.

**Comment by bkamins** [comment]
Closing. `pairs` is not working on `DataFrame` objects. `eachrow`/`eachcol` can be used instead depending on needs.
