### ISSUE TITLE
aggregate function: Add option to NOT re-name column

### ISSUE THREAD

**Issue by evveric** [JuliaData/DataFrames.jl#1756]
aggregate function:
https://juliadata.github.io/DataFrames.jl/stable/lib/functions.html#DataFrames.aggregate

```
using Statistics
df = DataFrame(a = repeat([1, 2, 3, 4], outer=[2]),
               b = repeat([2, 1], outer=[4]),
               c = randn(8))
aggregate(df, :a, sum)

```

This will Rename column b and c to be **b_sum, c_sum.**

I would appreciate if you add an Option "renamecolumn=true", so that I can choose to NOT re-name column name for the output result.

i.e. in above example, if I do:

`aggregate(df, :a, sum; renamecolumn=false)`

It will return with column name b and c

Thank you

**Comment by bkamins** [comment]
you can write:

```
df2 = aggregate(df, :a, sum)
names!(df2, names(df))
```

in your specific case (i.e. when the column by which you aggregate appears first in the source).

In general `aggregate` accepts multiple transformation functions so what you propose would not be possible. For a single function this is possible. Let us wait for other opinions.

Maybe we could add an option to pass a `Pair`: `suffix => function_name` as an alternative to simply passing a function name. Eg. `aggregate(df, :a, "_sum"=>sum)` and if the suffix is `nothing` we would not add a suffix. This would be also useful with anonymous functions.

**Comment by evveric** [comment]
Thank you. 

If I have this dataset as example:
date, customer,apple,orange,banana,pear, .... 100 fruit columns
20190101, Bob, 10, 2, 5, 1
20190101, Bob, 0, 2, 5, 1
20190101, Bob, 0, 2, 5, 1
20190101, Bob, 30, 2, 0, 2
20190101, Bob, 40, 1, 7, 3
20190101, Bob, 0, 0, 5, 4
20190101, Marry, 33, 7, 1, 0
20190101, Ted, 55, 0, 2, 0
....Many rows, Many records, storing all orders, and each day, one customer can have multiple orders on multiple fruits.

Now I want to compute a Timeseries, showing the "Daily Average Fruit Amount per each customer"

i.e. I need to first do "df2 = aggregate(df, [:date, :customer], sum)"
then do "df3 = aggregate(df2, [:Date], mean)"

this will show on average, each day, one customer will buy X amount of apple, Y amount of banana etc etc...

I need to do two aggregate operations, so it is better that the "fruit name" from df2 will NOT show up and "apple_sum"
Otherwise the df3 column will show up as "apple_sum_mean" which totally doesn't make sense...

thank you!
 

On one day, customer "Bob" can have 100 orders at different time, buying different amount of fruit, apple, banana, etc etc
On

**Comment by bkamins** [comment]
As I have said - we will discuss adding `Pairs` argument to `aggregate`.

For the time being what you can do is `stack` your data, then run the aggregations you need and `unstack` the result. In this way you will have the original column names retained.

**Comment by evveric** [comment]
> As I have said - we will discuss adding `Pairs` argument to `aggregate`.
> 
> For the time being what you can do is `stack` your data, then run the aggregations you need and `unstack` the result. In this way you will have the original column names retained.

Perfect, will do. thank you! 
If you decided to add this feature in the future, I will def appreciate it.

**Comment by bkamins** [comment]
@nalimilan - related to the future of `aggregate`.

**Comment by bkamins** [comment]
My recommendation is that we will leave `aggregate` in its current functionality but not develop it further (in particular your request is problematic when multiple functions are passed to `aggregate`). For what you wanted use (after 0.21 release) `select` or `by` (depending on your use case).
E.g.:
```
gdf = groupby(df, :a)
combine(gdf, valuevars(gdf) .=> sum .=> valuevars(gdf))
```

Please reopen if you would like to discuss it more.
