### ISSUE TITLE
Classic Datasets no longer included?

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#1760]
Ran into problem testing for `FreqTables`, but seems like issues is here: I don't see the Iris dataset in the package install anymore ([though docs still say it's there](http://juliadata.github.io/DataFrames.jl/v0.11.7/man/getting_started.html#Loading-a-Classic-Data-Set-1)). 

Is that gone for good?

**Comment by davidanthoff** [comment]
I think the two packages that provide access to a variety of datasets these days are https://github.com/johnmyleswhite/RDatasets.jl and https://github.com/queryverse/VegaDatasets.jl.

**Comment by bkamins** [comment]
You use version 0.11.7 documentation that is outdated.
In latest (https://juliadata.github.io/DataFrames.jl/latest/) all is fixed. The iris.csv file is now in docs/src/assets directory. It is referenced e.g. in this part of the manual https://juliadata.github.io/DataFrames.jl/latest/man/split_apply_combine.html#The-Split-Apply-Combine-Strategy-1.
