### ISSUE TITLE
Floating point number formatting

### ISSUE THREAD

**Issue by tk3369** [JuliaData/DataFrames.jl#1762]
How can we show more decimals when a DataFrame is displayed in REPL?   

Two ideas:

Using `IOContext`:
1. Respect `:compact => false` 
2. Accept `:renderer => f` where f can be a custom function to render cells e.g.`f(value, column_name, column_index, column_type)::AbstractString`.  

Reference
https://discourse.julialang.org/t/display-more-decimals-in-dataframe/22545/1

**Comment by bkamins** [comment]
CC @nalimilan 

Ad1. I think we can harmlessly make `ourshowcompact` use `:compact` from `IO` if it is defined and default to `false`. Probably then the function should be renamed to something like `internalshow`.

Ad2. `f` should be jest `f(value)` if we decide to add it and we would change:
```
ourshowcompact(io::IO, x::Any) =
    show(IOContext(io, :compact=>true, :typeinfo=>typeof(x)), x) # -> Void
```
to
```
function ourshowcompact(io::IO, x::Any)
    renderer = get(io, :renderer, nothing)
    if renderer === nothing
        show(IOContext(io, :compact=>true, :typeinfo=>typeof(x)), x) # -> Void
    else
        show(io, renderer(x))
    end
end
```

but I am not sure if we really need to add it (but we can so comment please).

**Comment by nalimilan** [comment]
I think we should do the same thing as array printing in Base. AFAICT it just sets `:compact=>true` when `!haskey(io, :compact)`. A custom rendered sounds a bit too much IMHO.

**Comment by bkamins** [comment]
So - this is essentially option 1. I will make a PR.
