### ISSUE TITLE
`eltype` for `describe` is confusing users

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1765]
Referencing [this thread](https://discourse.julialang.org/t/pca-not-working/22645/3) on discourse. The user used `describe` and thought their columns were not missing because they weren't listed as such in `eltype`. 

* Would it be possible to return `Union{T, Missing}` with nice printing? 
* We could use a more informative name.

**Comment by bkamins** [comment]
> Would it be possible to return `Union{T, Missing}` with nice printing?

we use `T⍰` syntax to indicate `Union{T, Missing}`. A PR introducing this convention for `describe` would be welcome (if you prefer I can implement it - please let me know - there are a few corner cases to consider - you can have a look at `show` implementation)

> We could use a more informative name.

what would you propose?

**Comment by pdeffebach** [comment]
I think we should overload the printing of `Union{T, Missing}` in all DataFrames to be `T ⍰`. 

Although a data frame of data types seems like a pretty small use case.

**Comment by bkamins** [comment]
see #1900
