### ISSUE TITLE
Why do we have `DataFrame(Int, 5, 5)`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1766]
In the constructors of DataFrame we have the following line:

https://github.com/JuliaData/DataFrames.jl/blob/8d6cd4327222c5acb58abdc093511f8465b8aca2/src/dataframe/dataframe.jl#L18

Do we know the original purpose of this constructor? It seems useful for pre-allocating a DataFrame and filling it in in a hot loop. But I don't think it's used anywhere aside from tests. 

If there are concerns about LOC in DataFrames we can deprecate it.

**Comment by bkamins** [comment]
In practice most of constructors creating an "unfilled" `DataFrame` (there is more of them) are not useful in my experience (I have never used them as it is better to `push!`, `append!` or `vcat`).

However, they are rather light so I think they would not save us much in terms of load time. @nalimilan - what do you think?

**Comment by nalimilan** [comment]
These are probably remnants from a time when `Array(T, nr, nc)` was a thing. Now they don't even match the `Array` syntax.

That won't save much code, but probably better deprecate them before 1.0 and see whether we get any complaints.

**Comment by bkamins** [comment]
I will propose what to deprecate after "ownership" PR is merged (to avoid rebasing, as that PR heavily changes related parts of code)
