### ISSUE TITLE
`by` result column names default for length-1 aggregation

### ISSUE THREAD

**Issue by ianfiske** [JuliaData/DataFrames.jl#1768]
```
df = DataFrame(a = [1, 1, 2, 2], b = 1:4)

by(df, :a) do df
    (sum_b = sum(df.b))
end
```
gives
```
2×2 DataFrame
│ Row │ a     │ x1    │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 3     │
│ 2   │ 2     │ 7     │
```

but it seems like the column name should be `sum_b`, not `x1`.  I have DataFrames v0.17.1.

**Comment by bkamins** [comment]
Seems to be a bug. This works OK (but is not recommended as it is slower):
```
julia> by(df, :a) do df
           DataFrame(sum_b = sum(df.b))
       end
2×2 DataFrame
│ Row │ a     │ sum_b │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 3     │
│ 2   │ 2     │ 7     │
```

**Comment by bkamins** [comment]
It is not a bug, you missed a comma in the specification:
```
julia> by(df, :a) do df
           (sum_b = sum(df.b),)
       end
2×2 DataFrame
│ Row │ a     │ sum_b │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 3     │
│ 2   │ 2     │ 7     │
```

Please reopen the issue if something is not clear.

**Comment by nalimilan** [comment]
Yeah it's annoying that `(x=y)` doesn't create a named tuple, but it's needed by the language.

BTW, better use `by(df, :a, :b => sum)` or `by(df, :a, b_sum = :b => sum)` in recent versions, it's much faster.

**Comment by ianfiske** [comment]
@nalimilan @bkamins Thank you for looking into this and for the pointers!
