### ISSUE TITLE
Removing DataStreams.jl integration

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1773]
Before the coming release we probably should deprecate DataStreams-based IO for DataFrames.jl. So that we can remove it in the next release.

The relevant code is at the end of src/abstractdataframe/io.jl file.

CC @quinnj, @nalimilan

**Comment by oxinabox** [comment]
Reason for this is the Tables.jl has replaced that?

**Comment by bkamins** [comment]
@quinnj (who is a best person to comment on the way we should go - that is why I have opened an issue not a PR) mentioned earlier that this should be needed now.

In particular, if what you say is true (or it is not 100% true, but the functionality is not needed currently), we can reduce loading time of DataFrames.jl by 0.5 sec, which is a part of solving problems discussed in https://github.com/JuliaData/DataFrames.jl/issues/1764.
