### ISSUE TITLE
datavaluerows not defined

### ISSUE THREAD

**Issue by yakir12** [JuliaData/DataFrames.jl#1776]
I get this error
```julia
julia> using MyExample
[ Info: Recompiling stale cache file /home/yakir/.julia/compiled/v1.1/MyExample/vTfRK.ji for MyExample [1214170b-0e78-58d0-ac9e-2baa6215f30c]
ERROR: LoadError: UndefVarError: datavaluerows not defined
Stacktrace:
 [1] getiterator(::DataFrames.DataFrame) at /home/yakir/.julia/packages/DataFrames/IKMvt/src/other/tables.jl:31
 [2] #table#351(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::DataFrames.DataFrame) at /home/yakir/.julia/packages/IndexedTables/DgX0A/src/tabletraits.jl:50
 [3] table at /home/yakir/.julia/packages/IndexedTables/DgX0A/src/tabletraits.jl:49 [inlined]
 [4] |>(::DataFrames.DataFrame, ::typeof(IndexedTables.table)) at ./operators.jl:813
 [5] top-level scope at none:0
 [6] top-level scope at none:2
in expression starting at /home/yakir/MyExample/src/MyExample.jl:7
ERROR: Failed to precompile MyExample [1214170b-0e78-58d0-ac9e-2baa6215f30c] to /home/yakir/.julia/compiled/v1.1/MyExample/vTfRK.ji.
```
from using this MWE package:
```julia
module MyExample
using CSV, JuliaDB
file = joinpath(@__DIR__, "file.csv")
x = CSV.read(file) |> table
end # module
```
`file.csv` just contains some mock data:
```csv
x,y,z
1,2,3
4,5,6
```
Here's a github repo with this example: https://github.com/yakir12/MyExample.jl
I think `datavaluerows` belongs to `Tables.jl` so I'll tag @quinnj, hope that's ok.

**Comment by nalimilan** [comment]
`datavaluerows` is only defined in Tables.jl when DataValues is loaded. Yet `Tables.rows` calls `getiterator`, which is defined in DataFrames to unconditionally call `datavaluerows`.

We should probably just stop using Requires in Tables, as it slows down loading.

**Comment by bkamins** [comment]
@nalimilan - are you going to follow up on this in Tables.jl?

**Comment by nalimilan** [comment]
Let's hear what @quinnj says when he's back first.

**Comment by bkamins** [comment]
@quinnj - could you please have a look at it as I think it would be good to have a clear situation with it before we make a release.

**Comment by quinnj** [comment]
Ok, this will be fixed with https://github.com/JuliaData/Tables.jl/pull/81
