### ISSUE TITLE
Error in conversion from ExcelFile

### ISSUE THREAD

**Issue by braamvandyk** [JuliaData/DataFrames.jl#1780]
I have existing code that used to run without errors. It reads an Excel file using FileIO.jl and converts the result to a DataFrame, which is then processes and an array of structs is returned.

The relevant code is:

```
using FileIO
using DataFrames

function readdata(source)
    data = DataFrame(load(source, "Data"))
    <further processing to create array of structs called emps>
    return emps
 end
```
When called the first time, it errors. When called immediately again, it runs:

```
julia> emps = readdata(".\\data\\Data.xlsx")
ERROR: ArgumentError: unable to construct DataFrame from ExcelFiles.ExcelFile
Stacktrace:
 [1] DataFrame(::ExcelFiles.ExcelFile) at C:\Users\braam\.julia\packages\DataFrames\IKMvt\src\other\tables.jl:23
 [2] readdata(::String) at D:\Braam\Documents\Julia Source\EEMC\src\data_retrieval.jl:33
 [3] top-level scope at none:0

julia> emps = readdata(".\\data\\Data.xlsx")
458-element Array{Employee,1}:
<snip>
```

This seems to be a bug in the current version of DataTables, but I am leaving a lot of room for the error being on my side. Any advise would be appreciated.

**Comment by bkamins** [comment]
In order to diagnose this I would go through these steps (or please provide a fully reproducible code):

1. What is the type of the object returned by `load(source, "Data")` in this case?
2. Does the returned object `x` pass `applicable(iterate, x)` test
3. Does the returned object `x` pass `Tables.istable(x)` test

**Comment by davidanthoff** [comment]
Could you also post what version of DataFrames.jl and Tables.jl you are using? 

The stack trace indicates that things are going wrong [here](https://github.com/JuliaData/DataFrames.jl/blob/359bf31e8389263c991685dddca293a9fa575a78/src/other/tables.jl#L23). The error message also seems to indicate that the type of `x` is `ExcelFiles.ExcelFile` (as it should be). `Tables.istable` should return `true` for that, but apparently doesn't?

**Comment by braamvandyk** [comment]
Thank you for the rapid response! It is deeply appreciated.

## Version information

Julia Version 1.1.0 (official binaries)
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

[a93c6f00] DataFrames v0.17.1
[89b67f3b] ExcelFiles v0.9.1
[5789e2e9] FileIO v1.0.6
[bd369af6] Tables v0.1.18

In Manifest.TOML, I have the following:

[[ExcelFiles]]
deps = ["DataValues", "Dates", "ExcelReaders", "FileIO", "IterableTables", "IteratorInterfaceExtensions", "Printf", "PyCall", "TableShowUtils", "TableTraits", "TableTraitsUtils", "Test", "XLSX"]
git-tree-sha1 = "e157d1ea01f94df971e0515b0fba322cbc812f14"
uuid = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"
version = "0.9.1"

[[ExcelReaders]]
deps = ["DataValues", "Dates", "PyCall", "Test"]
git-tree-sha1 = "6f9db420dd362bd5bcea3a0f6dabf8bda587fec3"
uuid = "c04bee98-12a5-510c-87df-2a230cb6e075"
version = "0.11.0"

[[IterableTables]]
deps = ["DataValues", "IteratorInterfaceExtensions", "Requires", "TableTraits", "TableTraitsUtils", "Test"]
git-tree-sha1 = "18d6084924b2ac78deb65229cbcaa04d56ecb075"
uuid = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
version = "0.11.0"

## Types and Tests
The call to read returns an `ExcelFiles.ExcelFile` object, which is what I convert to a DataFrame
```
julia> data = load(source, "Roles")
9x1 Excel file
<content of file>

julia> typeof(data)
ExcelFiles.ExcelFile

julia> applicable(iterate, data)
false

julia> Tables.istable(data)
true
```

## Observations
I have several functions that read from the same Excel file. Each reads a different sheet and processes the data.

As mentioned previously, the error is on the first call of a function that reads from the Excel file. On the second call, and any call to any of the other functions that read from the Excel file, the call works flawlessly.
This does not seem to depend on which function is called first - the first attempt to convert from an ExcelFile object fails and any subsequent call works.

I also noted that the first call (that fails) takes a bit longer than the second call (that works). I would estimate 30-50% longer on a small table being read, if that is any use.

**Comment by braamvandyk** [comment]
Would you like a copy of the Excel file? I will need to clean it up to remove some sensitive information, but that is not a problem. It was created in Office 365, but that does not seem to be part of the issue, as FileIO/ExcelFiles has no problem reading it.

I have split the code into two lines - 1. Read the Excel file and 2. Convert to DataFrame, but this had no effect. The first conversion fails, the second passes.

**Comment by bkamins** [comment]
This is strange - I have reproduced your configuration exactly (except for the file of course) and all works correctly on some sample file.

**Comment by braamvandyk** [comment]
I'll uninstall and reinstall my packages and see if that fixes it. Will let you know as soon as I can. Thanks for the effort.

**Comment by braamvandyk** [comment]
No luck on that front. I uninstalled ExcelFiles and DataFrames. Garbage collected and deleted DataFrames.ji. Reinstalled and tested:
```
julia> numroles, roles = readroles(source)
ERROR: ArgumentError: unable to construct DataFrame from ExcelFiles.ExcelFile
Stacktrace:
 [1] DataFrame(::ExcelFiles.ExcelFile) at C:\Users\braam\.julia\packages\DataFrames\IKMvt\src\other\tables.jl:23
 [2] readroles(::String) at D:\Braam\Documents\Julia Source\EEMC\src\data_retrieval.jl:31
 [3] top-level scope at none:0

julia> numroles, roles = readroles(source)
(9, Dict("Vacant"=>0,"GroupLeadership"=>9,"ProcessOptimisation"=>3,"Operations"=>1,"ProcessImplementation"=>2,"Expertise"=>7,"Execution"=>4,"Specialisation"=>6,"Optimisation"=>5,"Leadership"=>8…))
```

**Comment by braamvandyk** [comment]
I have attached a small test file that also gives the issue. The code to read the file is:

```
"""
    function readroles(source)

Reads the specified Excel file and outputs the number of roles and a dictionary
of the roles, including Vacant, the latter which is not counted.

# Examples

```julia-repl
julia> numroles, roles = readroles(".\\data\\Data.xlsx")
(9, Dict(0=>"Vacant",4=>"Execution",7=>"Expertise",9=>"GroupLeadership",2=>"ProcessImplementation",3=>"ProcessOptimisation",5=>"Optimisation",8=>"Leadership",6=>"Specialisation",1=>"Operations"…))

julia> numroles
9

julia> roles
Dict{String,Int64} with 10 entries:
  "Vacant"                => 0
  "GroupLeadership"       => 9
  "ProcessOptimisation"   => 3
  "Operations"            => 1
  "ProcessImplementation" => 2
  "Expertise"             => 7
  "Execution"             => 4
  "Specialisation"        => 6
  "Optimisation"          => 5
  "Leadership"            => 8
```
"""
function readroles(source)
    data = DataFrame(load(source, "Roles"))
    numroles = length(data.Role)

    rolepairs=Array{Tuple{String, Int64}}(undef, numroles+1)
    rolepairs[1] = ("Vacant", 0)
    for i in 1:numroles
        rolepairs[i+1] = (data.Role[i], i)
    end
    roles = Dict(rolepairs)

    return numroles, roles
end
```

[Test.xlsx](https://github.com/JuliaData/DataFrames.jl/files/3103425/Test.xlsx)

**Comment by bkamins** [comment]
I have run this code and it goes through without a problem so this is really strange.

You can try setting-up a (private if you need) GitHub repository for your code and run automated Appveyor and Travis tests? Maybe they would catch something reproducible

**Comment by braamvandyk** [comment]
Thank. I'll try that. To add to the weirdness, when I step through the code with the debugger, it works. Seems like something is taking a while to initialize on my machine. I'll try it on another machine as well to check if I can see a difference.

**Comment by braamvandyk** [comment]
Some additional information:
Since recent updates, the error is now consistent on every call. Since running the line twice was no longer an option, I dug into this a little more.

Originally the code that gave the error was: 

```
data = DataFrame(load(source, "Roles"))
```
Where `source` holds the filename and `Roles` is the sheetname.

I split this into two lines:

```
xl = load(source, "Roles")
data = DataFrame(xl)
```

This still gives the error. However, I noticed to following:
```
julia> typeof(xl)
ExcelFiles.ExcelFile

julia> Tables.istable(xl)
true

julia> Tables.istable(ExcelFiles.ExcelFile)
false
```

This is, well, surprising and confusing.

**Comment by davidanthoff** [comment]
The recent Tables.jl 0.2 release introduced a number of bugs that pretty much broke the whole queryverse file IO story - DataFrames story... I think a recent PR by @nalimlian should have fixed the issues, but @quinnj needs to tag a new release for that to ship. You could try to use `Tables#master` in the meantime. Reporting back whether things work with `Tables#master` would also be useful information (I believe @nalimilan's PR should have fixed things, but some confirmation for that would be great!).

**Comment by quinnj** [comment]
@davidanthoff, I find your tone a bit unnecessarily hostile. Saying the latest Tables.jl release "introduced a number of bugs" is inaccurate. It changed some quite complicated logic handling the integration of TableTraits/IteratorInterfaceExtensions/all iterable types in Julia and missed a case where certain Queryverse objects return `isiterable(x) === true`, but aren't themselves iterable (only the result of `IteratorInterfaceExtensions.getiterator` is actually iterable). Let's remember this is open source, we're all human, and mistakes will be made. I'm sorry this release caused issues, but I'm also very committed to fixing things that break (indeed, I spent most of last night reviewing every use of `Tables.istable` across all packages and a good chunk of time today reviewing ever package that defines `IteratorInterfaceExtensions.isiterable`). 

The fact of the matter is that we're going to run into issues like this while the majority of Julia packages are pre-1.0. If Queryverse packages, DataFrames, Tables and anyone else involved had proper semver bounds, there would have been much less breakage. But while packages are pre-1.0, we also understand that it's hugely inconvenient to apply conservative semver restrictions, so we're stuck in a bit of a tricky spot.

Anyway, I believe I have a proper, simple fix in https://github.com/JuliaData/Tables.jl/pull/91. I've also gone through every Queryverse IO package to ensure things work as expected with that change. I'll tag a new release once tests pass.

**Comment by braamvandyk** [comment]
@quinnj Thanks for the awesome effort. Is there any testing I could assist with? I would love to be able to contribute. Just let me know what I can do.

**Comment by nalimilan** [comment]
It should just work now if you update your packages.

**Comment by braamvandyk** [comment]
Will do so ASAP. Thanks!
