### ISSUE TITLE
Improvement of rename!

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1782]
`rename!(f::Function, df)` is not really convenient as `f` normally has to convert column names to string, operate on a string and convert it back to `Symbol`.

Two ideas:
1. (more radical) maybe we should change `rename!` to assume that `f` takes a string a returns a string and `Symbol` unwrapping/wrapping happens automatically
2. (less radical) maybe we can add a kwarg to `rename!` that would allow the user to choose if `f` is from string to string or from `Symbol` to `Symbol`

**Comment by nalimilan** [comment]
At least we could allow returning a string in addition to a symbol. Not sure about converting the argument to string before passing it, as it would be inconsistent with the fact that we use symbols everywhere.

**Comment by bkamins** [comment]
Actually in this case the change could be quite small and non breaking - we can simply cast whatever is returned by `f` to `Symbol` (or restrict casting only to `AbstractString`).

**Comment by kescobo** [comment]
Would also be great to be able to do pairs of Int=>Symbol so that one can rename columns by index rather than name. I'm often in a situation where I need to rename the first column of a bunch of tables where I don't necessarily know the name. So something like `rename(df, 1=>:a)` and `rename(df, [1=>:a, 2=>:b])`

**Comment by bkamins** [comment]
Now we allow string or `Symbol` as "oldcol", do we still want to add integers?

**Comment by nalimilan** [comment]
Why not, if somebody wants to implement that...

**Comment by bkamins** [comment]
I have opened https://github.com/JuliaData/DataFrames.jl/pull/2030 for this (as the docstrings for `rename` and `rename!` needed decoupling and a clean-up anyway).

**Comment by bkamins** [comment]
all is done here. closing.
