### ISSUE TITLE
add coalesce for dataframe

### ISSUE THREAD

**Issue by babaq** [JuliaData/DataFrames.jl#1791]
some times we want to replace all missing to a value in a dataframe, why not add 
`coalesce!(df::DataFrame,rep=0)=foreach(c->df[c]=coalesce.(df[c],rep),names(df))`?

**Comment by bkamins** [comment]
I think that doing this in place has little value as you replace all vectors anyway in your proposal.

Currently such an not in-place operation should be written as `mapcols(x -> coalesce.(x, 10), df)` which I find concise enough and explicit.

The hesitation I have is that `coalesce` does not work on collections, so making `coalesce!` do so would be a bit problematic.

**Comment by babaq** [comment]
the not-in-place `coalesce` version will be a one liner as you shown using `mapcols`. I am not sure of in-place one since i just natrually try to coalesce a DataFrame and found it not exist.

what do you mean `coalesce` not working on collections, I thought each column already a collection.

**Comment by bkamins** [comment]
> what do you mean `coalesce` not working on collections, I thought each column already a collection.

`coalesce` treats its arguments as scalars and you have to broadcast it using `.` to make it work on e.g. vectors.

**Comment by babaq** [comment]
I see, i think make coalesce to handle DataFrame as a type is to hide those details, so you don't have to think a bout `mapcols(x -> coalesce.(x, 10), df)` using map and broadcast.

**Comment by bkamins** [comment]
@nalimilan - do you have an opinion on this issue?

**Comment by nalimilan** [comment]
IIRC we had mentioned the possibility of implementing `replace(df, missing=>0)` instead. Maybe we could have `replace!` too and have it allocate new vectors by default, a bit like `disallowmissing!`.

**Comment by bkamins** [comment]
`replace`/`replace!` is a better name.

Two comments, if we decided to add this functionality:
* probably, to be consistent with other methods, we should add an optional argument allowing to specify the columns that are to be changed
* in general I think we have to allocate new vectors as the replacement can have a different type than is allowed by the vector. Here we only have a small clash with what `replace!` now does in base (which is fully in-place).

**Comment by nalimilan** [comment]
Yes, there's always that ambiguity about what in-place means for a data frame. I tend to think modifying the column vectors in-place isn't that useful and probably not what users expect in general, so maybe it's OK to allocate new vectors. Though that would be somewhat inconsistent with `push!`/`append!`, but `disallowmissing!` and `categorical!` already behave differently, so...

**Comment by bkamins** [comment]
IMO the user-visible inconsistency is that `replace!` for `DataFrame` would not fail in cases when `replace!` for an array fails. But maybe this is not a problem 😄.

**Comment by bkamins** [comment]
But to sum up - I am OK with adding `replace` and `replace!` along the lines we have discussed here, i.e. `replace!` would create new columns, and `replace` would guarantee copying of all columns. They should follow `replace`/`replace!` API from Base except that `count` keyword argument should apply per column (not total number of replacements) and we should add `cols` keyword argument allowing to specify which columns should be considered for replacement.

**Comment by pdeffebach** [comment]
So we have

1. Make whole new data frame and copy everything over 
```
replace(df, 1 => missing)
```

2. Make new columns but keep rest of dataframe intact and return that
```
replace!(df, 1 => missing)
```

3. Keep rest of data frame *and* replace the columns in place. Only works if `df[name]` can already contain missings and will fail otherwise. This thing might eventually be called `replace!!`. 
```
for name in cols 
    replace!(df[name], 1 => missing)
```

**Comment by bkamins** [comment]
Option 3 can be written as:
```
foreach(col -> replace!(col, 1=>missing), eachcol(df))
```

**Comment by bkamins** [comment]
Closing, as now you can simply write:
```
coalesce.(df, replacement_value)
```
to get what you want.

CC @nalimilan - I was surprised how easy it now is 😄.
