### ISSUE TITLE
Push! row to DataFrame initialized via variable

### ISSUE THREAD

**Issue by Crown421** [JuliaData/DataFrames.jl#1800]
I have found strange behaviour when initializing an empty DataFrame and then adding a row.
Depending on how it was initialized the behaviour differs in a way that does not make sense to me, and I would like to ask whether this is intentional or not. 
Also if its the former, I would be curious what the reasoning is, as I am not sure I fully understand Types in Julia yet. 

Following the Getting Started section, typing
```   
tp = Int[]  
df = DataFrame(A = Int[], B = Int[])
push!(df, (1,2))
```
returns the expected 
```
2×2 DataFrame
│ Row │ A     │ B     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2    │
```
However, when trying to make it more modular (I want to construct several frames in a very similar way, but with different content (types)), I tried to following
```   
tp = Int[]  
df = DataFrame(A = tp, B = tp)
push!(df, (1,2))
```
which returns:
```
2×2 DataFrame
│ Row │ A     │ B     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 1     │
│ 2   │ 2     │ 2     │
```
The push! command still requires a tuple/array with the same number of elements as existing columns, but appears to repeat them into each column, so adding a row with n elements to a column with n columns yields a n,n - DataFrame. 

It gets stranger when using different types for the columns. Typing
```
tp = Int[]  
df = DataFrame(A = String[], B = tp, C = tp)
push!(df, ("a",1,2))
```
results in
```
│ Row │ A      │ B     │ C     │
│     │ String │ Int64 │ Int64 │
├─────┼────────┼───────┼───────┤
│ 1   │ a      │ 1     │ 1     │
```

and, when adding the row twice we find 
```
tp = Int[]  
df = DataFrame(A = String[], B = tp, C = tp)
push!(df, ("a",1,2))
push!(df, ("a",1,2))
```
we find
```
│ Row │ A      │ B     │ C     │
│     │ String │ Int64 │ Int64 │
├─────┼────────┼───────┼───────┤
│ 1   │ a      │ 1     │ 1     │
│ 2   │ a      │ 2     │ 2     │
```

If this is intended behaviour, I would be interested to learn, and maybe it might be worth adding a note to the documentation.

**Comment by bkamins** [comment]
This is a bug. I will fix it today.
