### ISSUE TITLE
Not able to access cols having dot(.) in them

### ISSUE THREAD

**Issue by janismdhanbad** [JuliaData/DataFrames.jl#1807]
Hi All,
I am trying to access a column having a dot(.) in it for eg. "Sepal.Length" and it's giving me error below. If someone could please refer me to the correct way of accessing that.

Thanks!

![image](https://user-images.githubusercontent.com/15145740/57582572-04003a00-74e4-11e9-9427-f2122f21a33f.png)

**Comment by bkamins** [comment]
use `data[Symbol("Sepal.Length")]` syntax. The limitation comes from the fact that `.` is not allowed in identifiers in Julia. You can also pass column number like `df[1]`.

**Comment by janismdhanbad** [comment]
Thanks, it got resolved. Is there any way to index the columns using some similar syntax?
I am trying to do `data[:,:Symbol("Seoal.Length")]` and it's throwing error below:

MethodError: objects of type Symbol are not callable

Stacktrace:
 [1] top-level scope at In[75]:1

**Comment by bkamins** [comment]
`data[:,Symbol("Sepal.Length")]` but this is essentially the same as above (the only difference is that it performs a copy of the column). But you can write also something like `data[1:10,Symbol("Sepal.Length")]` to subset columns.

**Comment by janismdhanbad** [comment]
worked like a charm, thanks a lot.
