### ISSUE TITLE
Unnecessary copy for any Queryverse source

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataFrames.jl#1809]
I think (if I understand the current state of constructors and Tables.jl correctly) that we have a pretty major regression for the entire Queryverse integration with the recent versions because essentially anything a la:
```julia
df = DataFrame(anything_queryverse)
```
makes an unnecessary temporary copy of all the columns during the construction of the `DataFrame` instance.

I think here is what is happening currently: 

a) if `anything_queryverse` implements the `get_columns_copy_using_missing` interface from [TableTraits.jl](https://github.com/queryverse/TableTraits.jl/blob/816661ce6c5e16e92a161a7fa35201c597a023ad/src/TableTraits.jl#L35), then `Tables.columns` will return the column vectors that `TableTraits.get_columns_copy_using_missing ` returned, and then the `DataFrame` constructor will make a copy of each of these columns and use those. That is not good, because the whole point of the `get_columns_copy_using_missing` interface is that the source allocates a set of column vectors that the sink then owns, i.e. they are by the definition of the interface already copies that the sink can use.

b) if `anything_queryverse` implements the iterable tables interface (i.e an iterator of named tuples), then `Tables.columns` will allocate new column vectors and populate them with the values from the source, and then return those. And then the `DataFrame` constructor makes copies of those vectors, which again are really unnecessary large temporary allocations. After all, those vectors that are being allocated are _only_ allocated for this specific sink, so really they are best interpreted as copies for the sink as well.

I'm not sure what a good solution to this is, but it would be good to find some solution to this, given that this used to work well for a long time before the recent set of changes.

It would of course be easy to solve this if DataFrames.jl implemented the TableTraits.jl interfaces directly: they are explicit about column ownership, so the `DataFrame` constructor would always know whether it is getting columns from a source that it (DataFrame) then owns. I think the difficulty here stems from the fact that `Tables.columns` does not distinguish between a case where a source is returning a copy of columns and one where it is returning something that is still owned by the source. So what happens in the end is that `Table.columns` when called on any TableTraits.jl source will return vectors that are already copies, but for other sources `Tables.columns` can return a view. As the consumer, the `DataFrame` constructor then doesn't really know what to do: in the first case it shouldn't make a copy of what is returned by `Tables.columns`, in the second it should. I think the core problem is that those two cases are now conflated in the `Tables.columns` function.

@quinnj any idea what one could do about this?

EDIT: Oh, and I should add that I might well misunderstand what is happening right now! So a sanity check whether my description of when copies are made is correct would also be great!

**Comment by quinnj** [comment]
Ah yes, this is indeed an issue; but let's be clear: nothing in Tables.jl has changed or caused this. It was the most recent 0.18 release of DataFrames that introduced the `copycols=true` keyword argument to all constructors. I remember bumping into this in CSV.jl while working on the overhaul there, but it depends on DataFrames directly, so the affect on other Tables.jl sources didn't occur to me.

Now, I do believe Tables.jl can provide some kind of solution here; we could introduce some kind of `Tables.columncopies(x)` function that DataFrames could use to know whether the result of `Tables.columns(x)` is providing a copy of the input columns or not.

**Comment by bkamins** [comment]
>  As the consumer, the `DataFrame` constructor then doesn't really know what to do

This is exactly the key problem we tried to solve when 0.18 was released. Currently (in 0.18) we take a safe approach, i.e. copy columns unless we can prove that we do not have to copy columns.
For instance `DataFrame(x::Vector{<:NamedTuple}` does not do unnecessary copies, because we know it is safe not to copy.

We have discussed that we need in the future some way of passing the information along with the data structure if it requires copying or not, but this is "outside" the DataFrames.jl package. Of course when such information is available we should update the DataFrames.jl codes to use this fact.

For the time being `DataFrame!` function is provided so that you can manually call it when you are sure that no copying is needed (so the long term solution is kind of automatic detection if we should use `DataFrame` or `DataFrame!` function to construct a `DataFrame`).
