### ISSUE TITLE
type-mismatch problem when push! to data frame introduced by CSV.jl v.0.5.2 changes

### ISSUE THREAD

**Issue by disleyland** [JuliaData/DataFrames.jl#1812]
in CSV.jl v.0.4.3, the eltype of a column in a data frame used to something like Array.Union{missing, string}, but in the latest CSV.jl update (0.5.2), the DataFrame column is now CSV.Column{String,String}.     This means push!(df,["string","string"]) for example throws up a type-mismatch error.  I've tried to set types created by the CSV.read/file process, but the new eltypes are all CSV.Column's.  So I'm currently having to manually convert all columns.  Am I missing a trick?

**Comment by bkamins** [comment]
What is your question exactly? Most probably you should use `DataFrame(CSV.File("filename"))` to create your data frames that can be mutated. By default CSV.jl returns read-only columns now.

**Comment by disleyland** [comment]
sorry hit enter before typing

**Comment by disleyland** [comment]
ah I didn't know this trick! let me try

**Comment by disleyland** [comment]
ok thanks.  this now creates the eltype WeakRefStrings.StringArray.  Is this eltype compatible with functions that worked with Array.Union{missing, string} or might I find some breaking in legacy code you think?

**Comment by bkamins** [comment]
I think nothing should break as `WeakRefStrings.StringArray{String,1}` is subtype of `AbstractVector{String}`. I will open an issue in CSV.jl repo though as probably this requires clarification in the docs.

**Comment by disleyland** [comment]
Thanks for the help.  I was using the CSV.jl instructions as well which didn’t work:   CSV.File(file) |> DataFrame! .  Bad that their approach to DataFrame creation differ from the DataFrame(CSV.File) approach

Richard

**Comment by bkamins** [comment]
This is the same.

`CSV.File(file) |> DataFrame` makes sure you can mutate the output but is slower while `CSV.File(file) |> DataFrame!` is faster (which probably is relevant only for very large files), but returns immutable columns.

**Comment by disleyland** [comment]
Ah I spoke too soon. There are possible breakages. 

In the earlier version, some columns were converted as Array{Union{Missing, String},1}, are now being turned into PooledArrays.PooledArray{String,UInt32,1,Array{UInt32,1}}

**Comment by bkamins** [comment]
Yes - your general problem is that in your code you assume `Vector{Union{String,Missing}}` and you should assume `AbstractVector{Union{String,Missing}}`. But - as I noted in https://github.com/JuliaData/CSV.jl/issues/435 I think we should provide the way to return "plain old vector" if the user wishes so.

**Comment by nalimilan** [comment]
Please report if you encounter methods that work on `Vector{Union{String,Missing}}` but not on `PooledArray{String}` or `StringArray{String}`. These just need to be fixed.

**Comment by disleyland** [comment]
problem i am having with CSV.jl is that in v.0.4.3,  the default type was always Union{Missing, String}, Unions{Missing, Int64} etc.  Now when I turn CSVs into dataframes I am getting discrepancies in the types, and they all so far seem to be unhappy with missing and thus failing to add rows.  

So this bit of code is constantly breaking, eg., push!(df,[“string”,”string”,missing])

**Comment by bkamins** [comment]
@quinnj - is it possible now in CSV.jl to simply make all columns accept `Missing` in union even if source data did not contain any missing values? (I think not, but please confirm).

@disleyland if what I ask above is not possible then use `allowmissing!` on your `DataFrame`.

**Comment by nalimilan** [comment]
Yes AFAIK one needs to call `allowmissing!` manually. That's a bit annoying, but operations are much faster if you don't expect missing values to be present, so that's a good default.

**Comment by bkamins** [comment]
Yes - but then the question is if this is a design we leave, or some kwarg to `CSV.File` should be added to handle this case.

**Comment by quinnj** [comment]
fwiw, I'm trying to avoid unnecessary keyword arguments in CSV.jl that have pretty trivial solutions otherwise. It complicates the package surface area and makes large code changes much more painful trying to re-support everything.

**Comment by bkamins** [comment]
OK

**Comment by nalimilan** [comment]
Yes, I'm not sure an argument is really more convenient than calling `allowmissing!` in that case. Though the deprecation could point to `allowmissing!`/`disallowmissing!`.

**Comment by disleyland** [comment]
Yes. I think splashing a notice on CSV.jl that there is a big change in 0.5.2 where the implication is not only that CSV.read generate a "read-only” file with its own eltype, but also that conversion to a DataFrame is no longer automatically setup to missing data if it wasn’t there already, so beware an use allowmissing!(df).  I’ve just never known about these things because I’ve never had to.  Now I do :) 

And in my case, this is really a migration issue from Julia v.6 to 1.1 issue where old CSVs had NA in them (which is why CSV conversion is not auto-detecting a need for missing)

**Comment by disleyland** [comment]
+1 on the depreciation message idea
