### ISSUE TITLE
Surprising setindex/setproperty behaviour

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaData/DataFrames.jl#1815]
Here's a surprising result: `df.col = 1` and `df[:col] = 1` broadcast i.e. act like `.= 1` - which is inconsistent with `df.col` returning the underlying vector.

Example:
```julia
julia> df = DataFrame(:a => 1:10, :z => 1:10);

julia> df.a
10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

julia> b = collect(1:10);

julia> df.a == b
true

julia> df.a = 1;

julia> df.a
10-element Array{Int64,1}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

julia> b = 1;

julia> b
1

julia> df.a == b
false
```

**Comment by bkamins** [comment]
This will be fixed soon. See https://github.com/JuliaData/DataFrames.jl/issues/1806 and https://github.com/JuliaData/DataFrames.jl/pull/1804 for first steps towards that. The design is not simple though.

**Comment by bkamins** [comment]
See the new target rules here: https://github.com/JuliaData/DataFrames.jl/blob/master/docs/src/lib/indexing.md

They should be consistent and work as expected (we need another release cycle to get there).

I am closing this PR, but feel free to reopen if you have more comments.
