### ISSUE TITLE
does groupby preserve order in SubDataFrames?

### ISSUE THREAD

**Issue by tpapp** [JuliaData/DataFrames.jl#1817]
Are the rows in a `SubDataFrame` returned by iterating the result of a `groupby` guaranteed to be in the same order as in the original dataframe? Eg
```julia
julia> df = DataFrame(A = repeat(1:4, inner = 2), B = repeat(1:2, outer = 4))
8×2 DataFrame
│ Row │ A     │ B     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 1     │
│ 2   │ 1     │ 2     │
│ 3   │ 2     │ 1     │
│ 4   │ 2     │ 2     │
│ 5   │ 3     │ 1     │
│ 6   │ 3     │ 2     │
│ 7   │ 4     │ 1     │
│ 8   │ 4     │ 2     │

julia> [issorted(d.B) for d in groupby(df, [:A])]
4-element Array{Bool,1}:
 1
 1
 1
 1
```
My reading of the code suggests that this is the case, but I am wondering if this is something one can rely on, or an accident of the implementation. Since docs don't specify this, there is no particular reason the rows could not be exchanged.

**Comment by bkamins** [comment]
Yes they are guaranteed to have the same order up to my understanding how the code works (but the groups can have different order, e.g. they can be sorted).

@nalimilan has written this code so probably it is best that he confirms 😄.

**Comment by tpapp** [comment]
Thanks. The question is not only about the code, but whether this is a property that the API commits to. 

Simply clarifying it in the docstrings (and maybe a few tests, which I am happy to contribute once a decision is made) would resolve the issue for me.

**Comment by bkamins** [comment]
This is what I thought we should do 😄, but I am waiting for @nalimilan to confirm.

**Comment by nalimilan** [comment]
Yes, AFAIK we guarantee that the original order is preserved within each group, and the test currently test that. We should indeed document it (probably saying that the algorithm is stable).
