### ISSUE TITLE
Negated indexing

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#182]
It would be nice to make a general purpose negated indexing API for DataFrames:

```
df[not("Column9")]
df[not("Column2", "Column9")]
```

**Comment by Nosferican** [comment]
Should this issue be closed now?

**Comment by ararslan** [comment]
Yes. Will hopefully be addressed more broadly in 1.1, at which point we can use whatever solution Base comes up with.
