### ISSUE TITLE
DataFrame error

### ISSUE THREAD

**Issue by samberk93** [JuliaData/DataFrames.jl#1821]
I try the following code after installing DataFrames.jl

```
Using DataFrames
x = rand(4,4)
convert(DataFrame,x)
In my Window PowerShell, it worked 
but in the jupyter notebook and the juliabox, they keep telling me the message:
UndefVarError: DataFrame not defined

Stacktrace:
 [1] top-level scope at In[57]:2
```

Can anyone help me with this problem

**Comment by bkamins** [comment]
It seems you have a typo in your code. `Using` should be written in lower-case.
Additionally you can simply write `DataFrame(x)`.
Also please make sure that DataFrames.jl is installed in your environment.

**Comment by samberk93** [comment]
Also, If I have the following data
A = [["1.1", "1.2", "1.3"] , ["1.1, "1.5", "1.6"]]
in pythonn I can do 
pd. DataFrame(A, columns = ['x', 'y','z'], dtype = float)
it will return 
x y z
1.1 1.2 1.3
1.1 1.5 1.6
How can I do it in julia
DataFrame(A)
give me
1.1 1.1
1.2 1.5
1.3 1.6
Thanks

**Comment by bkamins** [comment]
Can you please copy-paste code that works without errors and quote it (I have done it twice above to show you how).

Regarding the question. You can write:
```
DataFrame([getindex.(A, i) for i in 1:3])
```
or
```
DataFrame(permutedims(reduce(hcat, A)))
```

The reason of the difference is that DataFrames.jl works column-wise.

Also in general I recommend asking usage questions at https://discourse.julialang.org/ or https://stackoverflow.com/questions/tagged/julia. We typically restrict issues on GitHub to topics related to the development of the package like feature requests of bug reports.
