### ISSUE TITLE
select and deletecols for `SubDataFrame` and `DataFrameRow`

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1825]
I feel that we should (for sure we can) define: `select`, `select!`, `deletecols` and `deletecols!` for:
* `SubDataFrame`
* `DataFrameRow`

But please comment on it before I make a PR.

**Comment by nalimilan** [comment]
Sure. Actually that would be nice for https://github.com/JuliaData/DataFrames.jl/pull/1824.

**Comment by bkamins** [comment]
This was the point. I will change #1824 (and rename it) to include these changes.

**Comment by bkamins** [comment]
@nalimilan things are never simple when you dig into them. I will put #1824 on hold till we discuss the general design approach here (and then - depending on what comes out from it decide how to proceed with the PRs).

Here is a list of things to be discussed (I write what I think should happen), but in general.
* `select(sdf, cols, copycols=true)` -> a new `DataFrame` is created with columns freshly allocated; this is the default
* `select(sdf, cols, copycols=false)` -> a new `SubDataFrame` is created with the same parent (this is a bit problematic as then `select` on `sdf` is not type stable, but it is a small union so it should be OK)
* `deletecols(sdf, cols, copycols=true)` -> a new `DataFrame` is created with columns freshly allocated; this is the default
* `deletecols(sdf, cols, copycols=false)` -> a new `SubDataFrame` is created with the same parent (this is a bit problematic as then `select` on `sdf` is not type stable, but it is a small union so it should be OK)

all other operations are disallowed, in particular:
* we do not allow any `!` functions on views, as we want to treat views as immutable (but this is debatable - technically we could allow mutation of views)
* we do not allow `select` and `deletecols` for `DataFrameRow` (as it is not clear for me if when `copycols` is `true` then a `NamedTuple` or `DataFrameRow` should be created; in general I think there is no huge need for these functions for `DataFrameRow`)

**Comment by nalimilan** [comment]
Sounds good in general. Do we really need to keep `deletecols`? It sounds a bit weird to say "delete" since it returns a copy. Maybe we could just keep `select(df, Not(...))`? That would also simplify the API. Same for `deletecols!` then.

A few remarks:
> `select(sdf, cols, copycols=false)` -> a new `SubDataFrame` is created with the same parent (this is a bit problematic as then `select` on `sdf` is not type stable, but it is a small union so it should be OK)

We could also return a `DataFrame` with `SubArray` columns, but that would be less clear than a `SubDataFrame`. Anyway I think the compiler will be able to propagate the value of `copycols` when it's a literal, so that the type is inferred.

>     * we do not allow any `!` functions on views, as we want to treat views as immutable (but this is debatable - technically we could allow mutation of views)

Yes, it could be interesting to allow `!` to return a view, as that would be more convenient than `copycols=false`. But we can decide that later.

**Comment by bkamins** [comment]
`deletecols!` was there before I started to work on this package. `deletecols` is for consistency (probably `dropcols` would be a better name thinking of it).

The problem with `Not` is that two packages in the ecosystem define it in a conflicting way. I have opened an issue on this https://github.com/davidavdav/NamedArrays.jl/issues/77, but got no response yet.

**Comment by bkamins** [comment]
To be clear - I am ok to use `Not` instead of `deletecols` and `deletecols!` but we have to decide how we resolve the name conflict. In general this should be easy as both packages use the same definition of the `struct`.

**Comment by bkamins** [comment]
Any opinion on how we should handle `Not`?

We should decide it either now (and implement it in the first place) or drop the discussion for some time, as the required changes would be conflicting with further `setindex!` and broadcasting work (we will have manually to bake-in handling of `Not` into `getindex`, `view` and `setindex!`).

**Comment by nalimilan** [comment]
I think all packages should use `Not` from InvertedIndices (and probably later from Base directly). Let's use it, and then make a PR against NamedArrays if needed.

**Comment by bkamins** [comment]
OK - so I will make a PR with `Not` after Regex PR is done.

**Comment by bkamins** [comment]
All is done what was discussed here.

**Comment by jzazo** [comment]
Is there an equivalent `select` for rows? I find that when pruning a DataFrame, the cols are selected, and the rows have to be deleted. This behavior is strange.

Could it be more consistent and have both `deletecols`/`deleterows`, or make `select` also select rows? It does not hurt to keep `deletecols!`, why remove it?

I just got my deprecation warning on `deletecols!` today...

**Comment by nalimilan** [comment]
@jzazo These questions aren't related to this issue, please file a separate one or ask on Slack. Thanks. (Also see `filter`.)
