### ISSUE TITLE
Allow empty `keys` argument in `by()`

### ISSUE THREAD

**Issue by alecloudenback** [JuliaData/DataFrames.jl#1837]
When exploring data or creating a function to abstract the process of generating a fixed set of results for different combinations of variables, it would be nice to be able to pass an empty array which would simply "group-by" all the rows in the dataset, e.g.

````julia
function summarize(varies_by)

    by(iris,varies_by) do df
          (m = mean(df.PetalLength), s² = var(df.PetalLength))
    end
end

summarize([])
````

would return 

| |m|s²|
|--- |--- |--- |
|1|3.75867|3.11318|

Currently it errors: 

````julia
BoundsError: attempt to access ()
  at index [1]
````

**Comment by nalimilan** [comment]
Currently `GroupedDataFrame` isn't prepared to handle this, but I guess that would be doable (putting all rows in the same group). Is this allowed by other implementations (like dplyr and Pandas)?

**Comment by alecloudenback** [comment]
In R: 

````r
library(dplyr)
starwars %>%
  group_by(species) %>%
  summarise(
    n = n(),
    mass = mean(mass, na.rm = TRUE)
  ) %>%
  filter(n > 1,
         mass > 50)
````

returns 

````r
# A tibble: 8 x 3
  species      n  mass
  <chr>    <int> <dbl>
1 Droid        5  69.8
2 Gungan       3  74  
3 Human       35  82.8
4 Kaminoan     2  88  
5 Mirialan     2  53.1
6 Twi'lek      2  55  
7 Wookiee      2 124  
8 Zabrak       2  80 
````

And leaving the group_by empty just aggregates across all:

````r
starwars %>%
  group_by() %>%
  summarise(
    n = n(),
    mass = mean(mass, na.rm = TRUE)
  ) %>%
  filter(n > 1,
         mass > 50)
````
returns:

````r
# A tibble: 1 x 2
      n  mass
  <int> <dbl>
1    87  97.3
````

**Comment by alecloudenback** [comment]
While R **does** (above), Pandas **does not**:

````python
> grouped = df.groupby()
TypeError: You have to supply one of 'by' and 'level'
````

**Comment by nalimilan** [comment]
OK, then I guess we could support this too. Though that's not high priority for us, but feel free to make a pull request.

**Comment by bkamins** [comment]
fixed
