### ISSUE TITLE
Redesign `insertcols!`

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1851]
It would be good to add `copycols` kwarg to `insertcols!` and make it insert columns at the end of the data frame by default.

**Comment by c42f** [comment]
If you're changing `insertcols!` would it be possible to allow the insertion of more than one column? I just tried to do this and was quite confused that it's disallowed given the function name is pluralized.

**Comment by bkamins** [comment]
See #2078 for the proposed implementation.
