### ISSUE TITLE
Why calling error() rather than just throw() in insert!()?

### ISSUE THREAD

**Issue by petershintech** [JuliaData/DataFrames.jl#1868]
I found the following code in index.jl. Not sure why calling error() rather than just throwing the BoundsError()? Also would be better to provide some message to help users.
```
function Base.insert!(x::Index, idx::Integer, nm::Symbol)
    1 <= idx <= length(x.names)+1 || error(BoundsError())
    for i = idx:length(x.names)
```

**Comment by bkamins** [comment]
Also agreed. There are also several more places where `error` is used (mostly because this is part of code that was not touched for a longer time and was not cleaned up). Feel free to open a PR if you wish.

**Comment by petershintech** [comment]
Ok I will dig up a little bit more. I prefer small and isolated commits so you might receive multiple PRs for each small change.

**Comment by bkamins** [comment]
OK - no problem.
