### ISSUE TITLE
describe StatsBase vs DataAPI

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1882]
@quinnj & @nalimilan 
Given DataAPI has been released my question is about the plan regarding the source of importing `describe` to DataFrames.jl (I assume this should be synced with StatsBase.jl).

**Comment by nalimilan** [comment]
Yes I think they should both import and reexport `DataAPI.describe`.

**Comment by quinnj** [comment]
I already have PRs; I'll update them now that DataAPI is registered.

**Comment by quinnj** [comment]
Ok, DataAPI is now integrated w/ DataFrames and StatsBase for `describe`.
