### ISSUE TITLE
dropna

### ISSUE THREAD

**Issue by waweruk2001** [JuliaData/DataFrames.jl#1884]
Hi 
its me again, 
i keep getting this message: ERROR: UndefVarError: dropna not defined..
this is the plot  i am trying to draw;
 using Plots

julia> plots.histogram(dropna(train[:ApplicantIncome]),bins=50, xlabel="ApplicantIncome",labels="frequency")
ERROR: UndefVarError: dropna not defined
Please assist

**Comment by bkamins** [comment]
There is no such function as `dropna` in DataFrames.jl (nor any package it exports, nor in Base).

There is a function `skipmissing` that is defined in Base. And probably this is what you want to use like this:
```
plots.histogram(skipmissing(train.ApplicantIncome),
                          bins=50, xlabel="ApplicantIncome", labels="frequency")
```

**Comment by waweruk2001** [comment]
thank you so much ... i am learning data science using julia at this site: https://www.analyticsvidhya.com/blog/2017/10/comprehensive-tutorial-learn-data-science-julia-from-scratch/
and i had copied this instruction directly from their site. 
thank you very much for your help

**Comment by bkamins** [comment]
It is a very nice resource, but unfortunately it is significantly outdated (note that it uses Julia 0.6 which is long gone now).

In order to get an understanding how DataFrames.jl package works under its current version you can check out https://github.com/bkamins/Julia-DataFrames-Tutorial.
