### ISSUE TITLE
Allow column name transformations in unstack

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1886]
It would be useful to allow `unstack` to have a kwarg that allows to apply a function to transform generated column names.

CC @oxinabox

**Comment by oxinabox** [comment]
For sake of readers I am going to post more from the the whole conversation:

> 
> I wish unstack took a column name prefix
> I tend to do things like
> ```unstack(load_table, :time, :region, :load);```
> which gives me 1 row per time, and then 1 column per region,
> and the cells contain the load.
> The columns are thus named `North`, `South` etc. per the entriesi nthe Region column
> but I wish I could say to name them `load_North`, `load_South` etc.
> 
> Depending o nwhat other data I am joining it on to, I might want to say `load_North_region`
> So maybe even should just be a function?
> 
> You can join symbols with
> ```oldname->Symbol(:load_, oldname, :_region)```
> Which just seems more compact than a prefix and a suffix option.
> 
> Main usecase beyond suffixing and prefixing, I have, would be normalizing cases.
> Often things in the values are in “ALL CAPS” (with spaces even)

and I would like to transform that to `lower_case` before I make it a column name

**Comment by bkamins** [comment]
And to add to this - normalizing **before** making it a column name could lead to a warning and data loss. So we should decide if we prefer this or throwing an error if duplicate column name is produced.
