### ISSUE TITLE
show for DataFrameRows should display a table

### ISSUE THREAD

**Issue by oschulz** [JuliaData/DataFrames.jl#1894]
It would be very nice (a lot more readable) if `show` on `DataFrameRows` would display a table.

Just discussed this with @bkamins at JuliaCon.

**Comment by bkamins** [comment]
This should be doable for both `DataFrameRows` and `DataFrameCols` where we could delegate plotting to `parent` `show` and only change the caption. @nalimilan - any opinion?

**Comment by nalimilan** [comment]
Makes sense.

**Comment by oschulz** [comment]
Thanks!

**Comment by bkamins** [comment]
Please check out https://github.com/JuliaData/DataFrames.jl/pull/1901.

**Comment by oschulz** [comment]
Looks great - thanks, @bkamins!

**Comment by bkamins** [comment]
Fixed by #1917
