### ISSUE TITLE
Support getproperty on DataFrameRows

### ISSUE THREAD

**Issue by oschulz** [JuliaData/DataFrames.jl#1895]
In some applications that require a vector of something struct-like, `DataFrameRows` is better choice than `DataFrame`. It would be very helpful if `.field` via getproperty would also work on `DataFrameRows` since column access is still often required. This would also make `DataFrameRows` a mutable, API-compatible alternative to `TypedTables.Table`.

Just discussed this with @bkamins at JuliaCon.

**Comment by ararslan** [comment]
This already works.
```
julia> df = DataFrame(a=1:3, b=2:4)
3×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
│ 2   │ 2     │ 3     │
│ 3   │ 3     │ 4     │

julia> row = first(eachrow(df))
DataFrameRow
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │

julia> row.a += 1
2

julia> df
3×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 2     │ 2     │
│ 2   │ 2     │ 3     │
│ 3   │ 3     │ 4     │
```

**Comment by bkamins** [comment]
@oschulz idea is to add `getproperty` to `DataFrameRows` that would essentially be defined as:
```
getproperty(dfrs::DataFrameRows, s::Symbol) = getproperty(parent(dfrs), s)
```
I think it is acceptable to add it. We could also add it to `DataFrameCols`.

So you could write `eachrow(df).a` and it would the same as `df.a`.

**Comment by ararslan** [comment]
If I'm understanding correctly, that seems very breaking. What I showed above is something I personally have used several times just in the past week...

**Comment by bkamins** [comment]
@ararslan - your proposal is exactly like `eachrow` was designed to be used.

@oschulz proposal is breaking as now we expose properties `df` and `index` in `DataFrameRows` object, but I would assume that people do not rely on this.

The idea was to make `DataFrameRows` object behave like [StructArrays.jl](https://github.com/piever/StructArrays.jl) currently do. Do you see any serious shortcomings of such approach (apart from the fact - noted above - that this was not the original design intention).

**Comment by ararslan** [comment]
Okay, I think I'm not properly understanding the proposal then.

**Comment by bkamins** [comment]
Just to clarify. @oschulz wants to port this:
```
julia> using StructArrays

julia> t = StructArray((a = [1, 2], b = ["x", "y"]))
2-element StructArray(::Array{Int64,1}, ::Array{String,1}) with eltype NamedTuple{(:a, :b),Tuple{Int64,String}}:
 (a = 1, b = "x")
 (a = 2, b = "y")

julia> t.a
2-element Array{Int64,1}:
 1
 2
```
behavior to be also handled by `DataFrameRows` object, so that the last operation in this sequence:
```
julia> using DataFrames

julia> df = DataFrame(a = [1, 2], b = ["x", "y"])
2×2 DataFrame
│ Row │ a     │ b      │
│     │ Int64 │ String │
├─────┼───────┼────────┤
│ 1   │ 1     │ x      │
│ 2   │ 2     │ y      │

julia> dfrs = eachrow(df)
2-element DataFrameRows:
 DataFrameRow
│ Row │ a     │ b      │
│     │ Int64 │ String │
├─────┼───────┼────────┤
│ 1   │ 1     │ x      │
 DataFrameRow
│ Row │ a     │ b      │
│     │ Int64 │ String │
├─────┼───────┼────────┤
│ 2   │ 2     │ y      │

julia> dfrs.a
ERROR: type DataFrameRows has no field a
```
also would work.

**Comment by ararslan** [comment]
Ohhh, that makes sense. Thanks for explaining, I appreciate it. +1

**Comment by oschulz** [comment]
Yes, sorry for the confusion - I should have been more clear. Like @bkamins describes, I'm proposing the same getproperty to access columns that `StructArrays` and `TypedTables` provide.

**Comment by bkamins** [comment]
@nalimilan - what is your opinion on this?

If we did this we could also add this to `DataFrameColumns` object for symmetry.
Then we could add ability to index `DataFrameColumns` using `Symbol`s.

All this can be added and is not problematic, but I just wonder if it is needed (essentially we would then almost have two new subtypes of `AbstractDataFrame` with special single element indexing rules).

**Comment by oschulz** [comment]
> All this can be added and is not problematic, but I just wonder if it is needed

I think it would be very helpful for enabling generic user code if we had API-compatibility between `DataFrameRows` and `TypedTables.Table`, so that depending on application the one or the other (`TypedTables.Table` may not do so well with a very large number of columns, but has advantages in other use cases) can be chosen without changing code.

IMHO the "table == vector of ntuples" paradigm is very valuable - especially if convenient column access via `getproperty` is possible at the same time.

**Comment by nalimilan** [comment]
> If we did this we could also add this to `DataFrameColumns` object for symmetry.
> Then we could add ability to index `DataFrameColumns` using `Symbol`s.
> All this can be added and is not problematic, but I just wonder if it is needed (essentially we would then almost have two new subtypes of `AbstractDataFrame` with special single element indexing rules).

Yes, I guess it would make sense to have `DataFrameRows` and `DataFrameColumns` implement the full `AbstractDataFrame` API, returning an object of the same type rather than a `DataFrame`. Maybe with metaprogramming it can be done without duplicating too much code?

**Comment by bkamins** [comment]
As currently they are both subtypes of `AbstractVector` this is a bit problematic (without rewriting a lot of stuff). But we can easily make them support Tables.jl interface. This is what I would do, as it it will be sufficient for most cases (and then in particular adding `getproperty` makes sense).

**Comment by nalimilan** [comment]
Do we really need/want these to be `AbstractVector`s though? Maybe we should just define 1D indexing?

**Comment by bkamins** [comment]
We can discuss this (there is no rush to make the change in either way). The benefit of `AbstractVector` is that we get many functionalities "for free" as all methods, e.g. from Base, that expect `AbstractVector` just work. But we could go into `AbstractDataFrame` with 1D indexing direction if we see more benefits from this (personally I am OK with `AbstractVector` as you always can take `parent` of `DataFrameRows` or `DataFrameCols` to access an underlying `DataFrame`).

**Comment by oschulz** [comment]
> Do we really need/want these to be AbstractVectors though? Maybe we should just define 1D indexing?

The prime reason I suggested to add `getproperty` to these if *because* they are `AbstractVector`s, because that's what makes them so useful. If they just had 1D indexing, they couldn't be used in functions and datastructures that expect vectors. Because they are vectors, they could be grouped with `ArraysOfArrays`, be distributed as a `DistributedArray`, and be used as columns in other tables. That's one of the reasons I've used `TypedTables` so much lately - because having the `vector of tuple/struct-like` interpretation explicit instead of implicit make as lot of stuff possible that otherwise isn't. `AbstractVector`s just compose so very well.

**Comment by bkamins** [comment]
@nalimilan - so are you OK with staying with `AbstractVector` and only adding `getproperty`? If yes I will open a PR for this

**Comment by nalimilan** [comment]
Yes, sounds fine. Anyway, whether they are `AbstractVector`s or `AbstractDataFrame`s is somewhat orthogonal.

**Comment by oschulz** [comment]
Thanks a lot, @bkamins !

**Comment by oschulz** [comment]
Do you guys plan a new release of "DataFrames" in the near future?

**Comment by bkamins** [comment]
I have tagged a release a few hours ago, so 0.19.3 including these changes should be in a few hours/days (depending on when it gets merged to package registry).

**Comment by oschulz** [comment]
Oh, should have checked first, lol. Thanks a lot, @bkamins!
