### ISSUE TITLE
Sync the behavior of push!, vcat and append! in DataFrames.jl with Base

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1904]
When the decision in https://github.com/JuliaLang/julia/issues/25904 is made I think we should use consistent rules by default (and optionally have a keyword argument to add/reduce flexibility - depending if https://github.com/JuliaLang/julia/issues/25904 will end up being flexible or strict).

**Comment by bkamins** [comment]
@nalimilan - actually looking at the current API the only change I would make is to add `:identical` option for `cols` kwarg, that is even stricter than `:equal` and requires not only that the names match but that they must be in the same order. Then we could, in the future change `vcat` to default to `:identical` instead of current `:equal`.

**Comment by nalimilan** [comment]
Why not. Names aren't very descriptive but it's hard to find better ideas.

**Comment by bkamins** [comment]
Yes - I had a problem with `:equal` as it is already in use, but I could not come up with anything better.

**Comment by nalimilan** [comment]
We could deprecate `:equal` if we can find a better name...
