### ISSUE TITLE
Suggestion: Hide sidebar on the Website

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#1909]
I am following along with the DataFrames get started page from the [website](https://juliadata.github.io/DataFrames.jl/).

I think that adding a small feature to hide the sidebar would make the page more readable when splitting a monitor in halves. Otherwise the sidebar takes a large portion of the screen.

This is not urgent, just a suggestion.
Thanks!

**Comment by bkamins** [comment]
@mortenpi - is it possible to add an option to allow hiding/unhiding a sidebar in Documenter.jl? Thank you!

**Comment by mortenpi** [comment]
Hmm. It does get hidden automatically if the page becomes narrow enough. It might be worth optimizing when that happens though.

**Comment by bkamins** [comment]
Shall I open a PR in Documenter.jl?

(closing as this is not an issue in DataFrames.jl)

**Comment by mortenpi** [comment]
I think it's best to do it as part of JuliaDocs/Documenter.jl#1043 with the new front end. Feel free to open an issue though to make sure we don't forget it.
