### ISSUE TITLE
Column of dataframe syntax change?

### ISSUE THREAD

**Issue by pmcvay** [JuliaData/DataFrames.jl#1910]
When referring to columns of a dataframe, the getting started guide of the documentation says
"Columns can be accessed via df.col or df[:col]. The latter syntax is more flexible as it allows passing a variable holding the name of the column, and not only a literal name"

However, I'm getting a depreciation warning for that the `df[:col]` syntax. Is this an internal depreciation warning or is the syntax changing but the docs just haven't been updated yet?

Example
```julia 
julia> df = DataFrame(A = 1:3, B = ['a', 'b', 'c'])
3×2 DataFrame
│ Row │ A     │ B    │
│     │ Int64 │ Char │
├─────┼───────┼──────┤
│ 1   │ 1     │ 'a'  │
│ 2   │ 2     │ 'b'  │
│ 3   │ 3     │ 'c'  │

julia> df[:B]
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
3-element Array{Char,1}:
 'a'
 'b'
 'c
```

**Comment by ararslan** [comment]
That's an expected change, seems the docs just haven't been updated yet.

**Comment by pnadon** [comment]
I've noticed alot of tutorials for many packages ([Gadfly](http://gadflyjl.org/stable/tutorial/), [SolverBenchmark](https://juliasmoothoptimizers.github.io/SolverBenchmark.jl/latest/tutorial/) for example) now display this error, and I receive the same error when attempting to follow the tutorial. 

Is there anything I can do on my end to fix this, or should I wait for a fix from the developer / make a pull request with a fix myself?

And in the case of the latter, would anyone have any tips on how I would go about fixing this bug? I'm still new to Julia coming from a Python / Java background, and would greatly appreciate advice!

**Comment by pmcvay** [comment]
For my example, instead of `df[:B]` use `df[!, :B]`

**Comment by bkamins** [comment]
Please either make a PR to such package or open an issue and mention me in it and then I can fix this.

**Comment by bkamins** [comment]
If a symbol is not a dynamically generated variable the recommended syntax is `df.B`. The intention is that `df[!, :B]` is syntax for two cases (of course you can use `df[!, :B]` always if you like it):
* column name is not a valid identifier, e.g. (`Symbol("My column name")`)
* you dynamically generate column names at run-time, e.g. `col=some_computed_value; df[!, col]`

**Comment by pmcvay** [comment]
Is there a reason for the change? I liked the `df[:B]` notation. `DataFrameRow` doesn't have the same depreciation warning for `row[:B]`. Is that going to change as well?

**Comment by bkamins** [comment]
`DataFrameRow` is a 1-dimensional object, so it uses 1-dimensional indexing, so `df_row[:B]` will stay. `AbstractDataFrame` is a 2-dimensional object. See https://discourse.julialang.org/t/release-announcements-for-dataframes-jl/18258/51 for an extended discussion.
