### ISSUE TITLE
describe(df) when used in IJulia quit working on subset dataframes

### ISSUE THREAD

**Issue by proudindiv** [JuliaData/DataFrames.jl#1912]
```
df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
describe(df[1,:])
```
`MethodError: no method matching describe(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::DataFrameRow{DataFrame,DataFrames.Index})`

julia-1.1.1
DataFrames v0.19.1
IJulia v1.19.0

**Comment by bkamins** [comment]
`DataFrameRow` does not have a `describe` method (it essentially keeps one row of a data frame).

If you really want this use `describe(df[1:1,:])` as `df[1:1,:]` creates a `DataFrame` not a `DataFrameRow`.

**Comment by proudindiv** [comment]
thanks
