### ISSUE TITLE
using a tuple of keys to join-on, rather than a vector acts weird

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/DataFrames.jl#1915]
I forgot that `DataFrames` likes ot use `Vectors` whenever talking about collections of keys,
and I attemtped to join on a tuple.

This gave me an unexpected error.

Below is a MWE, showing the correct (expected) way this goes
and what happens with my mistake..

```
using DataFrames
df1 = DataFrame(A=1:10:1000, B=1:100,)
df2 = DataFrame(A=1:20:2000, B=1:2:200, C=true);

expected = join(df1, df2; on=[:A, :B], kind=:left)
first(expected, 5)|> repr |> print

mistake = join(df1, df2; on=(:A, :B), kind=:left)
```

Output:
```
5×3 DataFrame
│ Row │ A     │ B     │ C       │
│     │ Int64 │ Int64 │ Bool⍰   │
├─────┼───────┼───────┼─────────┤
│ 1   │ 1     │ 1     │ true    │
│ 2   │ 11    │ 2     │ missing │
│ 3   │ 21    │ 3     │ true    │
│ 4   │ 31    │ 4     │ missing │
│ 5   │ 41    │ 5     │ true    │


ArgumentError: Duplicate variable names: :A. Pass makeunique=true to make them unique using a suffix automatically.

```

**Comment by bkamins** [comment]
I have not designed it, but it seems intended:

> * `on` : A column, or vector of columns to join df1 and df2 on. If the column(s)
>     that df1 and df2 will be joined on have different names, then the columns
>     should be `(left, right)` tuples or `left => right` pairs, or a vector of
>     such tuples or pairs. `on` is a required argument for all joins except for
>     `kind = :cross`

I.e. we treat `Tuple` like a `Pair`.

What behavior would you expect (I guess to treat `Tuple` like a vector - right?).

**Comment by oxinabox** [comment]
Yeah, I would expect vector.
(As an aside, I did not know about the pair behavour, that is super cool)

**Comment by bkamins** [comment]
I think then I will deprecate `Tuple` for a moment (as it is ambiguous what it does), and later we can decide if we want to support a `Tuple` like a vector (I guess it is OK).

CC @nalimilan

**Comment by nalimilan** [comment]
Yeah, better only accept `Pair`s for the current meaning of `Tuple`.
