### ISSUE TITLE
Generic iterables vs DataFrame operations

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1921]
Currently in `push!` (and soon in `setindex!` in #1899 if we keep this approach) we allow any iterable as a source of data. This sometimes leads to surprising results, e.g.
```
julia> df = DataFrame(ones(1, 3))
1×3 DataFrame
│ Row │ x1      │ x2      │ x3      │
│     │ Float64 │ Float64 │ Float64 │
├─────┼─────────┼─────────┼─────────┤
│ 1   │ 1.0     │ 1.0     │ 1.0     │

julia> push!(df, "abc")
2×3 DataFrame
│ Row │ x1      │ x2      │ x3      │
│     │ Float64 │ Float64 │ Float64 │
├─────┼─────────┼─────────┼─────────┤
│ 1   │ 1.0     │ 1.0     │ 1.0     │
│ 2   │ 97.0    │ 98.0    │ 99.0    │
```
Technically this is OK, as in this case `String` is an iterable. The question is if we want to allow this.

We can do three things:
1. allow any iterable (current approach)
2. allow any iterable except `AbstractString` (this is probably the most common case where a user can go wrong)
3. allow only selected class of iterables

@nalimilan, @quinnj - do you have any opinion on this?

**Comment by nalimilan** [comment]
I'd say it's OK. It's a bit surprising, but not the end of the world. I would also be fine with only accepting vectors and (named) tuples, though. Do we have use cases for accepting other types?

**Comment by bkamins** [comment]
The only relevant case other than vector and tuple is a generator, so something like e.g.
`(some_function(i) for i in 1:10)`. Or various iterators from `Iterators` package.
In short - when the user wants a lazy collection. And this happens in practice.

**Comment by nalimilan** [comment]
Right. So probably better continue allowing this.

**Comment by bkamins** [comment]
OK - so I am closing this, but we can reopen it if someone wants to comment.
