### ISSUE TITLE
Revert head and tail

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1933]
Following closed #1932.

The question is if we should remove `head` and `tail` or keep them as aliases to `first( , ::Integer)` and `last( , ::Integer)`.

My personal opinion is that I am OK to keep them as they are really common names. My personal experience is that I used to use `head` and `tail` a lot, and stopped using them as `first` and `last` are a bit more cumbersome to write.

CC @xiaodaigh, @mkborregaard, @nalimilan

**Comment by nalimilan** [comment]
I'd rather keep things as they are. `head` and `tail` have been deprecated for several months, and we haven't heard complaints until now. We're rather trying to clean up the API for 1.0, we can add these later if it turns out to be really needed.

We could improve our default printing method to print the few first *and last* rows, which would make these functions less needed.

**Comment by mkborregaard** [comment]
In jupyter you usually get everything, no?

**Comment by bkamins** [comment]
> We could improve our default printing method to print the few first and last rows, which would make these functions less needed.

This is what we have already in REPL AFAICT. That is why my opinion was a "very small con". I do not use `head` and `tail`, because most of the time I already see what I need when printing, and Julia is smart enough not to flood the console with output like R.

**Comment by bkamins** [comment]
@mkborregaard In Jupyter you get first rows only (typically around 20-30 depending on your settings). If you feel we should print also last rows this is doable (but I put this as a lower priority task than some other things I currently implement). If someone feels like it please open a PR for printing to HTML and LaTeX (they have to be changed in sync for Jupyter).

**Comment by nalimilan** [comment]
Let's close this has it hasn't come up in the last few months?
