### ISSUE TITLE
Allow partial re-ordering for `permutecols!`

### ISSUE THREAD

**Issue by nilshg** [JuliaData/DataFrames.jl#1942]
`permutecols!` currently requires passing a full list of column names in the desired order. It would be nice to have the option of only reordering the start of the DataFrame, a common operation that mirrors Stata's `order` command.

Desired outcome would be something like:
```
using DataFrames
df = DataFrame(rand(100,20))
leading_cols = [:x5, :x9, :x13]
df = df[!, vcat(lead_cols, setdiff(names(df), leading_cols)]
```

**Comment by bkamins** [comment]
What about reordering only columns that appear in the second argument (i.e. that we allow any subset of columns - not only the starting columns). This will not be ambiguous.

**Comment by nalimilan** [comment]
Why not. Though that doesn't allow the symmetric operations of moving some columns to the end. Another (alternative or complementary) solution would be to take pairs giving the name/index and its new position.

Anyway, does that really need to be in 1.0?

**Comment by bkamins** [comment]
I removed the milestone (but I will implement it pretty fast as this is a simple change, so it does not matter). The problem with `name/index => newindex` is that it can be sometimes hard to disambiguate what was the intention (is the operation sequential or one shot).

To move a column `5` to the end you will pass `[6:ncol(df); 5]`.

The permutation notation is unambiguous as it specifies a new order of columns within a subset of columns (so columns not included in the permutation do not move).

**Comment by bkamins** [comment]
A current approach is in https://github.com/JuliaData/DataFrames.jl/pull/1964

**Comment by bkamins** [comment]
Given our current implementation the reordering you asked for is achieved by:
```
select!(df, :x1, :x5, :x2, :)`
```
(i.e. give the first three columns and then indicate by `:` to include the rest of them)

so I am closing this issue (please reopen if you feel there is something more to be added here)
