### ISSUE TITLE
should `hcat!` be exposed in the public API?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#1948]
As far as I know there is no single function in the publicly exposed API right now which allows one to horizontally concatenate dataframes in-place.  It seems to me that there should be one, especially since `hcat` is already exposed.

I suppose we should consider whether having this means we should also have a `vcat!` (presumably entirely equivalent to `append!`) for consistency.

**Comment by bkamins** [comment]
I will try to look into it soon. Exposing `hcat!` should not be too hard to add.

Regarding `vcat!` it is the same as `append!`, so we would have to discuss if we want to add a new function with a duplicate functionality (in the past we tried to avoid this).

**Comment by bkamins** [comment]
Now `hcat!` can be written as:
```
insertcols!(df, pairs(eachcol(df2))...)
```
(also it is more general as you can insert `df2` anywhere)
given this do you think it is worth to add support for it?

CC @nalimilan - maybe you have some opinion on this.

**Comment by bkamins** [comment]
Closing as `insertcols!` does what is needed
