### ISSUE TITLE
API for functions that help reduce memory usage

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFrames.jl#1954]
Should DataFrames provide a set of utilities to reduce memory usage? E.g. 

`try_reduce_size` can do things like retype `Int64` as `Int32` and looking for String columns that have many repeat values and compress it down to `CategoricalArrays` etc. 

Maybe `try_reduce_size` isn't a good name. But it's the idea here that counts. Or should this API sit in another package?

**Comment by xiaodaigh** [comment]
I want to propose this because I think large DataFrames just take up too much RAM in general.

**Comment by bkamins** [comment]
DataFrames already has `categorical` function to do this for `Strings`. Regarding numeric types (ints, floats, etc.) I think this functionality should be in a separate package as it is not DataFrames.jl specific (you might want to reduce size of any parametric container in this way).

**Comment by xiaodaigh** [comment]
https://github.com/xiaodaigh/JDF.jl now has some simple method for compressing a dataframe.

```julia
using JDF
type_compresss!(df) # compresses df
```

**Comment by bkamins** [comment]
Thank you for sharing. A few comments that might be useful for you:
* in unsigned types you do not have to check the lower bound (it will always be met)
* you are compressing `Float64` to `Float32` (which loses precision), but you are not compressing the same in union with `Missing`
* you are not compressing `String`s to categorical type with minimum type for level count
* you are not compressing `AbstractVector{Bool}` to `BitArray`

**Comment by xiaodaigh** [comment]
Float32 should be controlled by an option. String compression is next. The best combination is categorical followed by rle encoding. Also have an idea to compress string with common prefixes. Also detect Date types and compress
