### ISSUE TITLE
can't join more than two dataframes?

### ISSUE THREAD

**Issue by felluksch** [JuliaData/DataFrames.jl#1962]
Hi, 
I would expect that you could join more than two DataFrames with `join(df1, df2, df3, on = :id)` since the documention doesn't explicitly say otherwise (and even states "We often need to combine **two or more** data sets").

```julia
using StatsKit

df1 = DataFrame(id = 1:10, df1_col2 = 1:10, df1_col3 = 1:10)
df2 = DataFrame(id = 1:10, df2_col2 = 1:10, df2_col3 = 1:10)
df3 = DataFrame(id = 1:10, df3_col2 = 1:10, df3_col3 = 1:10)
df = join(df1, df2, on = :id) # works
df = join(df1, df2, df3, on = :id) # doesn't work
arr = [df1, df2, df3]
df = join(arr..., on = :id) # doesn't work

df = join(df1, df2, on = :id) # workaround
df = join(df, df3, on = :id)
```
I find it just a bit weird that you have to split it up. Or am I missing something?
Thanks for the work you put into this package btw!

**Comment by bkamins** [comment]
I have not implemented this, but I guess this can be added. The challenge is to make it efficient (in the worst case we can do it recursively for the time being). I guess you would want joining and the `kind` kwarg to be applied left-to-right order - right (like in `foldl`)?

**Comment by felluksch** [comment]
If you want to invest into this, would be great of course. But maybe it'll suffice to just add a disclaimer to the doc and tell the people they have to write their own function. In my case I wrote something like this: 
```julia
function joinDataFrames()
    arr = [df1, df2, df3, df4]
    old_e = arr[1]
    df = arr[1]
    for e in arr
        new_e = e
        if old_e != new_e
            df = join(old_e, new_e, on = :id)
        end
        old_e = df
    end
    return df
end
println(joinDataFrames())
```
But of course it would be more convenient to have it as core functionality as I feel it's a common use case (think several timecoded files you want to join on their timestamps).

**Comment by bkamins** [comment]
See #1963

**Comment by felluksch** [comment]
Thanks a lot for the immediate implementation! I guess we're done here.
