### ISSUE TITLE
Drop AppVeyor in favour of TravisCI

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaData/DataFrames.jl#1980]
What are peoples thoughts on dropping AppVeyor Windows builds in favour of using TravisCI Windows builds? Back in August TravisCI began supporting Julia Windows builds, [link](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187).

It seems that AppVeyor builds are [quite slow](https://ci.appveyor.com/project/nalimilan/dataframes-jl/history), and moving everything to TravisCI would centralize everything nicely.

**Comment by bkamins** [comment]
@ararslan - do you know how to set up 32-bit Julia on 32-bit machine tests on Travis. I could not find how to do it (it seems it is not possible).
Without this feature we have to stick with AppVeyor (actually this allowed us to catch some important bugs, even this month).

**Comment by ararslan** [comment]
It's possible [for Windows](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187) and also [for Linux](https://discourse.julialang.org/t/32-bit-linux-julia-builds-are-now-available-on-travis-ci/27786) using `arch: x86`.
