### ISSUE TITLE
Allow returning DataFrame() or NamedTuple() in combine

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1981]
Re-posted from Slack.

> I have a function inside a `DataFrame` by that I want to have return rows only in some cases.  When it doesn't return rows I can't just return `nothing` or `DataFrame()` -- I have to explicitly construct a zero-row `DataFrame` with the same columns.  Is there any way to avoid this?

My opinion is that `nothing` is not a good option (it can be a valid value), but returning `DataFrame()` if other groups return `DataFrame`s or `NamedTuple()` if other groups return `NamedTuple`s should be allowed. Essentially `DataFrame()` should be treated as zero-row `DataFrame` with appropriate columns. The same for `NamedTuples`.

@nalimilan - probably you have most to say here. If we decide to do it it should be before 1.0 release I think.

**Comment by nalimilan** [comment]
Makes sense. It shouldn't be too hard, maybe all what's needed is return without doing anything instead of throwing an error when the result has no columns here:
https://github.com/JuliaData/DataFrames.jl/blob/57aec338a4f270c1fb95bdbd3f845b0031fb617b/src/groupeddataframe/grouping.jl#L891-L893
and here:
https://github.com/JuliaData/DataFrames.jl/blob/57aec338a4f270c1fb95bdbd3f845b0031fb617b/src/groupeddataframe/grouping.jl#L810-L812

**Comment by bkamins** [comment]
Thank you for the analysis. I think we can disallow `NamedTuple()` if this is problematic, but it seems it should not (of course this would have to be tested):
```
julia> NamedTuple() isa NamedTuple{<:Any, <:Tuple{Vararg{AbstractVector}}}
true
```

We could simply append nothing if we get an object with no columns.

The thing we would need to change is probably:
https://github.com/JuliaData/DataFrames.jl/blob/57aec338a4f270c1fb95bdbd3f845b0031fb617b/src/groupeddataframe/grouping.jl#L842
and
https://github.com/JuliaData/DataFrames.jl/blob/57aec338a4f270c1fb95bdbd3f845b0031fb617b/src/groupeddataframe/grouping.jl#L922
as it is possible that the first group might happen to be empty (we would have to have a special logic that waits till we hit a value with at least one column).

**Comment by nalimilan** [comment]
Ah, funny, so that should work. I suspect that if we just add a check in `append_rows!` to make it a no-op for empty tables, everything should be fine. Line 842 shouldn't be changed, as it only applies to the situation where a single row is returned (and in that case we rely on the assumption that there is one row per group).

**Comment by amellnik** [comment]
I can take a swing at this over the weekend if no one beats me to it.

**Comment by amellnik** [comment]
I didn't get very far, and won't have a chance to look at this again for a while -- sorry!  There's tests and a small part of the changes [here](https://github.com/amellnik/DataFrames.jl/tree/empty-by-groups) if it is useful to anyone.

**Comment by bkamins** [comment]
Thank you for working on this.

Usually I prefer @nalimilan to make changes in `groupby` related codes, as he has most experience in this area, and it is pretty tricky.

@nalimilan - would you have time to work on it (otherwise I can prepare a PR if you prefer).

**Comment by nalimilan** [comment]
Thanks @amellnik. Does that pass the tests though? It sounds too beautiful to be true. I would expect `append_rows!` to throw an error when it gets a non zero number of columns for the second group...

**Comment by amellnik** [comment]
It only passes tests for one of the four cases (appending an empty `DataFrame` after the first group).  I tried to modify `_combine_with_first!` to allow the initial groups to be empty, but didn't get very far.

**Comment by nalimilan** [comment]
Yeah, that will be a bit tricky to get right (I've highlighted a possible strategy above).

**Comment by bkamins** [comment]
@nalimilan - I think it would be good to have this for v0.20 release. If you do not have time to work on this issue then please let me know - then I can try to make a PR sometime around next weekend (I have not looked at the source code in detail so I am not sure yet how hard the fix would be).

**Comment by nalimilan** [comment]
I can't promise anything, so feel free to have a look.

**Comment by bkamins** [comment]
An additional decision to be made is if we allow returning `NamedTuple()` if all other `NamedTuples` return scalars (I think we should allow it, but current code assumes that if a `NamedTuple` with scalars is returned the produced `DataFrame` has number of rows known upfront).

**Comment by nalimilan** [comment]
> An additional decision to be made is if we allow returning `NamedTuple()` if all other `NamedTuples` return scalars (I think we should allow it, but current code assumes that if a `NamedTuple` with scalars is returned the produced `DataFrame` has number of rows known upfront).

Maybe we could shrink the output columns if we get an empty tuple, but I'm not sure how hard it will be to handle correctly.

**Comment by bkamins** [comment]
I have decided to disallow it for now as it would require to significantly rewrite a lot of code (the code assumes that the number of created rows is known upfront), and I think it is not really useful. We allow these empty containers only for vector-oriended `combine` in the PR.
