### ISSUE TITLE
Warning T is deprecated, use nonmissingtype instead

### ISSUE THREAD

**Issue by juliohm** [JuliaData/DataFrames.jl#1987]
Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = compacttype(::Type, ::Int64) at show.jl:39
└ @ DataFrames /Users/julio.hoffimann@gmail.com/.julia/packages/DataFrames/0Em9Q/src/abstractdataframe/show.jl:39

**Comment by bkamins** [comment]
Please update your DataFrames.jl version and the problem will be solved, see https://github.com/JuliaData/DataFrames.jl/releases/tag/v0.19.4.
