### ISSUE TITLE
master still on v0.19.3, though release branch already on v0.19.4

### ISSUE THREAD

**Issue by rapus95** [JuliaData/DataFrames.jl#1990]

**Comment by bkamins** [comment]
0.19.4 is on a bux-fix branch only. master contains all relevant commits (if it is not the case please reopen).

**Comment by nalimilan** [comment]
Bump.

**Comment by rapus95** [comment]
What I wanted to note was actually a more conceptual thing. I know that release branches diverge from master at every feature freeze, bugfix etc. But as far as I udnerstood that workflow, the versionnumber that is in the Project.toml should refer to the version that is developed in the branch. Thus, master should not be behind any released branch. Whether going ahead of any released branch depends upon whether you know whether it will be a patch or minor increase. But since the master holds changes that shouldn't go into patch releases, I guess, it is safe to assume that the next version that will diverge directly from master will be a minor increase.
Please consider this as a purely academical question about the workflow! (As I don't really have professional long term experience)

**Comment by bkamins** [comment]
> Thus, master should not be behind any released branch.

Probably this is right (essentially this means that the commit holding the version bump to 0.19.4 did not go into master).

Anyway - hopefully very soon master should have v0.20 released so all will be consistent.
