### ISSUE TITLE
Merge meanings of cols keyword arguments between push! and vcat

### ISSUE THREAD

**Issue by rapus95** [JuliaData/DataFrames.jl#1991]
:intersect does mean different things currently

**Comment by bkamins** [comment]
Agreed this should be fixed. What alternative name for what `:intersect` in `push!` does do you think is good. I think that in `vcat` it is an appropriate name. In `push!` we should not change the behavior, so we should change the name of this option.

Thank you!

**Comment by rapus95** [comment]
As :subset means that the new row at most needs to be a subset of columns. How about :superset?

**Comment by bkamins** [comment]
Yes - `:superset` is a good name for this!

**Comment by bkamins** [comment]
Given #1958 is merged is this still on 1.0 roadmap (I think not so I have removed the tag). The additional functionalities discussed here are non-breaking.

**Comment by rapus95** [comment]
I'll add it in the oberhaul I wanted to make. As #1958 is now merged, I guess I can start working on it, can't I?

**Comment by bkamins** [comment]
Yes, but I removed 1.0 milestone, as I understand your changes will be non-breaking (they will only clean up internal code or add functionality) - right?

**Comment by rapus95** [comment]
> Yes, but I removed 1.0 milestone, as I understand your changes will be non-breaking (they will only clean up internal code or add functionality) - right?

Indeed, if every keyword meaning is cleaned up and consistent now and we have enough test coverage that pass, then my change will not introduce any changes to the API besides adding some new keywords. If we will add any new arguments to an API function then we'll add it by keywords, thus, that should be compatible aswell, I guess.

**Comment by bkamins** [comment]
Closed in favor of #2032
