### ISSUE TITLE
using DataFrames in Jupiter lab and notebook hangs... 

### ISSUE THREAD

**Issue by pstaabp** [JuliaData/DataFrames.jl#1996]
I'm using Julia 1.3rc-4 and if I run in Jupiter lab or Jupiter notebook, entering the following
```
using DataFrames
```

this seems to load fine, then any other cell, like:
```
2+2
```

just hangs.  I'm running the latest Jupiter notebook (1.2.0) on MacOS (Mojave). 

 In a standard console, no problem.  I'm not even sure how to try to trouble shoot this.  There is no message in the terminal, where I start either the notebook or the Jupiter lab.

**Comment by nalimilan** [comment]
Can you file an issue against Jupyter? I have no idea what DataFrames may be doing that could trigger this problem...

**Comment by pstaabp** [comment]
The latest release candidate (1.3.0rc5) of Julia seems to have fixed this.
