### ISSUE TITLE
Documenting the difference betwen df[!, :col] and df[:, :col]

### ISSUE THREAD

**Issue by aminya** [JuliaData/DataFrames.jl#1999]
In the documentation, I see `!` sign being used which is acting similar to `:`, but it isn't documented anywhere what are the differences.
https://github.com/JuliaData/DataFrames.jl/blob/master/docs/src/man/getting_started.md

**Comment by nilshg** [comment]
Have you looked at https://juliadata.github.io/DataFrames.jl/stable/lib/indexing/ which described all types of indexing strategies in great detail?

**Comment by bkamins** [comment]
Ideally I would like also to have a decision on https://github.com/JuliaData/DataFrames.jl/pull/1961 to make the target API of `:` vs `!` final (please comment in that PR if you have an opinion on this - as the decision is pending as @nalimilan and I want to collect more feedback where it should go). Thank you!

**Comment by aminya** [comment]
> 
> 
> Have you looked at https://juliadata.github.io/DataFrames.jl/stable/lib/indexing/ which described all types of indexing strategies in great detail?

I think it should be also described brefiely in Getting started. I didn't find this page until you sent it.
