### ISSUE TITLE
describe should also apply to Vector

### ISSUE THREAD

**Issue by scls19fr** [JuliaData/DataFrames.jl#2010]
Hello,

`describe` function is very convenient to have a quick look at dataframe value.
But it will be great if it could apply to Vector also

I was expecting to be able to do:

    describe(df[!, :column])

Kind regards

**Comment by bkamins** [comment]
Use `describe(select(df, :column))`.

`describe` for an `AbstractVector` is defined in StatsBase.jl:

```
julia> using StatsBase

julia> describe([1,2,3,4])
Summary Stats:
Length:         4
Missing Count:  0
Mean:           2.500000
Minimum:        1.000000
1st Quartile:   1.750000
Median:         2.500000
3rd Quartile:   3.250000
Maximum:        4.000000
Type:           Int64
```

**Comment by scls19fr** [comment]
Thanks @bkamins maybe [doc](http://juliadata.github.io/DataFrames.jl/stable/lib/functions/#DataAPI.describe) should be improved to show such a usage (`describe(select(df, :column))`)

**Comment by bkamins** [comment]
OK - I will update the docs anyway today so I can add it.

**Comment by bkamins** [comment]
See https://github.com/JuliaData/DataFrames.jl/pull/2011 (please leave a comment if something is not clear)

**Comment by scls19fr** [comment]
Thanks @bkamins
