### ISSUE TITLE
Add `flatten` function

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2012]
[This post](https://discourse.julialang.org/t/juliadb-flatten-equivalent-in-dataframes/31048/2) on Discourse requested a `flatten` function. 

I wrote what I think is a pretty efficient implementation of a `flatten` function while answering the question. It could probably be added to DataFrames.

Or even better, it could be added to `TablesApi` with a few tweaks.

**Comment by bkamins** [comment]
I think it is OK to add it to DataFrames.jl. Would you care to make a PR?

A small note though. The implementation should not use indexing into data frames in the triple nested loop (it will be a performance killer); either a barier function or delayed data frame creation (both discussed in https://github.com/bkamins/Julia-DataFrames-Tutorial/blob/master/11_performance.ipynb) should be used here for performance.

**Comment by nalimilan** [comment]
FWIW JuliaDB already has that function: https://juliacomputing.github.io/JuliaDB.jl/latest/api/#IndexedTables.flatten
It would make sense to add it to DataAPI.

**Comment by bkamins** [comment]
closing ad #2013 added the functionality
