### ISSUE TITLE
Add an argument allowing to select columns to calculate statistics on for describe

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2014]
See https://github.com/JuliaData/DataFrames.jl/pull/2011#discussion_r345219099

**Comment by bkamins** [comment]
@nalimilan - this would have to be a keyword argument, as currently we use positional arguments to indicate which statistics should be calculated.

Do you think adding this kwarg is worth it?

**Comment by nalimilan** [comment]
Ah yes that's annoying. Probably not worth it then given that `describe(select(df, cols))` is relatively short. We could also switch all other functions to keyword arguments, but...

**Comment by nalimilan** [comment]
I realize I've kind of disproved my point, as `describe(select(df, cols))` makes an unnecessary copy, which probably indicates that most people will fall into that trap. Ah, well...

**Comment by bkamins** [comment]
Ah - my bad. We do not use kwargs. I will make a PR adding this functionality.
