### ISSUE TITLE
Switch cols to kwarg from positional args

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2023]
Following the comment by @nalimilan in https://github.com/JuliaData/DataFrames.jl/pull/2020 after seeing what changes I make in https://github.com/JuliaData/DataFrames.jl/pull/1958 currently I came to the conclusion that we should cleanup `cols` to be a keyword argument everywhere.

This should be changed prior to 1.0 release, but is non-blocking for 0.20 I think. I will make a PR for this.

**Comment by bkamins** [comment]
@nalimilan Here is the result of `cols` usage review.

`cols` is a positional argument in:
* `sort` and `issorted` (actually we have a reverse deprecation to what we discuss in these cases)
* `allowmissing`
* `disallowmissing`
* `categorical`
* `completecases`
* `dropmissing`
* `nonunique`
* `unique`
* `disallowmissing`
* `grouping`
* `getindex`
* `view`
* `DataFrameRow` and `SubDataFrame` constructors

`cols` is a kwarg in:
* `describe` is kwarg
* `vcat` is kwarg but has a broader meaning
* `push!` and `append!` has a different meaning

Given this I recommend to leave things "as is", as we would change a bunch of stuff to make a rarely used functionality consistent.
Only `describe` is really conflicting with what we do currently (`cols` as positional arg).
In `describe it is natural to have `cols` as kwarg as there is no other option, so there should be no confusion.
`vcat`, `push!` and `append!` are different anyway and also I think there should be no confusion.

What is your opinion? I would just close this issue.

**Comment by nalimilan** [comment]
OK, thanks for checking. Let's leave this as-is then.
