### ISSUE TITLE
Add an easy way to get a number of rows in by

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2035]
The kind of question "how to get a number of rows in `by`" is one of the most common ones.

Currently we have a pattern `newname = :oldname => function` (also `:oldname` can be several names). We consider adding a pattern `:oldname => function => :newname`, which is not-conflicting.

Now what we could consider is allowing:
* `newname = function`, in which case `function` would get a `SubDataFrame` and it would be expected that it returns a scalar or a vector; as a complement `function => :newname` could be added with the same effect
* I would then deprecate the "dangling" function form in case a scalar of vector is returned (which in that case automatically generates column names `:x1`, `:x2` etc.) as it is not useful in practice); the form should be retained for the case when the function returns e.g. a `DataFrame`

If we went for this the original problem would be solved by e.g. something like:
```
by(df, :x1, nrow => :n)
```
or
```
by(df, :x1, n = nrow)
```
(currently the code like `by(df, :x1, nrow)` fails but code `by(df, :x2, nrow)` works, because `:x1` is an autogenerated column name - and this is exactly the thing that I do not like in the current design)

I know it will be slower than `by(df, :x1, n = :x1 => length)`, but I think that for such a common operation we can allow it. We even could intercept `nrow` in `by(df, :x1, n = nrow)` and have a special fast path for it.

@nalimilan - what do you think? (I am dropping this in as a breaking decision for 1.0). We could make it non-breaking if we decided to retain "dangling" function form that automatically generates column name.

**Comment by nalimilan** [comment]
Makes sense. I think we should definitely have a fast path for `nrow` though, otherwise that would be a performance trap.

A more explicit alternative would be to require `: => function => :newname`. That could reduce possible confusion between `:oldcol => function` and `function => :newname`.

Not sure about deprecating the form which generates names. It doesn't sound too bad to keep it.

**Comment by bkamins** [comment]
Agreed. I think having a fast path for `nrow` is needed no matter what we do with other.

`: => function => :newname` should be added anyway, so it is a matter if we want to allow `function => :newname` as a shorthand. I think it is OK, but it can always can be added later.

So, just to sum up we have four things in split-apply-combine that I think we should have for 1.0 release (but I would say after 0.20 release):
* `:oldcol => function => :newcol` syntax
* allow returning `DataFrame()` or `NamedTuple()` to drop a group in combine
* allow to opt-out from adding grouping columns in combine
* fast patch for `nrow`

I did not touch any of these things as you know this part of the code base better and it is better to have these things synchronized as the PRs changing them would likely to be conflicting. So the question to you is do you feel you would have time to cover these changes (or some of them) some time after 0.20 release? Thank you!

**Comment by bkamins** [comment]
ah - plus 5th thing: allowing broadcasting in `combine` when specifying transformations (this can be also useful for `select`/`select!` later in #1975)

**Comment by nalimilan** [comment]
Sounds like a good plan. Maybe let's leave `function => :newname` out for now as it's just a small convenience improvement. I wouldn't mind some help, though. :-)

**Comment by bkamins** [comment]
> Maybe let's leave `function => :newname` out for now as it's just a small convenience improvement.

Sure.

> I wouldn't mind some help, though. :-)

Sure again. As you probably noticed I started learning this part of code to be able to contribute. Let us finish #2047 first and then make a quick PR changing the default of `sort`; it should be relatively easy (most work will be in fixing tests) - I can make it after #2047 is merged to avoid merge conflicts. Once we are stabilized with these we can add new functionalities.

**Comment by bkamins** [comment]
Given the plan in #2156 this will become obsolete (one will have write `:somecol => length => :lengthcolname` as currently is required)

**Comment by bkamins** [comment]
> So, just to sum up we have four things in split-apply-combine that I think we should have for 1.0 release (but I would say after 0.20 release):
> *    :oldcol => function => :newcol syntax
> *    allow returning DataFrame() or NamedTuple() to drop a group in combine
> *    allow to opt-out from adding grouping columns in combine
> *    fast patch for nrow

All done on master, so closing.
