### ISSUE TITLE
SQL Interface

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#206]
We should grab ideas from this codebase:

https://github.com/yhat/pandasql

It seems to have a BSD-like license and can provide more direct inspiration for an SQL interface than the comparable R package.

**Comment by nalimilan** [comment]
This kind of DSL won't live in the DataFrames package.

**Comment by essenciary** [comment]
I know that ORMs are usually either loved or hated -- honestly, for web development in an MVC framework, I would not want to work without one. 

Hence, it's one of the first things I built. I'm quite happy with the result so far but I'd appreciate a helping hand if you're interested in an ORM. 

I don't entirely agree that ORMs are inherently slow -- in my experience with web programming, many more times the connection and the database itself are slower than the server-side code. 

Here is a notebook I prepared for JuliaCon this year: 
https://github.com/essenciary/SearchLight_JuliaCon18/blob/master/SearchLight%20--%20Tame%20Your%20Databases.ipynb

And here is the repo: 
https://github.com/essenciary/SearchLight.jl

It supports MySQL, Postgres and SQLite. 

I wouldn't see it integrated with `DataFrames`, but it does know how to do things like, which I find useful: 
```julia 
df = SearchLight.DataFrame(Todo, 
                        where("completed = ?", false) + 
                        where("due_at < ?", Dates.today()) + 
                        order(:due_at) + 
                        limit(10) + 
                        offset(2))
```

**Comment by javadba** [comment]
Does your DSL allow just straight sql?  I just want to drop a sql statement in and go - a la sqldf or pandasql.

**Comment by essenciary** [comment]
Yes, there's a lower level API which allows that. 
Ex: `SearchLight.query(sql)` which returns a `DataFrame`

**Comment by javadba** [comment]
Danke schoen.  I already evangelized julia to my network yesterday.  Main apparent drawback is simply _adoption_  .  I will use it for my own work as the data science/ML/stats complement to scala (for multithreaded/jvm and spark work).
