### ISSUE TITLE
Error in `by` when composing with `skipmissing`

### ISSUE THREAD

**Issue by nilshg** [JuliaData/DataFrames.jl#2061]
On 0.20 I observe the following:

```
julia> using DataFrames, Dates

julia> df = DataFrame(id = [1,1,2,2], date = [Date(2010, 10, 10), missing, missing, missing]);

julia> grouped = by(df, :id, :date => maximum ∘ skipmissing)
2×2 DataFrame
│ Row │ id    │ date_function          │
│     │ Int64 │ Date                   │
├─────┼───────┼────────────────────────┤
│ 1   │ 1     │ 2010-10-10             │
│ 2   │ 2     │ -252522163911150-01-01 │
```

This seems like a bug - as @bkamins pointed out on Slack
```
julia> grouped = by(df, :id, :date => x -> (maximum ∘ skipmissing)(x))
ERROR: ArgumentError: reducing over an empty collection is not allowed
```
gives the expected error with `missing`-only groups

**Comment by bkamins** [comment]
This is a bug as the line:
https://github.com/JuliaData/DataFrames.jl/blob/master/src/groupeddataframe/grouping.jl#L999
never gets executed in your case.

We will need to keep a sentinel that the operation was executed at least once, but @nalimilan knows this part of code best, so I would wait for him to comment.

**Comment by nalimilan** [comment]
Good catch. That's a corner case that wasn't covered correctly by tests. See https://github.com/JuliaData/DataFrames.jl/pull/2063.
