### ISSUE TITLE
Implicit broadcasting in DataFrame constructor

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2082]
Currently `DataFrame` constructor is the only place where we allow for an implicit broadcasting, like:
```
DataFrame(a=1, b=[1,2,3])
```
or
```
DataFrame(:a=>1, :b=>[1,2,3])
```

The question is do we want to keep allowing this. Pros are that this is convenient. The con is that this is the only place where we support it. My intuition is that it is not a feature that is used very often, but I might be wrong. I would welcome comments. This change would be breaking so I would prefer to have a decision on it before 1.0 release. Thank you.

CC @nalimilan, @quinnj, @piever, @pdeffebach, @oxinabox.

**Comment by nalimilan** [comment]
I guess one argument in favor of keeping it is that there's no short replacement syntax, contrary to `.=` vs. `=`. Writing `fill(1, n)` isn't a big deal, but it requires repeating `n`, which might be something a bit long like `length(col2)`.

But certainly removing that wouldn't be the end of the world.

**Comment by pdeffebach** [comment]
I agge with Milan. we would just be getting people to write `fill` a lot which would be a pain.

**Comment by bkamins** [comment]
OK - so it is a decision then. We leave it.
