### ISSUE TITLE
Add rectangularize, rectangularize! functions

### ISSUE THREAD

**Issue by jmboehm** [JuliaData/DataFrames.jl#2085]
It would be great to add functions that "rectangularize" a DataFrame, i.e. produce a new (or update) DataFrame that contains all possible combinations of values from a set of categorical variables in the DataFrame. The other variables take the existing values for the existing combinations of the categorical variable, and `missing` for the non-existing ones. Essentially what [fillin](https://www.stata.com/manuals13/dfillin.pdf) does in Stata.

The obvious application is panel data.

**Comment by bkamins** [comment]
If what you propose is https://github.com/JuliaData/DataFrames.jl/pull/1864 then I recommend to close this issue and keep the discussion in the PR.

**Comment by jmboehm** [comment]
It is indeed, thank you.
