### ISSUE TITLE
Implicit broadcasting rules

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2086]
Following https://github.com/JuliaData/DataFrames.jl/issues/1727#issuecomment-576043702 I realized we have two special cases for implicit broadcasting for which we might consider changing our behavior:
* `Ref`: now we simply reuse it => my proposal would be to unwrap it and broadcast the contents (this would serve the same purpose as it serves in normal broadcasting)
* `Array{T,0}`: now we error when they are passed => my proposal is similar to `Ref` we should unwrap the value stored and broadcast it

This would apply to `DataFrame` constructor, `insertcols!` and possibly `select`/`combine`/`transform` in the future.

**Comment by nalimilan** [comment]
That would be more consistent with `Array` broadcasting, right? If so, then that's a good idea.

**Comment by nalimilan** [comment]
That would be more consistent with `Array` broadcasting, right? If so, then that's a good idea.

**Comment by bkamins** [comment]
It would. The difference from array broadcasting I think we should keep is that we should not expand 1-element vectors into n-element vectors (I only propose to promote 0-dimensional arrays to vectors and expand them accordingly), so passing something like `DataFrame(a=[1], b=[1,2,3])` should be an error.
