### ISSUE TITLE
redesign of eachcol

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2090]
Following the discussion on Slack we can consider to redesign `eachcol` in the following way:
* deprecate two argument form, allow only `eachcol(df)` that would be equivalent to `eachcol(df, false)`
* define `getindex(::DataFrameColumns, ::Symbol)`
* define `keys(::DataFrameColumns)` to produce symbols (this is breaking)
* define `pairs(::DataFrameColumns)` to produce symbol=>value pairs (this is breaking)
* after the deprecation period drop the second parameter in type definition of `DataFrameColumns`

Overall this change would simplify the design. We would have to make sure though that such changes do not break some API assumptions that are made for arrays (it seems not, but this might be delicate). Other packages, like AxisArrays.jl do not override default `keys` and `pairs` definitions.

**Comment by bkamins** [comment]
I have checked and `keys` seems be safe to override. So do we go for this change? I can implement it.

**Comment by nalimilan** [comment]
Sounds good. I guess the main drawback is that `getindex` would be slower with symbols, but people should use `eachindex` for maximum performance (as for arrays), and that shouldn't be a bottleneck anyway.

**Comment by bkamins** [comment]
we will still allow `getindex` with integers - this will be just an additional method.
