### ISSUE TITLE
Using the public API should be safe

### ISSUE THREAD

**Issue by PhilipLoewen** [JuliaData/DataFrames.jl#2094]
Here's a copy-paste from the intro page. Do you really mean this?

>  it is not safe to directly access fields of types that are a part of public API

I expect a public API to expose things that ARE safe to access. Perhaps there is a missing word "not" in this phrase.

This text appears in the third paragraph under API on this page: [http://juliadata.github.io/DataFrames.jl/stable/](http://juliadata.github.io/DataFrames.jl/stable/).

Thank you.

**Comment by bkamins** [comment]
I have not written this sentence but it states is what typically is recommended, i.e.:
* we do not guarantee that internal design of the types will not change so you should not rely on it; if something is meant to be available to the user it will be provided by exported
* directly changing an internal structure of the object might invalidate it, so it should be avoided (so it is best not to access them directly, getter/setter functions should be used instead)

Still some types need to be exported as they provide their constructors. So for sure `DataFrame` should be exported.

However, `DataFrameRow`, `GroupedDataFrame` and `SubDataFrame` should not be constructed manually by the user so maybe we should not export them. @nalimilan - what do you think (I think we should not export them)

**Comment by PhilipLoewen** [comment]
Thanks for this clarification. I did not properly understand the paragraph in which the quoted phrase appears, and now I think I do. Please do not extrapolate from my ignorance to a redesign request! Minor rewording of the paragraph in question would have made it easier for me to absorb, and that may be enough. Here's how I understand the situation now. Is this accurate?

_Please be warned that while Julia makes it possible to access internal functions or types of DataFrames.jl, these may change without warning between versions of DataFrames.jl. So an appropriate exported function should be used whenever some operation on fields of defined types is being considered. In particular it is not safe to directly access the fields of types that are a part of the public API of the DataFrames.jl package (by using, e.g., the getfield function)._

**Comment by bkamins** [comment]
Yes - your understanding is correct 😄.

However, it prompted me to reconsider exporting the types I have listed.
For example we do not export `Index` type because the user should not use it directly.

So the pros and cons of exporting `GroupedDataFrame`, `SubDataFrame`, and `DataFrameRow` are the following:
* pros: user can define user's own functions with type asserts (essentially: we guarantee that the names of the types will not change and that the types themselves will exist)
* cons: it is not really advisable to construct these types manually

**Comment by PhilipLoewen** [comment]
Thanks again for recalibrating me ... and, of course, for your work on this important package!

**Comment by nalimilan** [comment]
> However, `DataFrameRow`, `GroupedDataFrame` and `SubDataFrame` should not be constructed manually by the user so maybe we should not export them. @nalimilan - what do you think (I think we should not export them)

Yeah that's a difficult issue. At least for `DataFrameRow` and `SubDataFrame`, it could make sense for the user to build them directly by passing row indices. For `GroupedDataFrame` it's much less likely. But wouldn't it be weird to print `DataFrames.GroupedDataFrame`?

**Comment by bkamins** [comment]
OK - I think then we can close this. Any objections?

**Comment by bkamins** [comment]
Closing. If someone feels it should be reopened please comment and do so.
