### ISSUE TITLE
DataFrame from array of tuples to specify header/column name

### ISSUE THREAD

**Issue by darrencl** [JuliaData/DataFrames.jl#2096]
Hi, 

I would like to have a functionality when I supply an array of tuples in the `DataFrame` constructor to specify column names.

```
julia> tup = [(10,20,30), (4,5,6)]
2-element Array{Tuple{Int64,Int64,Int64},1}:
 (10, 20, 30)
 (4, 5, 6)   

julia> DataFrame(tup)
2×3 DataFrame
│ Row │ 1     │ 2     │ 3     │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 10    │ 20    │ 30    │
│ 2   │ 4     │ 5     │ 6     │
```
Saw there's this `cnames`, but then I couldn't use this for some reason. If there's something wrong in a way I put this, please let me know cause I couldn't find this usage in the doc.

```
julia> DataFrame(tup, 
DataFrame(columns::AbstractArray{T,1} where T, cnames::AbstractArray{Symbol,1}; makeunique, copycols) in DataFrames at /home/darren/.julia/packages/DataFrames/yH0f6/src/dataframe/dataframe.jl:183

julia> DataFrame(tup, [:val1, :val2, :val3])
ERROR: ArgumentError: columns argument must be a vector of AbstractVector objects
Stacktrace:
 [1] #DataFrame#103(::Bool, ::Bool, ::Type, ::Array{Tuple{Int64,Int64,Int64},1}, ::Array{Symbol,1}) at /home/darren/.julia/packages/DataFrames/yH0f6/src/dataframe/dataframe.jl:184
 [2] DataFrame(::Array{Tuple{Int64,Int64,Int64},1}, ::Array{Symbol,1}) at /home/darren/.julia/packages/DataFrames/yH0f6/src/dataframe/dataframe.jl:183
 [3] top-level scope at none:0
```

Thanks!

**Comment by bkamins** [comment]
This behavior is not from DataFrames.jl, but from Tables.jl, where `Tables.columns(tup)` does not accept argument to pass column names. I do not think that Tables.jl will change this behavior (but maybe @quinnj will comment).

So for the time being I just recommend you to call `names!(df, vector_of_column_names)` after creating the data fame using the method you have described above.

**Comment by bkamins** [comment]
@quinnj - given Tables.jl 1.0 is released I understand this can be closed and what I wrote should be used. If not - please comment. If I understand it correctly can you please close this issue?
