### ISSUE TITLE
rand(::GroupedDataFrame) sampler?

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#2097]
Hello,
I was wondering if there is a reason that a Sampler for the `rand` function is not practical for the `GroupedDataFrame` type.
It seems like a relatively easy and useful feature.
Thanks

**Comment by bkamins** [comment]
`GroupedDataFrame` does not allow duplicates and `rand` does return them in general if passed a dimension. Also it is easy enough to write `gdf[rand(1:lengh(gdf))]` if you want to pick a single group at random or `[gdf[rand(1:lengh(gdf))] for _ in 1:how_many]` if you want many of them.

**Comment by anandijain** [comment]
definitely, hear you on `gdf[rand(1:lengh(gdf))]`
I still don't fully understand why `rand(gdf)` shouldn't work though.

**Comment by bkamins** [comment]
`rand(gdf)` could work, but then we would not be able to support the whole `rand` API, which is defined as:

> Pick a random element or array of random elements from the set of values specified by `S`

However it would be possible to support `rand(gdf)` and that is why I have not closed this issue to let people comment (this is a similar decision to: https://github.com/JuliaData/DataFrames.jl/issues/2048, it is easy to add it, but it is also easy to have the functionality without adding it).

**Comment by bkamins** [comment]
After the discussion in #3437 I am closing this issue.
