### ISSUE TITLE
Add Tables.namedtupleiterator implementation

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2100]
Following https://github.com/JuliaData/Tables.jl/pull/131#issuecomment-582652739 we should add:
```
Tables.namedtupleiterator(df::AbstractDataFrame) = Tables.namedtupleiterator(Tables.columntable(df))
```
after that PR is closed and new version of Tables.jl tagged.

**Comment by bkamins** [comment]
@quinnj - having https://github.com/JuliaData/Tables.jl/pull/131 merged should we additionally change anything in DataFrames.jl apart from the change I describe here (which is only performance related)?

**Comment by quinnj** [comment]
Yes, I have the changes in a local branch; let me see if I can push them here
