### ISSUE TITLE
quick replace values in entire dataframe?

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#2105]
~ apologies for the issue spam ~

I am looking for the simplest way to replace values in a dataframe.

For example, I have a CSV, with "None" values, that I need to replace with missing or something else:

```julia
df .== "None"  # returns boolean df

replace!(df, "None"=>missing)  # error

DataFrame(replace.(eachcol(df), "None"=>missing))  # loses column names, more confusing imo
```
I don't know the quickest way to do this without iterating over columns.
I think it would be useful to have a memorable, easy one-liner to do this.

Thanks!

**Comment by bkamins** [comment]
A nice question. We support broadcasting in DataFrames.jl so if you want to do it in-place your columns must allow `missing` values:
```
julia> df = allowmissing!(DataFrame(a = ["a", "None", "b", "None"], b = [1,2,3,4], c = ["None", "x", "y", "z"]))
4×3 DataFrame
│ Row │ a       │ b      │ c       │
│     │ String⍰ │ Int64⍰ │ String⍰ │
├─────┼─────────┼────────┼─────────┤
│ 1   │ a       │ 1      │ None    │
│ 2   │ None    │ 2      │ x       │
│ 3   │ b       │ 3      │ y       │
│ 4   │ None    │ 4      │ z       │

julia> @. df = ifelse(df == "None", missing, df)
4×3 DataFrame
│ Row │ a       │ b      │ c       │
│     │ String⍰ │ Int64⍰ │ String⍰ │
├─────┼─────────┼────────┼─────────┤
│ 1   │ a       │ 1      │ missing │
│ 2   │ missing │ 2      │ x       │
│ 3   │ b       │ 3      │ y       │
│ 4   │ missing │ 4      │ z       │
```
if you want  a new data frame then just write:
```
julia> df = DataFrame(a = ["a", "None", "b", "None"], b = [1,2,3,4], c = ["None", "x", "y", "z"])
4×3 DataFrame
│ Row │ a      │ b     │ c      │
│     │ String │ Int64 │ String │
├─────┼────────┼───────┼────────┤
│ 1   │ a      │ 1     │ None   │
│ 2   │ None   │ 2     │ x      │
│ 3   │ b      │ 3     │ y      │
│ 4   │ None   │ 4     │ z      │

julia> @. ifelse(df == "None", missing, df)
4×3 DataFrame
│ Row │ a       │ b     │ c       │
│     │ String⍰ │ Int64 │ String⍰ │
├─────┼─────────┼───────┼─────────┤
│ 1   │ a       │ 1     │ missing │
│ 2   │ missing │ 2     │ x       │
│ 3   │ b       │ 3     │ y       │
│ 4   │ missing │ 4     │ z       │
```

**Comment by anandijain** [comment]
Thanks for this! Makes total sense.

I think it would be nice to have a small section of examples (like this one) in the `Getting Started` part of the docs on the most common broadcasting operations, most likely taken from the indexing page.

Replacing values is so common, that it might be nice to add at the bottom of the `Working with DataFrames` section below `Column-Wise Operations`.

**Comment by bkamins** [comment]
Sure - can you please propose what you think would be nice to add as a PR or here as a copy paste of dump of an example session and then I can make a PR out of it?
