### ISSUE TITLE
Sync with Tables.jl 1.0 release

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2109]
1. Update dependencies in Project.toml
2. make sure we are a proper source for Tables.jl operations
3. make sure we properly handle a table from Tables.jl as a source to create a `DataFrame`

@quinnj - I assigned it to you as I understand from what you have written you already have an initial implementation of this - right?

**Comment by bkamins** [comment]
I also marked it "breaking", but maybe it will not be breaking (not sure, so I leave the label for now to be on a safe side).

**Comment by quinnj** [comment]
Fixed via #2111
