### ISSUE TITLE
`pkg> add DataFrames Tables` installs DataFrames v0.19.4 and Tables v1.0.0

### ISSUE THREAD

**Issue by tkf** [JuliaData/DataFrames.jl#2112]
Maybe it's better to add bound to DataFrames < v0.20 in the registry?

(I know how to workaround this personally. I just thought it may be good to make this work out-of-the-box for other users.)

Example:

```julia
julia> Pkg.activate(mktempdir())
Activating new environment at `/tmp/jl_OZLTBk/Project.toml`

(jl_OZLTBk) pkg> add DataFrames Tables
 Resolving package versions...
  Updating `/tmp/jl_OZLTBk/Project.toml`
  [a93c6f00] + DataFrames v0.19.4
  [bd369af6] + Tables v1.0.0
```

Another way to get a strange behavior is:

```julia
julia> Pkg.activate(mktempdir())
Activating new environment at `/tmp/jl_hL3Nqk/Project.toml`

(jl_hL3Nqk) pkg> add DataFrames
...

(jl_hL3Nqk) pkg> add Tables
...

(jl_hL3Nqk) pkg> st
    Status `/tmp/jl_hL3Nqk/Project.toml`
  [a93c6f00] DataFrames v0.20.0
  [bd369af6] Tables v0.2.11

(jl_hL3Nqk) pkg> up
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `/tmp/jl_hL3Nqk/Project.toml`
  [a93c6f00] ↓ DataFrames v0.20.0 ⇒ v0.19.4
  [bd369af6] ↑ Tables v0.2.11 ⇒ v1.0.0
  Updating `/tmp/jl_hL3Nqk/Manifest.toml`
  [34da2185] ↓ Compat v3.5.0 ⇒ v2.2.0
  [a93c6f00] ↓ DataFrames v0.20.0 ⇒ v0.19.4
  [bd369af6] ↑ Tables v0.2.11 ⇒ v1.0.0
```

Note that `Tables` is upgraded to 1.0 and `DataFrames` is downgraded to 0.19.4.

**Comment by quinnj** [comment]
Yeah, this isn't great. In 0.19.4, we had `Tables = ">= 0.2.3"` for the compat

**Comment by bkamins** [comment]
The only solution I see is to tag a 0.20.1 release. See https://github.com/JuliaRegistries/General/pull/9401, so I am closing this issue

**Comment by bkamins** [comment]
As a temporary solution install #master branch of DataFrames.jl before adding Tables.jl.

**Comment by bkamins** [comment]
Well - it does not work unfortunately if you also have CSV.jl installed as it also upper-bounds Tables.jl. What I have written works if you remove CSV.jl.

**Comment by tkf** [comment]
FYI, you can also manually edit `D/DataFrames/Compat.toml` retroactively in the General registry.  See e.g., https://github.com/JuliaRegistries/General/pull/5098

I've never used but https://github.com/bcbi/RetroCap.jl seems to help this.

**Comment by tkf** [comment]
Nevertheless, thanks a lot for quickly implementing a solution!

**Comment by bkamins** [comment]
OK - 0.20.1 is out. Now other packages (chiefly CSV.jl) need to be updated.

**Comment by quinnj** [comment]
I think we should change the Compat.toml in General as @tkf suggested.
