### ISSUE TITLE
Should we export Tables

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2114]
I was thinking if we want to export `Tables` name from `DataFrames`.
What we would get is that I constantly type `using DataFrames, Tables` and the change would simply allow to write `using DataFrames` and get access to `Tables`.

This is just a loose thought. We do not have to do this. Does anyone have some opinion on this?

**Comment by quinnj** [comment]
I think it makes sense.

**Comment by nalimilan** [comment]
Yeah, why not.

**Comment by bkamins** [comment]
So do we do:
```
export Tables
```
or
```
@reexport using Tables
```
The difference is re-exporting of `rowtable` and `columntalbe`.

**Comment by quinnj** [comment]
Either way; I'd lean towards reexport.

**Comment by nalimilan** [comment]
Not sure, but not reexporting is always safer.
