### ISSUE TITLE
Disallow passing zero columns to aggregate functions in combine/by

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2118]
Currently wa allow:

```
julia> df = DataFrame(rand(3,4))
3×4 DataFrame
│ Row │ x1       │ x2       │ x3       │ x4       │
│     │ Float64  │ Float64  │ Float64  │ Float64  │
├─────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ 0.894754 │ 0.686974 │ 0.537174 │ 0.702784 │
│ 2   │ 0.666891 │ 0.60511  │ 0.52412  │ 0.118299 │
│ 3   │ 0.53011  │ 0.765504 │ 0.778253 │ 0.591448 │

julia> by(df, :x1, z = [] => x -> [x])
3×2 DataFrame
│ Row │ x1       │ z            │
│     │ Float64  │ NamedTup…    │
├─────┼──────────┼──────────────┤
│ 1   │ 0.894754 │ NamedTuple() │
│ 2   │ 0.666891 │ NamedTuple() │
│ 3   │ 0.53011  │ NamedTuple() │
```

I think it is not useful to allow this. I do not see in what cases it would be useful. On the other hand passing 0-columns is qualitatively different than passing at least one column. The difference is that the function knows number of rows contained in a group (in the case of no columns passed you have no way to learn it).

**Comment by nalimilan** [comment]
As I noted at https://github.com/JuliaData/DataFrames.jl/pull/2117#discussion_r379849062, I'm not sure it's a problem. And for `by`/`combine`, contrary to `select`, I don't think it makes a difference in terms of implementation, since we know how many rows the group contains even if no columns are passed, right?

**Comment by bkamins** [comment]
> I don't think it makes a difference in terms of implementation, since we know how many rows the group contains even if no columns are passed, right?

It will make a difference exactly in the situation we are discussing in `select`. I.e. when we allow `ByRow` in `combine` (which I guess we will add at some point). I will leave the issue open till we finalize the `select` design.

**Comment by bkamins** [comment]
OK - closing this. We leave `combine` as-is. When we add `ByRow` to combine we will reconsider this special case.
