### ISSUE TITLE
Unexpected `BoundsError` message

### ISSUE THREAD

**Issue by heliosdrm** [JuliaData/DataFrames.jl#2125]
```julia
df = DataFrame(words=["one","two"], numbers=[1,2])
df[1,3]
```

```
ERROR: BoundsError: attempt to access String
Stacktrace:
 [1] getindex(::DataFrames.DataFrame, ::Int64, ::Int64) at D:\.julia\packages\DataFrames\S3ZFo\src\dataframe\dataframe.jl:310
 [2] top-level scope at none:0
```

Julia version 1.3.1 and DataFrames 0.20.2

The offending line is:

```julia
throw(BoundsError("attempt to access a data frame with $(ncol(df)) " *
                  "columns at index $row_ind"))
```

Seems that the problem is calling `BoundsError(::String)`, whereas according to the docs, the interface of `BoundsError` is:

```markdown
`BoundsError([a],[i])`

An indexing operation into an array, `a`, tried to access an out-of-bounds element at index `i`.
```

(By the way, the interpolated value for that particular error should be `$col_ind`, right?)

**Comment by bkamins** [comment]
Thank you for reporting this. Fortunately it is fixed on master, see: https://github.com/JuliaData/DataFrames.jl/blob/master/src/dataframe/dataframe.jl#L317.
