### ISSUE TITLE
ERROR: BoundsError: attempt to access String

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2134]
Came across a weird error in DataFrames:

```
julia> df = DataFrame(rand(4,4))
julia> df[0, :x1]
ERROR: BoundsError: attempt to access String
Stacktrace:
 [1] getindex(::DataFrame, ::Int64, ::Symbol) at /home/peterwd/.julia/packages/DataFrames/uPgZV/src/dataframe/dataframe.jl:325
 [2] top-level scope at REPL[32]:1
```

I'll see if I can explore the stacktrace more in depth later to get a solution. But it is a weird error.

**Comment by bkamins** [comment]
This should be fixed on master. If not, please reopen.
Thank you for reporting this.

**Comment by pdeffebach** [comment]
yes this is fixed in master. Thanks.
