### ISSUE TITLE
⍰ character in header output

### ISSUE THREAD

**Issue by cormullion** [JuliaData/DataFrames.jl#2139]
I was wondering what the odd little character in the header output was:

<img width="399" alt="Screenshot 2020-03-04 at 11 31 40" src="https://user-images.githubusercontent.com/52289/75875494-ba366680-5e0b-11ea-9a1e-dfdb60ab7afe.png">

I thought at first there was an error with the font - since it's more or less the same as the `.notdef` character which is displayed when a font can't display a suitable glyph. (See [here](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph) for more info.)

I found out that it's an APL SYMBOL QUAD QUESTION, '⍰': Unicode U+2370 (category So: Symbol, other). 

So given that it's not entirely clear whether there's a "problem" with the dataframe or the font (and assuming I'm not the only person daft enough to wonder), is this the wrong choice of character and would some other symbol be more suitable?

An obvious suggestion is an ordinary question mark or exclamation mark. Unicode gives many  possibilities - ⁈ (2048), ⁉︎ (2049). Or even the interrobang ‽ (203D). (A mixture of "where? and watch out!). 

```
5×3 DataFrame
│ Row │ i     │ x       │ y       │
│     │ Int64 │ Int64⁈  │ String⁈ │
├─────┼───────┼─────────┼─────────┤
│ 1   │ 1     │ missing │ missing │
│ 2   │ 2     │ 4       │ missing │
│ 3   │ 3     │ missing │ c       │
│ 4   │ 4     │ 2       │ d       │
│ 5   │ 5     │ 1       │ e       │
```

These would presumably fall back to `?` anyway... Just don't use emojis..🤣

**Comment by pdeffebach** [comment]
It's not a problem, we use `⍰` to signify missingness. But I agree that it can confuse users who think there is a problem with their font, particularly in Windows where the terminal font isn't that great.

I don't like the idea of a `!` because missingness shouldn't be considered a problem. But I agree we can consider another symbol. This is a non-breaking change so it can be considered after 1.0.

**Comment by bkamins** [comment]
I would prefer to use `?`. The major benefit is that some variable width fonts display `⍰` as a bit too wide.

The only reason why we did not go for it is that it was considered to use `?` in a type signature in Base to signify an `Union` with `Nothing`.

However, if we consider this change as non-breaking 😄 (it seems the topic what is breaking recently became hot), then I would opt to switch to `?` and just switch to something else if Base starts using `?` for `Union` (looking at the PRs to Base it does not seem likely it will happen soon).

@nalimilan - any opinion on this?

**Comment by nalimilan** [comment]
I guess we could use `?`. In the worst case it will eventually be used for `Union{T, Nothing}` and we'll have to change it. In the best case it will be used for `Union{T, Missing}` and everything will be fine.

**Comment by bkamins** [comment]
OK. I will make a PR as it should be an easy fix :).

**Comment by quinnj** [comment]
I’ve also been confused by this and think using a plain quotation mark would be better

**Comment by nalimilan** [comment]
I guess that could be part of a strategy to claim `T? = Union{T, Missing}`. :smiling_imp:
