### ISSUE TITLE
Redesign of combine

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2156]
In this issue I write down how I think `combine` should be redesigned for 1.0 release (with consequence on `by` and `map`).

`combine(fun::Function, gdf)`:
a function `fun` will be passed `SubDataFrames`, and may return:
- A single value.
- A named tuple of single values or a `DataFrameRow`.
- A vector.
- A data frame, a named tuple of vectors or a matrix (in case of matrix return value we will keep current naming convention with `x1`, ...).

(other forms for `fun` - `Tuple` and `NamedTuple` in particularwill be disallowed)

`combine(gd::GroupedDataFrame; (colname = cols => f)...)` will be allowed but will be deprecated to free up kwargs for other purposes in the future (but if `cols` is a multiple selector then auto-splatting will be used).

`combine(gd::GroupedDataFrame, f)` will be disallowed without deprecation.

`combine(gd::GroupedDataFrame, cols => f...)` will be extended to fully and strictly follow `select` API. In particular:
* `ByRow` will be allowed,
* `(:a, :b) => fun` will be disallowed, as only `[:a, :b] => fun` is a valid indexing rule, as a benefit things like `r"^A" => fun` and similar will be allowed;
* automatic column naming will follow the convention of `select`

It seems that all this is doabe:
* without changing of the internal API of `_combine` except for switching to auto-splatting form passing a `NamedTuple` if multiple columns selector is used;
* with low (no?) risk of backward errors (i.e. all breaking changes will error and not silently produce a wrong result)

**Comment by bkamins** [comment]
And a usual request to @pdeffebach and @oxinabox to comment on it if you have time to take a look at the proposed changes.

**Comment by nalimilan** [comment]
Sounds good. A few comments:

> `combine(gd::GroupedDataFrame, f)` will be disallowed without deprecation.

Why not keep a deprecation for at least one cycle?

> `ByRow` will be allowed,

I'm not sure it can be useful since it's equivalent to calling `select` on the ungrouped data frame, so probably not urgent.

>     * `(:a, :b) => fun` will be disallowed, as only `[:a, :b] => fun` is a valid indexing rule, as a benefit things like `r"^A" => fun` and similar will be allowed;

AFAICT we don't need to disallow tuples to allow regexes. Is there are particular reason not to support them, except simplification? I'm afraid this will be annoying for users, without a very clear gain.

**Comment by bkamins** [comment]
> Why not keep a deprecation for at least one cycle?

we can try to keep it (I will see how much problems in dispatch it would cause)

> `ByRow`

this would be "out-of-the-box" as `ByRow` is a functor

> AFAICT we don't need to disallow tuples to allow regexes

That is why I have raised it. We can allow tuples as a special case (i.e. I cannot just delegate it to `AbstractIndex`). However, then the question then is - maybe we should allow tuples in `AbstractIndex` and consequently everywhere? I just wanted to avoid inconsistency that we allow them in `combine` but disallow e.g. in `select`.

**Comment by bkamins** [comment]
Regarding tuples as a selector - as discussed on Slack - we will deprecate them and see the feedback (if people really like tuples over vectors we can start allowing `df[:, (:col1, :col2)]`, but as for now we only allow `df[:, [:col1, :col2]]`).

**Comment by pdeffebach** [comment]
I'm split on this. I agree that it's unintuitive because Tuples are the default way that arguments are passed to functions. i.e. `(x, y) -> foo(x, y)` for anonymous functions.   

But it's there is so much more consistency to just allowing vectors. And it's so much simpler to programatically construct your arguments when using vectors.

**Comment by bkamins** [comment]
That is why I would disallow tuples in the long run. In general the survey during last months has shown that actually not many people currently use `combine` with multiple columns so it is a rare use case (at least now), so this should not be a huge problem I think.

**Comment by bkamins** [comment]
@nalimilan - I vaguely remember that there was some request to add an option to drop grouping columns in `combine`. I could not find it in issues. Maybe you remember where it was raised (and in general if this would be something we want to support as it would be easy to add in the PR for `combine` redesign I am preparing now)

**Comment by nalimilan** [comment]
Yes that's https://github.com/JuliaData/DataFrames.jl/pull/1555.

**Comment by bkamins** [comment]
Ah - it was a PR. I will implement it then here.
