### ISSUE TITLE
[BREAKING] Making combine more flexible

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2166]
I am splitting a discussion of additional functionalities of combine to a separate issue (to keep size of changes manageable). The two related things that should be added are:
* allow column selection and renaming in combine (just like in `select`)
* allow pseudo-broadcasting of scalars if they are mixed with vectors (just like in `select` very soon)

This is non breaking, so can go for 1.x release (but probably we will have it before this but this is not blocking 0.21 release)

**Comment by pdeffebach** [comment]
Added to this is a possible `combine(gd, :, cols => fun)` so a user can transform a column by group and keep all the others, returning a data frame. We can do the same with `by`.

**Comment by bkamins** [comment]
Agreed (if I understand your point correctly this is a special case of "allow column selection and renaming in `combine` - just writing it to make sure we have the same understanding what I meant above).

**Comment by bkamins** [comment]
(first note - column renaming is already here - we got it for free)
 
@nalimilan - we will have to work on this issue for 1.0. The reason is that we currently have a very significant bug in `_combine` (I am showing results from 0.20.2, the same is on master).

When solving it I can try implement implicit broadcasting as a side effect I think (I will have to double check to make sure):

```
julia> df = DataFrame(g=[1,2]);

julia> f1(i) = i[1] == 1 ? ["a", "b"] : ["c"];

julia> f2(i) = i[1] == 1 ? ["d"] : ["e", "f"];

julia> by(df, :g, :g => f1, :g => f2)
res = [([1, 1, 2], ["a", "b", "c"]), ([1, 2, 2], ["d", "e", "f"])]
3×3 DataFrame
│ Row │ g     │ g_f1   │ g_f2   │
│     │ Int64 │ String │ String │
├─────┼───────┼────────┼────────┤
│ 1   │ 1     │ a      │ d      │
│ 2   │ 1     │ b      │ e      │
│ 3   │ 2     │ c      │ f      │
```

**Comment by bkamins** [comment]
Also, for a reference, we kind of already allow mixing single values and vectors in special cases (which is also a bug):
```
julia> f1(i) = i[1] == 1 ? ["a"] : ["c"];

julia> f2(i) = i[1] == 1 ? "d" : "e";

julia> df = DataFrame(g=[1,2]);

julia> by(df, :g, :g => f1, :g => f2)
2×3 DataFrame
│ Row │ g     │ g_f1   │ g_f2   │
│     │ Int64 │ String │ String │
├─────┼───────┼────────┼────────┤
│ 1   │ 1     │ a      │ d      │
│ 2   │ 2     │ c      │ e      │
```
and
```
julia> f1(i) = i[1] == 1 ? ["a","c"] : [];

julia> f2(i) = i[1] == 1 ? "d" : "e";

julia> by(df, :g, :g => f1, :g => f2)
2×3 DataFrame
│ Row │ g     │ g_f1 │ g_f2   │
│     │ Int64 │ Any  │ String │
├─────┼───────┼──────┼────────┤
│ 1   │ 1     │ a    │ d      │
│ 2   │ 1     │ c    │ e      │
```

**Comment by bkamins** [comment]
#2170 implements all I mention here
