### ISSUE TITLE
Add a method to insert a column to last index

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2175]
I've been experimenting with piping via Lazy's `@>` macro. And the new funcitonality. 

It all works super well! However one feature that would be nice is an `insertcols!` method that doesn't take an index for position. The current syntax to insert a column with a particular name at the end of the dataframe -- with a function call where `df` is the first argument -- is 

```
y = rand(nrow(df))
transform(df, 1 => (x -> y) => :y)
```

Which is kind of a pain.

**Comment by bkamins** [comment]
`insertcols!(df, :y => y)` works on master.

**Comment by pdeffebach** [comment]
great! I thought I was on master but I guess not!

**Comment by bkamins** [comment]
OK - but please check (there is always a risk we have a bug)
