### ISSUE TITLE
sort and sort! API

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2178]
Currently `sort` and `sort!` in DataFrames.jl accepts a vector or a tuple as column selector.
It would be more consistent with the rest of the API to allow a list of positional parameters, so rather than writing:
```
sort(df, (:a, :b, :c))
```
to support:
```
sort(df, :a, :b, :c)
```
what do you think?

Fortunately the deprecation should be relatively easy. It would be great to have this decision before 1.0 release.

CC @nalimilan, @pdeffebach, @oxinabox

**Comment by nalimilan** [comment]
OK for deprecating passing a tuple, but I don't really see the need to support multiple arguments. Let's see whether somebody request it first.

Are there other places where tuples would have to be deprecated? Just to make sure it wouldn't be too disruptive to apply that rule everywhere.

**Comment by bkamins** [comment]
I think it is the only place left. Also note that this case is not the same as other cases as we have a differnt API here in general. E.g.:
```
sort(df, (:x, order(:y, rev=true)))
```
and
```
(:x, order(:y, rev=true))
```
is not a valid column selector anyway, so we can have a different rule here (and even allow tuples - as this is simply a different API).

I just thought it would be simplest to just allow:
```
sort(df, :x, order(:y, rev=true))
```
and the code to fix old code deprecation would just be `sort(df, some_old_selection_rule...)`.

In summary, we have three options:
1. leave things as is
2. deprecate tuple, but allow vector
3. switch to a list of positional arguments

Since anyway the API here is different than everywhere else (as we allow `order` to be passed) I think we are free to select what we want. I just want to make a conscious and explicit decision before we go for 1.0 release, when things will be frozen.

So given this perspective what would you recommend?

I thought of "switch to a list of positional arguments" option because it would be consistent with what we have in `select` now.

**Comment by oxinabox** [comment]
> OK for deprecating passing a tuple, but I don't really see the need to support multiple arguments. Let's see whether somebody request it first.

We should definately support sorting on multiple columns. Not supporting that would be very annoying.

I don't have perference for API

**Comment by bkamins** [comment]
OK, I will switch to supporting vectors only + `ColumnIndex` + `All` + `Not` + `Between` + regex + `:` (to be more consistent with the whole API). When this is done we will be able e.g. to simplify the API for deprecation of `aggregate`.

I will fix this deprecation here or in https://github.com/JuliaData/DataFrames.jl/pull/2174 depending what gets merged first (actually I opened this issue exactly because of the problem with deprecating `aggregate`).

**Comment by andreasnoack** [comment]
Just noticed this one when trying to upgrade to 0.21 so I'm too late to the game. However, I don't understand why you wouldn't prefer using tuples over vectors for this.

**Comment by bkamins** [comment]
`Tuple` is not a valid column selector in DataFrames.jl. We now consistently in every function allow only the same rules for passing column selectors (`sort` and `sort!` are the exception that we allow `order` but this is orthogonal).

Additionally there is only a minimal performance benefit of using `Tuple` over a vector (I do not think anyone would notice it), while it comes at a cost of compilation for each new signature (which is in practice more visible).

**Comment by andreasnoack** [comment]
> `Tuple` is not a valid column selector in DataFrames.jl.

My argument applies generally. Whenever you provide a list of column names, such as in `select`, I think a tuple would be the more natural thing to use. It's not really a matter of performance but more about style. Using a vector here reminds me of languages that I no longer use.

I guess the reason is slicing syntax where you normally slice with vectors. However, I don't think it's a good idea to use slicing syntax in non-getindex methods. I'm not a big fan of slicing syntax for dataframes generally but that is really a separate point.

I'm sorry for the negative comment. There a lot of good things to say about DataFrames but I was just a bit frustrated about this change.

**Comment by bkamins** [comment]
I understand your point.

Just to expand on it more to give a rationale:
1. first - again - using `Tuple` instead of vector leads to compilation each time a new signature is encountered, we do not want users to wait for compilation every time they change the selector
2. it is much easier to work with vectors when you dynamically construct the selector (you can do `push!`, `append!` etc.)
3. 90% of code in DataFrames.jl already allowed only vectors, so we had a choice:
    - allow vectors and sometimes also `Tuples`: it was my personal preference that I find it inconsistent
    - allow only vectors (this is what I ended up as a best trade-off)
    - allow only tuples (this would be clean, but it would be very breaking and would have the two problems I note above)

So I ended up deciding to allow only vectors in the future (currently wherever `Tuple` was accepted it is still accepted with deprecation - but I must admit that this is I think 3 methods only of tens of methods we provide).
