### ISSUE TITLE
It is not possible to see individual files in Coveralls

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2180]
As in the description. It says:
```
Source Not Available

The file "src\dataframerow\dataframerow.jl" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.
```

@nalimilan - I have checked and I do not see any bug in DataFrames.jl repo (probably there is some integration set up for this - on Coveralls but I do not seem to have access to it).

**Comment by nalimilan** [comment]
I've triggered a new sync with GitHub and it seems to work. Can you check?

I'm not sure why you don't have access to it. It's supposed to be connected with GitHub. Maybe the sync also fixed that?

**Comment by bkamins** [comment]
I took your PR from today: https://github.com/JuliaData/DataFrames.jl/pull/2202
and still there is a problem e.g. https://coveralls.io/builds/30251069/source?filename=src\DataFrames.jl

It looks like for some reason `/` gets replaced by `\` in the paths and this makes Coveralls fail when trying to display the file.

**Comment by nalimilan** [comment]
Too bad. Though it works for all tabs except "tree", right?

**Comment by bkamins** [comment]
Ah - right. So I think we can close it?
