### ISSUE TITLE
unrelated error message when trying to access 0 index 

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#2182]
I saw #2123 but this was for OffsetArray.jl.

If you have a DataFrame and try to access index zero (common coming from python), like so:
```
df = DataFrame(:A => 1:150)
df[0:50, :] 
```
It correctly gives bound error, but says `attempt to access String`. I was wondering what the logic behind this is.
When indexing zero-th element for normal array in julia, it returns `BoundsError: attempt to access 150-element UnitRange{Int64} at index [0]`.

Responding with the index [0] immediately reminds me of my mistake.

**Comment by bkamins** [comment]
This is fixed on master.
```
julia> df[0:50, :] 
ERROR: BoundsError: attempt to access 150×1 DataFrame
  at index [0:50, Colon()]
```
