### ISSUE TITLE
Base.depwarn stopped printing warnings on Julia 1.5

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2184]
Using `Base.depwarn` like we now do e.g.:
```
        Base.depwarn("In the future `push!` will not allow passing collections of type" *
                     " $(typeof(row)) to be pushed into a DataFrame. " *
                     "Only `Tuple`, `AbstractArray`, `AbstractDict`, `DataFrameRow` and " *
                     "`NamedTuple` will be allowed.", :push!)
```
does not print a warning even in CI tests on Julia 1.5 (I know about https://github.com/JuliaLang/julia/pull/35362, but I thought it should not affect CI).

@oxinabox - is this intentional, or we have something incorrectly configured in DataFrames.jl.

CC @KristofferC

**Comment by KristofferC** [comment]
We need to update Pkg on master for this to show up.

**Comment by bkamins** [comment]
Thank you.

So I am closing this and waiting for an update.
