### ISSUE TITLE
New name for `names` and `rename!`

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2185]
One of the last but major decisions.

Do we want to keep `names` and `rename!` functions

or

they should be renamed to

`colnames` and `renamecols!`?

Rationale - both seem OK. The minor issue with `names` is that it is defined in Base for something else, and in general `names` and `rename!` are common names. Still we could live with this (there should be no dispatch ambiguity risk).

It would be good to make this decision before 1.0 freeze. I do not say we have to change this, but the issue popped up several times so I prefer to ask before the release.

CC @oxinabox @pdeffebach @nalimilan @quinnj

**Comment by oxinabox** [comment]
I am inclined to leave it as it.
I don't see there is much gain from changing it.

We allso very rarely write `foocols` as a function name anymore so I am inclined to leave it as is.
Unless we plan to bring back `deletecols!`
Then `renamecols!` + `insertcols!` + `deletecols!` is kind of nice

**Comment by pdeffebach** [comment]
I think its pretty easy to get tripped up with something like 

```
names = [:x1, :x2]
for n in names(df)
    # stuff
end
```
This would throw an error, so there is a benefit of having a function name that isn't likely to be used as a variable name. 

I like `rename`, though. It fits with other verbs like `transform` and `select`. 

I wonder if the rule should really be to make sure functions have names that are verbs.

**Comment by nalimilan** [comment]
I think it will also depend on whether we deprecate `mapcols` (https://github.com/JuliaData/DataFrames.jl/issues/2186). If so, only `insertcols!` will remain with the "cols" suffix, meaning that wouldn't really be a convention anymore.

**Comment by bkamins** [comment]
As commented in #2186 I think `mapcols` will stay (that is why I have closed it and no one objected).

`insertcols!` should stay as is as we have to be explicit that we insert columns (as we work on rows by default).

So I guess `rename!` will stay as is given the discussion here.

I see the point of @pdeffebach though. I saw such a bug in user's code several times already, so maybe we should go for `colnames` in this case? (personally I have no problem to stay with `names`, but I see the benefits of `colnames` so I am not sure what is best here)

`deletecols!` is not needed as it is now `select!(df, Not(cols_to_delete))`.

Also note that we have `groupcols` and `valuecols` for `GroupDataFrame`, so `"cols"` is not going away anyway.

**Comment by CameronBieganek** [comment]
I come from R, so I'm used to `names`. However, R also has `colnames` and `rownames` which work for both matrices and data frames. So, I'd probably vote for `colnames` since it's more explicit.

**Comment by bkamins** [comment]
Any more thoughts on this? Given a mild preferences probably we will just close this and keep old naming to be less breaking.

**Comment by CameronBieganek** [comment]
I guess `names` is not too ambiguous, since data frames don't have row names. To paraphrase the misattributed Einstein quote:

> Function names should be as short as possible, but not shorter.

**Comment by bkamins** [comment]
OK - I am closing it. We will stay with what we have here. (All: please reopen/comment if you have a feeling we should discuss it more)
