### ISSUE TITLE
Performance comparison with SQL?

### ISSUE THREAD

**Issue by kavir1698** [JuliaData/DataFrames.jl#2193]
Is there any performance comparison of DataFrames.jl with an in-memory SQL database, say, SQLite.jl, for basic operations like select, add, remove, etc?

**Comment by bkamins** [comment]
You have some benchmarks here https://h2oai.github.io/db-benchmark/.

But if you feel it would be good to have a benchmark against eg. SQLite.jl then you are welcome to share back the results. Thank you!

**Comment by bkamins** [comment]
I am closing this because it will likely be hard to maintain properly. We have now added /benchmark/ tests to the repository.
