### ISSUE TITLE
Extend categoric values by category data

### ISSUE THREAD

**Issue by asprionj** [JuliaData/DataFrames.jl#2198]
I don't know whether the wording of the title makes any sense, I'm not into data analytics / data science at all. Here's a seemingly simple use case that I encountered today, probably there's already a solution of which I don't know.

I have some data, e.g.

```julia
data  = DataFrame(case=[2,1,1], val=rand(3))
```

```
3×2 DataFrame
│ Row │ case  │ val      │
│     │ Int64 │ Float64  │
├─────┼───────┼──────────┤
│ 1   │ 2     │ 0.104666 │
│ 2   │ 1     │ 0.026703 │
│ 3   │ 1     │ 0.547913 │
```

So there's some actual values, and one categorical column. Now in another dataset, I have the description of the cases, e.g.

```julia
cases = DataFrame(case=[1,2], val2=[10,20], val3=[11,22])
```

```
2×3 DataFrame
│ Row │ case  │ val2  │ val3  │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 1     │ 10    │ 11    │
│ 2   │ 2     │ 20    │ 22    │
```

Probably you already know what I want. I want to have `data` extended by two columns `val2` and `val3`, containing the values of those quantities corresponding to the respective case. To visualise it, the result should be:

```
3×4 DataFrame
│ Row │ case  │ val       │ val2  │ val3  │
│     │ Int64 │ Float64   │ Int64 │ Int64 │
├─────┼───────┼───────────┼───────┼───────┤
│ 1   │ 2     │ 0.104666  │ 20    │ 22    │
│ 2   │ 1     │ 0.026703  │ 10    │ 11    │
│ 3   │ 1     │ 0.547913  │ 10    │ 11    │
```

I did this manually for now, but shouldn't there be a simple way of doing this? It's similar to `recode`, but may add multiple columns, and the pairs are already in a `DataFrame`.

- Is there? (Possibly in some higher-level package such as Query.jl...)
- If not, any pointers on where to start to add such a functionality?

For large datasets, it would probably be even better to not actually copy the values into new columns but to somehow "link" the `cases` description into `data`, so that every time I want to get `val2` or `val3` from `data`, it is looked up on-the-fly...

- Is this already implemented, planned, or a reasonable idea at all?

**Comment by bkamins** [comment]
use the `join` function:
```
julia> join(data, cases, on = :case)
3×4 DataFrame
│ Row │ case  │ val       │ val2  │ val3  │
│     │ Int64 │ Float64   │ Int64 │ Int64 │
├─────┼───────┼───────────┼───────┼───────┤
│ 1   │ 2     │ 0.0773144 │ 20    │ 22    │
│ 2   │ 1     │ 0.440789  │ 10    │ 11    │
│ 3   │ 1     │ 0.812834  │ 10    │ 11    │
```
You specify which kind of join you want using `kind` keyword argument (see the docstring for details as the list is long).

Note that as of version 0.21 that should be released soon `join` will be deprecated and you should explicitly state which kind of join you want in function name (`innerjoin`, `outerjoin` etc.).
