### ISSUE TITLE
Decide if we want to rename All to Cols

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2203]
When https://github.com/JuliaData/DataAPI.jl/issues/16 is decided. But we should have this decision before 0.21 release as it is potentially breaking.

**Comment by bkamins** [comment]
Moving to 1.x, as `All` will stay anyway, and `Cols` can be added any time.

**Comment by CameronBieganek** [comment]
I vote for adding `Cols`.

Is there an argument for keeping both `All` and `Cols`, aside from being non-breaking? It seems like it would be a little confusing to have both if they do exactly the same thing.

**Comment by bkamins** [comment]
Well - they do not do exactly the same thing and that is the point I guess :).

`Cols` will be added. Probably we will keep support for `All` as it does not hurt, but just stop advertising it. As long as `DataAPI.jl` has `All` we will support it (as other packages might support it and if people write cross-Tables.jl code it should work).

**Comment by CameronBieganek** [comment]
Ohhhh, right. I had to look really closely at the docstrings to discern the difference:

**All:**

```julia
If `cols == ()`, select *all* columns.
```

**Cols:**

```julia
If `cols == ()`, select *no* columns.
```

(Emphasis mine.)

**Comment by bkamins** [comment]
Closing as the semantics is set. Only `All()` is allowed and it is the same as `:`. Otherwise use `Cols`.
