### ISSUE TITLE
Kwarg to choose missing values for unstack

### ISSUE THREAD

**Issue by kescobo** [JuliaData/DataFrames.jl#2205]
Current behavior:

```julia
julia> df = DataFrame(key=[:a,:a,:b,:b], variable=["x","y","x","z"], value=rand(4));

julia> wide = unstack(df, :variable, :key, :value)
3×3 DataFrame
│ Row │ variable │ a        │ b        │
│     │ String   │ Float64⍰ │ Float64⍰ │
├─────┼──────────┼──────────┼──────────┤
│ 1   │ x        │ 0.464025 │ 0.672549 │
│ 2   │ y        │ 0.570984 │ missing  │
│ 3   │ z        │ missing  │ 0.400742 │
```

What I'd like to get out instead:

```
julia> for col in names(wide)[Not(1)]
           wide[!,col] = disallowmissing(replace(wide[!,col], missing=>0.))
       end; wide
3×3 DataFrame
│ Row │ variable │ a        │ b        │
│     │ String   │ Float64  │ Float64  │
├─────┼──────────┼──────────┼──────────┤
│ 1   │ x        │ 0.464025 │ 0.672549 │
│ 2   │ y        │ 0.570984 │ 0.0      │
│ 3   │ z        │ 0.0      │ 0.400742 │
```

Keyword suggestions: `missing_values`, `fillmissing` (I don't love either of these, but thought it would be good to get the ball rolling)

**Comment by pdeffebach** [comment]
This is a good idea. I ran into an issue recently where `freqtables` was slow (I can't reproduce right now), but a workflow using `by` and `unstack` was fast. But then you had to fill in `0` for missing values.

**Comment by kescobo** [comment]
Consideration that came up on slack: `missing`s that were already in the data would be replaced with my version (and the more concise version from @alejandromerchan: `coalesce.(unstack(df, :variable, :key, :value), 0)`). If we only want to replace things that arise during the unstack, here's a different MWE to start:

``` 
julia> df = DataFrame(key=[:a,:a,:a,:b,:b], variable=["x","y","m","x","z"], value=[.1,.2,missing,.3,.4]);
```
And we'd want
```
julia> wide = unstack(df, :variable, :key, :value, missing_values=0.) # hypothetically
4×3 DataFrame
│ Row │ variable │ a        │ b        │
│     │ String   │ Float64⍰ │ Float64  │
├─────┼──────────┼──────────┼──────────┤
│ 1   │ m        │ missing  │ 0.0      │
│ 2   │ x        │ 0.1      │ 0.3      │
│ 3   │ y        │ 0.2      │ 0.0      │
│ 4   │ z        │ 0.       │ 0.4      │
```

Though actually, I'm not sure what we'd want at `wide[1, :b]` in this case...

**Comment by bkamins** [comment]
The same pattern was already discussed in https://github.com/JuliaData/DataFrames.jl/pull/1864, so we would be consistent between the functions (that PR is currently extremely hard to look at but I hope you will see the idea).

**Comment by kescobo** [comment]
Oh, awesome - if the pattern has been considered and consensus reached, as long as it's consistent I think that's great. I don't have a strong intuition about it.

**Comment by metanoid** [comment]
I'd prefer something like `filldefault` or `default` instead of `fillmissing` because I think that makes it clearer that we're only inserting the default value where the row was omitted from the source `df`, not overwriting existing `missing`s in the source df.

**Comment by bkamins** [comment]
This is now supported with `fill` kwarg
