### ISSUE TITLE
possible test failure in upcoming Julia version 1.5 

### ISSUE THREAD

**Issue by rfourquet** [JuliaData/DataFrames.jl#2221]
A PkgEval run for a Julia [pull request](https://github.com/JuliaLang/julia/pull/29240) which changes the generated numbers for `rand(a:b)` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master branch).

Also, you might be interested in using the new [StableRNGs.jl](https://github.com/rfourquet/StableRNGs.jl) registered package, which provides guaranteed stable streams of random numbers across Julia releases.

Apologies if this is a false positive. Cf. https://github.com/JuliaCI/NanosoldierReports/blob/ab6676206b210325500b4f4619fa711f2d7429d2/pkgeval/by_hash/52c2272_vs_47c55db/logs/DataFrames/1.5.0-DEV-87d2a04de3.log

**Comment by bkamins** [comment]
@rfourquet - thank you for caring so much to inform the package maintainers about the change!

**Comment by bkamins** [comment]
@nalimilan - I will make this update after https://github.com/JuliaData/DataFrames.jl/pull/2214 is merged. It affects only tests so it can be done after 0.21 release

**Comment by bkamins** [comment]
In #2223 I have made the tests independent of PRNG used (which should have been done from the start).
