### ISSUE TITLE
In docs, note subsets are copies (unless of columns)?

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#2224]
Loving updated docs, and the (clear!) discussion up front about views v. copies (my greatest pet peeve about pandas). 

Are people open to noting in [Indexing](http://juliadata.github.io/DataFrames.jl/dev/man/getting_started/#Indexing-syntax-1) that subsets of columns with `!` are non-copies, while subsets of rows always generate copies (I assume?). Can PR if supported.

**Comment by bkamins** [comment]
Sure - go ahead with a PR please. And yes - `getindex` always creates a copy if row index is anything except `!` or a single row selected using an integer (in which case it is either a single value if a single column is selected or a `DataFrameRow` if multiple rows are selected - in the last case note that `DataFrameRow` is a `view`). Feel free how much of this complexity should go to "getting started" and what can be left as "advanced stuff" :smile:.

**Comment by nickeubank** [comment]
Thanks @bkamins! I definitely don't want to over complicate -- for me though, knowing when you have a view and when you have a copy has profound implications for that most critical of things -- data integrity -- so I think it's worth pushing up front.

**Comment by nickeubank** [comment]
But `df[!, [firstcolumn, secondcolumn]]` isn't a view, right? That's a copy?

```
julia> df = DataFrame("a" => [42, 47], "b" => ["y", "z"])
2×2 DataFrame
│ Row │ a     │ b      │
│     │ Int64 │ String │
├─────┼───────┼────────┤
│ 1   │ 42    │ y      │
│ 2   │ 47    │ z      │


julia> df[!,["a", "b"]] === df
false
```

**Comment by bkamins** [comment]
`df[!, [firstcolumn, secondcolumn]]` is a copy of a wrapper but not a copy of the contents.

As 1 data frame is a container we have THREE types of selection:
* `df[:, [:a, :b]]` - copy of columns in a freshly allocated `DataFrame`
* `df[!, [:a, :b]]` - alias (no copy, no view) of columns in a freshly allocated `DataFrame (old and new data frames share columns `:a` and `:b` and the columns pass `===` test if compared)
* `df2 = @view df[:, [:a, :b]]` or `df2 = @view df[!, [:a, :b]]` are the same and create a `SubDataFrame` (containing all rows and two columns of `df`), you have that for columns `:a` and `:b` that `parent(df2.a) === df.a`.

The details are described [here](https://juliadata.github.io/DataFrames.jl/stable/lib/indexing/#getindex-and-view-1). In general we have indexing and broadcasting design that is fully compatible with Base (+ an extension of `!`) while at the same time it allows you to have the ability to express any kind of indexing behaviour that can be needed (copy - safe, alias - fast and unsafe, view - fast and explicit that it is unsafe).

**Comment by nickeubank** [comment]
@bkamins PR with a "Note" on this topic. Thoughts?

**Comment by nickeubank** [comment]
Thanks. Tweaked a few places you are definitely right, left language ambiguities for others to review.

**Comment by matthieugomez** [comment]
Do we really need “!” in the end? It sounds like the behavior can be obtained either by df.”$x” or select (to get dataframes).

**Comment by bkamins** [comment]
we need it for `setindex!` and broadcasting.
