### ISSUE TITLE
no method matching InvertedIndex(::String, ::String)

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2227]
```
Not("var_1", "var_2")
```

fails. I think that we want it to work, right?

**Comment by bkamins** [comment]
This API is not supported by InvertedIndices.jl, so it is up to us to decide if we want to support it or not (it will be a small type piracy). The current API is `Not(All("var_1", "var_2"))`.

**Comment by bkamins** [comment]
or `Not(["var_1", "var_2"])`.

**Comment by pdeffebach** [comment]
Can we ask InvertedIndices to add this?

**Comment by bkamins** [comment]
Sure we can ask - if you open an issue there can you CC me please?

**Comment by pdeffebach** [comment]
We might have to resort to type piracy since if we wanted more consistency we would want 

```
Not(:a, [:b, :c]) == Not(:a, :b, :c)
```

Which would probably cause problems in a lot of other applications of InvertedIndices. But we will see.

**Comment by bkamins** [comment]
Yes, and I think it will not be that problematic. I guess you want the following invariant:
```
Not(args...) == Not(Cols(args...))
```
right?

**Comment by bkamins** [comment]
ah - probably not - as in the other PR you want to allow non-existent columns in `Not`. So this is more complex then.

**Comment by pdeffebach** [comment]
I can still move that PR forward and we will cross that bridge when we come to it.

**Comment by bkamins** [comment]
This works:
```
julia> df = DataFrame(a=1,b=2,c=3)
1×3 DataFrame
 Row │ a      b      c
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      2      3

julia> df[:, Not([:a, :b])]
1×1 DataFrame
 Row │ c
     │ Int64
─────┼───────
   1 │     3
```
and I think it is sufficient. Allowing multiple arguments to `Not` could be confusing.

If you feel otherwise please reopen.
