### ISSUE TITLE
first/last/etc. documentation problem

### ISSUE THREAD

**Issue by Byrth** [JuliaData/DataFrames.jl#2232]
http://juliadata.github.io/DataFrames.jl/stable/lib/types/

Below the "Common methods" header, some of the links are broken.
* first
* last
* unique
perhaps more.

**Comment by bkamins** [comment]
Thank you for reporting this

**Comment by bkamins** [comment]
@mortenpi - do you have a quick tip how to make documentation point to a function we extend from Base and we have a docstring specific for the extension, e.g. now we write `[`first`](@ref)` should it be `[`first`](@ref DataFrames.first)` to work correctly? Thank you!

**Comment by mortenpi** [comment]
I think the issue is that you just haven't included those docstrings in the manual. There are quite a few issues in the documentation build: https://travis-ci.org/github/JuliaData/DataFrames.jl/jobs/684387165#L256-L358

**Comment by bkamins** [comment]
OK - thank you - I will have a look and try to fix them.
