### ISSUE TITLE
Make DataFrame's BoundsError message more informative and similar to that of Base.Matrix

### ISSUE THREAD

**Issue by AzamatB** [JuliaData/DataFrames.jl#2234]
Consider two error messages:
```Julia
julia> df[6,4]
ERROR: BoundsError: attempt to access DataFrame
  at index [6, 4]

julia> a[6,4]
ERROR: BoundsError: attempt to access 3×4 Array{Float64,2} at index [6, 4]
```
It would be nice if the error message generated for `DataFrame` would print its dimensions and without inserting line break before `at index` similar to how `Base.Matrix` does this.

**Comment by bkamins** [comment]
Please update the DataFrames.jl to the latest release to see:
```
julia> df = DataFrame(a=1)
1×1 DataFrame
│ Row │ a     │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │

julia> df[6,4]
ERROR: BoundsError: attempt to access 1×1 DataFrame
  at index [6, 4]
```
it is impossible to remove the newline though as this is the way Julia Base prints errors for non-matrices.

**Comment by AzamatB** [comment]
Turns out it was a [bug](https://github.com/JunoLab/Juno.jl/issues/578) with Juno.jl.

**Comment by bkamins** [comment]
Thank you for reporting
