### ISSUE TITLE
Audio issues in DataFrames youtube tutorials?

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/DataFrames.jl#2235]
Hey @bkamins -- saw JuliaLang just posted a [new video tutorial](https://www.youtube.com/watch?v=eLVPC08NAJc) you put together, and I know you're doing a Q&A later today. I just wanted to note that there are some big audio issues in that video (as there was in your 2018 tutorial on youtube).

I'm not sure of the exact nature of the issue -- looks like you bought a nice mic in the new video -- but you put a lot of work into these and I want to make sure they're as usable as possible, so I wanted to flag this for troubleshooting!

**Comment by nickeubank** [comment]
Also the video resolution is too low for reading code... 

![image](https://user-images.githubusercontent.com/9683693/81407996-6a756380-910a-11ea-8e8a-1811b59644c3.png)

**Comment by bkamins** [comment]
Sure - thank you for reporting.

Regarding the video quality - you should change the quality to 1080p instead of the default and it should be OK (@logankilpatrick - is it possible to make the 1080p resolution the default).

Regarding the audio issues - can you comment in more detail what is their nature (so that we can determine if they can be fixed - I am not an audio expert unfortunately).

**Comment by nickeubank** [comment]
Oh! NVM re: video quality. When I first opened I couldn't get more than 360p, but that must have just have been because I found the video before Youtube had posted all the versions. Oops!

Re: audio: In the first [video](https://www.youtube.com/watch?v=eLVPC08NAJc) there's a weird echo / reverb. Not sure if it's a compression artifact of some sort, or just a result of (a) the microphone being too far from your mouth and/or (b) not having enough sound insulation in your room (as a result of which the mic is picking up echos of your voice almost as strongly as the original sound). 

It does seem like audio is better in video 2/6 than 1/6. 

[But the strong echo is back in 4/6](https://www.youtube.com/watch?v=MfR2QUane_M)

**Comment by logankilpatrick** [comment]
Video quality should be all good, it takes YouTube a little time to process. I am not hearing any echo in the first 5 minutes of video 4.

**Comment by logankilpatrick** [comment]
There is some in the other video's but it is not too bad.

**Comment by nickeubank** [comment]
@logankilpatrick They're definitely usable, don't get me wrong, and a lot better than the 2018 tutorials (which I couldn't get through... :( ). But over ~4 hours of video, that type of audio issue can be really fatiguing. I think audio issues are the video-tutorial version of website loading lags -- even small issues end up having big effects on usage. I'd hate to have people deterred from using these great tools because of something like that. 

I'm not sure if there's anything to do about it once a video has been recorded (though if there are any audiophiles who know reverb-filters, maybe there is?), but want to be sure to flag it for future reference!

**Comment by bkamins** [comment]
@pszufe - maybe you know how to fix this echo?

**Comment by pszufe** [comment]
@bkamins  I know it can be done in several video editing software (echo removal feature) but I have never done it myself.

**Comment by bkamins** [comment]
I close it as I was unable to fix the problem. I will create new tutorials when the new release of DataFrames.jl is out and hopefully fix the audio issues.
