### ISSUE TITLE
Tables.columns should return a DataFrameColumns object

### ISSUE THREAD

**Issue by oschulz** [JuliaData/DataFrames.jl#2244]
Currently, we have

```julia
cols = Tables.columns(df::DataFrame) === df
```

Returning the `DataFrame` isself is not ideal, I think. A `DataFrame` is conceptually *not* really a collection of columns - for example, `length(cols)` is not defined, and you also can't `map(f, cols)` over the columns, nor can you iterate over the columns with `[... for col in cols]` or similar.

I think we should do

```julia
Tables.columns(df::DataFrame) = eachcol(df)
```

instead.

**Comment by quinnj** [comment]
The only things required of the return type of `Tables.columns` is that `Tables.columnnames` and `Tables.getcolumn` are defined, which `DataFrame` satisfies. I think what you're looking for is [`Tables.Columns(df)`](https://juliadata.github.io/Tables.jl/dev/#Tables.Columns), which provides the iteration/getindex/getproperty convenience methods you mentioned.

**Comment by bkamins** [comment]
Both `DataFrameColumns` and `DataFrame` support `Tables.columns` interface. Also if I understand things correctly `Tables.columns` does not promise an object that is "conceptually a collection of columns".

Can you please give more justification for the proposed change? The reason is that we would like to avoid being breaking till 1.0 release and what we have now conforms to the `Tables.columns` contract.

**Comment by oschulz** [comment]
I understand - no one likes breaking things that close to a v1.0. :-)

I was looking for a way to transform `DataFrame` columns in a generic way that would also work for `TypedTables.Table`, etc. For example, one may want to convert all columns to another format, or use `Adapt.adapt` to push them to a GPU, etc.

So thought combining `Tables.columns` and `Tables.materializer` would be the natural way - but maybe there's a better way that doesn't require breaking changes?

**Comment by oschulz** [comment]
Ah, should have read your comment on #2245 first. Indeed, one can simply use `Tables.columntable(df)`.
