### ISSUE TITLE
Rename nrow to nrows, ncol to ncols

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaData/DataFrames.jl#2247]
I would like to propose to pluralize the `nrow` and `ncol` functions.

I always stumble upon these functions having a singular name whereas many (most?) Julia functions that report the number of things (!) have a pluralized name, e.g.:

```
# Base/Core
ncodeunits
ndigits
ndims
nfields

# Distributed
nprocs
nworkers

# Threads
nthreads
```

Many variable usages in DataFrames.jl also use the plural `nrows` (assigning things like `nrows, ncols = size(...)` or `nrows = size(..., 1)` or `nrows = length(axes(...)[1])`), even the `DataFrame` constructor has keyword arguments `nrows` and `ncols`:

```
- `nrows`, `ncols` : number of rows and columns
```

I agree that it is a plus to have an interface that is very close to similar packages from other ecosystems like R. Though, in my opinion, Julia should strive for consistency within itself - not with other languages.

Another argument against making the change is that one can no longer use `nrows` and `ncols` as identifiers without masking the proposed functions. This might lead to #406, #1224 and similar, but that's a different discussion.

**Comment by jonas-schulze** [comment]
Nice alternative (verbose) variable names would be just `rows` and `cols` since their meaning would be clear by the assignment from `nrows(...)` and `ncols(...)` and their type. So that objection might not be that important.

**Comment by bkamins** [comment]
Thank you for submitting proposal.

I agree that it would be more consistent. However, I have the following comments:
1. We are currently in non-breaking mode in DataFrames.jl (unless there is a very good reason to be breaking); so most likely this proposal would stay open till 2.0 release of DataFrames.jl
2. We are aware of both pros and cons of what you have outlined above (i.e. it is not consistent with Julia style, at the benefit of (a) being more friendly for R users, and (b) as you note `nrows`/`ncols` is often used as a variable name - even internally in DataFrames.jl sourcode - so making this change would be more breaking than it seems; i.e. actually introducing a common exported name is as breaking as any other breaking change)
3. People who want to be conformant to Julia-style probably use `size` anyway (and this was the plan in the posts you reference), we kept `nrow` and `ncol` to be more user-friendly only

Still - I will keep this issue open, as other JuliaData membes might have some more to add here.

**Comment by bkamins** [comment]
It seems that people find this issue minor, so I am closing it, as introducing the change would be breaking, but if you strongly oppose please comment.
