### ISSUE TITLE
Implement `empty` / `empty!` as the truncate operation

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataFrames.jl#2251]
Proposal to have these definitions implemented and added to the API
```
empty(df::AbstractDataFrame) = similar(df, 0)
empty!(df::AbstractDataFrame) = filter!(row -> false, df)
```

**Comment by bkamins** [comment]
I think the deprecation on `empty!` was long enough there that it is OK to add it back.
`empty!` will be implemented as (note that it is not for `AbstractDataFrame` as it may not be mutable)
```
empty!(df::DataFrame) = foreach(empty!, eachcol(df))
```

**Comment by bkamins** [comment]
see https://github.com/JuliaData/DataFrames.jl/pull/2262
