### ISSUE TITLE
update docs at pkg.julialang.org

### ISSUE THREAD

**Issue by pfarndt** [JuliaData/DataFrames.jl#2255]
Please update docs at:

https://pkg.julialang.org/docs/

Right now only the"old" version is linked there:

https://pkg.julialang.org/docs/DataFrames/AR9oZ/0.20.2/

Quite confusing with all these recent changes. Thanks

**Comment by bkamins** [comment]
@StefanKarpinski or @logankilpatrick - I have never used https://pkg.julialang.org/docs/ (or even been aware of its existence). Do you happen to know who is supporting that website or how it is updated? Also DataFrames.jl has MIT License (the website says it is "OTHER").

**Comment by StefanKarpinski** [comment]
https://pkg.julialang.org/docs/ is old and fully replaced by https://juliahub.com; the only reason it's still up and running is that it's running on the same infrastructure as the pkg.julialang.org package server which we're not quite ready to switch over yet. How are you getting to that directly?

**Comment by bkamins** [comment]
OK - so this issue can be closed as juliahub gives a correct version. Thank you for clarifying.

**Comment by pfarndt** [comment]
oh - fancy site! - somehow this escaped my attention - Thanks
