### ISSUE TITLE
Rename `tail` to avoid clash with `Base.tail`

### ISSUE THREAD

**Issue by cossio** [JuliaData/DataFrames.jl#2261]
I typically import `Base: tail` into scope. If I then do `using DataFrames`, I get a warning

```
WARNING: using DataFrames.tail in module Main conflicts with an existing identifier.
```

Although `Base.tail` is not exported, it is documented (https://docs.julialang.org/en/v1/base/collections/#Base.tail) and I think many people use it regularly.

To avoid this clash, maybe `DataFrames` can use a different name for this function? Or it could just extend `Base.tail`.

**Comment by bkamins** [comment]
see https://github.com/JuliaData/DataFrames.jl/pull/2262

**Comment by cossio** [comment]
@bkamins Any estimate of when this change will be released? I keep getting annoying bugs / warnings because of this (end up calling the wrong `tail`).

**Comment by bkamins** [comment]
Well - we could make a release now as we have enough functionality to justify it, but users wanted to postpone the release to make sure we include all breaking things in 0.22 and there are several loose ends related to `select`/`transform`/`combine` that need working out and might lead to breakage.

CC @oxinabox @nalimilan

**Comment by oxinabox** [comment]
I would really like hold off on release until we are done.

**Comment by bkamins** [comment]
Just as a reference https://github.com/JuliaData/DataFrames.jl/issues/2410 and https://github.com/JuliaData/DataFrames.jl/issues/2314 (and related) are major pain points.
