### ISSUE TITLE
Index a grouped data frame by a vector of pairs

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2264]
With the new ability to index with symbols, it's hard to index a grouped data frame with a named tuple when you are working with column names as strings.

**Comment by bkamins** [comment]
That is why it is allowed to index them by `Tuple`s also. Is there something you could propose alternatively (also as I have commented on discourse - it is easy to create a `NamedTuple` from a `DataFrameRow` - as you know :smile:).

Still - do you have some proposal what we could change? Maybe we can additionally allow iterables of `key => value` paris?

**Comment by pdeffebach** [comment]
See #2265 for an implementation. I think it's readable and makes strings "first class" etc.

**Comment by bkamins** [comment]
done on master
