### ISSUE TITLE
ENV["COLUMNS"] not working as expected in Jupyter Lab

### ISSUE THREAD

**Issue by lungben** [JuliaData/DataFrames.jl#2266]
`ENV["COLUMNS"]` seems not to work correctly:

```
using DataFrames
df = DataFrame()
for i=1:100
    df[!, Symbol(i)] = 1:10
end
ENV["COLUMNS"]="20"
df
```
This shows only 3 columns (not 20) for me when executed in Jupyter Lab.
Setting COLUMNS to very high numbers shows all columns.

Environment:
Jupyter Datascience Notebook Docker container, Julia 1.4.1, DataFrames.jl version 0.21 and master.
I got the same issue for Jupyter Lab in a Windows Conda environment.

**Comment by lungben** [comment]
Sorry, I missed the corresponding description in the manual.
Thanks for nilshg for pointing it out in
https://discourse.julialang.org/t/problem-with-package-tableview-julia-usage/39369/8

**Comment by bkamins** [comment]
`"COLUMNS"` is number of "terminal columns" (so for most characters it is number of characters, but some characters do not have width 1)

**Comment by lungben** [comment]
Sorry, I somehow over-read this point in the documentation and implicitly assumed that it does the same as Pandas `pdf.options.display.max_columns`.
Thanks!
