### ISSUE TITLE
diag(::DataFrame)? 

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#2268]
The diag function from LinearAlgebra is pretty handy. It may just be extra clutter to have in DataFrames, but it isn't hard to write and I can think of a few cases where it'd be nice to have (heatmaps, etc).

I think that `diag(::DataFrame)` can be written st you can `@assert diag(df, n) == diag(Matrix(df), n)` so it wouldn't pollute the namespace as much as if it returned a different type. 

Thoughts?

**Comment by bkamins** [comment]
I am not sure it would be useful. `DataFrame` is not a matrix and I think it is easy enough to write e.g. what you have written in practice.

A different pattern would be `getindex.(Ref(df), axes(df)...)` which should be much more efficient for large data frames.

**Comment by anandijain** [comment]
`getindex.` and `axes` is a nice pattern, although it doesn't work on non-square dfs.

this is what i wrote to solve that
```julia
min_axes = minimum(axes(df))
getindex.(Ref(df), (min_axes, min_axes...)
```
also what would be the nice way to write `diag` using the shift argument:
```julia
  julia> A = [1 2 3; 4 5 6; 7 8 9]
  3×3 Array{Int64,2}:
   1  2  3
   4  5  6
   7  8  9

  julia> diag(A,1)
  2-element Array{Int64,1}:
   2
   6
```

Overall, I think I agree that a separate `diag()` doesn't need to be written, and was mainly looking for the efficient pattern.
