### ISSUE TITLE
describe on columns with e.g. Integers

### ISSUE THREAD

**Issue by KristofferC** [JuliaData/DataFrames.jl#2269]
Right now, `describe` is documented with:

> If a column's base type derives from Real, :nunique will return nothings.

The worry is that, in general. computing the number of distinct elements requires memory proportional to the length of the column.
There are perhaps a few ways we could tweak things:

- Compute the number of unique values below some threshold
- Above some threshold, use a technique like HyperLogLog to get an approximate number.

The drawbacks of thresholds are that it could perhaps be surprising to write code that works for a given dataframe size and have it suddenly stop working when you load a bigger dataframe. For techniques like approximate counting (HyperLogLog) the drawback is that user might  think that the count is always exact and allocate datastructures with a certain size based on it (which might then fail when one tries to put in all the distinct values)

Ref https://github.com/JuliaData/DataFrames.jl/pull/1435

**Comment by nalimilan** [comment]
Another advantage of not special-casing `Real` is that the high cardinality problem can also happen with other types (e.g. dates and times) so it would be more robust. I think we could start with the simple solution of stopping after some threshold, and later we could implement HyperLogLog (see the old [HyperLogLog.jl](https://github.com/johnmyleswhite/HyperLogLog.jl)).

**Comment by bkamins** [comment]
My recommendation would be:
* handle everything in the same way when computing `:nunique`; I do not think presenting an approximate count is a good idea - we should do an exact calculation;
* disable computing of `:median` and `:nunique` by default (leave them as opt-in)

This will dramatically improve usability of `describe`. Currently for non-toy data sets `describe` is in practice very slow because of computing `:median` and `:nunique`. If someone really wants to see these statistics they can be opt-in.

**Comment by piever** [comment]
Maybe relevant: HyperLogLog is implemented in OnlineStats [here](https://joshday.github.io/OnlineStats.jl/stable/api/#OnlineStats.HyperLogLog).
On the same vein, OnlineStats also has the [P square algorithm](https://joshday.github.io/OnlineStats.jl/stable/api/#OnlineStats.P2Quantile) for approximated quantiles.

**Comment by StefanKarpinski** [comment]
I have an implementation of HyperLogLog with the best new corrections to the estimator that I can contribute. I should probably put it up in a new package.

**Comment by bkamins** [comment]
My personal preference would be to leave that out of DataFrames.jl to keep the list of the dependencies low. `describe` allows to pass any function for aggregation, so in a sense "this is already available". The question is in my opinion only about what we will show by default (and as I have commented actually I would prefer to limit this to most basic statistics to make `describe` respond fast).

**Comment by nalimilan** [comment]
I'm fine with not reporting the number of uniques by default.

Though even if we do that it would still be nice to be able to use it 1) without it taking ages even if you have a numeric column with many unique values and 2) if you want to know the number of unique values of e.g. an integer column with few unique values. That said, I don't have a perfect solution to that.

**Comment by bkamins** [comment]
The solution I think is `describe(df, :nunique => fun, other statistics ...)` where `fun` is a function of your choice (exact count or approximate, from whatever package you like).

**Comment by pdeffebach** [comment]
Stata's [summarize](https://www.stata.com/manuals13/rsummarize.pdf), the inspiration for this command, doesn't include it. So I'm fine dropping it as we aren't losing feature parity. Plus i've found `describe` a bit too wide sometimes. This will help with that.

**Comment by pdeffebach** [comment]
I played around with this the other day and the best way to print summary statistics for a grouped data frame is 

Which is still not ideal. I don't have any better ideas for this, though. Perhaps when metadata is added we can have something that controls printing. 

```
julia> df = DataFrame(a = rand(1:5, 1000), b = rand(1000));

julia> combine(describe, groupby(df, "a"), ungroup = false) |> (t -> show(t, allrows = true, allgroups = true))
GroupedDataFrame with 5 groups based on key: a
Group 1 (2 rows): a = 2
│ Row │ a     │ variable │ mean     │ min       │ median  │ max      │ nunique │ nmissing │ eltype   │
│     │ Int64 │ Symbol   │ Float64  │ Real      │ Float64 │ Real     │ Nothing │ Nothing  │ DataType │
├─────┼───────┼──────────┼──────────┼───────────┼─────────┼──────────┼─────────┼──────────┼──────────┤
│ 1   │ 2     │ a        │ 2.0      │ 2         │ 2.0     │ 2        │         │          │ Int64    │
│ 2   │ 2     │ b        │ 0.511089 │ 0.0032423 │ 0.51914 │ 0.994888 │         │          │ Float64  │
Group 2 (2 rows): a = 3
│ Row │ a     │ variable │ mean     │ min        │ median   │ max      │ nunique │ nmissing │ eltype   │
│     │ Int64 │ Symbol   │ Float64  │ Real       │ Float64  │ Real     │ Nothing │ Nothing  │ DataType │
├─────┼───────┼──────────┼──────────┼────────────┼──────────┼──────────┼─────────┼──────────┼──────────┤
│ 1   │ 3     │ a        │ 3.0      │ 3          │ 3.0      │ 3        │         │          │ Int64    │
│ 2   │ 3     │ b        │ 0.508742 │ 0.00174766 │ 0.541555 │ 0.997982 │         │          │ Float64  │
Group 3 (2 rows): a = 1
│ Row │ a     │ variable │ mean     │ min       │ median   │ max      │ nunique │ nmissing │ eltype   │
│     │ Int64 │ Symbol   │ Float64  │ Real      │ Float64  │ Real     │ Nothing │ Nothing  │ DataType │
├─────┼───────┼──────────┼──────────┼───────────┼──────────┼──────────┼─────────┼──────────┼──────────┤
│ 1   │ 1     │ a        │ 1.0      │ 1         │ 1.0      │ 1        │         │          │ Int64    │
│ 2   │ 1     │ b        │ 0.532574 │ 0.0107663 │ 0.560414 │ 0.994937 │         │          │ Float64  │
Group 4 (2 rows): a = 5
│ Row │ a     │ variable │ mean     │ min        │ median   │ max      │ nunique │ nmissing │ eltype   │
│     │ Int64 │ Symbol   │ Float64  │ Real       │ Float64  │ Real     │ Nothing │ Nothing  │ DataType │
├─────┼───────┼──────────┼──────────┼────────────┼──────────┼──────────┼─────────┼──────────┼──────────┤
│ 1   │ 5     │ a        │ 5.0      │ 5          │ 5.0      │ 5        │         │          │ Int64    │
│ 2   │ 5     │ b        │ 0.496365 │ 4.74044e-5 │ 0.495809 │ 0.990004 │         │          │ Float64  │
Group 5 (2 rows): a = 4
│ Row │ a     │ variable │ mean     │ min       │ median   │ max     │ nunique │ nmissing │ eltype   │
│     │ Int64 │ Symbol   │ Float64  │ Real      │ Float64  │ Real    │ Nothing │ Nothing  │ DataType │
├─────┼───────┼──────────┼──────────┼───────────┼──────────┼─────────┼─────────┼──────────┼──────────┤
│ 1   │ 4     │ a        │ 4.0      │ 4         │ 4.0      │ 4       │         │          │ Int64    │
│ 2   │ 4     │ b        │ 0.506765 │ 0.0109599 │ 0.504049 │ 0.99936 │         │          │ Float64  │
```

**Comment by bkamins** [comment]
Unless there is some other comment I will open a PR implementing the recommendation:

> disable computing of `:median` and `:nunique` by default (leave them as opt-in)

(the issue has popped up again on Slack and newcomers can be really surprised by the slow response time for large data sets)

**Comment by bkamins** [comment]
See #2339
