### ISSUE TITLE
special case `percentage` in `combine`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2272]
Currently `combine` special cases `nrow` to get the number of rows. 

It's actually pretty hard to get the percentage of observations in a group when doing a combine operation. You have to do `nrow` before, then save that variable, then make a new `nrow`. 

It might be worth considering adding something like 

```
julia> df = DataFrame(
           sex = rand(["Man", "Woman", "Other"], 100), 
           race = rand(["White", "Black", "Other"], 100), 
           income = rand(100));

julia> combine(groupby(df, "race"), percentage)
```

be a shorthand for 

```
N = nrow(parent(df))
n = nrow(sdf)
return n / N
```

**Comment by bkamins** [comment]
Actually it is even harder than you think, as `gdf` can be subsetted, so your code is incorrect, it should rather be:
```
n = [nrow(sdf) for sdf in gdf]
return n ./ sum(n)
```
which is not only not easy to type but also tricky.

I think it is OK to add this at some point.

**Comment by bkamins** [comment]
added `:proprow`
