### ISSUE TITLE
Add a `pushfirst!` method

### ISSUE THREAD

**Issue by apbraun** [JuliaData/DataFrames.jl#2275]
I was wondering if it is possible to add `pushfirst` for DataFrames. Since `push!` is already implemented it seemed convenient to be able to use `pushfirst!` as well.

**Comment by bkamins** [comment]
I think it can be added in the future along with other methods that operate rowwise as requested in other issues.

**Comment by bkamins** [comment]
x-link #2936

**Comment by bkamins** [comment]
done
