### ISSUE TITLE
no method matching iterate(::InvertedIndex{BitArray{1}}), trying to any() a BitArray 

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#2285]
I have a DataFrame with some integer columns that I selected with regex and I'm trying to see if any of the rows are sorted.

It seems a little odd that you can't `any(Not((...))`

```julia
rows = eachrow(df[:, r"n_\d"])
any(Not(issorted.(rows, rev=true))) # doesn't run
any(.!(issorted.(rows, rev=true))) # runs
```

**Comment by bkamins** [comment]
This issue is not related to DataFrames.jl. `Not` is defined in https://github.com/mbauman/InvertedIndices.jl and its sole function is negation of indices, use `!` for logical negation (as you did).
