### ISSUE TITLE
Fatal error: ERROR: UndefVarError: identifier not defined

### ISSUE THREAD

**Issue by liwen-alt** [JuliaData/DataFrames.jl#2286]
mydata = dataset("datasets","iris")
Error encountered while loading "C:\\Users\\Administrator\\.juliapro\\JuliaPro_v1.4.0-1\\packages\\RDatasets\\1Ih8s\\src\\..\\data\\datasets\\iris.rda".
![image](https://user-images.githubusercontent.com/63285313/84570089-6f8a9a00-adbd-11ea-8c61-276bad54c9bd.png)
![image](https://user-images.githubusercontent.com/63285313/84570101-8a5d0e80-adbd-11ea-9a2e-d359a1fba882.png)

**Comment by bkamins** [comment]
This is a problem with RDatasets.jl. The issue is already opened there: https://github.com/JuliaStats/RDatasets.jl/issues/97.
