### ISSUE TITLE
isless for DataFrameRow

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2287]
`isless` for `DataFrameRow` ignores column names, but `==` checks them.

For `NamedTuple` `isless` is undefined so there is no inconsistency there. But we have it for `DataFrameRow`.

We have two options I think:
1. disallow `isless` for `DataFrameRow` (I think this is the way to go)
2. change `==` to ignore column names

**Comment by nalimilan** [comment]
`isless` is defined for named tuples when they have identical names. I guess we could do the same and throw an error when names differ. Is that used in a common pattern?

**Comment by bkamins** [comment]
it is not that common, but possible. I was misguided by the error message for `NamedTuples`:
```
julia> (a=1,b=2) < (a=3,c=4)
ERROR: MethodError: no method matching isless(::NamedTuple{(:a, :b),Tuple{Int64,Int64}}, ::NamedTuple{(:a, :c),Tuple{Int64,Int64}})
```
but forgotten that `NamedTuple` has key names in type signature. I will make a fix as you suggest as it makes most sense!
