### ISSUE TITLE
Mop-up after allowing strings as column names

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2298]
After allowing strings as column names we in general:
* return strings from `names`
* return `Symbol`s from `propertynames`, `keys`, and `groupcols`

The question is if it would not be more consistent to make `keys` and `groupcols` return `String`s and only make `propertynames` return `Symbol`s.
I am OK with the current behaviour, as `keys` and `groupcols` are probably not used to transform column names, but rather to access them only.
Though maybe for entry users it would be better to expose strings everywhere except for `propertynames`?

**Comment by Nosferican** [comment]
I think I am good either way. No strong inclination... Maybe someone can showcase use cases to guide the decision.

**Comment by oxinabox** [comment]
I think I am ok with current behavour.

I have never seen `groupcols` before, so don't understand implication there.
But should we have `groupnames` returnign strings and `groupkeys` returning symbols

**Comment by pdeffebach** [comment]
I vote for `String`s everywhere. I like the propertynames, names distinction a lot. I'm glad you've thought it over.

**Comment by bkamins** [comment]
I think the name `groupcols` should stay as `keys` has a different usage and it would be confusing, so `cols` stands out more clearly. Fortuantely I thing we can treat `Symbol`->`String` change as mildly breaking. Most of user code probably does not rely on this.

**Comment by bkamins** [comment]
@Nosferican  (and all). I think the best examples are:
```
julia> using DataFrames

julia> df = DataFrame(rand(1,2))
1×2 DataFrame
│ Row │ x1       │ x2       │
│     │ Float64  │ Float64  │
├─────┼──────────┼──────────┤
│ 1   │ 0.959014 │ 0.423606 │

julia> pairs(eachcol(df))
Iterators.Pairs(::DataFrames.DataFrameColumns{DataFrame}, ::Array{Symbol,1}) with 2 entries:
  :x1 => [0.959014]
  :x2 => [0.423606]

julia> pairs(Tables.columntable(df))
pairs(::NamedTuple) with 2 entries:
  :x1 => [0.959014]
  :x2 => [0.423606]

julia> keys(df[1, :])
2-element Array{Symbol,1}:
 :x1
 :x2

julia> keys(NamedTuple(df[1, :]))
(:x1, :x2)
```
This is the current behaviour. That is - where it makes sense we behave "as if" we were a type-unstalbe `NamedTuple` (of course there is not 100% 1-2-1 matching, but this is a mental model). Now function `names` returns strings, but this is OK, as this function **is not** defined for `NamedTuple`s.

So in other words: we are still treating `Symbol` as a "base" type of column names, but allow `names` to return strings for convenience (and in other functions that explicitly assume you will manipulate names like `raneme` or `unstack`).

The alternative is to switch this mental model and treat string as a "base" column name and treat `propertynames` returning `Symbol` as an exception. In both examples above we would have `Symbol` changed to `String` when working with a `DataFrame`.

So here is a summary of the current behaviour (`Symbol` everywhere except `names` function):
* pro: DataFrames.jl is kind of more consistent with Tables.jl interface in general (i.e. in more places you can not-care if this is a `DataFrame` or some other table, as you know you will be getting `Symbol` as column name)
* con: it is easier to manipulate strings

So having reflected on this my opinion is to stick to the current behaviour as more consistent with the ecosystem. But of course - as usual - please comment what you think!

**Comment by Nosferican** [comment]
I would concur. I might be tempted to advocate for strings everywhere and `names` the exception but consistency with the tables API and related ecosystem seems to out-weight the small convenience of strings everywhere.

**Comment by bkamins** [comment]
Anyone has some more comments on this. If not we leave things as is, i.e. only `names` will produce strings.

**Comment by pdeffebach** [comment]
I think we have yet to see user experience with the `String` vs `Symbol` output. So I am okay with only `names` producing strings and we will get more feedback when people start working again, or when the school-year starts.

**Comment by nalimilan** [comment]
I think being consistent with Tables.jl and NamedTuple for functions that they cover is a good criterion. The difficulty is for `groupcols`, which isn't part of their APIs (like `names`). Though it's probably not a big deal either way.

**Comment by bkamins** [comment]
> The difficulty is for `groupcols`

Here I would prefer to keep the rules as simple as possible, and the rule I currently have in my mind is:

> `Symbol`s are always returned except for `names` function

**Comment by bkamins** [comment]
If there are no more comments on this the decision is:

"Leave things are they are now, ie. mostly return `Symbol` except for `names` and transformation functions that naturally except strings."

@pdeffebach when this is decided we can go back to https://github.com/JuliaData/DataFrames.jl/pull/2281.

**Comment by bkamins** [comment]
OK - I am closing this. Please comment if you want to reopen.
