### ISSUE TITLE
Showing of very wide data frames

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2302]
Currently `show` computes the width of **all** columns before trying to show them. It is problematic for very wide data frames. We could consider optimizing it to avoid computation for columns that will not be show anyway.

**Comment by bkamins** [comment]
@ronisbr - I assume that PrettyTables.jl does not have this problem?

**Comment by ronisbr** [comment]
Hi @bkamins ,

No it doesn't. If the output must be cropped to fit the `io` size, then it only processes the number of columns and rows required to fill the screen.
