### ISSUE TITLE
What happened to by()?

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#2306]
I had grown quite accustomed to the `by()` function, however, I can't find it in the documentation anymore. 

What is the reasoning for removing it?

**Comment by bkamins** [comment]
1. It saves very little typing
2. with the current design it is much better to store `GroupedDataFrame` in a variable and reuse it later (expensive operations are cached) - so it is better to have this habit
3. syntax like `by(df, :a, :b, :c)` or `by(:b, df, :a)` would be confusing - on a Julia level there is no ambiguity, but it is not visually clear that that `:a` in these forms has a completely different meaning than `:b` or `:c`
4. `by` is not a verb
5. in general we try to limit the function count in API (that is why `aggregate` is also deprecated)
6. If you still like to use `by` - just add its definition to your script (it is essentially a one liner)

**Comment by anandijain** [comment]
ty!
