### ISSUE TITLE
How to save dataframe to CSV file

### ISSUE THREAD

**Issue by liwen-alt** [JuliaData/DataFrames.jl#2312]
the function writetable() 
![image](https://user-images.githubusercontent.com/63285313/86504201-4cfe0680-bde8-11ea-94a3-be88447d1d00.png)

**Comment by bkamins** [comment]
```
using CSV
```
and then
```
CSV.write(file, table; kwargs...)
```
or
```
table |> CSV.write(file; kwargs...)
```

**Comment by liwen-alt** [comment]
this method can write dataframe to csv file

**Comment by bkamins** [comment]
yes, is something not working in what I have referenced to?

**Comment by liwen-alt** [comment]
this is my coding, I will the df1 write into a .csv file ,i can choice，this method can satisfy the needing?
cn = zeros(Float64,100)
aa = zeros(Float64,100)
ra = zeros(Float64,100)
pa = zeros(Float64,100)
lhn1 = zeros(Float64,100)
jaccard = zeros(Float64,100)
lp = zeros(Float64,100)
auc = zeros(Float64,100)
precison = zeros(Float64,100)
for j = 1 : length(datasets)
    for i = 1 : 100
        data = load_example_data(datasets[j])
        net = DivideNet(data,0.9)
        train = net[1]
        test = net[2]
        cn[i]=CN(train)
        aa[i]=AA(train)
        ra[i]=RA(train)
        pa[i]=PA(train)
        lhn1[i]=LHN1(train)
        jaccard[i]=Jaccard(train)
        lp[i]=LP(train,0.001)
    end
    df1 = DataFrame()
    df1[:CNsim] = cn
    df1[:AAsim] = aa
    df1[:RAsim] = ra
    df1[:PAsim] = pa
    df1[:LHN1sim] = lhn1
    df1[:Jaccardsim] = jaccard
    df1[:LPsim] = lp
    CSV.write(df1,'100sim.csv')
end

**Comment by bkamins** [comment]
Please check the signature I have provided. You should write:
```
CSV.write("100sim.csv", df)
```
Also note that `'` is not a valid delimiter of strings in Julia

**Comment by liwen-alt** [comment]
ok,thank you
