### ISSUE TITLE
remove `DataFrame!`?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaData/DataFrames.jl#2317]
As far as I can tell, this doesn't mutate anything, so the `!` is not appropriate. For the cases where it gives errors, `DataFrame` could instead give the error if `copycols=false` is passed.

**Comment by bkamins** [comment]
Yes, `DataFrame!` does not mutate anything.

> For the cases where it gives errors,

Having this method is not related with errors - it is just a convenience.

The reason why it exists is that Base Julia does not provide a convenient syntax for partial function application,
and being able to easily avoid copying data when `DataFrame` is created was considered important by users for performance reasons. The `!` in the name was to warn the user that mutation of the source might happen in the future (as in general `DataFrame` guarantees to perform a copy), as mutation of the source was a major source of bugs in codes using DataFrames.jl.

Now - the major use case for this method was in the past:
```
CSV.File(filename) |> DataFrame!
```
which is relevant for very large source files. However, with the changes in https://github.com/JuliaData/CSV.jl/pull/687 this will not be needed.

Therefore, I think we can deprecate `DataFrame!`, but let us wait for some feedback about this proposal before making a PR.

**Comment by quinnj** [comment]
I think we should deprecate it; I don't think anyone really _likes_ the bang operator here because it's just slightly confusing why it's there.
