### ISSUE TITLE
add `filter` example to docs on taking subsets

### ISSUE THREAD

**Issue by floswald** [JuliaData/DataFrames.jl#2318]
hey, 
just learned on twitter and https://bkamins.github.io/julialang/2020/07/17/pair.html that I can `filter` on an entire dataframe. blew my mind ! i think should be added to the docs in the *taking a subset* section.

**Comment by bkamins** [comment]
Indeed we could add a documentation to `filter` and `filter!` with both `predicate` and `cols => predicate` as a first argument (the `=>` style is faster and often more terse).

If you feel like it - please open a PR with some examples that you would consider instructive (if not - then let me know and I will propose something).
