### ISSUE TITLE
Different behavior of names() on mac and windows 10

### ISSUE THREAD

**Issue by biona001** [JuliaData/DataFrames.jl#2336]
On mac,
```
help?> names

  names(df::AbstractDataFrame)

  Return a `Vector{Symbol}` of names of columns contained in `df`.
```

but on windows, `names` returns a `Vector{String}`! The windows doc says I needed to use `propertynames` to get a `Vector{Symbol}`. I find this very unexpected.

**Comment by bkamins** [comment]
The problem is not Win/Mac issue, but that you have a different version of DataFrames.jl installed. Use 0.21 or later where `names` returns `AbstractVector{String}`. Earlier versions did not support string indexing, so `Symbol` was returned.
