### ISSUE TITLE
Add support for rich display output of Markdown.MD cells

### ISSUE THREAD

**Issue by NicholasWMRitchie** [JuliaData/DataFrames.jl#2347]
With fairly minor code changes, it is possible to display cells containing Markdown.MD objects with rich formatting in HTML, and LaTeX documents.  It is possible to format text with bold, italic and header formats.  It is possible to insert URL links and images.   Pull request #2346 implements this functionality with only minor changes to the display code.

**Comment by bkamins** [comment]
I am closing this issue as there is a PR for this already.
