### ISSUE TITLE
Docstring for constructor not accurate about Tables

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2361]
From [here](https://github.com/JuliaData/DataFrames.jl/blob/cc83566056c00185cb47a4301508464ba4f0a8c4/src/dataframe/dataframe.jl#L54)

> - `table` : any type that implements the
  [Tables.jl](https://github.com/JuliaData/Tables.jl) interface; in particular
  a tuple or vector of `Pair{Symbol, <:AbstractVector}}` objects is a table.

Is this true? 

```
julia> t = [Symbol(:x, i) => rand(4) for i in 1:3]
3-element Array{Pair{Symbol,Array{Float64,1}},1}:
 :x1 => [0.5573539958624172, 0.3630628238122373, 0.7365553241090261, 0.992079812253625]
 :x2 => [0.20328638835669954, 0.2610347993070954, 0.08235343898725067, 0.042372554830341524]
 :x3 => [0.24416901853453532, 0.25952027635286656, 0.5845586486615153, 0.8373104112643548]

julia> using DataFrames.Tables

julia> Tables.istable(t)
false
```

**Comment by pdeffebach** [comment]
[here](https://github.com/JuliaData/DataFrames.jl/blame/cc83566056c00185cb47a4301508464ba4f0a8c4/src/dataframe/dataframe.jl#L183) is the git blame for this change. 

I think this is a bug since its not a table we don't need to define a constructor for it and we can throw an error.

**Comment by bkamins** [comment]
The documentation is accurate in a sense that we accept it, but indeed now it does not follow Tables.jl API. I wonder why I have add it - most likely it was a table in the past (@quinnj - can you remember this).

Anyway - the decision is:
do we want to keep these constructors? if yes then we should change the docstring. If not - the methods should get removed.

I think it is OK to drop these constructors.

**Comment by bkamins** [comment]
Now I remember - we changed it on purpose so that splatted and non splatted `Pair`s work the same. So the only thing to change is:
```
in particular a tuple or vector of Pair{Symbol, <:AbstractVector}} objects is a table.
```
to
```
as a particular rule a tuple or vector of Pair{Symbol, <:AbstractVector}} objects is considered to be table.
```
and I would leave the functionality as is (as commented above I find this behavior better than having `:first` and `:last` column).

Do you agree? If yes - can you please make a PR for a docstring or otherwise I can make it.
