### ISSUE TITLE
How to use showcols? 

### ISSUE THREAD

**Issue by whitehorsse** [JuliaData/DataFrames.jl#2366]
`@time showcols (flights_df)`
gives 

LoadError: MethodError: no method matching @time(::LineNumberNode, ::Module, ::Symbol, ::Symbol)
Closest candidates are:
  @time(::LineNumberNode, ::Module, ::Any) at timing.jl:169
in expression starting at In[68]:1

Stacktrace:
 [1] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

Why no wiki or manual ?

**Comment by bkamins** [comment]
`showcols` is a deprecated method. You can use it only for legacy reasons and in the next release of DataFrames.jl it will be removed. Use `julia --depwarn=yes` when starting your Julia session to get information about deprecated functions. In your code the problem is that you have inserted space between `showcols` and `(`.

**Comment by whitehorsse** [comment]
In your code the two problems are that 1) a breaking change has been introduced without documenting the pathway to upgrade; and 2) that a presence or absence of a space (empty character by nature) is regarded as syntax error. Thanks/

**Comment by bkamins** [comment]
If you ask about deprecation instruction for `showcols` then it was given, as you see here: https://github.com/JuliaData/DataFrames.jl/pull/1418. However, you are trying to use a function that was removed from the package over 2 years ago. We have a policy that we do not keep deprecation warnings that long (sorry for mixing things up in the original response).

> that a presence or absence of a space (empty character by nature) is regarded as syntax error.

Please read https://docs.julialang.org/en/v1/manual/metaprogramming/#Macro-invocation-1 to see that in macro calls whitespace is actually significant in Julia.

Then you can check https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872 to see why it is not likely to change in the future.
