### ISSUE TITLE
Applying simple operations during transform

### ISSUE THREAD

**Issue by tk3369** [JuliaData/DataFrames.jl#2369]
I frequently need to very simple math e.g. 

```julia
transform(df, [:x1, :x2] => ((x,y) -> x .+ y) => :sum_x)
```

It seems a little verbose to write an anonymous function for basic operations like this?  What if we define an `apply` function that just broadcast a function over all the arguments? e.g.

```julia
apply(op) = (args...) -> broadcast(op, args...)
```

Then, I can do:
```julia
transform(df, [:x1, :x2] => apply(+) => :sum_x)
```

Just an idea.

**Comment by bkamins** [comment]
We already have this and it is called `ByRow`:
```
transform(df, [:x1, :x2] => ByRow(+) => :sum_x)
```
