### ISSUE TITLE
`columnindex` for DataFrameRow

### ISSUE THREAD

**Issue by raphaelsaavedra** [JuliaData/DataFrames.jl#2379]
There is currently no `columnindex` for DataFrameRows. This isn't a problem in general, but suppose you're in a local scope with no access to the original DataFrame and want to do something like

```
for name in names
    if row_[name] == ...
        @test !ismissing(row_[columnindex(row_, name) + 1])
    end
end
```

The only current nice way of doing it without resorting to `findfirst` or similar is `DataFrames.index(row_)[name]`.

**Comment by nalimilan** [comment]
Currently DataFrames doesn't implement `columnindex` directly, it relies on the fallback definition in Tables.jl. Though I guess we could override it to reuse the internal `index` and offer O(1) lookup. Then I guess we could also implement it for DataFrameRow , even if it's not a Table.

**Comment by bkamins** [comment]
Indeed - I have noticed now that Tables.jl does copying. I will make a PR.

**Comment by bkamins** [comment]
see https://github.com/JuliaData/DataFrames.jl/pull/2380. Your request helped me to find a nasty bug in view indexing that this PR also fixes.

**Comment by raphaelsaavedra** [comment]
Thanks! Glad I could (unintentionally) help :)
