### ISSUE TITLE
Provide `nunique` for `<:Real` columns in `describe`

### ISSUE THREAD

**Issue by nilshg** [JuliaData/DataFrames.jl#2384]
Currently, `describe` defaults to showing `nothing` when calculating `nunique` for `<:Real` columns. This is probably sensible in many cases as it doesn't make sense to try and count unique floating point values, but I find it useful for two reasons: (1) for `Float` columns it basically provides `nrow` as part of the `describe` table, which is convenient, and (2) it can actually be informative (i.e. not just equal to `nrow`) for `Int` columns.

@bkamins mentioned on Slack that `nunique` is not calculated by default anymore, lowering the risk that someone accidentally tries to compute the number of unique floats in a multi-million row DataFrame.

**Comment by bkamins** [comment]
Since this is breaking @nalimilan - the decision here is to either:
1. keep things as is and tell users they can always write `:unique => x -> length(unique(x))` if they want, or
2. make `nunique` calculate number of unique values always. It will be slow, but we do not compute it by default now.

@nilshg - for your use case of checking if `nrow` is the same as number of uniques I would rather use `:mycol => allunique` function.

so given these considerations what do you think?

**Comment by nalimilan** [comment]
This decision to stop reporting the number of unique values by default was taken at https://github.com/JuliaData/DataFrames.jl/issues/2269. I'm not entirely happy with the fact that we never print the number of unique values for `Int` columns, but we couldn't find a good way to do it when it's useful and at the same time avoid computing it when it would take ages. Even if it's not by default, if you have a large data frame with one `Float64` column the computation will take a long time.

@nilshg Can you have a look at that issue and tell us what you think?

**Comment by bkamins** [comment]
As a reference:
```
julia> x = collect(1:10^8);

julia> @time allunique(x);
 17.085821 seconds (82 allocations: 4.499 GiB, 2.06% gc time)

julia> @time length(Set(x));
 13.011330 seconds (14 allocations: 3.375 GiB, 2.09% gc time)
```

**Comment by nilshg** [comment]
Shouldn't this be okay if it's not the default? 

I'd say to use `:nunique` if it's not provided by default a user would have to read the docs, so we could insert a warning there, letting the user decide whether to accept a bit of a wait or to call `describe(df[!, Not(:myfloatcolumn)])` or similar instead.

**Comment by nalimilan** [comment]
Yeah, maybe. Though I've just checked, and if you hit Ctrl+C during the computation, it only stops the current function call, and goes on to the next one. We still return a `DataFrame` with the entry set to `nothing`. This is problematic if you have dozens of columns. We should probably make the `try... catch` rethrow `InterruptException`, and then maybe it will be OK to apply `nunique` to all column types.

**Comment by bkamins** [comment]
@nilshg - we probably will not change the current behavior, as it would be breaking. Do you want to keep this PR for the future reference, or it can be closed?

**Comment by nilshg** [comment]
Fine to close!
