### ISSUE TITLE
do we want to limit column size to 32 characters in text/plain display

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2389]
In https://github.com/JuliaData/DataFrames.jl/pull/2346 this is what we do for markdown. Maybe it would be good to do for all types?

**Comment by nalimilan** [comment]
Makes sense, though we should check that other implementations do.

**Comment by bkamins** [comment]
Also CC @ronisbr

**Comment by ronisbr** [comment]
I totally agree with that! Anyway, with PrettyTables.jl, it will be very easy to let the user change this if they want.

**Comment by bkamins** [comment]
OK - I will implement it when #2390 is merged.
