### ISSUE TITLE
A nice looking cheat sheet

### ISSUE THREAD

**Issue by tk3369** [JuliaData/DataFrames.jl#2393]
Related to #1530, I would like a nice-looking cheatsheet that is similar to the ones for R and Python:

* https://rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
* https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

I have started putting together the cheat sheet on Google slides. Here's a draft for the first page:

https://docs.google.com/presentation/d/1mpvPyR0z3MY23sPtzQP2xICBWU8XyGBuU2M2eyf4jPM/edit?usp=sharing

I suppose it can be hosted somewhere in the documentation when it's finished.

**Comment by bkamins** [comment]
This is very nice. You have essentially two options:
1. you maintain it somewhere and then we just add a link to it in DataFrames.jl (this is the approach with https://github.com/bkamins/Julia-DataFrames-Tutorial)
2. you want this tutorial to be curated (personally I would not recommend this, as it is much harder to maintain - as you have witnessed with #2378). In this case it would have to be in a format that is possible to be easily maintained and built via GitHub (so either MarkDown compiled to HTML by Documenter.jl (preferable) or LaTeX but then we would have to work out the pipeline to build PDFs correctly during documentation build (thus hard and not recommented))

I am closing this as it is essentially follow up to #1530 so can you please further comment on your thoughts and progress there? Thank you! (I will comment on your cheat sheet when it is ready as there are some details that I think it would be worth to make a bit more precise)

**Comment by tk3369** [comment]
Sounds good. Your feedback is very helpful.

An interesting note is that I actually started working on the cheat sheet with Luxor. After creating some frames and graphics, I realize that it's probably going to take me too long. And there are some quirks of text formatting that I cannot do it easily with that.

**Comment by bkamins** [comment]
This is what I would assume :). Just please let me know when you are happy with the state of your cheat sheet and I will comment on it.

**Comment by nalimilan** [comment]
Great! It's a great time to do this as we are approaching 1.0 (before the risk would have been that it would get outdated quickly...).

I think it would be nice to regroup our documentation material under the official repo to make it easier to maintain and discover.
