### ISSUE TITLE
add a kwarg to reuse the input column names in cols => fun in select/transform/combine

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2396]
This request is showing often as sometimes adding transformation function name is not desired.
A working idea is to add a `suffix` kwarg that would handle this (actually the suffix might be more flexible than just `true`/`false`, but a general suffix - I will propose something).

I will make a PR for this. This is an issue to keep track that this happens.

**Comment by bkamins** [comment]
@nalimilan - the only problematic case to decide what to do is `[] => fun`. What should be the column name then when we drop adding function as a suffix? It can be `Symbol("")`,  as we allow it, but it seems to be obscure. However, maybe it is OK, as one has to be explicit to get this outcome.

**Comment by nalimilan** [comment]
I'd say `Bool` is OK for a start, even if later we might want to allow passing any function. For `[] => fun` let's just throw an error?

Though for consistency with `join` (https://github.com/JuliaData/DataFrames.jl/pull/2313) shouldn't the argument be called `rename`?

**Comment by bkamins** [comment]
Now I see this comment. So maybe in joins I also change it to `renamecols` to have the same kwarg name everywhere?

> For [] => fun let's just throw an error?

OK

**Comment by nalimilan** [comment]
Yeah if you want to avoid breaking `unstack` then better use `renamecols` and change `join` to use that before a release includes it.

**Comment by bkamins** [comment]
This is what I will do.
