### ISSUE TITLE
a function similar to pandas.DataFrame.fillna

### ISSUE THREAD

**Issue by norci** [JuliaData/DataFrames.jl#2407]
pandas has a function [fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html)

the parameter method is very helpful

> method{‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default None
>   Method to use for filling holes in reindexed Series pad / ffill: propagate last valid observation forward to next valid backfill / bfill: use next valid observation to fill gap.

Is there a similar function in Julia?
Or could we implement one?
Thanks.

**Comment by bkamins** [comment]
I think you are looking for https://github.com/invenia/Impute.jl (if not please comment)

**Comment by norci** [comment]
> I think you are looking for https://github.com/invenia/Impute.jl (if not please comment)

This is what I need.
Many thanks.

And could we add this info into DataFrames.jl's document?

**Comment by bkamins** [comment]
See https://github.com/JuliaData/DataFrames.jl/pull/2408
