### ISSUE TITLE
do we want combine(df, pair) to behave the same way as combine(pair, df)?

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2409]
Pros:
1. you can have in `combine(df/gdf, cols => fun)` for `fun` to return `NamedTuple`; also this will most likely to be non-conflicting in the future (as we want to add it anyway)
2. it is relatively simple to add

Cons:
1. `combine(df/gdf, pair1, pair2)` will behave differently than `combine(df/gdf, pair1)`
2. it is easy enough to explain the difference between `combine(pair, df/gdf)` and `combinedf/gdf, pair)`
3. `select` and `transform` for now will not allow `NamedTuples` in `select(df/gdf, pair)`

Also I would not support `combine(df/gdf, ::Function)` and only allow `combine(::Function, df/gdf)`

CC @dmbates @nalimilan @pdeffebach

**Comment by dmbates** [comment]
I don't really have enough experience with the current system to contribute much insight.  I am finding the `combine(::Function, df/gdf)` form to be very useful, perhaps more useful than the forms with `pair1` or `pair1, pair2`.  But it may be a matter of just getting more experience with the different forms.

**Comment by bkamins** [comment]
> I am finding the `combine(::Function, df/gdf)` form to be very useful

And this is a canonical way to do things.

The `Pair` stuff serves two purposes:
1. make aggregations faster, eg `:col => mean` will be much faster than `x -> mean(x.col)` (order of magnitude)
2. and as you can see in point 1) this form is a bit shorter, especially if you want to set a target name of the column `:col => mean => :some_name` in comparison to `x -> (some_name = mean(x.col),)`

**Comment by bkamins** [comment]
closing, as we will resolve it in https://github.com/JuliaData/DataFrames.jl/issues/2410
