### ISSUE TITLE
add transpose(df, src_namescol, dst_namescol)

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2420]
This should transpose the contents of a `DataFrame` except `src_namescol` which should be converted to column names, while `dst_namescol` should be a first column name in the target data frame holding the names of columns before transposing.

**Comment by tbeason** [comment]
Not sure if this is going to be helpful for whoever tackles this, but I have a function
```
transposedf(df,col) = unstack(stack(df,Not(col)),:variable, col,:value)
```
that I use semi-often right now. I think it maybe provides the imagined functionality but it only transposes on one column.

**Comment by bkamins** [comment]
Thank you for posting your approach.

The key difficulty with this issue is to find a most efficient way to transpose. I have not looked into it yet, as it is non urgent.
