### ISSUE TITLE
make sure aggregation uses fast path if a single column is used

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2423]
I will fix it. Currently `:x => sum` uses a fast path, but `[:x] => sum` does not.

**Comment by sa-** [comment]
Looking into this. Pasting some of your Slack messages here in case the messages get deleted: 

```
fast path is implemented here: https://github.com/JuliaData/DataFrames.jl/blob/main/src/groupeddataframe/fastaggregates.jl

10:30
In the fast path you do not have to calculate grouping views. You can just pre-allocate the target container (whose eltype you know upfront) and just iterate groups and perform reduction.
```

**Comment by bkamins** [comment]
The key thing to do here is to rewrite code like:
```
@chain df begin
    groupby(:a)
    combine([:b] => sum)
end
```
to:
```
@chain df begin
    groupby(:a)
    combine(:b => sum)
end
```
before executing it.

We should check in the syntax `src => fun` and `src => fun => dst` if `src` is `Union{AbstractVector{<:AbstractString}}, AbstractVector{Symbol}, AbstractVector{<:Union{Signed, Unsigned}}` of length 1 and if this is so its first element should be fetched with `only` before further processing.

**Comment by sa-** [comment]
Can this be closed now?

**Comment by bkamins** [comment]
yes
