### ISSUE TITLE
`propertynames` doesn't error with positional arguments

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2425]
```
julia> df = DataFrame(a = [1], b = [2])
1×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │

julia> propertynames(df, Not(:a))
2-element Array{Symbol,1}:
 :a
 :b
```

I don't think its necessary for `propertynames` to support positional arguments like `Not` the way `names` does, but it seems like this should error, right?

**Comment by bkamins** [comment]
This is a problem in Julia Base. I have filed https://github.com/JuliaLang/julia/pull/37550
