### ISSUE TITLE
Should there be a quality for packages to be included in the doc?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFrames.jl#2431]
E.g. DataFramesMeta and Query are included. Not saying they are bad, but good to have some measure that says a package needs to met this to qualify for inclusion in the readme.

With clear rules, when a pkg fails some quality standard, they can be removed.

**Comment by bkamins** [comment]
The current rule is:

> below is a list of well-supported libraries

which is stated in the manual. I agree it is vague, but it essentially means that it is up to JuliaData maintainers to decide if this condition is met or not when "approving" the PR to DataFrames.jl (note that any PR needs such an approval so it is always possible to discuss).

We have discussed to make it more crisp. However, it is hard to make this statement more precise, as with any set of rules there will be an exception which we accept although it might not meet these standards.

Let me give a list here though, for a future reference (remembering that it is not carved in stone - even now it is probably not met by all the packages listed):
* package must support Julia LTS and current Julia release
* package dependencies must be in sync with DataFrames.jl dependencies
* package must support current release of DataFrames.jl
* package must be actively maintained (i.e. if there is upgrade of Julia or DataFrames.jl then within a reasonable time it is synced with an appropriate release)
* package must have a good test coverage of its own functionality and integration with DataFrames.jl
* package must have an up-to date documentation (at least in docstrings)
* package must be relevant to DataFrames.jl and be in line with the general design principles of Julia code
* package must have a permissive licence

As you can see - any of these will be opinionated anyway, so I think just saying "well-supported" and later hoping that JuliaData members have a good judgement.

**Comment by xiaodaigh** [comment]
The list there is good. Some minimum standards to follow
