### ISSUE TITLE
Add reverse and reverse! functions similar to sort and sort!

### ISSUE THREAD

**Issue by ppalmes** [JuliaData/DataFrames.jl#2438]
- there are cases where you just want to reverse the order of dataframe and currently there is no implementation of the reverse() function

**Comment by Chandu-4444** [comment]
I'm trying to implement this. I wrote a function named `reverse` and put that in `src/abstractdataframe/reverse.jl`. But when I try to use my function, it didn't get recognized. But I placed the same function in sort.jl and it worked only that the docstrings I wrote weren't recognized (And they didn't show up during `?reverse`). Is there somekind of procedure to create new functions in a module?

**Comment by Chandu-4444** [comment]
> I'm trying to implement this. I wrote a function named `reverse` and put that in `src/abstractdataframe/reverse.jl`. But when I try to use my function, it didn't get recognized. But I placed the same function in sort.jl and it worked only that the docstrings I wrote weren't recognized (And they didn't show up during `?reverse`). Is there somekind of procedure to create new functions in a module?

I figured out that I need to add the new files that hold usable functions in `ModuleName.jl` file. This works fine, and now my function is working. But I didn't understand why my docstrings aren't getting shown when I use `?reverse`.

**Comment by bkamins** [comment]
added in 1.4 release
