### ISSUE TITLE
Allow keeping first or last observation with unique function 

### ISSUE THREAD

**Issue by tk3369** [JuliaData/DataFrames.jl#2443]
Pandas has a `keep` option:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html

Current behavior of DataFrames.jl keeps the first occurrence. 
```
julia> x = DataFrame(x=[1,1,2], y=[2,2,3], z=[3,4,5])
3×3 DataFrame
│ Row │ x     │ y     │ z     │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 1     │ 2     │ 3     │
│ 2   │ 1     │ 2     │ 4     │
│ 3   │ 2     │ 3     │ 5     │

julia> unique(x, [:x, :y])
2×3 DataFrame
│ Row │ x     │ y     │ z     │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 1     │ 2     │ 3     │
│ 2   │ 2     │ 3     │ 5     │
```

Shall we enhance the API to support keeping the first or last observation?

P.S. I don't know how useful this kind of lossy operation is but at least one use case was mentioned in this issue https://github.com/tk3369/www.ahsmart.com/issues/2#issuecomment-692109878

**Comment by bkamins** [comment]
Sure - it is not a problem to add this in the future. Thank you for the suggestion!
