### ISSUE TITLE
Add `insert!`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2446]
Now that we have coalesced around a DataFrame being a collection of rows, other than a few notable exceptions, we should add an `insert!` method

```
insert!(df, row)
```

where `row` matches anything that can be `push!`ed to a DataFrame.

**Comment by pdeffebach** [comment]
Context: I'm using `xtable` in R to make a data-frame that can be outputted to a publication-quality table using `dplyr`. So I have to be very particular about the order of rows etc. This seems hard to do in R and maybe we can make peoples' lives easier in Julia.

**Comment by bkamins** [comment]
Yes it is not a problem to add it. There is a bunch of similar functions waiting to be added. But we treat this as non critical for 1.0 release. Of course is someone wants to make a PR it is welcome.

**Comment by CameronBieganek** [comment]
> `insert!(df, row)`

Shouldn't that be the following?

```julia
insert!(df, i, row)
```

Otherwise it would be the same as `push!`.

**Comment by bkamins** [comment]
x-ref #2936

**Comment by bkamins** [comment]
added
