### ISSUE TITLE
Add `columnindex` for selectors such as `Between`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFrames.jl#2448]
For example 

`columnindex.(df, Between(:b, :c))`

`columnindexes(df, Between(:b, :c))`

`columnindices(df, Between(:b, :c))`

**Comment by bkamins** [comment]
We could do this. The only issue is to choose the right API as usual.

> `columnindex.(df, Between(:b, :c))`

this will not be allowed as `df` is broadcastable. You would have to use `Ref` wrapper around `df`. Also `Between` is not broadcastable now (but it might be in the future.)

**Comment by xiaodaigh** [comment]
Good point. I am okay with `columnindex(df, Between(...)) ` even though English has plural rules. So `columnindexes` as an alias is OK too.

**Comment by pdeffebach** [comment]
I think `columnindex.(names(df, Between(...))` is explicit enough

**Comment by xiaodaigh** [comment]
yeah I think so too.

**Comment by bkamins** [comment]
The only problem is it should be:
```
columnindex.(Ref(df), names(df, Between(:x2, :x3)))
```
but actually I would assume that:
```
names(df, Between(:x2, :x3))
```
most of the time should be enough as in DataFrames.jl all functions that accept integer indexing accept name indexing (if something is missing please open an issue).
