### ISSUE TITLE
`droprows` `keeprows`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/DataFrames.jl#2460]
There is `filter` and `where`. But I think `droprows` and `keeprows` are more explicit names. 

Can we think about adding them?

**Comment by bkamins** [comment]
`filter` is a name with a meaning in Julia Base.

We are discussing about adding `where`, but one of the things to be decided is the name for this function. I am closing this and moving the discussion into https://github.com/JuliaData/DataFrames.jl/issues/2323.
