### ISSUE TITLE
Add method to filter on `Bool` column symbols

### ISSUE THREAD

**Issue by jkbest2** [JuliaData/DataFrames.jl#2465]
Would it be reasonable to define a method `filter(b::Symbol, df::DataFrame)` that attempts to coerce `df.b` to `Bool` and then `filter`s on that?

**Comment by bkamins** [comment]
it is an interesting idea. I think it should rather ho to `where`, see https://github.com/JuliaData/DataFrames.jl/issues/2323, as we tend toward leaving only `filter(fun, data_frame)` in the long run. Let us see how things go.

Note that already you can write `df[df.b, :]` to get what you want.

**Comment by bkamins** [comment]
Closing it, as it is implemented as `subset(df, :b)` now.
