### ISSUE TITLE
support vector values instead of scalar or categorical only?

### ISSUE THREAD

**Issue by yupbank** [JuliaData/DataFrames.jl#2470]
hey, I'm trying to create dataframes with each cell having values as vectors, and right now it's not supported

```julia
df = DataFrame(A=randn(4, 2))
```
And I'm wondering if this is easy to support or is there any work around?

**Comment by bkamins** [comment]
It is supported:
```
df = DataFrame(A=Ref(randn(4, 2)))
```
The rules of pseudo broadcasting are described e.g. here https://bkamins.github.io/julialang/2020/09/13/pseudobroadcasting.html

In general - please specify what output you want, as `rand(4,2)` could be treated in several ways (I have shown you a most natural one - store a matrix in a cell of a data frame)
