### ISSUE TITLE
Always use ? for Union{T, Missing}

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#2480]
Currently we use a different representation for `Union{T, Missing}` column eltypes depending on whether the column's content are wide or not. This gives an inconsistent result. Wouldn't it be better to always use `T?`?
```julia
julia> DataFrame(x=[missing, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"], y=[missing, "a"])
2×2 DataFrame
│ Row │ x                             │ y       │
│     │ Union{Missing, String}        │ String? │
├─────┼───────────────────────────────┼─────────┤
│ 1   │ missing                       │ missing │
│ 2   │ aaaaaaaaaaaaaaaaaaaaaaaaaaaaa │ a       │
```

(Maybe PrettyTables already does that.)

**Comment by bkamins** [comment]
The current rule is:
1. display type in full if it is possible to do so
2. otherwise shorten it but ensure that it is clear if it is a union with `Missing`

What you show follows this rule.

To complement we also have:
```
julia> df = DataFrame(a=Union{Int, String, Missing}[1, "1", missing])
3×1 DataFrame
│ Row │ a       │
│     │ Union…? │
├─────┼─────────┤
│ 1   │ 1       │
│ 2   │ 1       │
│ 3   │ missing │
```
and
```
julia> df = DataFrame(a=Union{Int, String, Missing}[1, "1"^30, missing])
3×1 DataFrame
│ Row │ a                              │
│     │ Union{Missing, Int64, String}  │
├─────┼────────────────────────────────┤
│ 1   │ 1                              │
│ 2   │ 111111111111111111111111111111 │
│ 3   │ missing                        │
```
which is also a consequence of this rule.

We could add a special case:
3. if the `Union` is over exactly two types `Union{T, Missing}` and `T` is not a union then always write `T?`

CC @ronisbr

**Comment by bkamins** [comment]
@ronisbr - what is your thinking about using `?` to show "`Union` with `Missing`" consistently also in PrettyTables.jl?

**Comment by bkamins** [comment]
fixed on master:
```
julia> DataFrame(x=[missing, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"], y=[missing, "a"])
2×2 DataFrame
 Row │ x                              y       
     │ String?                        String? 
─────┼────────────────────────────────────────
   1 │ missing                        missing 
   2 │ aaaaaaaaaaaaaaaaaaaaaaaaaaaaa  a
```
