### ISSUE TITLE
clean-up unstack

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2485]
While reviewing `unstack` to remove CategoricalArrays.jl dependency I noticed:
```
julia> struct A
       x
       end

julia> df = DataFrame(x=[A(1), A(2), A(3)], y=[A(1), A(2), A(3)], variable=1, value=1)
3×4 DataFrame
│ Row │ x    │ y    │ variable │ value │
│     │ A    │ A    │ Int64    │ Int64 │
├─────┼──────┼──────┼──────────┼───────┤
│ 1   │ A(1) │ A(1) │ 1        │ 1     │
│ 2   │ A(2) │ A(2) │ 1        │ 1     │
│ 3   │ A(3) │ A(3) │ 1        │ 1     │

julia> unstack(df)
ERROR: MethodError: no method matching isless(::A, ::A)
```
my plan is to:
* add `sort` kwarg that allows user to decide if sorting should be performed (with default to `true`)
* add kwarg to handle cases when we currently print warnings (on duplicates and on `missing`s) - it will be more consistent to either throw an error or silently accept it (which would be managed by the kwarg)

**Comment by bkamins** [comment]
cc @nalimilan

**Comment by nalimilan** [comment]
Maybe we could try sorting and just skip that if it's not possible? That's what `levels` does.

I agree with throwing an error in cases where we currently print a warning.

**Comment by bkamins** [comment]
> That's what `levels` does.

Yes - I know, but actually I thought that it is not always desirable to sort, so it would be good to allow the user to opt-out of it.

The only difference would be that in my proposal `sort=true` by default and we throw an error if the column is not sortable (you have to pass `sort=false`) and in your proposal we silently do not sort it. I am not sure which behaviour is better (my personal preference is explicit `sort`, but I am not strongly attached to it).

**Comment by nalimilan** [comment]
As usual, we can throw an error, and stop doing so later if people complain.
