### ISSUE TITLE
sort with `by` accepts tuples still

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2500]
here is the relevant code for `by` with `sort`: https://github.com/JuliaData/DataFrames.jl/blob/40c368d02edea325bac3ca3a9ed3ed62e2e606d8/src/abstractdataframe/sort.jl#L474

```
julia> df = DataFrame(a = [1, 2], b = [3, 4]);

julia> sort(df, [:a, :b], by = (identity, identity))
2×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 3     │
│ 2   │ 2     │ 4     │
```

not sure if it matters, though.

**Comment by bkamins** [comment]
Yeah - we should fix it.
