### ISSUE TITLE
Immutable DataFrames

### ISSUE THREAD

**Issue by adkabo** [JuliaData/DataFrames.jl#2507]
Mutability can be convenient for editing values. On the other hand, in many cases, immutability can be safer, less confusing, and more performant.

For example, for a 3-column dataframe, a simple transformation gets a 20x speedup when I don't have to copy columns and a 100-column dataframe gets a 600x speedup. `copycols=true` needs to be the default for safety on mutable frames, but copying is unnecessary when the frame is immutable, 

How would you feel about having an immutable frame type which lacks the `!` functions and uses `copycols=false`? If both are supported, they might share a parent type.

```julia
df = DataFrame(rand(Float64, (3_000_000,100)))


julia> @benchmark transform(df, :x1 => ByRow(round) => :x0, copycols=true)
BenchmarkTools.Trial: 
  memory estimate:  2.26 GiB
  allocs estimate:  465
  --------------
  minimum time:     1.912 s (89.00% GC)
  median time:      1.974 s (88.63% GC)
  mean time:        2.075 s (84.10% GC)
  maximum time:     2.340 s (76.26% GC)
  --------------
  samples:          3
  evals/sample:     1

julia> @benchmark transform(df, :x1 => ByRow(round) => :x0, copycols=false)
BenchmarkTools.Trial: 
  memory estimate:  22.91 MiB
  allocs estimate:  265
  --------------
  minimum time:     2.873 ms (6.88% GC)
  median time:      3.104 ms (7.96% GC)
  mean time:        3.189 ms (8.63% GC)
  maximum time:     5.308 ms (7.41% GC)
  --------------
  samples:          1566
  evals/sample:     1




julia> @benchmark transform(df, :x1 => ByRow(round) => :x0, copycols=true)
BenchmarkTools.Trial: 
  memory estimate:  91.56 MiB
  allocs estimate:  61
  --------------
  minimum time:     58.001 ms (85.34% GC)
  median time:      59.741 ms (84.97% GC)
  mean time:        60.451 ms (85.22% GC)
  maximum time:     73.418 ms (86.46% GC)
  --------------
  samples:          83
  evals/sample:     1

julia> @benchmark transform(df, :x1 => ByRow(round) => :x0, copycols=false)
BenchmarkTools.Trial: 
  memory estimate:  22.89 MiB
  allocs estimate:  55
  --------------
  minimum time:     2.759 ms (8.23% GC)
  median time:      3.070 ms (8.18% GC)
  mean time:        3.155 ms (9.80% GC)
  maximum time:     43.789 ms (93.32% GC)
  --------------
  samples:          1583
  evals/sample:     1
```

**Comment by bkamins** [comment]
This is indeed a valid use case, and there exist separate packages that provide this, e.g. [TypedTables.jl](https://github.com/JuliaData/TypedTables.jl). DataFrames.jl will remain type-unstable and mutable, as this is the use case against which DataFrames.jl is designed.

**Comment by quinnj** [comment]
Isn't this just a use-case for `transform!`, i.e. the "mutating" version, which would imply `copycols=false`?

**Comment by adkabo** [comment]
The goal is not updating the dataframe in place (`transform!`), but rather returning a new dataframe containing most of the same columns (not copied), with some columns replaced. 

Most pure functions don't need to deep-copy their arguments. Why in this case is there a `copycols` parameter?

**Comment by bkamins** [comment]
The case is exactly as you have said - create a new data frame reusing columns. This behaviour was causing a lot of bugs in user code and that is why it is not the default.
