### ISSUE TITLE
create maprow to be complementary with mapcol

### ISSUE THREAD

**Issue by ppalmes** [JuliaData/DataFrames.jl#2510]
mapcol is useful to do some feature summary and transformations which returns a dataframe. there is no maprow counterpart that can be used for row-wise operations returning a dataframe.

**Comment by nalimilan** [comment]
Since DataFrames are considered as collections of rows, `map` would be the right function if we wanted to add this feature.

**Comment by bkamins** [comment]
This is tracked in https://github.com/JuliaData/DataFrames.jl/issues/2053 so I am closing this.
