### ISSUE TITLE
Improve inline documentation of select to include examples of multiple columns not to be included

### ISSUE THREAD

**Issue by ppalmes** [JuliaData/DataFrames.jl#2513]
- provide examples of `select(df, Not([:col1, :col2, ...]))` to have multiple columns excluded

**Comment by bkamins** [comment]
We have a very similar example in https://github.com/JuliaData/DataFrames.jl/blob/master/docs/src/man/getting_started.md already (with a regular expression not a vector, but this is the same).

Also `Not` is already documented in InvertedIndices.jl.

Still, if you think it would be useful to make this specific example - just please propose a PR. Probably it best fits https://github.com/JuliaData/DataFrames.jl/blob/master/docs/src/man/getting_started.md.

**Comment by bkamins** [comment]
This is covered in basics.md
