### ISSUE TITLE
Consider include index methods similar to set_index, reset_index and reindex, similar to pandas

### ISSUE THREAD

**Issue by lucascr91** [JuliaData/DataFrames.jl#2517]
I like the whole set of index methods in pd (set_index, reset_index, and reindex). They are convenient and simple. For example, if I want a table in latex with a statistic from groups I just type `df.groupby("species").agg({k:mean for k in ["petal_length", "petal_width"]}.to_latex()` or if I want to compute the % in columns I will just iterate over columns in `100*df.col=df.col/df.col.sum()` after run `df.set_index("species")`. In both cases, DataFrames.jl will treat species as a regular column which create an undesired output in first operation and simply don't work in the second.

I also like `reindex` in pandas that allows me to set a desired order in rows after a `groupby` operation, for example.

It would be nice to have the option of use index in julian DFs like in pandas

**Comment by bkamins** [comment]
Thank you for opening an issue, as indeed it is best to discuss it here.

What I am not clear, as asked on SO, what you would like to get that `groupby` does not offer you?

In particular:

> `df.groupby("species").agg({k:mean for k in ["petal_length", "petal_width"]}.to_latex()`

is just:
```
combine(groupby(df, "species"), ["petal_length", "petal_width"] .=> mean)
```
(but maybe you expect some other result - if so please comment)

> `100*df.col=df.col/df.col.sum()` after run `df.set_index("species")`

is just (I assume you misplaced `100`?):
```
transform(groupby(df, "species"), "col" => (x -> 100 * x ./ sum(x)) => "col%")
```

> I also like `reindex` in pandas that allows me to set a desired order in rows

1. you can index into `GroupedDataFrame` to change the order of groups in it (you can eg. write `gdf = groupby(df, "col"); gdf[length(gdf):-1:1]` to reverse the order of groups)
2. you can also just run `sort!(df, "colname)` which does sort in-place

**Comment by lucascr91** [comment]
Ok. Thanks for the kind answer. I think I'm too influenced by pandas way of think. You have presented a _de facto_ equivalent syntax in julia. In particular, I wasn't aware of `transform` function.

**Comment by bkamins** [comment]
So the limitation to keep in mind is that index of `GroupedDataFrame` in DataFrames.jl must be a column of a parent data frame, while in pandas it does not have to be. But I hope this is not a very significant limitation.
