### ISSUE TITLE
Sync tests with Tables 1.2

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2529]
Some tests are broken under Tables.jl 1.2.
This also means that Tables.jl dependency should be bumped.

I will open a PR when I finish updating it.

**Comment by bkamins** [comment]
Here is an interesting case:
```
julia> function f()
       df = DataFrame()
       res = [1, "1"]
       select(df, [] => ByRow(() -> res) => AsTable)
       end
f (generic function with 1 method)

julia> f()
0×0 DataFrame

julia> df = DataFrame()
0×0 DataFrame

julia> res = [1, "1"]
2-element Array{Any,1}:
 1
  "1"

julia> select(df, [] => ByRow(() -> res) => AsTable)
ERROR: ArgumentError: type does not have a definite number of fields

julia> const res2 = [1, "1"]
2-element Array{Any,1}:
 1
  "1"

julia> select(df, [] => ByRow(() -> res2) => AsTable)
0×0 DataFrame
```

**Comment by nalimilan** [comment]
Why does the `const` make a difference here?

**Comment by bkamins** [comment]
because with `const` type inference works and gives a more precise `eltype` of a produced vector. Without `const` the output vector has `eltype` `Any` and `Any` does not produce a proper schema in Tables.jl.
