### ISSUE TITLE
Register 0.22.0 release

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2539]
@JuliaRegistrator register

**Comment by bkamins** [comment]
@JuliaRegistrator register

**Comment by bkamins** [comment]
@DilumAluthge - dyou have an idea why JuliaRegistrator is not triggered?

(I also tried commit https://github.com/JuliaData/DataFrames.jl/commit/ff9577ecb551a33c521a934a6b88a10bb2949e77#commitcomment-44184790 and it was also not triggering anything)

CC @nalimilan

**Comment by ronisbr** [comment]
Something seems down, there is one person also complaining in Slack.

**Comment by bkamins** [comment]
@JuliaRegistrator register

**Comment by bkamins** [comment]
I used JuliaHub.jl in the end.
