### ISSUE TITLE
Final ellipsis appears on next row

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/DataFrames.jl#2544]
I've just spotted a small bug which happens only under certain circumstances: the final ellipsis of the row appears on the next row because there are too many characters to fit on screen. A reproducer is
```julia
DataFrame(rand(["dddddffffffffffffddddda", "bbbbbdfffffffffffbfffffffffffffbbbb"], 100, 100))
```
(Yes, I know that constructor is deprecated... :-p)

See screenshot:
![image](https://user-images.githubusercontent.com/1120448/99198143-f1308a80-2796-11eb-8303-6caddf72c47e.png)

Cc: @ronisbr @bkamins

**Comment by bkamins** [comment]
We had this problem in legacy printing. We solved it by deducing 1 from horizontal width.

**Comment by bkamins** [comment]
@ronisbr - as agreed earlier I mark all display related issues with `display` badge so that you can easily find and manage them. Thank you!

**Comment by ronisbr** [comment]
Ok! I found a problem with the cropping mechanism together with a maximum size of the column. This is a bug in PrettyTables.jl. I will try to fix now.

**Comment by ronisbr** [comment]
The bug will be fixed as soon as PrettyTables.jl v0.10.1 is release. I am just waiting for the next iteration of the registration bot. Sorry about that!

<img width="1005" alt="Captura de Tela 2020-11-15 às 20 11 59" src="https://user-images.githubusercontent.com/1068295/99199566-d225fe80-277e-11eb-8408-19b91d90cabd.png">

**Comment by ronisbr** [comment]
What a mess a `-1` can do :D https://github.com/ronisbr/PrettyTables.jl/commit/44ee6b5c7c74a9ed841c0f8f715372706d680a90

**Comment by ronisbr** [comment]
Done! Can I close the issue?

**Comment by bkamins** [comment]
It is good now.

**Comment by nalimilan** [comment]
Perfect, thanks!
