### ISSUE TITLE
clarify the interface for crossjoin when makeunique=true

### ISSUE THREAD

**Issue by mkarikom** [JuliaData/DataFrames.jl#2545]
In the [docs](https://dataframes.juliadata.org/stable/lib/functions/#DataFrames.crossjoin) we have the language:

> join is performed recursively with left associativity

This implies but does not explicitly state that when makeunique=true:
```
df1=DataFrame(c1=[a],c2=[a]);df2=DataFrame(c2=[c],c1=[d])
df_crossjoin = crossjoin(df1,df2,makeunique=true)
names(df_crossjoin) = [c1,c2,c2_2,c1_2]
 ```
In other words the order of the columns is fully specified by the order of the input dataframes and their respective columns, Is this assumption correct?

**Comment by bkamins** [comment]
Yes:
```
julia> using DataFrames

julia> df1=DataFrame(c1=1,c2=2);

julia> df2=DataFrame(c1=3,c2=4);

julia> df3=DataFrame(c1=5,c2=6);

julia> crossjoin(df1, df2, df3, makeunique=true)
1×6 DataFrame
 Row │ c1     c2     c1_1   c2_1   c1_2   c2_2
     │ Int64  Int64  Int64  Int64  Int64  Int64
─────┼──────────────────────────────────────────
   1 │     1      2      3      4      5      6
```

If you have a suggestion how the docstring can be improved please open a PR.
