### ISSUE TITLE
Two small typos in docs

### ISSUE THREAD

**Issue by roualdes** [JuliaData/DataFrames.jl#2550]
1. There is a missing period, to end the sentence, immediately following the only right parenthesis of the paragraph beginning with `DataFrameRow` in the Type hierarchy design section of the [Types page](https://dataframes.juliadata.org/stable/lib/types/).

2. In the paragraph beginning with "All these functions take a specification" on the [The Split-Apply-Combine Strategy page](https://dataframes.juliadata.org/stable/man/split_apply_combine/), and within the second item of the ordered list, the phrase "which can be a any valid column selector" should not include the article a and should be changed to "which can be any valid column selector."

I'm happy to submit a PR for these, if that's easier for you.  Just let me know.

Thanks for such great documentation.

**Comment by bkamins** [comment]
If you would be willing to it would be easiest to review if you made a PR. I am not a native speaker, so usually @nalimilan is also involved 😄. Thank you!

**Comment by roualdes** [comment]
Great.  Just submit PR #2551.  Thanks.
