### ISSUE TITLE
ComposedFunction not found on julia 1.5.3

### ISSUE THREAD

**Issue by floswald** [JuliaData/DataFrames.jl#2562]
hey, 

trying to use latest release on julai 1.5.3:

```
 Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
ERROR: LoadError: LoadError: UndefVarError: ComposedFunction not defined
Stacktrace:
 [1] top-level scope at /Users/74097/.julia/packages/DataFrames/Zx5mm/src/other/utils.jl:82
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include at ./Base.jl:368 [inlined]
 [4] include(::String) at /Users/74097/.julia/packages/DataFrames/Zx5mm/src/DataFrames.jl:1
 [5] top-level scope at /Users/74097/.julia/packages/DataFrames/Zx5mm/src/DataFrames.jl:94
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:467
 [11] top-level scope at ./none:3
in expression starting at /Users/74097/.julia/packages/DataFrames/Zx5mm/src/other/utils.jl:79
in expression starting at /Users/74097/.julia/packages/DataFrames/Zx5mm/src/DataFrames.jl:94

(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [c52e3926] Atom v0.12.21
  [a93c6f00] DataFrames v0.22.1
  [e5e0dc1b] Juno v0.8.3
  [91a5bcdd] Plots v1.6.2

```

I checked in the `project.toml` and it should work with any julia version +1?

**Comment by bkamins** [comment]
The problem is that you are using Atom which is unmaintained and mixes up the packages loaded. Please check if the problem persists if you use VS Code (the currently maintained IDE for Julia), Jupyter Notebook, or just a terminal on a fresh environment.

If you keep having this problem can you please report and I will re-open the issue?

**Comment by floswald** [comment]
that was a terminal window. are you saying that i need to uninstall the Atom.jl package?

**Comment by bkamins** [comment]
please check in terminal window:
1) start Julia in an empty folder
2) go to package manager mode
3) write `activate .`
4) write `add DataFrames`
5) leave package manager
6) write `using DataFrames`

and please let me know if things work. If they work it means that you have something messed up in the default project (and it is likely that if you remove Atom.jl and `up` other packages things will work).

**Comment by jolars** [comment]
I was getting this error with VS code too, but it worked fine when I run Julia from the terminal. Removing `Atom.jl` (and maybe `Juno.jl`) and updating etc seems to have solved the issue.
