### ISSUE TITLE
:auto does not work in DataFrame()

### ISSUE THREAD

**Issue by Jdbeck66** [JuliaData/DataFrames.jl#2565]
I tried to run the example from the documentation - `DataFrame([1 0; 2 0], :auto)` and this does not work. Error message is below. This code `DataFrame("A" => [1,2], "B" => [true, false], "C" => ['a', 'b'])` works fine. 

Error Message -

`MethodError: no method matching DataFrames.DataFrame(::Array{Int64,2}, ::Symbol)
Closest candidates are:
DataFrames.DataFrame(::AbstractArray{T,2} where T) at /Users/jimbeck/.julia/packages/DataFrames/GtZ1l/src/dataframe/dataframe.jl:267
DataFrames.DataFrame(::AbstractArray{T,2} where T, !Matched::AbstractArray{Symbol,1}; makeunique) at /Users/jimbeck/.julia/packages/DataFrames/GtZ1l/src/dataframe/dataframe.jl:267
DataFrames.DataFrame(::AbstractArray{T,2} where T, !Matched::AbstractArray{var"#s40",1} where var"#s40"<:AbstractString; makeunique) at /Users/jimbeck/.julia/packages/DataFrames/GtZ1l/src/dataframe/dataframe.jl:272
...
top-level scope@Local: 1[inlined]`

**Comment by bkamins** [comment]
Please update your DataFrames.jl installation to 0.22 version. You on an older version of DataFrames.jl in this project.

**Comment by Jdbeck66** [comment]
I had a dependency that prevented the update - thanks - FYI Lathe and or GLM currently depended on 0.21.8.

**Comment by bkamins** [comment]
Thank you!

See https://github.com/emmettgb/Lathe.jl/issues/56 for Lathe.jl. GLM.jl does not depend on DataFrames.jl 0.22 (only tests depend but this should not affect you).
