### ISSUE TITLE
How to cite this package?

### ISSUE THREAD

**Issue by stevengogogo** [JuliaData/DataFrames.jl#2568]
Dear Developers,

Wonderful work!

I'm currently using this package for my thesis about modeling a biological systems, and preparing for publication. Hence, I'd like to know how to cite the package in my paper.

My manuscript is written in Latex, so I'll be glad if you provide the citation in `.bib` format.

Thank you.

Shao-Ting Chiu

**Comment by bkamins** [comment]
You can use this https://zenodo.org/record/4282946#.X8ThWWhKibg.

At some point probably it would be good to submit something to J. Stat. Soft.

**Comment by aramirezreyes** [comment]
Maybe this should be noted in the readme for discoverability? https://github.com/JuliaData/DataFrames.jl/pull/3297

**Comment by juliohm** [comment]
Exactly, it is missing in the README and in the docs @bkamins . We are citing it now too and had trouble finding the reference.

**Comment by bkamins** [comment]
OK - I merged https://github.com/JuliaData/DataFrames.jl/pull/3297
