### ISSUE TITLE
DataAPI.describe argument passing function pair throws error

### ISSUE THREAD

**Issue by seetheforest** [JuliaData/DataFrames.jl#2577]
If I follow the commands in the DataAPI.describe function documentation, my REPL of Julia throws an error.  I'm not too experienced with Julia/programming so it could be my fault.

This works:
`df = DataFrame(i=1:10, x=0.1:0.1:1.0, y='a':'j');`

This works:
`describe(df, :min, :max)`

This throws an error:
`describe(df, :min, sum => :sum)`

> describe(df, :min, sum => :sum)
ERROR: MethodError: no method matching describe(::DataFrame, ::Symbol, ::Pair{typeof(sum),Symbol})
Closest candidates are:
  describe(::AbstractDataFrame, ::Union{Symbol, Pair{var"#s38",B} where B where var"#s38"<:Union{AbstractString, Symbol}}...; cols) at /Users/andrew/.julia/packages/DataFrames/cdZCk/src/abstractdataframe/abstractdataframe.jl:537
  describe(::AbstractDataFrame; cols) at /Users/andrew/.julia/packages/DataFrames/cdZCk/src/abstractdataframe/abstractdataframe.jl:540
Stacktrace:
 [1] top-level scope at REPL[12]:1

Thanks for your help with Julia.  It's a really nice tool.

**Comment by bkamins** [comment]
Please update DataFrames.jl to version 0.22. You are on an older version of DataFrames.jl which does not support this syntax yet.
