### ISSUE TITLE
combine function failed to return mutliple columns

### ISSUE THREAD

**Issue by 1991jhf** [JuliaData/DataFrames.jl#2580]
when i run the Iris example in the documentation:

gdf = groupby(iris, :Species)
combine(gdf, :PetalLength => (x -> [extrema(x)]) => [:min, :max])

I get following error:
ERROR: ArgumentError: Unrecognized column selector: :PetalLength => (var"#208#209"() => [:min, :max])

**Comment by bkamins** [comment]
I have just checked and it works. Have you checked that you are using the version of documentation that matches the version of DataFrames.jl you have installed? The documentation you use is for DataFrames.jl 0.22.

You can check it by running:
```
(@v1.5) pkg> st DataFrames
Status `~/.julia/environments/v1.5/Project.toml`
  [a93c6f00] DataFrames v0.22.1
```
