### ISSUE TITLE
Speed-up groupby of integer columns

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2590]
Currently we have the following:
```
julia> df = DataFrame(x=rand(1:10^4, 10^6));

julia> df.y = categorical(df.x);

julia> @btime groupby($df, :x);
  11.363 ms (31 allocations: 23.26 MiB)

julia> @btime groupby($df, :y);
  1.414 ms (57 allocations: 7.83 MiB)
```

However, we could calculate `extrema` of integer columns and if they are "narrow"-enough we could treat such a column like we treat categorical columns in grouping.

@nalimilan - what do you think?

It should be done in a way that both `groupby` and `join` can take advantage of it.

**Comment by nalimilan** [comment]
Yes I think we discussed this in the past. It should be quite easy to do.

**Comment by bkamins** [comment]
@nalimilan - this is done - right?

**Comment by nalimilan** [comment]
Yes!
