### ISSUE TITLE
Performance cliff in `groupby`

### ISSUE THREAD

**Issue by yurivish** [JuliaData/DataFrames.jl#2591]
I noticed that `groupby` has surprising performance when used on a `String` column of unique values – it takes over 8x as long to group 16.7 million elements as it does to group 16 million elements.

As a minimal example, here are some timings on a `DataFrame` with 16.7 unique `Strings`:

```julia
julia> using DataFrames

julia> df = DataFrame(value=[string(i) for i in 1:16_700_000]);
```

Here are `groupby` timings on sequentially increasing subsets of the data:

```julia
julia> let sub_df = df[1:1_000_000, :]
        @time groupby(sub_df, :value) # warmup
       end;
  0.518480 seconds (839.81 k allocations: 65.423 MiB)

julia> let sub_df = df[1:1_000_000, :]
        @time groupby(sub_df, :value)
       end;
  0.067117 seconds (31 allocations: 23.261 MiB)

julia> let sub_df = df[1:2_000_000, :]
        @time groupby(sub_df, :value)
       end;
  0.277287 seconds (31 allocations: 46.520 MiB)

julia> let sub_df = df[1:4_000_000, :]
        @time groupby(sub_df, :value)
       end;
  1.097153 seconds (31 allocations: 93.037 MiB, 38.14% gc time)

julia> let sub_df = df[1:8_000_000, :]
        @time groupby(sub_df, :value)
       end;
  1.657669 seconds (31 allocations: 186.073 MiB)

julia> let sub_df = df[1:16_000_000, :]
        @time groupby(sub_df, :value)
       end;
  3.870164 seconds (31 allocations: 372.143 MiB)

julia> let sub_df = df[1:16_700_000, :]
        @time groupby(sub_df, :value)
       end;
 35.768592 seconds (31 allocations: 382.824 MiB, 1.24% gc time)
```

The timings increase gradually with the number of elements but somewhere around 16.7 million datapoints the growth really spikes.

Here is a Pluto [notebook](https://gist.github.com/yurivish/98c5017a27ed8b23ee22c994d66c19bd) that reproduces the issue and makes the following plot:

![image](https://user-images.githubusercontent.com/114388/103714319-6432d200-4f8c-11eb-92f3-e878a1bf8166.png)

```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by bkamins** [comment]
The problem is with line https://github.com/JuliaData/DataFrames.jl/blob/main/src/dataframerow/utils.jl#L124. In certain cases `sz` is set to a too small value and we are creating too many collisions. We should probably change the rule we use to set `sz`.

**Comment by bkamins** [comment]
Actually the same problem is in Julia Base but less problematic:
```
julia> @time Set(df.value[1:16_700_000]);
  5.968966 seconds (15 allocations: 559.412 MiB)

julia> @time Set(df.value[1:16_800_000]);
  4.068847 seconds (10 allocations: 416.174 MiB, 13.53% gc time)
```

**Comment by bkamins** [comment]
@nalimilan - do we rely on the size of `gslots` anywhere to be what is returned by `Base._tablesz`? Maybe we should just set the size of `gslots` to be `3/2` of the `length(rhashes)`? (it seems to be a standard recommendation - but it would have to be investigated as maybe it is too much?)

**Comment by nalimilan** [comment]
I have no idea of what are the best rules to choose the size of the table, but we could certainly be a bit more generous. Anyway we already allocate more slots than rows by default, contrary to `Dict`, so allocating a bit more wouldn't be a radical change. Do you have any idea why the slowdown is much bigger with our code than with `Dict`?

This code was written by @alyst, maybe he has ideas.

**Comment by bkamins** [comment]
I know why we are worse. We are allocating only 2^n sizes. And when we are close to 2^n but a bit below we have a lot of hash conflicts.

The reason why `Dict` is faster is because it is more generous and makes sure there are enough empty slots when it is grown. I will propose a change to the code then.

**Comment by nalimilan** [comment]
Is `Dict` really more generous? From a quick look I got the impression that when it needs to grow it uses `Base._tablesz(length(d.keys))`, which is always lower than our size since we use the total number of rows while they use the number of groups. Did I get this wrong?

**Comment by bkamins** [comment]
It is only in `reshash!`, but rehash is called with:
```
    rehash!(h, h.count > 64000 ? sz*2 : sz*4)
```
where did you get `Base._tablesz(length(d.keys))`?

**Comment by nalimilan** [comment]
Ah, OK, I was only looking at the default value:
https://github.com/JuliaLang/julia/blob/9f8bdc2645cac4abf5143bf6f8b59577b3a79435/base/dict.jl#L175

That makes sense. So `Dict` has indeed a low risk of collisions since it allocates a lot of extra slots when the table is full. Our approach also typically has very few collisions as long as there are at last about 2 rows per group on average; but below that threshold the situation can get quite bad. We probably shouldn't optimize too much this very peculiar case, but allocating more slots than rows make sense if that can limit the problem. Your suggestion is to allocate 25% more slots than rows?

**Comment by bkamins** [comment]
It seems it can be even less like 1.125, 1.25 would be super safe (and targeting an unlikely case).

So we could take:
```
sz = Base._tablesz((length(rhashes)*9) >> 3)
```

**Comment by nalimilan** [comment]
OK then maybe go with 1.125 if benchmarks are reasonable.

**Comment by alyst** [comment]
I'm not sure I could be of great help here, also since I wrote it some time ago. I recall I was following `Dict` code quite closely. But most likely `Dict` was improving over time, so its performance was tuned. Anyway, :+1: for your work on fixing the issue :)
