### ISSUE TITLE
[BUG] names Function Not Returning an Array of Strings

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaData/DataFrames.jl#2606]
Hi JuliaData,

Thanks for the wonderful package! Use it daily at work. :smile: 

I recently was trying to get the names of each of my columns as strings by using the `names` function. Instead, it is returning an array of `Array{Symbol, 1}` which is the exact same return I get from `propertynames`. Any thoughts as to why this is happening?

I am using Julia 1.5.3 and DataFrames.jl version 0.20.2

**Comment by bkamins** [comment]
You are using 0.20.2 release, while the current release is already 0.22.3. Please update DataFrames.jl and `names` will return what you want.

**Comment by TheCedarPrince** [comment]
Ah! I was deceived! I had updated before opening the issue, but looking back on my environment, I had a package conflict which was not showing up until I tried to install the latest version. Thanks @bkamins! Take care!
