### ISSUE TITLE
Add `after` keyword argument to `insertcols!`

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaData/DataFrames.jl#2613]
Currently you have to do this if you want to insert columns after a certain column:

```julia
df = DataFrame(a=1:2, b=3:4, c=5:6)
i = findfirst(==(:b), propertynames(df))
insertcols!(df, i+1, :x => 7:8)
```

It would be nice if there were a boolean keyword argument `after` which defaults to `false`.

**Comment by bkamins** [comment]
Note that you can just write `columnindex(df, :b) + 1`. Other than that it could be added in the future.

**Comment by pdeffebach** [comment]
Re-ordering data more broadly is something Stata does really well. An `after` keyword is used heavily there.
