### ISSUE TITLE
Conditions of the query

### ISSUE THREAD

**Issue by Jianqing001** [JuliaData/DataFrames.jl#2618]
If df has columns A, B, and C, and I want to find the value in column A that is equal to 2 and in column B that is equal to 1, and assign it to 0, what do I do?

**Comment by bkamins** [comment]
Can you give an example of an input and output you want as currently it is not fully clear what you need.

Also consider asking questions on https://stackoverflow.com/questions/tagged/julia or https://discourse.julialang.org/ as GitHub is mostly intended for tracking bugs and feature requests. Thank you!

**Comment by Jianqing001** [comment]
Here is an example of an implementation in Python

I want to achieve the same effect in Julia and screen out the data with df.Sex==”female“ and df.Age is null

data：Titanic.csv

df=pd.read_csv("E:\\Study\\Titanic.csv")

input:    df.info()

output: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

input:       df[df.Sex=="female"][df.Age.isnull()]

output:

PassengerId | Survived | Pclass | Name | Sex | Age | SibSp | Parch | Ticket | Fare | Cabin | Embarked
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
19 | 20 | 1 | 3 | Masselmani, Mrs. Fatima | female | NaN | 0 | 0 | 2649 | 7.2250 | NaN | C
28 | 29 | 1 | 3 | O'Dwyer, Miss. Ellen "Nellie" | female | NaN | 0 | 0 | 330959 | 7.8792 | NaN | Q
31 | 32 | 1 | 1 | Spencer, Mrs. William Augustus (Marie Eugenie) | female | NaN | 1 | 0 | PC 17569 | 146.5208 | B78 | C
32 | 33 | 1 | 3 | Glynn, Miss. Mary Agatha | female | NaN | 0 | 0 | 335677 | 7.7500 | NaN | Q
47 | 48 | 1 | 3 | O'Driscoll, Miss. Bridget | female | NaN | 0 | 0 | 14311 | 7.7500 | NaN | Q
......

**Comment by bkamins** [comment]
Do:
```
df[ismissing.(df.Age) .& (df.Sex .== "female"), :]
```
or
```
filter(row -> ismissing(row.Age) && row.Sex == "female", df)
```
or
```
filter([:Age, :Sex] => (x,y) -> ismissing(x) && y == "female", df)
```
or (if you want to use development version, the function will be available in the next release):
```
subset(df, :Age => ismissing, :Sex => ==("female"))
```
