### ISSUE TITLE
combine and select without arguments

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2620]
Currently we have that:
* `combine(::AbstractDataFrame)`
* `combine(::GroupedDataFrame)`
* `select(::AbstractDataFrame)`
* `select(::GroupedDataFrame)`

return an empty result, except the last one which returns a copy of the original data frame. This is consistent, but at least for `combine` not very useful. We could discuss what to do in these cases.

**Comment by nalimilan** [comment]
See #2633.
