### ISSUE TITLE
Promote Documentation on Working with Data Frames

### ISSUE THREAD

**Issue by jessebett** [JuliaData/DataFrames.jl#2623]
The [Working with Data Frames](https://dataframes.juliadata.org/v0.17.0/man/getting_started.html#Working-with-Data-Frames-1) sub-section of the documentation contains important sub-sub-sections.

However, these are very difficult to discover because the left menu navigation bar does not display down to the sub-sub-section. 

Consider removing the Working with Data Frames section and promoting the sub sections so they can appear in the menu.

**Comment by bkamins** [comment]
Thank you for reporting this. I will announce today on Slack a call for proposal to re-organize DataFrames.jl manual.

**Comment by bkamins** [comment]
https://discourse.julialang.org/t/call-for-proposals-dataframes-jl-documentation/55418
