### ISSUE TITLE
Should be possible to pass names to the matrix constructor

### ISSUE THREAD

**Issue by alexlenail** [JuliaData/DataFrames.jl#2629]
Hello, 
I'm coming from pandas, please excuse me if I'm off here: 

In pandas: 
```
df = pd.DataFrame([[1, 2],[3, 4]], index=['a','b'], columns=['c', 'd'])
```
In DataFrames.jl:
```
df = DataFrame([[1, 2],[3, 4]])
rename!(df2, ["c", "d"])
```
What I'd like from DataFrames.jl: 
```
df = DataFrame([[1, 2],[3, 4]], columns=['c', 'd'])
```
What I'd like even more: 
```
df = DataFrame([[1, 2],[3, 4]], index=['a','b'], columns=['c', 'd'])
```

**Comment by bkamins** [comment]
Your question raises several issues:

1. This is supported:
```
julia> DataFrame([[1, 2],[3, 4]], ["c", "d"])
2×2 DataFrame
 Row │ c      d     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      3
   2 │     2      4
```
2. `[[1, 2],[3, 4]]` is a vector of vectors, not a matrix (but in this case this does not matter)

3. The syntax you use in `DataFrame([[1, 2],[3, 4]])` is deprecated (you will get a warning if you start Julia with `--depwarn=yes
`) you have to add `:auto` as a second argument if you want auto generated column names

4. To get fast indexing of rows in `DataFrame` you have to `groupby` it (and then indexing is fast in all cases - not like in pandas when it is slow if index contains duplicates)
```
julia> df = DataFrame(idx=["A", "A", "B", "B", "B"])
5×1 DataFrame
 Row │ idx    
     │ String 
─────┼────────
   1 │ A
   2 │ A
   3 │ B
   4 │ B
   5 │ B

julia> gdf = groupby(df, :idx)
GroupedDataFrame with 2 groups based on key: idx
First Group (2 rows): idx = "A"
 Row │ idx    
     │ String 
─────┼────────
   1 │ A
   2 │ A
⋮
Last Group (3 rows): idx = "B"
 Row │ idx    
     │ String 
─────┼────────
   1 │ B
   2 │ B
   3 │ B

julia> gdf[("A",)] # this is fast
2×1 SubDataFrame
 Row │ idx    
     │ String 
─────┼────────
   1 │ A
   2 │ A
```

**Comment by alexlenail** [comment]
Thanks for your thorough answer, @bkamins 

One follow up: In pandas, the keyword argument `index=['a','b']` isn't so much for indexing as it is just for just labeling the rows. How do you label the rows with given names (rather than simple integers) in DataFrames.jl?

**Comment by bkamins** [comment]
You do not have an option to label rows. What you can do is either:
*  add a column with row labels
* use e.g. https://github.com/mcabbott/AxisKeys.jl instead (this is a more general solution scaling to arbitrary number of dimensions)
