### ISSUE TITLE
Follow Julia 1.7 broadcasting rules

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2643]
see https://github.com/JuliaLang/julia/pull/39859

We have to decide what to do with:
```
julia> df = DataFrame(a=1:3)
3×1 DataFrame
 Row │ a     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2
   3 │     3

julia> x = zeros(3)
3-element Vector{Float64}:
 0.0
 0.0
 0.0

julia> x .= df
3-element Vector{Float64}:
 1.0
 2.0
 3.0

julia> df[!, 1] .= df
ERROR: DimensionMismatch("cannot broadcast a data frame into 1 dimensions")
```

**Comment by bkamins** [comment]
@nalimilan - do you think we should only fix the tests or allow `df[!, 1] .= df` if `df` has one column?

**Comment by nalimilan** [comment]
I'd keep throwing an error. I don't see a strong reason this pattern would be useful, and as you noted at JuliaLang/julia#39859 we are a bit stricter than arrays since data frames are always 2D.

**Comment by bkamins** [comment]
OK - so I will just fix tests.
