### ISSUE TITLE
add predicate/transformation version of unique?

### ISSUE THREAD

**Issue by pcjentsch** [JuliaData/DataFrames.jl#2651]
This issue is a place for continuing discussion of additional `unique` methods that accept predicates for comparing rows.

A simple way would be to follow `Base.unique(f, iter)`, which simply maps columns, and then checks for equality with `isequal`. 

Another would to specify an equivalence relation that accepts two rows as an argument and returns whether they are equivalent.

**Comment by bkamins** [comment]
I think we already support it:
```
julia> df = DataFrame(a=1:10, b=10:-1:1)
10×2 DataFrame
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1     10
   2 │     2      9
   3 │     3      8
   4 │     4      7
   5 │     5      6
   6 │     6      5
   7 │     7      4
   8 │     8      3
   9 │     9      2
  10 │    10      1

julia> unique(df, [:a, :b] => (a,b) -> a .+ b)
1×2 DataFrame
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1     10
```

Is this enough for you? If yes please close the issue.

**Comment by pcjentsch** [comment]
ah, nice!

**Comment by bkamins** [comment]
We need to update the docsting though so I will keep it open. Thank you for reporting

**Comment by MatthewRGonzalez** [comment]
The [documentation](https://dataframes.juliadata.org/stable/lib/functions/#Base.unique) for `unique` indicates, "cols can be any column selector or transformation accepted by select." 

In the following example,

```
julia> df = DataFrames.DataFrame(x=[1, 1, 3, 4], y=[2, 2, 6, 8])
4×2 DataFrame
 Row │ x      y     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     1      2
   3 │     3      6
   4 │     4      8

julia> unique(select(df, :x => (x -> (0 .* x) .+ 3) => :x, :y => (y -> y .+ 1) => :y))
3×2 DataFrame
 Row │ x      y     
     │ Int64  Int64 
─────┼──────────────
   1 │     3      3
   2 │     3      7
   3 │     3      9

julia> unique(df, :x => (x -> (0 .* x) .+ 3) => :x, :y => (y -> y .+ 1) => :y)
ERROR: MethodError: no method matching unique(::DataFrames.DataFrame, ::Pair{Symbol, Pair{var"#213#215", Symbol}}, ::Pair{Symbol, Pair{var"#214#216", Symbol}})
```
it appears that `unique` can only accept *one* selector or transformation. Is my understanding correct?
