### ISSUE TITLE
deprecate filter(:x => f, df)

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2654]
See discussion in https://github.com/JuliaData/DataFrames.jl/issues/2489#issuecomment-797502479.

I am in favor of deprecating it. The question is if we should keep `filter(::Function, :AbstractDataFrame)` or also deprecate it?

We should also check `GroupedDataFrame` case closely (but it seems it should be OK).

When we settle on the design I will implement it. I think we should also make a decision about `map` to resolve https://github.com/JuliaData/DataFrames.jl/issues/2053.

**Comment by nalimilan** [comment]
> I am in favor of deprecating it. The question is if we should keep `filter(::Function, :AbstractDataFrame)` or also deprecate it?

I think it's OK to keep it, that way we implement the collections interface.

**Comment by pdeffebach** [comment]
I think it's okay if we keep it as well. It's definitely weird to keep `filter(fun, df)` but not `filter(:x => fun, df)`. We should always allow `Pair`s where possible because of the performance hit.

**Comment by bkamins** [comment]
> We should always allow Pairs where possible because of the performance hit.

`subset` can be used with the same performance.

>  It's definitely weird to keep `filter(fun, df)`

That is why I asked. But if we add iteration protocol to data frame as proposed in #2662 then it is OK (as then we just follow Julia Base API in this case)

**Comment by pdeffebach** [comment]
I don't think we need to make a decision on iteration before 1.0.

The iterator as implemented in #2662 would be very un-performant. We've done fine so far not allowing iteration and our halfway stance on "A DataFrame is a collection of rows" has been good so far. 

And if we allow `filter(fun, df)` people *will* use it. But then if when they complain that DataFrames is slow, we have to tell them to use a different function entirely, `subset`, which would be a pain. Better to just tell them that if they want faster code they should do `filter(:x => fun, df)`.

**Comment by bkamins** [comment]
These were my original considerations when implementing `filter` in the first place, but it seems e.g. @andyferris feels that it is more important to have a consistent behavior. So we have a tension:
1. user-friendliness and a bit of inconsistency
2. consistency but lower discoverability for newcomers

(to be clear - I am OK to drop #2662 if we think that it would be too messy go that way)

**Comment by nalimilan** [comment]
Yes, implementing the collection interface with slow methods has the potential of being a performance trap for users. Maybe in the not-too-distant future we will be able to fix this using a trick similar to what @andyferris mentioned recently (I lost the link): if we can inspect the function's code to detect which variables are used, we can pass it a small `NamedTuple` instead of a `DataFrameRow` and benefit from type stability.

**Comment by storopoli** [comment]
I've just received the github alert for a new version of DataFrames and I saw the deprecation in filter.

From the history that I've gathered so far,  `filter(:x => fun, df)` is better than `filter(fun, df)`?

Here is some benchmark (DataFrames version 0.22.6):

```julia
julia> using DataFrames

julia> df = DataFrame(x = [3, 1, 2, 1], y = ["b", "c", "a", "b"])
4×2 DataFrame
 Row │ x      y      
     │ Int64  String 
─────┼───────────────
   1 │     3  b
   2 │     1  c
   3 │     2  a
   4 │     1  b

julia> @btime filter(row -> row.x > 1, $df)
  1.178 μs (13 allocations: 1.25 KiB)
2×2 DataFrame
 Row │ x      y      
     │ Int64  String 
─────┼───────────────
   1 │     3  b
   2 │     2  a

julia> @btime filter(:x => x -> x > 1, $df)
  918.973 ns (13 allocations: 1.22 KiB)
2×2 DataFrame
 Row │ x      y      
     │ Int64  String 
─────┼───────────────
   1 │     3  b
   2 │     2  a
```

**Comment by bkamins** [comment]
@storopoli - hi. `fitler` is not deprecated. You probably saw a temporary autogenerated diff, which unfortunately GitHub makes incorrectly. I have already fixed this at https://github.com/JuliaData/DataFrames.jl/releases/tag/v0.22.6.

See also https://discourse.julialang.org/t/release-announcements-for-dataframes-jl/18258/124.

**Comment by storopoli** [comment]
Ok thanks for clarifying! Yes I saw the auto generated diff...
