### ISSUE TITLE
Vertical line still visible when row number disabled

### ISSUE THREAD

**Issue by tomyun** [JuliaData/DataFrames.jl#2673]
```julia
using DataFrames
df = DataFrame(a=[10,20], b=[30,40], c=[50,60])
```

```julia-repl
julia> show(df)
2×3 DataFrame
 Row │ a      b      c
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │    10     30     50
   2 │    20     40     60
```

When `show_row_number` is turned off, the first vertical line is still displayed.

```julia-repl
julia> show(df, show_row_number=false)
2×3 DataFrame
 a     │ b      c
 Int64 │ Int64  Int64
───────┼──────────────
    10 │    30     50
    20 │    40     60
```

What I expected was something like this.

```julia-repl
julia> show(df, show_row_number=false, vlines=:none)
2×3 DataFrame
 a      b      c
 Int64  Int64  Int64
─────────────────────
    10     30     50
    20     40     60
```

Tested with DataFrames 0.22.5.

**Comment by bkamins** [comment]
@ronisbr - is this a problem in PrettyTables.jl in general or only how you used it in DataFrames.jl? I assume it can be easily fixed - thank you!

**Comment by ronisbr** [comment]
Hi @tomyun and @bkamins ,

Actually it is expected. We are passing `vlines = [1]` which mean add a vertical line after the column 1. I have no idea if this should be changed in DataFrames.jl. To "fix" it, we need to check if `kwargs...` in `show` has `show_row_number = false` and, in this case, add `vlines = :none`. It is easy, but I am not sure if we should do it. What do you think @bkamins ?

**Comment by bkamins** [comment]
I think that what @tomyun asks for is what the users will expect - i.e. that the vertical line is only displayed if the "Row" column is displayed. If it is not displayed then the vertical line should not be present.

The rationale is that the vertical line is used to separate the contents of the data frame (to the right of it) from the row counter that is not a part of the data frame (to the left of it).

**Comment by ronisbr** [comment]
OK, so I will add a check to `kwargs...` and modify `vlines`.

**Comment by ronisbr** [comment]
Done!
