### ISSUE TITLE
tag a release containing #2656 to fix `combine` on Arrow-backed DataFrames?

### ISSUE THREAD

**Issue by jrevels** [JuliaData/DataFrames.jl#2689]
👋 

I have a [downstream CI breakage](https://github.com/beacon-biosignals/Onda.jl/pull/68#issuecomment-809862342) that appears to be fixed by this PR - would it be possible to get a new release tagged with this fix :)

Thanks!

**Comment by bkamins** [comment]
I do not think #2682 should fix anything in the package (what it only does is throwing an error in cases when earlier we allow some aggregations that are non-standard; of course I might be wrong). You could use git bisect to locate the actual commit that fixes your issue then we can analyze if it can be backported. However, I expect to have 1.0 release of DataFrames.jl in a few weeks, so maybe it is enough for you to wait and just use `main` temporarily?

**Comment by jrevels** [comment]
Good call, I was making a (poor) guess based on the stacktrace and most recent git blame in that file.

Looks like the commit that actually solves my problem is https://github.com/JuliaData/DataFrames.jl/commit/140a3e0247de209d261ca039cb7444e0f9744169 (xref #2656). 

It seems this commit cherry-picks nicely onto `v0.22_patches` without conflicts - is that where new releases are tagged from at the moment? If I opened a PR to that branch that cherry-picks that commit + bumps the Project.toml to `v0.22.7`, would that be something we could merge/tag? Happy to do so if that's sufficient 🙂 

IMO since this affects any DataFrames + Arrow 1.3 users it seems worthwhile to backport soon if it's easy to do so

**Comment by bkamins** [comment]
I am OK to cherry-pick https://github.com/JuliaData/DataFrames.jl/pull/2656 and make a patch release.

I can do it today if @nalimilan approves.

**Comment by bkamins** [comment]
Release done:
https://github.com/JuliaData/DataFrames.jl/commit/8ce6f5f2be74bbd03a703e66b4da686a0748ab89#commitcomment-48933330

**Comment by jrevels** [comment]
Woohoo, thanks!
