### ISSUE TITLE
describe(...,:eltype) takes forever to complete on categorical columns

### ISSUE THREAD

**Issue by pgagarinov** [JuliaData/DataFrames.jl#2693]
`describe` takes forever to complete when run on categorical columns of Union{Missing, String} type

Let us create a dataframe of random repeated strings.

```
using DataFrames, Random
rand_addresses = [randstring(20) for k in 1:6500];
data_mat=(rand([rand_addresses;missing],500000,30));
df = DataFrame(data_mat);
@time describe(df,:eltype);
`>  0.274541 seconds (813 allocations: 150.049 MiB)`
```
`@time collect(skipmissing(df.x1));`
`> 0.008496 seconds (20 allocations: 5.001 MiB)`

now let us make all columns categorical

`categorical!(df);`

and now this takes forever!:

`@time collect(skipmissing(df.x1));`

and as well as this:

`@time describe(df,:eltype);`

Julia 1.6
DataFrames v0.22.6

**Comment by pdeffebach** [comment]
Can you test whether `collect(skipmissing(x))` has different timing for categorical vs. non-categorical columns?

**Comment by pgagarinov** [comment]
@pdeffebach `@time collect(skipmissing(df.x1));` takes forever if x1 is a categorical column in the example above. For plain columns there is no such problem. But why does `@describe` have to call `collect` when I just request the element type? Isn't the element type known in advance?

**Comment by bkamins** [comment]
I think we should skip `collect` altogether.

**Comment by pdeffebach** [comment]
I think we need collect because a lot of the functions used allocate anyway, like `median`, we also calculate `last`, which needs a `Vector`. Plus we allow people to  use their own functions, and want things to "just work". 

We only do this is there are missing values, which is the case in your example.

**Comment by pdeffebach** [comment]
interesting! I can explore this in a PR.

**Comment by pdeffebach** [comment]
Regardless, this is still likely a CategoricalArrays bug, right? `collect(skipmissing(x))` should not be exceptionally slow.

**Comment by bkamins** [comment]
@pdeffebach - right, it has been fixed AFAICT

@pgagarinov 

Please update CategoricalArrays.jl and DataFrames.jl, currently you will see for your data:
```
julia> @time describe(df, :eltype);
  0.162089 seconds (813 allocations: 150.049 MiB, 4.00% gc time)

julia> @time describe(df, :eltype);
  0.136962 seconds (813 allocations: 150.049 MiB, 3.13% gc time)

julia> @time collect(skipmissing(df.x1));
  0.021541 seconds (630 allocations: 5.044 MiB, 76.99% compilation time)

julia> @time collect(skipmissing(df.x1));
  0.005248 seconds (20 allocations: 5.001 MiB)
```

**Comment by bkamins** [comment]
This is without the PR I am preparing. We have made a lot of such improvements with @nalimilan when working on faster joins as it turned out that it were the "pooled" vectors that were most offending performance-wise.

**Comment by nalimilan** [comment]
I also see this (after replacing deprecated calls with the new syntax). That's because `collect` ends up calling `push!` repeatedly, and it needs to check for each value whether the source pool is a subset of the destination pool. This is a known issue and the only solution is to have a global table indicating whether pools are subsets/supersets/equal (or maybe more simply in this case, storing the hash of the pool and comparing it). A workaround would be to add a special method for `collect(::SkipMissing{<:CategoricalArray}))`.

**Comment by bkamins** [comment]
It is strange I did not see this - maybe I did some mistake.

> `collect(::SkipMissing{<:CategoricalArray}))`

I would add it.

(I thought the issue was fixed 😄)

**Comment by bkamins** [comment]
@pgagarinov - also please note that `CategoricalVector` was not designed for a use case you describe. It is optimized for cases when the number of groups is small. Use `PooledVector` if you have very many (but still duplicated) unique values.

**Comment by pgagarinov** [comment]
> @pgagarinov - also please note that `CategoricalVector` was not designed for a use case you describe. It is optimized for cases  when the number of groups is small. Use `PooledVector` if you have very many (but still duplicated) unique values.
Unfortunately,  I don't have a choice - I want columns with repeated values one hot encoded for the gradient boosting model in MLJ.jl and in order to do that those columns need to be categorical, otherwise they are not treated as MultiClass{n} by MLJScientificTypes and won't be one-hot encoded automatically:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/4868370/113109146-649adc00-920e-11eb-890f-0c2fc1f99aad.png">

>categorical!(df); are deprecated.

You may have your reasons but I can say that deprecating `categorical!` makes things less user-friendly as the recommended alternative is quite long and more difficult to remember. 

>This is without the PR I am preparing. We have made a lot of such improvements with @nalimilan when working on faster joins >as it turned out that it were the "pooled" vectors that were most offending performance-wise.

Does this mean we can expect better results for joins in Julia in this benchmark: https://h2oai.github.io/db-benchmark/ ?

**Comment by bkamins** [comment]
> deprecating `categorical!` makes things less user-friendly as the recommended alternative is quite long and more difficult to remember.

We would prefer not to deprecate it, but Julia currently does not support conditional dependencies. The deprecation is verbose as it is fully general. A short version of the deprecation would be:
```
transform!(df, cols .=> categorical, renamecols=false)
```
where `cols` is the list of columns you want to change to catregorical.

> Does this mean we can expect better results for joins in Julia in this benchmark

Yes

**Comment by nalimilan** [comment]
Actually there's an even shorter replacement for `categorical!` if you want to replace all columns and not just those holding strings: `mapcols!(categorical, df)`.

**Comment by bkamins** [comment]
yes, but I assume that typically one wants to transform only some columns I think. As an Idea we might add `cols` argument to `mapcols` and `mapcols!` similar to what we do in other functions (like `disallowmissing` etc.)

**Comment by nalimilan** [comment]
CategoricalArrays 0.9.4 should fix this: https://github.com/JuliaRegistries/General/pull/33246.
