### ISSUE TITLE
Consider making `ByRow` just `const ByRow = Base.BroadcastFun`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2696]
I'm working on a package right now to make the `if` statements easier at the level of a function wrapper, akin to [This PR](https://github.com/JuliaData/Missings.jl/pull/122/files) in Missings. 

I think there is a lot of ground for efficiency if we know a function is broadcasted. I can check if a function is a `Base.BroadcastedFun` but I can't check if it's `ByRow` without depending on DataFrames, which  would be a big dependency for a helper function.

**Comment by bkamins** [comment]
Indeed this is a very important decision. There are two issues releated:
1. making `ByRow` using broadcasting causes significant latency. In https://github.com/JuliaData/DataFrames.jl/pull/2691 I have proposed not to use broadcasting in `ByRow` exactly because of this
2. even before this change `ByRow` did not always work like broadcasting the exceptions were:
    a. when `NamedTuple` is passed to it (it is treated as a table)
    b. when an empty set of columns is passed to it (when it does automatic expansion)

**Comment by pdeffebach** [comment]
Okay. Thanks for the feedback. I thought it was a one-for-one thing. 

Let me continue working on this package, then, and see how it plays out before trying to change DataFrames.

**Comment by bkamins** [comment]
It is not, here is a simple example (and something that people ask for):
```
julia> df = DataFrame(x=1:3)
3×1 DataFrame
 Row │ x
     │ Int64
─────┼───────
   1 │     1
   2 │     2
   3 │     3

julia> transform(df, [] => ByRow(rand) => :rand)
3×2 DataFrame
 Row │ x      rand
     │ Int64  Float64
─────┼─────────────────
   1 │     1  0.375566
   2 │     2  0.105534
   3 │     3  0.724418
```

OK - I am closing it then (please reopen if you feel it is worth to keep discussing)
