### ISSUE TITLE
control fill value for missing cells in `unstack`

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaData/DataFrames.jl#2698]
Currently, when `unstack` encounters combinations of column and row keys that are not present in the DataFrame, the corresponding cell in the output is filled with `missing`.  It would be nice to be able to control the fill value used with a kwarg.  

For context, I hit this using `unstack` as a convenient way to make a confusion matrix (for which it's especially nice since you can add additional grouping variables on the rows), but cells that are missing really correspond to `0` in that situation.

**Comment by bkamins** [comment]
In general we should add an option to define a sentinel. In this case you can fortunately just do:
```
coalesce(unstack(...), 0)
```
(in general this will not work as you have to be able to distinguish `missing` produced by `unstack` and `missing` originally present in the data frame)

**Comment by kleinschmidt** [comment]
That's unfortunately not going to work in my particular case since there are real `missing`s in some of the key columns that I want to keep.

**Comment by bkamins** [comment]
Yeah - this is a thing we keep track of in the design but I hoped it would not be a problem. Though you could `coalesce` only the columns that hold counts (and this can be done in-place).

**Comment by sl-solution** [comment]
> Currently, when `unstack` encounters combinations of column and row keys that are not present in the DataFrame, the corresponding cell in the output is filled with `missing`. It would be nice to be able to control the fill value used with a kwarg.
> 
> For context, I hit this using `unstack` as a convenient way to make a confusion matrix (for which it's especially nice since you can add additional grouping variables on the rows), but cells that are missing really correspond to `0` in that situation.

#2743 is trying to address this issue.

**Comment by pstorozenko** [comment]
I'm working on this.
Suppose we have `filling_value`.
It's default to `missing`, but otherwise how would we like to solve scenario where `eltype(df[:value]) != type(filling_value)`?

I see potential solutions as:

- Throw an error
- Try to promote/convert `eltype(df[:value])` to `type(filling_value)` throw error if not possible
- Try to promote/convert  `type(filling_value)` to `eltype(df[:value])` throw error if not possible
- Find the nearest common supertype and promote both

**Comment by bkamins** [comment]
This was exactly the point I mentioned it needs to be discussed. I think we should use the `promote_type` on each output column separately. This is the same that e.g. the following does:
```
julia> [1, 2.0]
2-element Vector{Float64}:
 1.0
 2.0
```
The downside is that the sentinel could get promoted, e.g. from `1` to `1.0`, but at leas for `Missing` and `Nothing` it creates `Union` and we probably care most about these cases.

**Comment by bkamins** [comment]
Ah - and I do not thin we should error here. If someone passes some sentinel it means it should be put there.
