### ISSUE TITLE
performance expectation

### ISSUE THREAD

**Issue by waynelapierre** [JuliaData/DataFrames.jl#2699]
I would like to know if it is possible for DataFrames to catch up with R's data.table's performance. If yes, how long would that take?

**Comment by bkamins** [comment]
Can you please provide a concrete timing that is a problem for you?
(giving the same code and the timings of running it on the same number of threads for data.table and DataFrames.jl `main` branch)

Given your general question it is hard to comment on your question, as in some cases we are faster than data.table, and in some we are slower. However, if you see a significant regression of DataFrames.jl vs data.table please report.

Here is an example of joins on a single thread:

`main` of DataFrames.jl:
```
julia> using DataFrames

julia> df1 = DataFrame(x=1:10^8);

julia> df2 = copy(df1);

julia> @time innerjoin(df1, df2, on=:x); # compilation time
  3.814946 seconds (826.08 k allocations: 2.282 GiB, 2.24% gc time, 22.24% compilation time)

julia> @time innerjoin(df1, df2, on=:x); # compilation time
  2.808345 seconds (154 allocations: 2.235 GiB, 3.66% gc time)

julia> @time innerjoin(df1, df2, on=:x); # compilation time
  2.922306 seconds (154 allocations: 2.235 GiB, 2.81% gc time)
```

and here is data.table:
```
> library(data.table)
> setDTthreads(1)
> df1 <- data.table(x=1:10^8)
> df2 <- data.table(x=1:10^8)
> system.time(merge(df1, df2, all=FALSE))
   user  system elapsed 
  8.449   1.296   9.746 
> system.time(merge(df1, df2, all=FALSE))
   user  system elapsed 
  7.983   1.424   9.405 
> system.time(merge(df1, df2, all=FALSE))
   user  system elapsed 
  8.473   1.328   9.802 
```

so as you can see in this case we are around 3 times faster than data.table on `innerjoin`.

**Comment by waynelapierre** [comment]
I saw this benchmark website: 
https://h2oai.github.io/db-benchmark/

For the 50G groupby tasks, DataFrames.jl is always slower than data.table. For the last three tasks, DataFrames goes out of memory. This seems to suggest both a performance and memory efficiency issue.

For the 5G join tasks, DataFrames.jl is even much slower than pandas. 

Will DataFrames.jl's performance catch up after multiple threads are used?

**Comment by bkamins** [comment]
Regarding H2O benchark - we are aware of it. Please feel free to re-run the test suite it uses against `main` branch of DataFrames.jl.

As commented above for different tasks you can expect different platforms to be faster as they are optimized against different use cases. In general - you can expect DataFrames.jl `main` to be fast enough and competitive for all standard data processing tasks.

I will close this issue. However, if you have a concrete specific example that runs slowly on `main` please comment and I will re-open.
