### ISSUE TITLE
Review comparisons with R/Python

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2737]
https://dataframes.juliadata.org/stable/man/comparisons/ is outdated and needs fixing.

**Comment by floswald** [comment]
It would be great to add a data.tables comparison section. I could give it a stab. How exactly do you want to update this section, different examples?

By the way I was reassured to see that an updated configuration setting on the h2o benchmark resulted in a much better performance of dataframes.jl . (Pointed out by @pdeffebach on twitter !) In fact what was posted there yesterday under dataframes.jl v1 was a far cry from what I saw on bogumil's blog.

**Comment by bkamins** [comment]
You can comment in https://github.com/JuliaData/DataFrames.jl/pull/2725 if you want to contribute to the comparisons vs data.table. Thank you!
