### ISSUE TITLE
Potential confusion with subset

### ISSUE THREAD

**Issue by matthieugomez** [JuliaData/DataFrames.jl#2740]
`subset` acts on vectors by default.  This can introduce some confusion if users forget to use `ByRow`:
```julia
using DataFrames
df = DataFrame(x = [0, 1])
subset(df, :x => ==(0))
# 0×1 DataFrame
df2 = DataFrame(x = [0, missing])
subset(df2, :x => ismissing)
# 0×1 DataFrame
```
This happens because `==` and `ismissing` are applied to vectors
```julia
df.x == 0
# false
ismissing(df2.x)
# false
```
Unfortunately, this is very error prone. I was wondering whether something should be done about it.

**Comment by eloualiche** [comment]
Have you tried doing

`subset(df, :x => .==(0))`
?

**Comment by bkamins** [comment]
We could add a check if the predicate returns `AbstractVector{Bool}`. This would be mildly breaking, but as you note - at least not error prone. @nalimilan - what do you think?

**Comment by matthieugomez** [comment]
@bkamins For this fix, the downside would be that one can no longer keep groups based on summary statistics, e.g.,
```
using DataFrames
df = DataFrame(id = [0, 0, 1, 1], x = [-1, 1, 3, 4])
subset(groupby(df, :id), :x => (x -> sum(x) > 0))
```
right?

**Comment by bkamins** [comment]
Yes - that would be the tradeoff if we wanted to be consistent. We could theoretically apply this rule only to data frames, but I am not sure it is a good idea. Note that `filter` would still allow you to filter whole groups, so maybe it is OK to disallow it?

**Comment by matthieugomez** [comment]
yes, i think it'd be ok to disallow it. Also cc-ing @pdeffebach

**Comment by pdeffebach** [comment]
Yes definitely! 

I was not aware that `subset` could filter groups, but this seems like overly-context-dependen behavior.

**Comment by bkamins** [comment]
OK. It will not be super simple so I will do it once we resolve performance issues in 1.0.1 release.
Essentially we need to rewrite function calls that are not `ByRow` from `fun` into `(x...) -> (res = fun(x...); @assert res isa  AbstractVector{Bool}; return res)` (but with a nicer message. this should not affect performance significantly but I need to make a wrapper like `ByRow` for it to avoid compilation latency). And docs need updating.

**Comment by pdeffebach** [comment]
yes. But you need to account for `BitVector`s as well. I found that out while implementing `@where`.

**Comment by bkamins** [comment]
```
julia> BitVector <: AbstractVector{Bool}
true
```

**Comment by ericphanson** [comment]
Would it make sense to have a `ByGroup` wrapper so you could do
```julia
using DataFrames
df = DataFrame(id = [0, 0, 1, 1], x = [-1, 1, 3, 4])
subset(groupby(df, :id), :x => ByGroup(x -> sum(x) > 0))
```
in order to filter groups? I think though that would kind of imply that returning a vector from `subset` for a GroupedDataFrame would mean which groups to filter but currently it means which rows to filter from each group (I think).

**Comment by bkamins** [comment]
This is what `filter` currently does:
```
filter(:x => x -> sum(x) > 0, groupby(df, :id))
```
I suggested above to clearly differentiate `subset` and `filter` behavior in the documentation (as it turns out in the end that they are both useful).

**Comment by bkamins** [comment]
see #2744 for a PR implementing this.

A careful look and maybe additional test proposals would be welcome (in particular: the old behavior was tested in the previous tests - so if you could kindly have a look at tests now and judge if they are doing what we want would be great).

**Comment by bkamins** [comment]
I have reopened this issue as it is constantly raised by users. What @matthieugomez reported is one side of the situation. The other side is that by disallowing scalars we do not have an easy way to filter whole groups. See e.g. https://stackoverflow.com/questions/71286257/filter-grouped-dataframe-in-julia for a recent discussion.

Let us discuss it again before mating a 1.4 release.

CC @pdeffebach @nalimilan

**Comment by bkamins** [comment]
maybe we should add a kwarg that would allow scalars i.e. we would have `broadcast::Bool=false` by default but if you pass `true` you allow pseudo-broadcasting of scalars?

**Comment by matthieugomez** [comment]
I would rather have consistency rather than special cases with hard to find
options. How about displaying a warning message for the examples in my
original post?

**Comment by nalimilan** [comment]
Warnings are not really a solution as they are annoying/confusing when you really intended to write what you wrote. So we would need a way to turn them off, in which case throwing an error would be better.

**Comment by bkamins** [comment]
I agree we should not print warnings.

The crucial question is what @nalimilan asked:

> Do we have evidence that it creates lots of confusion?

i.e. I know someone can make an error but how risky is this? I.e. how high is the risk that the user writes an incorrect condition and does not notice the problem. In particular, it mostly applies to `==`, `isequal`, `===` and `ismissing` only in practical scenarios. All other cases would error. Maybe we should add an example in the docstring warning users about such cases and that would be enough?

**Comment by matthieugomez** [comment]
What about allowing it for GroupedDataFrame but not for DataFrame (if it’s possible)?

**Comment by bkamins** [comment]
It is technically possible, but I this would break one of the most important contracts of DataFrames.jl that operations on `DataFrame` work the same as operations on `GroupedDataFrame`. I think it is important to keep it as otherwise we will get a ton of complaints about such inconsistencies.

**Comment by bkamins** [comment]
Can interested people vote under this post so that I can move forward with 1.4 release? Thank you!
👍 - make `subset` consistent with other functions and make effort in the documentation to explain the situation
👎 - keep what we have now

**Comment by matthieugomez** [comment]
I have no preference.
