### ISSUE TITLE
Allow selecting columns based on predicate on column contents

### ISSUE THREAD

**Issue by SebRollen** [JuliaData/DataFrames.jl#2747]
Based on a discussion from slack:
> [Sebastian Rollén]: Potentially dumb question: How might I `select` only columns that don't have missing data in them? In R/dplyr I would use select_if, so I was looking for something similar
> 
> [Sebastian Rollén]: my best approach so far is to choose the column indices with `indices = map(x -> !any(ismissing, x), eachcol(df))` and then `df[:, indices]` , but I feel like there's probably a nicer solution?
>
> [Peter Deffebach]: you can use a type in `names`, something like `names(df, <:Missing)`. But this is all columns that allow missings, not the ones with missings.
>
> [Sebastian Rollén]: hm, that probably won't work in this case as all my columns allow missings as they are `unstack`ed from the same column
>
> [Sebastian Rollén]: I'm explicitly looking for the columns that don't have any missing values so I can filter out the other ones and then run `disallowmissing` so that I can get rid of the type union
>
> [Bogumił Kamiński]: What you use now is a currently recommended way. Currently in `names` if you pass predicate it looks at column name not at column contents. We have decided for this as it seemed more common. But agreed it is also useful to find columns based on a predicate of their contents. Maybe open an issue and we can discuss there how to design it.

It's currently possible to `select` a dataframe using a predicate in `names`, but this predicate applies to the types of the columns, not the contents of the columns themselves. The idea here is to have some function that allows `select`ing a column based on the contents of the columns instead, similar to `select_if` in dplyr

**Comment by sl-solution** [comment]
using `mapcols!`  

```julia
myfun(x) = any(ismissing.(x)) ? nothing : disallowmissing(x)
mapcols!(f12, df)
```
