### ISSUE TITLE
H2O benchmark Grouping Advanced Query 3 perofrmance

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2764]
In the H2O benchmark Grouping Advanced Query 3 "largest two v3 by id6" different solutions use different strategies about when to drop nulls and when to perform sorting. I think it is a nice entry level exercise to check for `n=100_000_000` which strategy is best for DataFrames.jl. Our current code is here:
https://github.com/h2oai/db-benchmark/blob/031495e404c2ae81a50bdd8ec69b99b48bb2a453/juliadf/groupby-juliadf.jl#L151

@pstorozenko - maybe this would be something interesting for you to experiment with so that we could learn if what we use now is best?
(no pressure - I just noted that you look into performance issues in DataFrames.jl 😄)

**Comment by sl-solution** [comment]
Not sure if it helps (more efficient for large vectors?), however, by default `sort` puts `missing` at the end, defining `lessthan` function as follow and use it as `lt` argument can handle `missings` for the code you mentioned.

```julia
lessthan(x, y) = isless(x, y)
lessthan(x, ::Missing) = false
lessthan(::Missing, x) = true
lessthan(::Missing, Missing) = false
```

**Comment by bkamins** [comment]
Thank you for commenting. I have thought about it, but such a verbose code will not be accepted.
Though we could go for `lt = (x,y) -> ismissing(y) ? false : (ismissing(x) : true : isless(x, y))` as Jan probably will allow for it.
Then we have to think of:
1. if sorting should be done before any operation (probably on a subset of a data frame).
2. if not then we will not be able to use `partialsort!`.
