### ISSUE TITLE
Flatten in case column contains string and array

### ISSUE THREAD

**Issue by sprmnt21** [JuliaData/DataFrames.jl#2766]
as described in [this discussion](https://discourse.julialang.org/t/flatten-in-case-column-contains-string-and-array/61284/3), the result of flattening a dataframe on a column containing arrays and strings is, in my opinion, unexpected.
A possible modification could include at least one keyword that optionally allows the possibility of managing the scalar-string elements as vectors of length 1.

**Comment by bkamins** [comment]
I have opened https://github.com/JuliaData/DataFrames.jl/issues/2767 in parallel with a more elaborate discussion of the issue. I will add a proposal of kwarg there.
