### ISSUE TITLE
Question: Small Delimited file into DataFrame

### ISSUE THREAD

**Issue by gitboy16** [JuliaData/DataFrames.jl#2772]
Hi,
I have read the following:
https://dataframes.juliadata.org/stable/man/importing_and_exporting/
Is there an alternative way to get a small text file delimited with '\t' into a dataframe in the first run without waiting 12 seconds for CSV.File to compile? 
The text file is different everytime.
Thank you

**Comment by bkamins** [comment]
use `DelimitedFiles` module from the standard library, see https://docs.julialang.org/en/v1/stdlib/DelimitedFiles/ (note that you might need to do some post-processing to the output before having a `DataFrame`, but it should be simple).

CSV.jl should be slow only on first run in a session.

**Comment by gitboy16** [comment]
Thank you @bkamins  I see how I can do this, I am closing this topic. I am trying to get people to use Julia in my company but most of them don't because of this first run issue with a lot of functions/packages. They prefer to stick with Python :-(

**Comment by bkamins** [comment]
I have opened https://github.com/JuliaData/DataFrames.jl/pull/2773 with the instructions you asked for, as indeed in some cases it might be useful.
