### ISSUE TITLE
UndefVarError: invrefpool not defined

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaData/DataFrames.jl#2787]
Hey folks, I am trying to do: 
```Julia
DF = innerjoin(dataframe_calories,dataframe_prices,on=:item)
```
but I keep getting:
```Julia
UndefVarError: invrefpool not defined

Stacktrace:
 [1] preprocess_columns(joiner::DataFrames.DataFrameJoiner)
   @ DataFrames ~/.julia/packages/DataFrames/nxjiD/src/join/core.jl:151
 [2] find_inner_rows(joiner::DataFrames.DataFrameJoiner)
   @ DataFrames ~/.julia/packages/DataFrames/nxjiD/src/join/core.jl:527
 [3] compose_inner_table(joiner::DataFrames.DataFrameJoiner, makeunique::Bool, left_rename::typeof(identity), right_rename::typeof(identity))
   @ DataFrames ~/.julia/packages/DataFrames/nxjiD/src/join/composer.jl:98
 [4] _join(df1::DataFrame, df2::DataFrame; on::Symbol, kind::Symbol, makeunique::Bool, indicator::Nothing, validate::Tuple{Bool, Bool}, left_rename::typeof(identity), right_rename::typeof(identity), matchmissing::Symbol)
   @ DataFrames ~/.julia/packages/DataFrames/nxjiD/src/join/composer.jl:386
 [5] #innerjoin#536
   @ ~/.julia/packages/DataFrames/nxjiD/src/join/composer.jl:561 [inlined]
 [6] top-level scope
   @ In[37]:1
````
any thoughts to resolve this?

**Comment by bkamins** [comment]
This is very strange. I can see you are on DataFrames.jl 1.1.1, which requires DataAPI.jl 1.6, and in this version it is defined: https://github.com/JuliaData/DataAPI.jl/blob/v1.6.0/src/DataAPI.jl#L96 and all should work.

I assume you have not edited anything manually in the source files. Therefore I would three steps to diagnose:
* check Manifest.toml what version of DataFrames.jl and DataAPI.jl you have (they should be 1.1.1 and 1.6, but from the error message it looks like you have exactly these versions)
* run e.g. `DataAPI.invrefpool([1,2,3])` - it should run without error, and produce `nothing`
* if the first two steps do not give you a clue what is the problem can you please share with me a reproducible example of your query?

Thank you!

**Comment by logankilpatrick** [comment]
I think the issue ended up being that Jupyter auto activated my local env which differed from my global env. It is all working now!

**Comment by bkamins** [comment]
Yeah - these things can get tricky. Thank you!
