### ISSUE TITLE
Differently typed columns when using `DataFrame(myVector)` vs `DataFrame(x = myVector)`

### ISSUE THREAD

**Issue by kimlaberinto** [JuliaData/DataFrames.jl#2798]
I found this seemingly unexpected behavior. I was able to produce (slightly) differently typed columns based on how I instantiate my DataFrame using my vector that is type `Vector{UUID}`. The typed columns are `UInt128` or `UUID` based on how you create the DataFrame.

I would call this issue minor though, code example below.
I expected that DataFrame would know that the type is supposed to be `UUID` since the input vector is `Vector{UUID}`.

## Minimal Code Example below
```
using UUIDs
using DataFrames

myVector = [uuid4() for _ in 1:5]
df1 = DataFrame(myVector)
df2 = DataFrame(x = myVector)
```
## df1
```
5×1 DataFrame
 Row │ value                             
     │ UInt128                           
─────┼───────────────────────────────────
   1 │ 10946103247743226645665383919085…
   2 │ 21863287386899153012382299214041…
   3 │  3311489548133513695140992459491…
   4 │ 21987028778519404676806998661841…
   5 │ 30541549827087951215386978692782…
```
## df2
```
5×1 DataFrame
 Row │ value                             
     │ UInt128                           
─────┼───────────────────────────────────
   1 │ 10946103247743226645665383919085…
   2 │ 21863287386899153012382299214041…
   3 │  3311489548133513695140992459491…
   4 │ 21987028778519404676806998661841…
   5 │ 30541549827087951215386978692782…
```
## Package versions below
```
pkg> st
      Status `/tmp/jl_mwLGJk/Project.toml`
  [a93c6f00] DataFrames v1.1.1
  [cf7118a7] UUIDs
```

**Comment by kimlaberinto** [comment]
I recently learned that this is typical/expected behavior because of how giving a vector to the DataFrames constructor de-structs the input by default, and is typical behavior of Tables.jl

Feel free to close in that case

**Comment by bkamins** [comment]
Exactly. What happens is the consequence of the fact that your `myVector` is a Tables.jl table. The behavior is not defined in DataFrames.jl but as you noted in Tables.jl.

Mental model of constructing `DataFrame` objects is:
* if `DataFrame(x)` is passed (single positional argument) then `x` is almost always (with a few convenience exceptions) treated as Tables.jl table
* if `DataFrame(colname=x)` is passed then `x` is treated as a column
