### ISSUE TITLE
DataFrame(table) != DataFrame(table, copycols=true)

### ISSUE THREAD

**Issue by altre** [JuliaData/DataFrames.jl#2799]
```julia
using Arrow
using DataFrames
Arrow.write("t.arrow",DataFrame(a=[1.]))
m=DataFrame(Arrow.Table("t.arrow"))
m.a[1]=4. # Results in ReadOnlyMemoryError
m=DataFrame(Arrow.Table("t.arrow"), copycols=true)
m.a[1]=4. # Works
```
This behavior is intentional (comment in code: '...the input is immutable so avoiding copies is desirable...' but not documented. The constructor documentation for DataFrame mentions a signature  `DataFrame(table; copycols::Bool=true)`. I was trying create a documentation pull request for this, but was finding it hard to formulate. 
Maybe: 
`copycols=true by default unless the input is of the type 'Tables.CopiedColumns' in which case it is not copied explicitly. This is useful for scenarios where the input is immutable so avoiding copies is desirable, but you may still want a copy for mutation. An example of this is the return value of Arrow.Table. `

As an aside, in my opinion this behavior seems unintuitive. If the user wants to avoid copies, why should he not be forced to pass copycols=false?

**Comment by bkamins** [comment]
1. this is documented in Arrow.jl (i.e. that by default copying does not happen)
2. this behavior is what I understand @quinnj intends it to be (so probably you would have to convince him to switch the default 😄)
3. Indeed we could add some more general comment in DataFrames.jl documentation. It is not only about "immutable input", but in general for cases where input signals it does not need to be copied (CSV.jl also works the same way).

I would say something along the lines (not a native speaker though so this probably requires correction):

> If the source columns are of `Tables.CopiedColumns` type then by default they are not copied. Use `opycols=true` explicitly to force copying them. An example of such behavior is when you read in the data from disk using `Arrow.Table` or `CSV.File`.

**Comment by nalimilan** [comment]
I agree this is a bit fishy. At least `copycols=true` is a lie now that more packages avoid copies by default. It should probably be shown as `copycols=nothing`.

TBH I'm a bit worried by this inconsistency. Being able to mutate a data frame is quite convenient, so I'm not sure it's a good default to keep immutable columns.

**Comment by bkamins** [comment]
@quinnj - we had this discussion several times already. What is your current thinking about this issue?

**Comment by quinnj** [comment]
I think it's just a documentation thing; happy to PR something to DataFrames. I do think we should clarify that the default for `copycols` is `nothing` and that some packages, only Arrow.jl currently, provide immutable columns by default, since that's the main use-case of using arrow data anyway. If anything, I see `copycols` as _more_ consistent now since it _will_ make mutable copies of columns when you pass `copycols=true` now, even for immutable arrow columns. 

I'm also happy to do another round on Arrow.jl docs to make this very clear; *arrow is an immutable data format*, so you should expect immutability when working with it and to have to do "extra" things in order to mutate. Luckily, this "extra" is only `copycols=true`, which honestly is way simpler than other arrow language implementations.

**Comment by bkamins** [comment]
> I'm also happy to do another round on Arrow.jl docs to make this very clear;

This is for sure something that makes sense to do no matter what we decide to do here.

> I think it's just a documentation thing; happy to PR something to DataFrames

This would be also appreciated, but let us first wait for the user feedback a bit on your proposal. Thank you!

**Comment by quinnj** [comment]
Oops, already made a PR; we can continue discussion on specific there if we want to include those docs; otherwise, I'm happy to see what other ideas people have here. (https://github.com/JuliaData/DataFrames.jl/pull/2805)

**Comment by bkamins** [comment]
sure. I have linked this issue to that PR
