### ISSUE TITLE
html dataframe representation includes invalid placement of <p> tag

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaData/DataFrames.jl#2800]
https://github.com/JuliaData/DataFrames.jl/blob/d5bb28daffb1471e93c185e99fcb68d2d26dfb8b/src/abstractdataframe/io.jl#L216-L223

I think you're not supposed to put anything between `</thead>` and `<tbody>`, the info printed there (x columns, x rows) ends up above the table in my browser, which is kind of weird. Is that intended?

**Comment by bkamins** [comment]
I am not sure what exactly you want to ask as the sentence below the code link seems to be missing something in the part:

> between and , the

In general this information should be printed above the data frame (this is the intention). Is this what you observe? The reason is that it is the only way to make sure that it will be visible for the user without scrolling.

**Comment by jkrumbiegel** [comment]
Whoops the tags were swallowed by github. Yes the text appears above but I had trouble styling it with css as it seems to be invalid to place it between head and body, and the browser can reorder tags to make the html valid again. At least I saw the p tag marked red in Firefox in some view of the source.

**Comment by bkamins** [comment]
Ah - indeed `<p>` is disallowed in `<table>`. I have opened https://github.com/JuliaData/DataFrames.jl/pull/2801 that hopefully fixes it.

**Comment by jkrumbiegel** [comment]
Maybe the p could be before the table and the whole thing wrapped in a div which gets the dataframe class. That way, one would have good options to style both together in a coherent way.

**Comment by bkamins** [comment]
Good point - I will fix it in #2801 (and could you give further comments there please to keep things in one place?)
