### ISSUE TITLE
Update the broadcasted getproperty when Julia 1.7 is out

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2804]
Just to keep track of it. See https://github.com/JuliaData/DataFrames.jl/pull/2655.

**Comment by nalimilan** [comment]
It's difficult to discuss intuitions as they vary a lot depending on previous experience, context, etc. IMO the main advantage of this change would be to have `df.x` be always equivalent to `df[!, :x]`. Given how complex the rules are, it seems important to avoid having three different syntaxes (`df.x`, `df[:, :x]` and `df[!, :x]`).

The downside is of course that we introduce an inconsistency between `df.x .= 1` and `v = df.x; v .= 1`.

Link to previous discussion (credits to @bkamins): https://github.com/JuliaData/DataFrames.jl/pull/2655.

**Comment by bkamins** [comment]
> to have `df.x` be always equivalent to `df[!, :x]`

this is my major personal motivation

**Comment by bkamins** [comment]
The plan is that we will change this behavior in DataFrames.jl 1.4. In 1.3 release an explicit warning message will be printed that the behavior will change in 1.4.
