### ISSUE TITLE
subset!(gd::GroupedDataFrame, ...) should make sure `gd` still works after

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2808]
Here's an example

```
julia> df = DataFrame(a = [1, 1, 2, 2], b = [1, 2, 3, 4]);

julia> gd = groupby(df, :a);

julia> subset!(gd, :b => (b -> b .> first(b)))
2×2 DataFrame
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     2      4

julia> gd
GroupedDataFrame with 2 groups based on key: a
First Group (2 rows): a = 1
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     2      4Error showing value of type GroupedDataFrame{DataFrame}:
ERROR: BoundsError: attempt to access 2×2 DataFrame at index [[3, 4], :]
```

`gd` is worthless after a call to `subset!` maybe we can repair it? If it isn't too costly.

**Comment by bkamins** [comment]
`@subset` is from DataFramesMeta.jl not from DataFrames.jl. In DataFrames.jl to get a `GroupedDataFrame` one writes:
```
julia> subset!(gd, :b => x -> x .> first(x), ungroup=false)
GroupedDataFrame with 2 groups based on key: a
First Group (1 row): a = 1
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      2
⋮
Last Group (1 row): a = 2
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     2      4
```
The idea is that if you omit `ungroup=false` and do not need `gd` (e.g. in a chain) you do not spend time on re-grouping.

However:
1. we might re-group `gd` if you feel we should (at some cost - but this is probably acceptable)
2. it prompts me to maybe add a methods doing validation of `GroupedDataFrame`, `DataFrameRow` and `SubDataFrame` just like we now have validation for `DataFrame`.

**Comment by bkamins** [comment]
@nalimilan - any opinion here. Should we favor performance (current design) or safety (what @pdeffebach proposes)

**Comment by nalimilan** [comment]
That's annoying, but I'd say we have to provide a minimum safety by default. Since after calling `subset!(gd, ...)` you can still use `gd`, it shoud be valid, or at least we should check whether it's valid before doing any operation on it (either to print an error if not or to fix it). Would it be possible to do this lazily like we currently do for indices?

**Comment by bkamins** [comment]
OK, I will make both:
1. update internals of `gd`
2. adding a check

We need both because there might be other `GroupedDataFrame`s than `gd` that have the same source - and these cannot be updated.

**Comment by bkamins** [comment]
Actually I think it is enough to add a check (and improve the documentation) - as if `subset!` does not add rows to a parent data frame.

**Comment by bkamins** [comment]
In the end in #2809 I decided both to add a check and to perform re-grouping. The reason is that re-grouping can be done quite efficiently and by re-grouping we are able to retain group order of the source `GroupedDataFrame` (even if it were originally re-ordered).
