### ISSUE TITLE
error in Julia

### ISSUE THREAD

**Issue by ModiShrushti** [JuliaData/DataFrames.jl#2813]
I am running ResistanceGA package with Circuitscape in Julia and I am getting this error.

Error happens in Julia. BoundsError: attempt to access 595×777 Matrix{Int64} at index [0, 663]

**Comment by bkamins** [comment]
Why have you opened this issue in DataFrames.jl repository? It seems unrelated. Probably you should open the issue in ResistanceGA?

**Comment by bkamins** [comment]
closing it as I am not clear how this is related to DataFrames.jl
