### ISSUE TITLE
"transform" function not available

### ISSUE THREAD

**Issue by ksgremes** [JuliaData/DataFrames.jl#2815]
Hi, I'm a beginner Julia user, so please forgive me for any mistakes.

I can't use `transform` function, it throws `UndefVarError` (and the function is nowhere to be found).

I'm using Julia 1.5.3 and DataFrames 0.20.2

Steps to reproduce:

1. Import DataFrames: `using DataFrames`
2. Run `transform`

Thanks in advance.

**Comment by bkamins** [comment]
As you can check [here](https://github.com/JuliaData/DataFrames.jl/blob/v0.20.2/src/DataFrames.jl) the `transform` function is not available in DataFrames.jl 0.20.2. Please use DataFrames.jl version 1.2 as this is a current release that is supported.

If you have to use DataFrames.jl 0.20.2 for some reason (but there should not be any such reason AFAICT) then use appropriate versions of the documentation and tutorials to learn what functionality was provided back then, see [here](https://dataframes.juliadata.org/v0.20/) and [here](https://github.com/bkamins/Julia-DataFrames-Tutorial/commit/3e4f96fff8a073a63bc83f0f393471db15764e84).
