### ISSUE TITLE
How to change the value of a cell to a different data type?

### ISSUE THREAD

**Issue by hongtaoh** [JuliaData/DataFrames.jl#2816]
I am using Julia v1.6.1 and DataFrames v1.2.0.

Currently, it's impossible to change the value of a cell in a column to a different data type:

```julia
a = 1:5
b = 'a':'e'
df = DataFrame(:A => a, :B => b)
```
```bash
julia> df
5×2 DataFrame
 Row │ A      B    
     │ Int64  Char 
─────┼─────────────
   1 │     1  a
   2 │     2  b
   3 │     3  c
   4 │     4  d
   5 │     5  e
```

```julia
df[!, :B][2] = "Bike"
```
This will throw an error:
```
MethodError: Cannot `convert` an object of type String to an object of type Char
```

After reading this thread, [DataFrames: convert column data type](https://discourse.julialang.org/t/dataframes-convert-column-data-type/35522), I know I can force this change by converting the data type of the column first:

```julia
df[!, :B] = string.(df[!, :B])
df[!, :B][2] = "Bike"
```
Now it's Okay to change the value. 

By contrast, it's acceptabled to change the column to a different data type:

```julia
df[!, :A] .= "Good"
```

My question is, why changing a column to a different type is allowed but not changing a single cell? Is it possible to allow changing the value of a cell to a different data type without having to convert the column's data type first?

**Comment by bkamins** [comment]
> why changing a column to a different type is allowed

It is allowed because users find it useful to change a column type. DataFrames.jl does not have a static schema, as static schema is not very convenient to use in most usage scenarios.

> Is it possible to allow changing the value of a cell to a different data type without having to convert the column's data type first?

No, because this is something that Julia Base disallows:
```
julia> b = collect('a':'e')
5-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

julia> b[2] = "Bike"
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Char
```
and DataFrames.jl just reproduces this error. Note that when you write `df[!, :B][2] = Bike` this is exactly evivalent to writing:
```
b = df[!, :B]
b[2] = "Bike"
```
so it must behave the way Julia Base handles vectors.

What you could do to achieve what you want is e.g.:
```
df.b = ifelse.(axes(df.b, 1) .== 2, "Bike", df.b)
```

**Comment by hongtaoh** [comment]
Thank you @bkamins so much for this amazing answer!
