### ISSUE TITLE
Error for `unstack`ing an empty dataframe

### ISSUE THREAD

**Issue by kollch** [JuliaData/DataFrames.jl#2841]
When attempting to run the `unstack` function on an empty dataframe, the error produced references an internal `MethodError`:

`ERROR: no method matching DataFrame(::Vector{Vector{Any}}, ::Vector{Any}; copycols=false)`

How to replicate:
```
df = DataFrame(a = [], b = [], c = [])
unstack(df, :b, :c)
```

I think it'd be nice to have a check for this, especially considering `stack` doesn't appear to have a similar problem.

**Comment by bkamins** [comment]
Thank you for reporting. This is a problem with broadcasting in base. Fixed in https://github.com/JuliaData/DataFrames.jl/pull/2842
