### ISSUE TITLE
AsTable docstring doesn't mention it can be used as a target for select etc.

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaData/DataFrames.jl#2850]
I was flailing around trying to figure out how to expand a column full of named tuples into columns, and remembered to look at `AsTable` but the docstring makes it sound like it's only mean to be used to wrap input to the transform/select/combine functions.  What I needed as `:col => AsTable`; a mention of this possibility in the docstring would have helped avoid my confusion!  If I have a bit of time I'll make a PR but wanted to open an issue at least to track the confusion.

**Comment by bkamins** [comment]
It is covered in https://github.com/JuliaData/DataFrames.jl/blob/3a71ae58d9b47d215a023ac4886f78b7f15b674c/src/abstractdataframe/selection.jl#L50:

> a `col => target_cols` pair, which renames the column `col` to `target_cols`, which must be single name (as a `Symbol` or a string), a vector of names or `AsTable`.

I agree this is a bit on a terse side. If you have a proposal how to improve this please comment or make a PR.

**Comment by bkamins** [comment]
(it has to be updated in the linked source + in the split-apply-combine section of the manual that has the same passage)

BTW. I personally find `:cols => AsTable` a super nice addition. I have blogged on it recently: https://bkamins.github.io/julialang/2021/07/02/dataframes-1.2.0.html.

**Comment by kleinschmidt** [comment]
Yup, agree all around.  Having that in the `AsTable` docstring would help with discoverability at the REPL.

**Comment by bkamins** [comment]
Ah - good point. I will make a PR for this.
