### ISSUE TITLE
delete! in DataFrames.jl

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2853]
We currently have `delete!` to remove rows from a `DataFrame`. However, `delete!` is defined for collections in Julia Base REMOVING A MAPPING for a passed key. Clearly this is not what `delete!` in DataFrames.jl does.

I propose to:
* deprecate `delete!` (it is a long term deprecation - it does not hurt to keep it)
* what `delete!` does should be `deleteat!`
* additionally implement `keepat!` to match Julia 1.7 behavior

(the issue is prompted by the fact that when we add `keepat!` it is strange to have `delete!` as its counterpart)

CC @nalimilan and @oxinabox (for end-user opinion as usual 😄)

**Comment by nalimilan** [comment]
For reference, I introduced `delete!` at https://github.com/JuliaData/DataFrames.jl/pull/2189 but it should clearly have been called `deleteat!`.
