### ISSUE TITLE
Support the Case of `Matrix{Any}` as Data and `Vector{Any}` as Header

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaData/DataFrames.jl#2858]
I have data as a `Matrix{Any}` (Data of integers, floats and strings) and `Vector{Any}` (Actually strings). I can create a table from them by `tTestData = Tables.table(mTestData; header = vTestHeader);`.
Yet I can't create a data frame by `dfTMP = DataFrame(mTestData, vTestHeader);`.
I can by pass it by `dfTMP = DataFrame(tTestData);`.

I think if `Tables.jl` can generate a table from the data so should `DataFrames.jl`.

**Comment by bkamins** [comment]
@RoyiAvital  Can you please test #2859 before I merge it if it works as you would expect? Thank you!

**Comment by bkamins** [comment]
added in https://github.com/JuliaData/DataFrames.jl/pull/2859
