### ISSUE TITLE
Allow DataFrame(matrix, names, copycols=false)

### ISSUE THREAD

**Issue by knuesel** [JuliaData/DataFrames.jl#2860]
The documentation suggests that e.g. `DataFrame(rand(2,2), [:a, :b], copycols=false)` should be supported:

https://github.com/JuliaData/DataFrames.jl/blob/0a736def9709cb9bc4c901d5a5117757d76fcf68/src/dataframe/dataframe.jl#L16-L18

but it fails with `got unsupported keyword argument "copycols"`.

It would be nice to have this as a simpler version of

```julia
A = rand(2,2)
DataFrame(collect(eachcol(A)), [:a, :b], copycols=false)
```

**Comment by bkamins** [comment]
I am not sure we want it. I would rather fix the documentation that we do not allow it.

The reason is that `DataFrame(collect(eachcol(A)), [:a, :b], copycols=false)` will be surprising for most of users as the columns will be `view`s which, while valid, are tricky to work with.

What is your use case?

@nalimilan - do you have any opinion here?

**Comment by nalimilan** [comment]
Interesting corner case! I'd say that we could allow `copycols=false` if somebody has a use case for it. But I wouldn't add it just for completeness, as the result could indeed be surprising.

**Comment by bkamins** [comment]
Agreed - that is why I asked for the use case. Again - most users find the behavior of DataFrames.jl confusing if the columns are `view`s, as you cannot e.g. `push!` or `append!`.

**Comment by knuesel** [comment]
I find the views reasonable since the user is basically asking for them by writing `copycols=false`. I expected it to work because the other "natural" ways to use views are not restricted (for example `DataFrame([:a, :b] .=> eachcol(A), copycols=false)`). But it's true there is a difference since here the views would be created by DataFrames.jl.

My use case: I was loading data from "large" Excel files (1 million rows). The column names are actually on the 4th row, and some columns must be discarded, so I get the actual data using `XLSX.readxlsx(file)[sheetname][range]` which returns a matrix. I was trying to wrap this in a data frame without copy. Full disclosure: I'll probably end up copying the columns anyway to narrow the types.

**Comment by bkamins** [comment]
> I was trying to wrap this in a data frame without copy.

Here is the crucial point of the question. Why do you want to avoid copying (apart from the fact that "you can"). Is there some reason to do it (the only I can see is to save memory, as copying should be fast).

**Comment by knuesel** [comment]
Indeed it was to save memory: some notebooks get very memory intensive as memory won't be reclaimed from temporary variables unless they're manually reassigned, and mybinder.org instances for example are only 1-2 GB...

**Comment by bkamins** [comment]
OK - I think we can have this change. I will add it to https://github.com/JuliaData/DataFrames.jl/pull/2859

**Comment by bkamins** [comment]
Added in https://github.com/JuliaData/DataFrames.jl/pull/2859. Can you please test?

**Comment by knuesel** [comment]
@bkamins sorry for the delay, I confirm it's now working for me on the main branch. Thanks!
