### ISSUE TITLE
Better error messages when frame is empty

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/DataFrames.jl#2867]
```jl
julia> df = DataFrame()
0×0 DataFrame

julia> rename(df, :a => :b)
ERROR: ArgumentError: Tried renaming :a to :b, when :a does not exist in the Index.
```

Many functions fail when the DataFrame is empty but they don't mention that it was empty in the error. It would help with debugging if it did mention it was empty.

**Comment by bkamins** [comment]
The error tells you that `:a` is not present in `df`. Can you please suggest what other error you would like to have as for me the error message seems clear (i.e. I understand it is confusing you, but I need to know the exact wording of the message that would be clearer to you).

**Comment by jtrakk** [comment]
This normally comes up when I construct a dataframe dynamically like

```jl
julia> xs = [];

julia> DataFrame((;a=x) for x in xs);

julia> df = DataFrame((;a=x) for x in xs);

julia> rename(df, :a => :b)
ERROR: ArgumentError: Tried renaming :a to :b, when :a does not exist in the Index.
```

"Tried renaming :a to :b, when :a does not exist in the Index." is nice, but it can supplement that with more information. For example "The DataFrame had 0 columns and 0 rows."

**Comment by jtrakk** [comment]
This also applies to other functions like `sort` which says `ArgumentError: column name :x not found in the data frame`. I'd want to have a hint at the reason -- there are no columns in the data frame. It could even just say 
```
ERROR: ArgumentError: column name :x not found in the (0x0) data frame
```
