### ISSUE TITLE
Add "Filtering" section to the documentation User Guide.

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#2871]
Currently the `filter` and `subset` functions are only described in the [API section](https://dataframes.juliadata.org/latest/man/working_with_dataframes/#Taking-a-Subset). Even [Taking a Subset](https://dataframes.juliadata.org/latest/man/working_with_dataframes/#Taking-a-Subset) does not show `subset` or `filter` being used.

This section should also highlight that column selectors can be used inside filter function definitions like:
```
filter!(row -> !all(x -> x == 0, row[Not(:y)]), df)
```

**Comment by bkamins** [comment]
There is an open PR for this https://github.com/JuliaData/DataFrames.jl/pull/2598. I am waiting for OP to finish it. If I do not get a response soon we will add it independently.

> `row[Not(:y)]`

Yes, we can add it. In general what is allowed as column selector is described in detail [here](https://dataframes.juliadata.org/stable/lib/indexing/#General-rules).

**Comment by nathanrboyer** [comment]
Okay, thanks.

**Comment by bkamins** [comment]
Thank you! (feel free to ping in #2598 if it gest stalled 😄)
