### ISSUE TITLE
mixing `:x => :y` and `:x => f => :y` syntax in vector to `select` errors

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaData/DataFrames.jl#2888]
MWE:

```julia
using DataFrames

tab = DataFrame(x = 1:10, y = 1:10)

xselector = :x => ByRow(x -> 2x) => :x2
yselector = :y => :Y
y2selector = :y => ByRow(y -> 2y) => :y2

# all okay
select(tab, xselector)
select(tab, yselector)
select(tab, xselector, yselector)
select(tab, (xselector, yselector)...)

# error:
select(tab, [xselector, yselector])
select(tab, [xselector, yselector]...)

# okay:
select(tab, [xselector, y2selector])
select(tab, [xselector, y2selector]...)
```

Errors are like

```
ArgumentError: Unrecognized column selector: Pair{Symbol, Any}(:x, ByRow{var"#3#4"}(var"#3#4"()) => :x2)

Stacktrace:
 [1] normalize_selection(idx::DataFrames.Index, sel::Any, renamecols::Bool)
   @ DataFrames ~/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/selection.jl:184
 [2] manipulate(::DataFrame, ::Any, ::Vararg{Any, N} where N; copycols::Bool, keeprows::Bool, renamecols::Bool)
   @ DataFrames ~/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/selection.jl:1311
 [3] #manipulate#470
   @ ~/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/selection.jl:1438 [inlined]
 [4] select(df::DataFrame, args::Any; copycols::Bool, renamecols::Bool)
   @ DataFrames ~/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/selection.jl:940
 [5] select(df::DataFrame, args::Any)
   @ DataFrames ~/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/selection.jl:940
 [6] top-level scope
   @ In[21]:1
 [7] eval
   @ ./boot.jl:360 [inlined]
 [8] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
```

**Comment by bkamins** [comment]
The reason is that we dispatch on type and not on value. Do you think we should change this?

**Comment by kleinschmidt** [comment]
I think the surprising thing is that the splatting is not equivalent to VarArg form.  I'd have thought that passing it through a function like this, you'd get the actual type and not whatever the `eltype` of the parent array is

**Comment by bkamins** [comment]
> I think the surprising thing is that the splatting is not equivalent to VarArg form.

Splatting has nothing to do with it. If you do:
```
julia> select(tab, (xselector, yselector)...)
10×2 DataFrame
 Row │ x2     Y
     │ Int64  Int64
─────┼──────────────
   1 │     2      1
   2 │     4      2
   3 │     6      3
   4 │     8      4
   5 │    10      5
   6 │    12      6
   7 │    14      7
   8 │    16      8
   9 │    18      9
  10 │    20     10
```
all is OK.

The problem is that vector creation performs type promotion.

**Comment by bkamins** [comment]
> you'd get the actual type and not whatever the `eltype` of the parent array is

You do get the actual type, this is the same as:
```
julia> [1, 2.0]
2-element Vector{Float64}:
 1.0
 2.0
```
and both values got promoted to `Float64`.

**Comment by pdeffebach** [comment]
I'm still not following this. Why pair is getting messed up by the promotion?

**Comment by kleinschmidt** [comment]
Yeah, I understand now.  I wonder if you could introduce another function barrier for the right-hand side of the pairs?

**Comment by bkamins** [comment]
Because the second parameter is promoted to a common supertype which is `Any`. Then in DataFrmes.jl we do dispatch on the type of the second `Pair` parameter, so it does not work. If we dispatched on value not on type it would work though (but the code would be less clean).

**Comment by pdeffebach** [comment]
I see, thank you.

**Comment by bkamins** [comment]
But the question is if we want to make this change? Essentially the practical solution is to use `Any` as eltype to make sure such promotion does not happen in such cases if we do not do anything.

The good thing is that broadcasting does not do such promotion:
```
julia> typeof.([1, :a] .=> [:a, (x->x) => :b])
2-element Vector{DataType}:
 Pair{Int64, Symbol}
 Pair{Symbol, Pair{var"#7#8", Symbol}}
```
it is only the vector constructor that messes up things.

**Comment by kleinschmidt** [comment]
I wonder whether it would be possible to have methods for `normalize_selection` that unpack Pairs into two args, which would introduce the necessary function barrier to get the actual type of the right-hand sides

**Comment by kleinschmidt** [comment]
`s/possible/worth it/`

**Comment by pdeffebach** [comment]
Here is one solution

```
julia> reconstruct_pair(p) = p[1] => p[2];

julia> p = [xselector, yselector]
2-element Vector{Pair{Symbol, Any}}:
 :x => (ByRow{var"#9#10"}(var"#9#10"()) => :x2)
 :y => :Y

julia> typeof.(p)
2-element Vector{DataType}:
 Pair{Symbol, Any}
 Pair{Symbol, Any}

julia> p2 = Any[reconstruct_pair(pi) for pi in p]
2-element Vector{Any}:
 :x => (ByRow{var"#9#10"}(var"#9#10"()) => :x2)
 :y => :Y

julia> typeof.(p2)
2-element Vector{DataType}:
 Pair{Symbol, Pair{ByRow{var"#9#10"}, Symbol}}
 Pair{Symbol, Symbol}
```

**Comment by kleinschmidt** [comment]
You could also introduce a pre-normalization step for pairs, something like

```
flatten_pair(x) = (x, )
flatten_pair(x::Pair) = (x[1], flatten_pair(x[2])...)
```

which will return a two-tuple for flat pairs and a three-tuple for nested ones

**Comment by kleinschmidt** [comment]
I guess that's not such a great idea because you can pass tuples of selectors though so you'll get an ambiguity there.  Might require a wrapper type

```
struct Selector
  in
  f
  out
end

Selector(x::Pair) = Selector(flatten_pair(x)...)
Selector(in, out) = Selector(in, identity, out)
```
