### ISSUE TITLE
renamecols function for transform

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/DataFrames.jl#2893]
I would like to pass a `renamecols` function to `transform`. `innerjoin` takes a `renamecols` function and `transform` takes a `renamecols::Bool`. I want to replace the Bool with a function parameter that defaults to `column_function(c) = "$(c)_function"` and can be replaced with `identity` for users who currently pass `renamecols=false`.

**Comment by bkamins** [comment]
This is a good proposal in line with some other proposals to allow `dst` to be a function in `src => fun => dst`, see https://github.com/JuliaData/DataFrames.jl/issues/2876.
We will just need to work out the best approach.

**Comment by jtrakk** [comment]
Your proposal is better than mine. Closing.
