### ISSUE TITLE
Strange behaviour with non-ASCII column names

### ISSUE THREAD

**Issue by wentasah** [JuliaData/DataFrames.jl#2901]
When a DataFrame contains non-ASCII column name like here:
```julia
d = DataFrame("power_µW" => [1,2,3])
```
access to the column leads to an "interesting" error:
```julia
d.power_µW
# ERROR: ArgumentError: column name :power_μW not found in the data frame; 
# existing most similar names are: :power_µW
```

This is weird, because typing `d.` and pressing `TAB` completes exactly the above command.

When using the following syntax, everything works as expected:
```julia
d."power_µW"
# 3-element Vector{Int64}:
#  1
#  2
#  3
```

Happens with DataFrames 1.2.2 as well as with [a93c6f00] DataFrames v1.2.2 `https://github.com/JuliaData/DataFrames.jl.git#main`.
```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
```

**Comment by bkamins** [comment]
This is a limitation in Julia design that opts-in to canonicalize Unicode identifiers. Here is an explanation https://github.com/JuliaLang/julia/issues/5434. CC @stevengj as he was the OP so that he is aware of this consequence.

A more verbose example showing the problem and how to work-around it:
```
julia> a, b = "xμ", "yµ"
("xμ", "yµ")

julia> collect(a)
2-element Vector{Char}:
 'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
 'μ': Unicode U+03BC (category Ll: Letter, lowercase)

julia> collect(b)
2-element Vector{Char}:
 'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)
 'µ': Unicode U+00B5 (category Ll: Letter, lowercase)

julia> d = DataFrame(a => 1, b => 2)
1×2 DataFrame
 Row │ xμ     yµ    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2

julia> d.xμ # autocompleted
1-element Vector{Int64}:
 1

julia> d.yµ # autocompleted
ERROR: ArgumentError: column name :yμ not found in the data frame; existing most similar names are: :yµ and :xμ
Stacktrace:
 [1] lookupname
   @ C:\Users\bogum\.julia\packages\DataFrames\vuMM8\src\other\index.jl:291 [inlined]
 [2] getindex
   @ C:\Users\bogum\.julia\packages\DataFrames\vuMM8\src\other\index.jl:297 [inlined]
 [3] getindex(df::DataFrame, #unused#::typeof(!), col_ind::Symbol)
   @ DataFrames C:\Users\bogum\.julia\packages\DataFrames\vuMM8\src\dataframe\dataframe.jl:513
 [4] getproperty(df::DataFrame, col_ind::Symbol)
   @ DataFrames C:\Users\bogum\.julia\packages\DataFrames\vuMM8\src\abstractdataframe\abstractdataframe.jl:356
 [5] top-level scope
   @ REPL[97]:1

julia> foreach(x -> display(collect(x)), names(d))
2-element Vector{Char}:
 'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
 'μ': Unicode U+03BC (category Ll: Letter, lowercase)
2-element Vector{Char}:
 'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)
 'µ': Unicode U+00B5 (category Ll: Letter, lowercase)

julia> d[:, a] # works
1-element Vector{Int64}:
 1

julia> d[:, b] # works
1-element Vector{Int64}:
 2
```

and here is how it works for custom structs:

```
julia> struct X
       xμ # note that this mu
       yµ # and this mu are not the same characters when we define X struct; you need a use a proper font to see the difference
       end

julia> foreach(d -> display(collect(d)), string.(fieldnames(X))) # but they end up being the same after it gets defined
2-element Vector{Char}:
 'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
 'μ': Unicode U+03BC (category Ll: Letter, lowercase)
2-element Vector{Char}:
 'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)
 'μ': Unicode U+03BC (category Ll: Letter, lowercase)
```

**Comment by bkamins** [comment]
@nalimilan - what do you think?

> normalize all of the column names when they are stored

I am not sure we want to do this. I think it is important for programmatic use cases to store column names as the user asks them to be stored. If we normalized - two columns having distinct names e.g. `"no\u00EBl"` and `"noe\u0308l"` would be considered as duplicate names, which we do not want I think.

The problem is only when the user wants to manually pass a `Symbol` using a literal. In all other cases the things work as expected:

```
julia> a, b = "no\u00EBl", "Noe\u0308l"
("noël", "Noël")

julia> sa, sb = Symbol.((a, b))
(:noël, :Noël)

julia> using DataFrames

julia> d = DataFrame(a => 1, b => 2)
1×2 DataFrame
 Row │ noël   Noël
     │ Int64  Int64
─────┼──────────────
   1 │     1      2

julia> d[:, sa]
1-element Vector{Int64}:
 1

julia> d[:, sb]
1-element Vector{Int64}:
 2

julia> d[:, a]
1-element Vector{Int64}:
 1

julia> d[:, b]
1-element Vector{Int64}:
 2

julia> d."no\u00EBl"
1-element Vector{Int64}:
 1

julia> d."Noe\u0308l"
1-element Vector{Int64}:
 2

julia> d.noël
1-element Vector{Int64}:
 1

julia> d.Noël
ERROR: ArgumentError: column name :Noël not found in the data frame; existing most similar names are: :noël and :Noël

julia> d[:, :noël]
1-element Vector{Int64}:
 1

julia> d[:, :Noël]
ERROR: ArgumentError: column name :Noël not found in the data frame; existing most similar names are: :noël and :Noël
```

If we go along my proposal I will add a documentation explaining this case.

**Comment by stevengj** [comment]
> two columns having distinct names e.g. `"no\u00EBl"` and `"noe\u0308l"`

In Unicode, these are considered "canonically equivalent" strings.  [According to the Unicode standard](https://www.unicode.org/faq/normalization.html#1):

> Programs should always compare canonical-equivalent Unicode strings as equal

**Comment by bkamins** [comment]
> (Alternatively, you could store both the normalized and the original non-normalized versions, and only use the former for comparing to Symbol, throwing an error if it is ambiguous.)

This is a good point. Actually we could compute it on the fly if the initial lookup fails so that we would not introduce an overhead for standard situations.

**Comment by nalimilan** [comment]
Yes it does: https://github.com/JuliaData/CSV.jl/blob/0f97e66e998e0a7918b73ab6d54460c253c86d67/src/utils.jl#L333-L338

**Comment by stevengj** [comment]
It was decided not to perform normalization on symbols constructed with `Symbol(“…”)` because those are typically programmatically constructed (rather than human identifiers) and are not required to be valid Julia identifiers.
