### ISSUE TITLE
`tf` keyword argument from PrettyTables.jl does not work in DataFrames.jl `show` function.

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#2903]
Can you export the table formats from PrettyTables to DataFrames?
```julia
julia> show(df, tf=tf_unicode)
ERROR: UndefVarError: tf_unicode not defined
```

**Comment by ronisbr** [comment]
What you actually are trying to do? You can always call PrettyTables directly with the default options. There is no point to maintain an entire printing system inside DataFrames and in PrettyTables.

**Comment by bkamins** [comment]
> There is no point to maintain an entire printing system inside DataFrames and in PrettyTables.

This is exactly the point.

> the power and prettiness are lost.

It is not lost. You can still fully use it. We just use fixed defaults to reduce latency which seems to be quite important for most users.
