### ISSUE TITLE
Printing of data frames in try-catch

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2925]
Motivated by [this discourse post](https://discourse.julialang.org/t/error-message-prints-entire-dataframe/70883/2)

```
julia> df = DataFrame(x = [1, 2]);

julia> try 
           length(df)
       catch e
           println(e)
       end
MethodError(length, (2×1 DataFrame
 Row │ x     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2,), 0x00000000000073ca)
```

Do we need some sort of more compact printing of the data frame?

This doesn't seem to be any better with `Vector`s

```
julia> function foo(x::Int)
           1
       end;

julia> x = [1, 2, 3];

julia> try 
           foo(x)
       catch e
           println(e)
       end
MethodError(foo, ([1, 2, 3],), 0x00000000000073cb)
```

The same holds for `display` and `show`. 

Perhaps we should file in Base?

**Comment by bkamins** [comment]
I think it would be best to open an issue in Base. Could you please follow up on this? Thank you!

**Comment by bkamins** [comment]
@pdeffebach - I guess given the comment by Jeff this can be closed?
