### ISSUE TITLE
add keepat! and insert! and pushfirst!

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2936]
In the future consider adding `keepat!` support (introduced in Julia 1.7).

**Comment by Chandu-4444** [comment]
Can I try adding `insert!`? Can you tell me how and where to start writing this function?

**Comment by bkamins** [comment]
I think `insert!` is hard to start with (unless you are really experienced with Julia).

You would need to use:

* https://github.com/JuliaData/DataFrames.jl/blob/main/src/dataframe/dataframe.jl#L1416
* https://github.com/JuliaData/DataFrames.jl/blob/main/src/dataframe/dataframe.jl#L1666
* https://github.com/JuliaData/DataFrames.jl/blob/main/src/dataframerow/dataframerow.jl#L501

and define similar `insert!` three methods for `insert!`. I encourage to review this source code and decide, but you will see that it is not an easy code and `insert!` will be a bit more complex than `push!` (not much but a still).

`keepat!` should be much easier as you just need to call `deleteat!` with an inverse selector (at least in the easiest scenario, i.e. not pushing performance to the limits). The only thing to be careful about is that `keepat!` will either need to be imported from `Base` or defined internally and exported depending on Julia version the user is on.

**Comment by bkamins** [comment]
If you are looking for easy PRs I would recommend:
* https://github.com/JuliaData/DataFrames.jl/issues/2845
* https://github.com/JuliaData/DataFrames.jl/issues/2443
* https://github.com/JuliaData/DataFrames.jl/issues/2438
