### ISSUE TITLE
Add `AsTable([:a, :b]) => AsTable`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2939]
This popped up while working on [this PR](https://github.com/JuliaData/DataFramesMeta.jl/pull/307). 

```
julia> df = DataFrame(rand(10,10), :auto);

julia> select(df, AsTable([:x1, :x2]) => AsTable)
ERROR: ArgumentError: Passing AsTable in AsTable([:x1, :x2]) => AsTable is not supported
```

Maybe we should allow it? no big deal if not. I can work around it.

**Comment by bkamins** [comment]
This would be the same as writing `[:a, :b]` - right? If I am correct I would not add it not to complicate things since it is not adding any useful functionality.

What do you think?

**Comment by pdeffebach** [comment]
Yeah I think it's fine. I will probably make it `AsTable(...) => identity => AsTable`.

**Comment by bkamins** [comment]
Agreed. The `:a => :b` is useful for renaming (and it is internally transformed to `:a => identity => :b` :))
