### ISSUE TITLE
Better error for disallowmissing function

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#2945]
The current error if you pass a data frame with missing values to `disallowmissing` comes from `convert`:
"ERROR: MethodError: Cannot `convert` an object of type Missing to an object of type Int64".

It would be nice to give the user a hint about where their missing data is, so they can go fix it. This would be slower, so it probably should be opt-in with something like `disallowmissing(df, verbose=true)`.

A rough example would be something like below:
```julia
if verbose == true
    missingrows = .!completecases(df)
    if sum(missingrows) > 0
        dfm = hcat(DataFrame(Row = 1:nrow(df)), df)
        show(dfm[missingrows,:], newline_at_end=true, show_row_number=false, vlines=[1])
        throw(ErrorException(
            "Cannot safely convert DataFrame to concrete type."*
            " Missing values detected in the rows above."))
    end
 end
```

**Comment by bkamins** [comment]
It is probably easier to wrap the conversion in a `try-catch` block and print a better error message. Do you want to give it a try (it should be a relatively simple intro PR assuming you know how to write `try-catch` and handle potentially varying error types and messages)

**Comment by nathanrboyer** [comment]
I'll give it a shot.

**Comment by nathanrboyer** [comment]
If someone else gets to this before me, they can go ahead. It's still on my to-do list, but it may be several more months before I get time to start working on this.

**Comment by bkamins** [comment]
Done in https://github.com/JuliaData/DataFrames.jl/pull/2966

**Comment by nathanrboyer** [comment]
Thanks! Sorry I haven't been able to work on anything lately.
