### ISSUE TITLE
Allow select and select! to operate on DataFrameRows?

### ISSUE THREAD

**Issue by eirikbrandsaas** [JuliaData/DataFrames.jl#2947]
Is there a reason why select doesn't work on DataFrameRows?
```Julia
 df = DataFrame(x=[1,2],y=[2,3],z=[3,4]) # create DataFrame
 select(df,[:x,:y]) # Works
 select(df[1,:],[:x,:y]) # Doesn't work

```

FWIW, this is on Julia 1.5.3, DataFrames 1.2.2, on a clean environment.

**Comment by bkamins** [comment]
`select` etc. work on data structures that are collections of vectors.

`DataFrameRow` is a collection of scalars. Best think of `DataFrameRow` as a mutable `NamedTuple` that is a view to its parent data frame.

The API design behind `select` etc. fundamentally relies on a fact that it operates on vectors not on scalars.

What would be your use case for `select` on `DataFrameRow`? If you just want to select some columns use column selector like `dfr = df[1, :]` and then `df[your_column_selector]` to get a subsetted `DataFrameRow`.

**Comment by eirikbrandsaas** [comment]
Hm, I see. What I wanted to do was: `select(df,Not([:x,:y]))` in a larger DataFrameRow. The `Not()` syntax is very convenient, and I don't know of anything similar for a DataFrameRow. 

If you ask me "why do you have a `DataFrameRow`"? Because I wanted one specific row of a DataFrame, so I did `dfr = DataFrame[iSpecific,:]` which creates a DataFrameRow.  But then later on in my code I want to drop some of the columns by name, hence the `select!(dfr,Not([:x1,:x2])).

For now, I'm instead doing `Dataframe[iSpecific:iSpecific,:]` which keeps `dfr` as a DataFrame, but looks pretty dumb.

**Comment by bkamins** [comment]
But why you do not just do `dfr[Not(:x1, :x2)]`? You can index-into `DataFrameRow` using all the column selectors that work elsewhere.

**Comment by eirikbrandsaas** [comment]
Well, I guess the reason is that I was converting code I had used for a `DataFrame`, and then didn't really think too hard. Didn't even consider it... Thanks, and sorry for opening this silly issue.

**Comment by bkamins** [comment]
No problem. If you have any further questions please ask.
