### ISSUE TITLE
Could it be useful to add the ungroup keyword to the filter function? 

### ISSUE THREAD

**Issue by sprmnt21** [JuliaData/DataFrames.jl#2954]
In the following dataframe, you want to remove all `id`'s with all missing values in `dv`.
A solution is found using the filter function, in this case the ungroup keyword would be useful to decide whether to have a dataframe or a GroupedDataFrame as a result.

```
df = DataFrame(id = [1,1,2,2,3,3, 4, 4], dv = [1,missing, missing, missing, 2, missing, missing, missing])
filter(x -> !all(ismissing, x.dv), groupby(df,[:id]))

```
The solution, suggested by nalimilan [here](https://app.slack.com/client/T68168MUP/C674VR0HH/thread/C674VR0HH-1638222801.378500), is currently simple and fast, but it may not be as easy for users to find, compared to a keyword that does just that. 

```
filter(fun, gdf::GroupedDataFrame)
filter(cols => fun, gdf::GroupedDataFrame)
```

**Comment by bkamins** [comment]
Can you pass the solution that @nalimilan provided explicitly so that I can assess it? Thank you!

In general:
* `filter` has a concrete contract in Julia Base and that is the reason it does not ungroup; we do not want to add too much functionality to `filter` because of this;
* it is easy to create a `DataFrame` from a `GroupedDataFrame` by passing it to a `DataFrame` constructor;
* `subset` function supports `ungroup` as you probably know so alternatively one can use the `subset` function.

Let us wait what other users think.

**Comment by sprmnt21** [comment]
I report in full the solution proposed by @nalimilan with the addition of his comment about it.
> It could make sense to add ungroup, but the implementation will probably be exactly the same as DataFrame(filter(...)) so it wouldn't really make a big difference. Feel free to file an issue to discuss this though.

**Comment by sprmnt21** [comment]
> subset function supports ungroup as you probably know so alternatively one can use the subset function (however it admittedly works a bit differently).
Yes, even with subset you can find a way to solve the problem. 
An example follows, of what I proposed.

`subset(select(groupby(dd,[:id]),:dv=>(x->!all(ismissing.(x)))=>:filter,:dv),:filter)`

But using filter on the GroupedDataFrame seems preferable to me

**Comment by bkamins** [comment]
Yes - so as @nalimilan said `DataFrame` is even shorter to write than `ungroup=true`. The issue is discoverability as you have commented.

As said - let us wait for other users to comment. Thank you!

**Comment by sprmnt21** [comment]
> * `filter` has a concrete contract in Julia Base and that is the reason it does not ungroup; we do not want to add too much functionality to `filter` because of this;

Could this functionality be delegated to a new `_subset_ `method? It acts on subgroups and by default brings out a dataframe, for example.

**Comment by nalimilan** [comment]
Yeah, supporting `ungroup` wouldn't be really shorter nor faster, but it would be more consistent with other functions and maybe easier to discover. So far we haven't given `filter` too much love as `subset` is more convenient in many cases, but maybe `filter` can be useful in its own right to select whole groups.

**Comment by bkamins** [comment]
OK - I will tag it for 1.4 release, as now we have feature freeze for 1.3 release.
