### ISSUE TITLE
Error message for "Number of returned columns does not match"

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/DataFrames.jl#2959]
Sometimes I get

```
ArgumentError: Number of returned columns does not match the length of requested output
```

I would like to know how many columns were expected and received, and what types they were, if available. It will help me debug my problem.

**Comment by bkamins** [comment]
Providing returned values could spam the terminal + would not be very informative unfortunately (we perform heavy internal transformations), but I can give you number of columns - expected and produced. See #3009

**Comment by jtrakk** [comment]
> Providing returned values could spam the terminal

Since this only occurs during an unrecoverable error, wouldn't it only be printed once?

**Comment by bkamins** [comment]
It would be printed once, but potentially it can be very wide. Also, as commented, the type of the internal value that is processed is most likely not the type you think it is (most of the time it is `DataFrame`).
