### ISSUE TITLE
The style is wrong of show(data_df; tf=tf_markdown) 

### ISSUE THREAD

**Issue by zsz00** [JuliaData/DataFrames.jl#2963]
show(data_df; tf=tf_markdown) 

![image](https://user-images.githubusercontent.com/12711073/145750249-4e716f03-17c5-41c8-ad01-5c99810ff6bc.png)

The printed style is not tf_markdown. 

I change the tf with tf_markdown, tf_mysql..  the table style is same.

**Comment by bkamins** [comment]
Use `pretty_table(data_df, tf=tf_markdown)` to get what I assume you want.

The `show` method has more defaults than only `tf` kwarg. What I assume you suggest is that in case `tf` kwarg is passed other kwargs should be ignored. @ronisbr is the best to judge if this is feasible/makes sense.

**Comment by zsz00** [comment]
Use pretty_table(data_df, tf=tf_markdown)  I get what I  want. 

but show() is not meeting expectations.

**Comment by bkamins** [comment]
The reason is - as commented - that `show` overrides many default settings of `pretty_table`. Of course you can re-set them manually by passing appropriate kwargs, but maybe if `tf` kwarg is passed to `show` we should re-set these options by default. I am sure @ronisbr can clarify this.

**Comment by ronisbr** [comment]
Hi @zsz00 

@bkamins is right. The printing configuration in DataFrames is heavily configured to meet the desire output. When you pass `tf = tf_markdown`, you are just changing the format of the table, but all the custom configurations remain. IMHO, for those cases, it is way better to just call `pretty_tables`. Adding an option to reset all the configurations inside of DataFrames seems a step in the wrong direction I think.

**Comment by bkamins** [comment]
I agree. Let us just close it then. When users want to customize printing they can use `pretty_table` and this is the general recommendation then.
