### ISSUE TITLE
Arrow Notation within Column Selection is Inconsistent

### ISSUE THREAD

**Issue by HiramTheHero** [JuliaData/DataFrames.jl#2969]
Hello all.

Thank you for your hard work with DataFrames.jl. I've been working on a package to have R data.table like syntax with DataFrames. One of the features is to add Arrow Notation into column Selection. To my surprise this is already allowed by DataFrames.jl (although it is inconsistent). I'm not sure if this behavior is intended or not.

Package Environment:
```
@v1.7) pkg> status
      Status `~/.julia/environments/v1.7/Project.toml`
[a93c6f00] DataFrames v1.3.0
[ce6b1742] RDatasets v0.7.6
```
Dataset I will be using:
```
using Statistics;
using DataFrames;
using RDatasets;
iris = RDatasets.dataset("datasets", "iris");
```
Column selection and basic arrow notations are allowed if wrapped in brackets.
```
julia> iris[:, [:SepalLength] ] # Allowed
150×1 DataFrame
 Row │ SepalLength 
     │ Float64     
─────┼─────────────
   1 │         5.1
   2 │         4.9
   3 │         4.7
   4 │         4.6
   5 │         5.0
  ⋮  │      ⋮
 147 │         6.3
 148 │         6.5
 149 │         6.2
 150 │         5.9
   141 rows omitted
```
```
julia> iris[:, [:SepalLength => mean] ] # Allowed
150×1 DataFrame
 Row │ SepalLength_mean 
     │ Float64          
─────┼──────────────────
   1 │          5.84333
   2 │          5.84333
   3 │          5.84333
   4 │          5.84333
   5 │          5.84333
  ⋮  │        ⋮
 147 │          5.84333
 148 │          5.84333
 149 │          5.84333
 150 │          5.84333
        141 rows omitted
```
Combination of the two are not allowed:
```
julia> iris[:, [:SepalLength, :SepalLength => mean] ] # Not Allowed
ERROR: ArgumentError: mixing `Symbol`s with other selectors is not allowed
```
More Complex Arrow Notation is allowed as long as **all elements** in the vector are arrow notation (Pair Type). I haven't checked all possible cases, this is just from my initial testing:
```
julia> iris[:, [names(iris, r"Sepal") => (+) => :sepal_sum, :Species => :SPECIES ] ] # Allowed
150×2 DataFrame
 Row │ sepal_sum  SPECIES   
     │ Float64          Cat…      
─────┼────────────────────────────
   1 │             8.6  setosa
   2 │             7.9  setosa
   3 │             7.9  setosa
   4 │             7.7  setosa
   5 │             8.6  setosa
  ⋮  │        ⋮             ⋮
 147 │             8.8  virginica
 148 │             9.5  virginica
 149 │             9.6  virginica
 150 │             8.9  virginica
                  141 rows omitted
```
While using multiple column selection is allowed, wrapping the multiple column selection in brackets is not allowed.
```
julia> iris[:, r"Sepal" ] # Allowed
150×2 DataFrame
 Row │ SepalLength  SepalWidth 
     │ Float64      Float64    
─────┼─────────────────────────
   1 │         5.1         3.5
   2 │         4.9         3.0
   3 │         4.7         3.2
   4 │         4.6         3.1
   5 │         5.0         3.6
  ⋮  │      ⋮           ⋮
 147 │         6.3         2.5
 148 │         6.5         3.0
 149 │         6.2         3.4
 150 │         5.9         3.0
               141 rows omitted
```

```
julia> iris[:, [r"Sepal"] ] # Not Allowed
ERROR: ArgumentError: idxs[1] has type Regex; only Integer, Symbol, or string values allowed when indexing by vector
```
Row Filtering with Arrow Notation is not allowed:
```
julia> iris[iris.SepalLength .> 5, [:SepalLength => mean] ]
ERROR: ArgumentError: idxs[1] has type Pair{Symbol, typeof(mean)}; only Integer, Symbol, or string values allowed when indexing by vector
```

So, a couple of thoughts.

If the behavior of using arrow notation is an intended feature then it needs to allow all cases that are permissible within the `select` , `combine` , and `transform` functions. Such as, `iris[:, [:SepalLength, :SepalLength => mean] ]` having the same meaning as `select(iris, :SepalLength, :SepalLength => mean)`. Also, row indexing with arrow notation should be allowed.

If this is not an intended feature, then I believe the issue may be with allowing the `MultiColumnIndex` type defined in src/other/index.jl to include the `AbstractVector` data type. To my understanding the `AbstractVector` datatype is only intended to be used if a vector of `Pair`, `Int`, and `String` is passed in. If so, I think replacing `AbstractVector` with `Vector{<:Pair}` , `Vector{<:Int}`, and `Vector{<:String}` may have the intended effect.

I am pretty new to all of this, and I am certainly not above proficient on this package nor with Julia. So if I am missing information as to why this is implemented the way it is or if I lead anyone astray, I apologize. Please let me know if you need anymore information.

Thank you all for your time and work.

**Comment by bkamins** [comment]
Thank you for reporting this. It is a serious bug. Its source is that in the past `select` has not allowed `Pair` notation and back then the `getindex` implementation was correct, but later `select` got more powerful, but we forgot to update `getindex` to reflect this.

See #2970 for the fix.

In short `iris[:, [:SepalLength => mean] ]` should be disallowed for exactly the reasons you mention (i.e. allowing it would create too much inconsistency and user confusion).

Now regarding why I did not do:

> I think replacing `AbstractVector` with `Vector{<:Pair}` , `Vector{<:Int}`, and `Vector{<:String}` may have the intended effect.

but rather used a different strategy. The point is that user can e.g. pass `Any[1, 2, 3]`. This is a valid selector, but unfortunately its `eltype` is too wide, still we want to accept it (and your proposal would reject it).

Thank you for looking into this issue so carefully.
