### ISSUE TITLE
Function to insert columns

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/DataFrames.jl#2972]
I would like an `insertcols` function that does not mutate the input df so I don't have to manually `copy(df)` before using it.

Tbh I think the `insertcols!` API could use some cleanup anyway, so probably this function should get a different name too. For example:

- `outputname=>val` is unusual for DataFrames.jl functions.
- `after::Bool` seems awkward. A more general position API would be nicer.

**Comment by bkamins** [comment]
I think we can add `insertcols`. I was also thinking about it.

Regarding your two proposals:

> `outputname=>val` is unusual for DataFrames.jl functions.

It is the same as for `DataFrame` constructor. Indeed it is unfortunately a bit inconsistent for the legacy reasons. What would be your proposal for the API (bearing in mind also the `DataFrame` constructor)

> `after::Bool` seems awkward.

Could you please clarify what you exactly propose?

**Comment by jtrakk** [comment]
In general I don't really like boolean keyword parameters. They can often be refactored, either split into two functions, or the boolean can be generalized into a handler.


dplyr has recently added [`before/after` parameters](https://dplyr.tidyverse.org/reference/mutate.html) that take a column-selector argument. I think that's a good idea. I'm not sure if these are quite right but the basic idea is:


Setting positions separately:

```jl
addcols(df, rand(nrow(df)) => BeforeCols(:bar) => :foo)
```
or together:
```jl
addcols(df, rand(nrow(df)) => :foo, rand(nrow(df)) => :bar; position=AfterCols(r"baz"))
```

or just

```jl
DataFrame(df, foo=rand(nrow(df)) => AfterCols(r"baz"))
```
