### ISSUE TITLE
Investigate performance of innerjoin between large tables

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2974]
In https://h2oai.github.io/db-benchmark/ benchmark query 5 when missing data is present we have a significant performance drop from what should be expected. This should be investigated.

CC @nalimilan @oscardssmith

**Comment by bkamins** [comment]
@oscardssmith - would it be a problem on your side to report for query 5 for the scenario of 5% NA data (for the 1e8 and 1e9 scenarios):
* what are types of all columns in both data frames (e.g. `mapcols(typeof, DF)` and `mapcols(typeof, big)` produces this)
* the result of `describe(DF, :all)` and `describe(big, :all)`

Thank you!

**Comment by bkamins** [comment]
I have reproduced the 1e8 test on my laptop. Interestingly my timings are faster than reported by @oscardssmith (not by much):
```
julia> @time ANS = innerjoin(x_df, big_df, on = :id3, makeunique=true, matchmissing=:equal);
 47.928528 seconds (6.12 k allocations: 9.943 GiB, 2.27% gc time, 0.07% compilation time)
```

I have identified the source of the problem. The issue is that in this benchmark in `:id3` column there are many (5%) duplicates in the `x_df` column (that is of `Union{Int, Missing}` type).

I would leave fixing it as to-do for optimization in the future (there are several things we could do to speed things up like: if one key does not allow missing but the other key allows them then we can ignore `missing`s in `innerjoin` as they are guaranteed not to match; but as you can see such optimization is targeted at very specific scenario so I have to think if we want to add it).

**Comment by consumere** [comment]
I'm on Julia Version 1.9.3 Windows, 32GB RAM, i7-7700 CPU @ 3.60GHz
DataFrames v1.6.1, 
VSCode Version: 1.84.2

got 30 tsv files in current folder of total size of 46.30 MB.
each file has 2 cols (date, and name) and 47488 lines.
running this code, windows consumes all of my RAM and freezes eventually.

` df = reduce((left, right) -> 
        innerjoin(left, right, on = :date,
            makeunique=true), 
        files)`
  
this is quite unexpected.

**Comment by bkamins** [comment]
Can you please provide more details?

First, if also:
```
innerjoin(files..., on = :date, makeunique=true)
```
fails.

If it also fails then if the following fails:
```
df = files[1] # assuming files is Vector
for i in 2:length(files)
    @show i
    global df = innerjoin(df, files[i], on = :date, makeunique=true)
end
```
(and if it fails when it stops)

Thank you.

**Comment by consumere** [comment]
Hello @bkamins 
Thank you for your quick response.
I switched to WSL Julia 1.8.5 DataFrames v1.6.1 w memory restrictions, since windows would freeze again.

i also cleaned up to 25 files, since there were some empty tsv files...
read-in to a vector of DFs works fine using this function:

`
function waread(x::String)
    """
    Read the text file, preserve line 1 as header column
    """
    ms = ["-9999","lin","log","--"]
    df = CSV.read(x, DataFrame; 
        delim="\t", header=1, missingstring=ms, 
        maxwarnings = 1, #silencewarnings = true,
        normalizenames=true, types=Float64)
    df = dropmissing(df, 1)
    dt2 = map(row -> Date(Int(row[1]), Int(row[2]), Int(row[3])), eachrow(df))
    df.date = dt2
    df = select(df, Not(1:4))
    DataFrames.metadata!(df, "filename", x, style=:note)
    for x in names(df)
        if startswith(x,"_")
            newname=replace(x,"_"=>"C", count=1)
            rename!(df,Dict(x=>newname))
        end
    end
    return df 
end

files = map(waread,glob(rgx))
`
your first suggestion errors julia almost immediately, the 2nd stops at step 21 (of 24)
i = 20
i = 21
i uploaded the data here:
[https://gigamove.rwth-aachen.de/de/download/45eb2cf53205970b7110f8374d3db7a6](url)

**Comment by bkamins** [comment]
I have checked your data. The problem is that indeed you run out of memory. The reason is that you have duplicate entries in `:date` column, which leads to an exponential explosion of number of rows generated.

If I de-duplicate source files, the process is fast (I just used `unique`, but you might choose another deduplication method):
```
julia> @time innerjoin(unique.(files, :date)..., on = :date, makeunique=true);
  0.396113 seconds (10.22 k allocations: 193.982 MiB)
```

**Comment by consumere** [comment]
Thank you for clarification. 
I certainly missed that point.
