### ISSUE TITLE
Replace and Missing Values

### ISSUE THREAD

**Issue by alfaromartino** [JuliaData/DataFrames.jl#2976]
I've been finding the new developments of DataFrames 1.3 quite useful in terms of missing values. I found this crucial since my experience as a Julia user is that working with missing values in DFs is really painful (I'll write more about it soon, in case my experience could be helpful for the developers).

I have questions about two functions and wanted to know whether which is inconsistent or any alternative would create some issues. I deal with `replace` in this question, and `subset` in a separate thread.

The MWE is as follows 
```julia
df=DataFrame(a=[nothing,1,3],b=["he,llo","xx","yy"],c=[missing,"hello","he,llo"])
```
Next, each line is executed with `df` as the original dataframe

```julia
#I'll use `nothing` as an example, but it's actually the same with missing values
df.a=replace.(df.a,nothing=>2) #it doesn't work
replace!(df.a,nothing=>2) #it works
df.a=replace(df.a,nothing=>2) #it works

df.b=replace(df.b,","=>"") #it does nothing
replace!(df.b,","=>"") #it does nothing
df.b=replace.(df.b,","=>"") #it works
```

At first I thought that the difference was that `nothing` is a type, but actually
```julia
df.a=replace.(df.a,3=>2) #error
df.a=replace(df.a,3=>2) #it works
```
and to end up more confused:
```julia
df.c=replace.(df.c,","=>"") #error
df.c=replace(df.c,","=>"") #it does nothing
replace!(df.c,","=>"") #it does nothing
df.c.=replace.(df.c,","=>"") #error
```
This is why I end up frustrated by dealing with missing values in julia: to be sure that it works I end up using an `if`, which is quite verbose:
```julia
[( (ismissing(df.c[i])==0) && (df.c[i]=replace(df.c[i], "," => "")) ) for i in eachindex(df.c)]
```

Thanks

**Comment by bkamins** [comment]
Use:
```
julia> using Missings

julia> passmissing(replace).(df.c,","=>"")
3-element Vector{Union{Missing, String}}:
 missing
 "hello"
 "hello"
```
maybe this post will help you: https://bkamins.github.io/julialang/2021/09/03/missing.html.

The issue is unrelated to DataFrames.jl, it should rather be discussed in https://github.com/JuliaData/Missings.jl if something is not clear for you here or would need an improvement. Thank you for reporting!
