### ISSUE TITLE
Subset and Missing Values

### ISSUE THREAD

**Issue by alfaromartino** [JuliaData/DataFrames.jl#2977]
I wanted to know whether this is what we should expect to get, or it's some inconsistency.

```julia
df=DataFrame(a=[missing,1,0],b=[1,2,3])
dfs=subset(df,:a=>(x->(!isequal).(x,1)),view=true,skipmissing=true)
```
yields

```julia
2×2 SubDataFrame
 Row │ a        b     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │       0      3
```
while
```julia
df=DataFrame(a=[missing,1,0],b=[1,2,3])
dfs=subset(df,:a=>(x->x.!=1),view=true,skipmissing=true)
```
produces

```julia
2×2 SubDataFrame
Row │ a       b     
     │ Int64?  Int64 
─────┼───────────────
   1 │      0      3
```

**Comment by bkamins** [comment]
This is expected.

The `x->(!isequal).(x,1)` test does not produce missing values so `skipmissing=true` does not affect the result.

The `skipmissing` kwarg is added to support cases when `missing` can be returned by the logical test, like in `x->x.!=1` in your second case.

In summary: `skipmissing` looks at the *output* of the operation not at the *input*.

In general, if you want to avoid too much magic in your code use:
```
subset(df,:a=>ByRow(x -> coalesce(x == 1, true)))
```
to keep rows that produce `missing` and
```
subset(df,:a=>ByRow(x -> coalesce(x == 1, false)))
```
to drop them.

Using `coalesce` is most explicit and even if someone does not know the details of how the `subset` function works it should be self explanatory.
