### ISSUE TITLE
Integer as destination in `src => fun => dest`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#2985]
Motivated by [this discourse discussion](https://discourse.julialang.org/t/recommended-way-to-select-multiple-dataframe-columns-parametrically-i-e-not-by-the-names/74220)

MWE:

```
julia> df = DataFrame(a = [1, 2]);

julia> transform(df, :a => (identity => 1))
ERROR: ArgumentError: Unrecognized column selector: :a => (identity => 1)
```

**Comment by bkamins** [comment]
@pdeffebach I am not sure what you would want to achieve here. How should `1` as target column name be interpreted (as it is an invalid column name)?

Do you mean `transform(df, :a => (identity => "1"))` or `transform(df, :a => identity, renamecols=false)` or `transform(df, :a => (identity => identity))`?

**Comment by pdeffebach** [comment]
`1` should be interpreted as positional. `renamecols` solves the problem where `src` and `dest` are the same integer. But if they were different one might want to write

```
2 => f => 1
```

to take the 2nd column, apply `f`, then stick the result in the 1st position. 

fwiw I don't think this is a good idea or a feature that should be added at the point. Closing, at least we can point to this issue in the future if needed. 


to take the 2nd column

**Comment by bkamins** [comment]
> stick the result in the 1st position.

position is determined by the order of transformations passed. The problem is that if you pass `1` as output position there is no way to determine what should be the name of this column (note that the name is for NEW data frame, which is initially empty)
