### ISSUE TITLE
`first(gdf::GroupedDataFrame, n::Int)` should give a `GroupedDataFrame`?

### ISSUE THREAD

**Issue by ericphanson** [JuliaData/DataFrames.jl#2993]
`first(df::DataFrame, n)` gives a `DataFrame` with the first `n` rows (and doesn't error if `n > nrow(df)`, matching Base). It would be nice if `first(gdf, n)` gave the first `n` groups (without erroring if `n` is more than the number of groups). Currently, it gives a `Vector{Any}`. However, one can do `gdf[1:min(n, end)]` instead.

I suppose this might be breaking, in which case it would be a request for DataFrames 2.0.

**Comment by bkamins** [comment]
Makes sense. Same with `last`. It should be an easy PR. Do you want to give it a try (otherwise I will add it).

It is not breaking I think as `first` contract in Base Julia does not specify output collection type.

Thank you for the suggestion.
