### ISSUE TITLE
unstack fails without an id column

### ISSUE THREAD

**Issue by fredcallaway** [JuliaData/DataFrames.jl#2994]
`unstack` does not correctly handle the case where all columns are either variable or value (such that the result should be one row).

Desired behavior (dplyr):
```r
df = tibble(x=c("one", "two"), y=c(1,2))
spread(df, x, y)
# A tibble: 1 × 2
    one   two
  <dbl> <dbl>
1     1     2
```

DataFrames.jl:
```julia
df = DataFrame(x=[:one, :two], y = [1, 2])
unstack(df, :x, :y)
ERROR: ArgumentError: No key column found
```

Adding another column `z=[0,0]` produces the expected result, but this shouldn't be necessary.r

EDIT: I now see that this might be intended. The error message "No key column found" was inscrutable to me because the I thought it was referring to the column key.  I think this case should be handled as it is in dplyr, but at the very least, the error message should specify that no _row_ key column was found.

**Comment by bkamins** [comment]
So you want the following behavior from `dplyr`?:
```
> fish_encounters[,2:3] %>% pivot_wider(names_from = station, values_from = seen)
# A tibble: 1 x 11
  Release    I80_1      Lisbon     Rstr       Base_TD    BCE       BCW       BCE2      BCW2      MAE       MAW      
  <list>     <list>     <list>     <list>     <list>     <list>    <list>    <list>    <list>    <list>    <list>   
1 <int [19]> <int [19]> <int [13]> <int [12]> <int [11]> <int [8]> <int [8]> <int [7]> <int [7]> <int [5]> <int [5]>
Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates 
```

**Comment by fredcallaway** [comment]
Thanks for the quick response! Looks like this issue will be resolved, will respond to duplicate handling in the pull request.
