### ISSUE TITLE
sort order with ties

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3008]
We currently have:
```
julia> using DataFrames

julia> df = DataFrame(a=1:6, b=1)
6×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      1
   2 │     2      1
   3 │     3      1
   4 │     4      1
   5 │     5      1
   6 │     6      1

julia> sort(df, :b)
6×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      1
   2 │     2      1
   3 │     3      1
   4 │     4      1
   5 │     5      1
   6 │     6      1

julia> sort(df, :b, rev=true)
6×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      1
   2 │     2      1
   3 │     3      1
   4 │     4      1
   5 │     5      1
   6 │     6      1
```
I was not sure if this is desired. In short - what should be the sort order of tied rows when `rev=false` vs `rev=true`?

**Comment by nalimilan** [comment]
At least we are consistent with Base:
```julia
julia> sortperm(fill(1, 6))
6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

julia> sortperm(fill(1, 6), rev=true)
6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
```

Also note this also works when mixing with other values:
```julia
julia> sortperm([1, 2, 2, 2, 3], rev=true)
5-element Vector{Int64}:
 5
 2
 3
 4
 1
```

I guess this is consistent with the definition of stable sort, i.e. the relative order of rows with equal values is preserved. A possible alternative definition would be that their order is reversed when `rev=true` but I'm not sure this definition exists anywhere.

**Comment by bkamins** [comment]
This is exactly what I have checked and thought also. Do you think we should close it then or dig further?

**Comment by bkamins** [comment]
Yes - we inherit it. Closing
