### ISSUE TITLE
Add keyword argument `source` in `mapreduce` to match `reduce`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#3016]
We currently have a keyword arguments in `reduce` to match those in `vcat`. 

[This Discourse issue](https://discourse.julialang.org/t/mapreduce-pass-extra-arguments-to-reduce-vcat-of-dataframes/77347/11) indicates maybe we should do the same for `mapreduce`. 

But as mentioned on the thread, a `Generator` works very well.

**Comment by bkamins** [comment]
It was already considered when `reduce` was added.

I am not closing this because maybe I miss something. What exactly signature would you propose for `mapreduce`?

For `reduce` we have a signature:
```
reduce(::typeof(vcat), dfs::Union{Tuple{AbstractDataFrame, Vararg{AbstractDataFrame}}, AbstractVector{<:AbstractDataFrame}}; cols, source)
```
which is OK, because it does not do type-piracy.

What signature do you imagine for `mapreduce` (I think it is not doable, but I might be wrong)?

**Comment by pdeffebach** [comment]
Ah I see. We would be restricting ourselves to `map`ing over a vector of DataFrames. But if the input is not a vector of data frames, like in OP's example, we would have to commit type piracy. 

This is a good point. 

But given this signature, it means a generator *also* won't work

```
julia> t = (DataFrame(a = 1) for i in 1:5);

julia> reduce(vcat, t; source = "id")
ERROR: MethodError: no method matching mapfoldl(::typeof(identity), ::typeof(vcat), ::Base.Generator{UnitRange{Int64}, var"#3#4"}; source="id")
```

Maybe we need our own `bind_rows` function... which is disappointing.

**Comment by bkamins** [comment]
The problem with `bind_rows` (or whatever other name) is that still it is problematic to make it efficient. I.e. if your `map` step produces data frames then just doing `map` and next doing `reduce` is anyway fastest what you can do. There would be no performance benefit of trying to squeeze it into one function.

What I mean is that what OP wrote:
```
f(p) = DataFrame(x = collect(1:10), y = p[1]*rand(10), z = p[2]*rand(10))  
tmp = map(f, ([1,2], [3,4], [5,6]))
all = reduce(vcat, tmp, source="id")
```
is essentially almost optimal performance wise. So the benefit would be only syntax, but you can just write:
```
reduce(vcat, map(f, ([1,2], [3,4], [5,6])), source="id")
```
which is not that bad I think.

The only better thing would be to have `mapreduce` supported, but this is not possible (adding a new name is not a solution as then users would need to learn it which is unlikely that they would even notice such a rarely needed function).

Given all this discussion I think we can close the issue.

**Comment by pdeffebach** [comment]
Thanks for the discussion!
