### ISSUE TITLE
Fix describe documentation

### ISSUE THREAD

**Issue by DanDeepPhase** [JuliaData/DataFrames.jl#3018]
describe documentation at https://docs.juliahub.com/DataFrames/AR9oZ/0.21.7/lib/functions/#DataAPI.describe

> stats::Union{Symbol, Pair}... : the summary statistics to report. Arguments can be:
> ...
>    A name => function pair where name is a Symbol or string. This will create a column of summary statistics with the provided name.

and then later, and example given is:
`julia> describe(df, :min, :sum => sum)`

This doesn't work for me, however, reversing it to "function => name pair" works

```julia
julia> df = DataFrame(i=1:10, x=0.1:0.1:1.0, y='a':'j')
10×3 DataFrame
 Row │ i      x        y    
     │ Int64  Float64  Char 
─────┼──────────────────────
   1 │     1      0.1  a    
   2 │     2      0.2  b    
  ⋮  │   ⋮       ⋮      ⋮   
  10 │    10      1.0  j    
              7 rows omitted

julia> describe(df, :min, :sum => sum)
ERROR: MethodError: no method matching describe(::DataFrame, ::Symbol, ::Pair{Symbol, typeof(sum)})
Closest candidates are:
  describe(::AbstractDataFrame, ::Union{Symbol, Pair{<:Union{Function, Type}, <:Union{AbstractString, Symbol}}}...; cols) at \DataFrames\BM4OQ\src\abstractdataframe\abstractdataframe.jl:602
  describe(::AbstractDataFrame; cols) at \DataFrames\BM4OQ\src\abstractdataframe\abstractdataframe.jl:605
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1

julia> describe(df, :min, sum => :arbitrarynamesum)
3×3 DataFrame
 Row │ variable  min  arbitrarynamesum 
     │ Symbol    Any  Union…
─────┼─────────────────────────────────
   1 │ i         1    55
   2 │ x         0.1  5.5
   3 │ y         a   
```

**Comment by DanDeepPhase** [comment]
my version is DataFrames v1.3.1

**Comment by bkamins** [comment]
Please update to DataFrames.jl v1.3.2 in which the outdated docstring is fixed.

**Comment by bkamins** [comment]
Also note that your link https://docs.juliahub.com/DataFrames/AR9oZ/0.21.7/lib/functions/#DataAPI.describe is to 0.21.7 version of the documentation. Use: https://docs.juliahub.com/DataFrames/AR9oZ/1.3.2/lib/functions/#DataAPI.describe

**Comment by bkamins** [comment]
(actually in 1.3.1 the docstring is OK, the problem was your link to the documentation)

**Comment by DanDeepPhase** [comment]
Thanks! I probably got there by searching google: "julia dataframes describe" and not checking the version after following the link. When i did that today i got to the latest version.

Sorry for the bother.
