### ISSUE TITLE
subset(df) with no conditions should return unaltered DataFrame

### ISSUE THREAD

**Issue by nielsls** [JuliaData/DataFrames.jl#3024]
Currently, `subset`/`subset!` requires at least one condition when filtering a DataFrame. However, this seems like an unneccesary constraint.

```
julia> subset(df)
ERROR: ArgumentError: at least one condition must be passed
```

Instead, when there are no constraints the original DataFrame should just be returned (*or a copy of the original in the case of subset*).

In general, the subset operation keeps all rows for which `all(conditions) == true` (applied for each row). Hence, passing no conditions is an implicit `true` for keeping all rows - just as `all(Bool[]) == true`.

This would allow logic e.g. where different conditions could be pushed arbitrarily to a vector `args`. And then, the following would work even when `args` is empty:
```
julia> subset(df, args...)   # valid for empty args
```

**Comment by bkamins** [comment]
The decision to disallow this was conscious to avoid possible mistakes on users' side.
However, there is no problem to lift this restriction.
(implementation note: there is a slight care that needs to be taken when we consider `GroupDataFrame` case)

@nalimilan - do you have an opinion on this?

**Comment by nalimilan** [comment]
Makes sense. Again we might have been too defensive (which is OK as a development strategy).

@nielsls Have you bumped into this in a real use case?

**Comment by bkamins** [comment]
second implementation note: corner case when source has no columns (easy, but needs to be taken care of separately)

**Comment by nielsls** [comment]
@nalimilan Yes - this is my current code:
```
if !isempty(instrumentfilter)
    subset!(holdings, df_filter.(instrumentfilter)...)
end
```
I have a library where the user can load stuff and supply filters(s). But the user can also choose to just load "everything" - hence, there are no filters to be applied. 
As such, the "mathematical inconsistency" with e.g. `all(Bool[]) == true` and `prod(Int64[]) == 1` caught me by surprise. In other words, I would have thought the subset of all rows is also a valid subset.
But then again - it's no a big deal in practical terms - the above code works just fine :)

**Comment by nielsls** [comment]
By the way, I can see that this actually works without args:
```
df = DataFrame(a=[1,2,3])
transform(df) # copy
select(df) # empty dataframe
```

**Comment by bkamins** [comment]
yes, also `combine` works.
