### ISSUE TITLE
make `clipboard(df)` work

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#3045]
I know about ClipData.jl, but it doesn't seem like that works from Julia -> Julia.

I have one REPL with a DF and I have another that I want it in. I usually use `clipboard` to move data between REPLs, but with DataFrame it just gives a view, not evaluable code.

**Comment by bkamins** [comment]
`clipboard` is defined to:

>  Send a printed form of x to the operating system clipboard

so we cannot redefine it the way you propose (i.e. we need to send the printed version to system clipboard).

However, ClipData.jl works just fine:

Session 1:
```
julia> df = DataFrame(a=[1, 2], b=["x", "y"])
2×2 DataFrame
 Row │ a      b
     │ Int64  String
─────┼───────────────
   1 │     1  x
   2 │     2  y

julia> cliptable(df)
```

Session 2:
```
julia> DataFrame(cliptable())
2×2 DataFrame
 Row │ a      b
     │ Int64  String1
─────┼────────────────
   1 │     1  x
   2 │     2  y
```

**Comment by bkamins** [comment]
(please comment/reopen if this is not what you want)
