### ISSUE TITLE
nrow and ncol for DataFrameRows and DataFrameColumns

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3054]
@nalimilan:
Do we want `DataFrameRows` and `DataFrameColumns` to be considered to be Tables.jl tables and eg. define for them `nrow` and `ncol`?

**Comment by nalimilan** [comment]
What's the context of this? I don't see a strong reason not to do this but better have use cases before adding features?

**Comment by bkamins** [comment]
The context is https://github.com/JuliaData/Tables.jl/pull/278#issuecomment-1132706343. If we decide to add `nrow` and `ncol` support for Tables.jl tables in general and decide to treat these two types as tables (apart of treating `AbstractDataFrame` as table) then we should add this support.

**Comment by nalimilan** [comment]
OK. Let's wait until a decision is made in Tables.jl first?

**Comment by bkamins** [comment]
Yes, I just want to track this here.
