### ISSUE TITLE
Report return type of subset function in error message

### ISSUE THREAD

**Issue by jariji** [JuliaData/DataFrames.jl#3077]
`ArgumentError: functions passed to `subset` must return an AbstractVector.` It would be helpful to say what was returned instead.

**Comment by bkamins** [comment]
Do you want to see type or value (value can be problematic as it can have very large text representation).

Also do you have this error when working on data frame or grouped data frame (if it is the latter then the behavior is changed on `main`).

**Comment by jariji** [comment]
At least showing type would help.

**Comment by bkamins** [comment]
Fixed in #3079
