### ISSUE TITLE
documentation enhancement request

### ISSUE THREAD

**Issue by JakeZw** [JuliaData/DataFrames.jl#3086]
As a new to DataFrames user, it took me a while to figure out how to make a new column by doing an arithmetic operation on multiple columns.  After a while of digging I figured it out.  It may make this process easier if an example were included in the [documentation ](https://dataframes.juliadata.org/stable/man/working_with_dataframes/) under the select heading with the following example 

```
julia> df = DataFrame(b=[1,3,5],c=[2,4,6])
3×2 DataFrame
 Row │ b      c
     │ Int64  Int64
─────┼──────────────
   1 │     1      2
   2 │     3      4
   3 │     5      6

julia> select(df, :b, :c, [:c,:b] => ((c,b) -> c./b) => :d)
3×3 DataFrame
 Row │ b      c      d
     │ Int64  Int64  Float64
─────┼───────────────────────
   1 │     1      2  2.0
   2 │     3      4  1.33333
   3 │     5      6  1.2
```

Thanks

**Comment by bkamins** [comment]
see https://github.com/JuliaData/DataFrames.jl/pull/3087
