### ISSUE TITLE
make subset keep group order when `ungroup=false`

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3093]
Currently we just re-group.

**Comment by bkamins** [comment]
This is mildly breaking, but I think this is what users would expect.

**Comment by david-macmahon** [comment]
In the Julia `#data` Slack channel, a concern was expressed about `subset` potentially dropping groups which then complicates the design decision of whether to retain sort order after the `subset`.  I might be taking an overly simplistic view, but it seems like dropping groups and retaining sort order are orthogonal.  What we have now is potentially dropped groups and an unspecified order in the GDF returned by `subset`.  If we retain sort order, then we still have the potential for groups to be dropped by a `subset` call, but by retaining the sort order only the position(s) of the group(s) that followed the dropped group(s) will change, which seems preferable to a complete abandonment of the sort order.  Maybe there are corner cases I'm not seeing?

**Comment by bkamins** [comment]
> Maybe subset could get a `retainsort::Bool=false` keyword argument to let the user decide.

I would just make this change without this kwarg.

**Comment by david-macmahon** [comment]
That keeps it simpler.  I'm happy either way.

**Comment by bkamins** [comment]
I classified it as bug in the end as it was a TODO left (there was an inconsistency between `subset` and `subset!`; now they are consistent and this is tested). See #3094
