### ISSUE TITLE
add length (or nrow) to describe

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3095]
There are two natural cases in `describe` that are currently hard:
1. get the number of rows;
2. get the number of non-missing rows.

@nalimilan - would you have any preference here?

**Comment by nalimilan** [comment]
Computing the number of rows doesn't sound too useful as it's the same for all columns. But indeed computing the number of non-missing entries sounds useful and even if `length(::SkipMissing)` https://github.com/JuliaLang/julia/issues/42672 was implemented it could make sense to support e.g. `:nonmissing` or `:nnonmissing` for clarity.

**Comment by bkamins** [comment]
OK - let us go for `:nnonmissing` for consistency
