### ISSUE TITLE
VSCode linter does not recognize names method.

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#3109]
I'm not sure if this is a VSCode issue or a DataFrames issue, but I'm guessing DataFrames needs to somehow tell VSCode this is okay.

![image](https://user-images.githubusercontent.com/65452054/182198345-5b2b9b49-99a6-4a06-9295-76f1e79a461d.png)

The code works fine, but VSCode complains about the syntax. I tried wrapping the regular expression in `Col()`, but it didn't change anything.

**Comment by bkamins** [comment]
It is most likely false-positive, as probably VSCode does not recognize methods for `names` defined in DataFrames.jl.

@pfitzseb - where should this issue be transferred?

**Comment by pfitzseb** [comment]
This is probably a variant of https://github.com/julia-vscode/julia-vscode/issues/1576, so no need for a separate issue.

**Comment by nathanrboyer** [comment]
Okay, thanks.
