### ISSUE TITLE
filter is assigning value by mistake

### ISSUE THREAD

**Issue by gustavoespitia** [JuliaData/DataFrames.jl#3117]
Hello, I appreciate all your effort in developing and supporting DataFrames.jl

I've noticed some strange behavior in `filter`, it's assigning a value to the key column in the first row when a typo is made.

MWE: 
```
using DataFrames
df = DataFrame(a=1:5, b=11:15, c=21:25)
5×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1     11     21
   2 │     2     12     22
   3 │     3     13     23
   4 │     4     14     24
   5 │     5     15     25
```
If filter by row, for a=3 per example, one get the expected results:
```
filter(row -> row.a == 3, df)
1×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     3     13     23
```
But if a typo is made writing only one equal symbol in filter argument and then fix that, the filter results is other:
```
filter(row -> row.a = 3, df)
ERROR: TypeError: non-boolean (Int64) used in boolean context
(full error message omitted)

filter(row -> row.a == 3, df)
2×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     3     11     21
   2 │     3     13     23
```
As you can see, after correcting the typo, the result of `filter` is different from the first one, this seems to be because with the typo the filter is assigning a value to the first row:
```
df
5×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     3     11     21
   2 │     2     12     22
   3 │     3     13     23
   4 │     4     14     24
   5 │     5     15     25
```
This behaviour is observed in DataFrames v1.2.2, v1.3.4 and v1.4.0

Thank you for your attention, warm regards.

**Comment by bkamins** [comment]
This behavior cannot be fixed. `DataFrame` is intentionally mutable, which means it allows you to change values stored in it.
If you use `=` (assignment) then you mutate the contents of the row of the data frame.

If you want to avoid such risks use the following syntax:
```
filter(:a  => ==(3), df)
```
which is both faster and safer.

**Comment by gustavoespitia** [comment]
@bkamins thanks for your answer and suggestion.
