### ISSUE TITLE
Creating SubDataFrame from SubDataFrame is extremely slow

### ISSUE THREAD

**Issue by tcpie** [JuliaData/DataFrames.jl#3118]
Dear all,

I've found that creating a SubDataFrame from another SubDataFrame can be extremely slow (about **40x slower** than creating a SubDataFrame from a DataFrame, in my test example, see below). In my real usecase I'd like to keep all data in one main DataFrame, and work from there. Copying data back-and-forth is a no-go, as the amount of data will be very large.

Below is a silly example that illustrates the problem 

```
using DataFrames
using Random
using StatsBase

# Prep
n = Int64(1e5)
ys = randn(n)

df = DataFrame(ys = ys)
df.cat = repeat(["0"],n)
df.cat[df.ys .> 0] .= "B"
df.cat[df.ys .<= 0] .= "A"

df_a = @view df[df.cat .== "A",:]
ys_test = Vector{Float64}(df_a.ys)

# Some test functions
calc_running_mean(ys_::AbstractArray) = mean(ys_)
get_vector_view(df::AbstractDataFrame,ind::Int64) = (@view df[1:ind,:]).ys
get_vector_view(ys::AbstractArray,ind::Int64) = @view ys[1:ind]

function calc_running_mean_(input)

    rets = Float64[]

    for ind = 1:size(input)[1]
        input_view = get_vector_view(input,ind)
        ret = calc_running_mean(input_view)

        push!(rets, ret)
    end

    return rets
end

##
# Run with dataframe
@time ans1 = calc_running_mean_(df_a)

##
@time ans2 = calc_running_mean_(DataFrame(df_a))

##
# Run with vector
@time ans3 = calc_running_mean_(ys_test)

##
# Are results approximately equal?
ans1 ≈ ans2
```

The second run of each test case (to get rid of compilation lag) yields:

For SubDataFrame -> SubDataFrame
  4.352164 seconds (546.99 k allocations: 9.333 GiB, 10.78% gc time)

For DataFrame -> SubDataFrame
  0.102576 seconds (499.05 k allocations: 16.039 MiB)

For Vector -> SubArray
  0.090076 seconds (10 allocations: 812.672 KiB)

Clearly we obtain best performance working directly with vectors, instead of DataFrames. I have to admit that I am still a novice at Julia, so perhaps I am overlooking something simple, but I'm surprised by this discrepancy in performance. Would it be possible to address this issue?

EDIT:
These results are skewed in favor of SubDataFrame -> SubDataFrame performance. If we compare *just* the cost of creating a new view for all three cases (so commenting out most things in `calc_running_mean_`), then I arrive at about **700x** slower performance compared to DataFrame -> SubDataFrame, and about **1e5x** slower performance compared to Vector -> SubArray...

**Comment by bkamins** [comment]
It is not possible to address this issue in general. This feature is not something specific to DataFrames.jl. You will have the same problem with standard vectors:

```
julia> x = rand(10^6);

julia> xv = view(x, rand(Bool, 10^6));

julia> x2 = copy(xv);

julia> @time view(xv, 1:10^5);
  0.000280 seconds (3 allocations: 781.344 KiB)

julia> @time view(x2, 1:10^5);
  0.000006 seconds (1 allocation: 48 bytes)
```

What is the reason for this? When you create a view of a view it is "unnested" i.e. all indices need to be recalculated to point to the original collection. This is done this way as normally it is assumed that one creates a view and then makes a lot of operations on it, so this unnesting has a performance benefit. In your case most of the work is creation of views, so best would be what you do as a last option:
1. extract the vector from a view and materialize it
2. next work with this materialized vector

**Comment by tcpie** [comment]
Thank you for the explanation! That's unfortunate to hear, but understandable.

Two follow-up questions (hope you have the time to answer, though I understand this is an upstream issue)
* Is it possible to tell this is happening / prevent this from happening (e.g., throw an error at compile or run-time)?
* Is this behavior (gotcha, to me) documented somewhere?

**Comment by bkamins** [comment]
This behavior is intended, as - as I have commended above - in typical use cases it will be faster. Your use case is specific situation where this is slower.

The fact that `view` is not nested is mentioned [here](https://docs.julialang.org/en/v1/devdocs/subarrays/#A-few-details).
