### ISSUE TITLE
Drop master branch?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaData/DataFrames.jl#3121]
This worked:
```
(@v1.9) pkg> add DataFrames#main

but out of habit, while debugging a problem I did, and scratch my head why (despite Compat entry no wrong):

(@v1.9) pkg> add DataFrames#master
     Cloning git-repo `https://github.com/JuliaData/DataFrames.jl.git`
    Updating git-repo `https://github.com/JuliaData/DataFrames.jl.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Compat [34da2185]:
 Compat [34da2185] log:
 ├─possible versions are: 4.2.0 or uninstalled
 ├─restricted to versions 3.17.0-3 by DataFrames [a93c6f00] — no versions left
 │ └─DataFrames [a93c6f00] log:
 │   ├─possible versions are: 0.22.1 or uninstalled
 │   └─DataFrames [a93c6f00] is fixed to version 0.22.1
 └─Compat [34da2185] is fixed to version 4.2.0
```

**Comment by bkamins** [comment]
It was discussed, and the decision was to keep it as there was no harm of keeping it (in particular it is not installable any more). But I would be OK to delete `master`. @nalimilan - any opinion?

**Comment by PallHaraldsson** [comment]
I can see you wanted to keep it (maybe) at the time, but it's 2+ years old by now, so what would be the point of keeping it? At some point I thought "master" was some magic in git, but it's just another branch(?) and I see branches being delete all the time.

I .e. I think it could be ok, and by now just a footgun.

**Comment by nalimilan** [comment]
I also get confused at times when I do `git checkout master`. I guess it would be OK to remove it now.

**Comment by bkamins** [comment]
OK. So let us remove it. @nalimilan - first you need to change target of your PR https://github.com/JuliaData/DataFrames.jl/pull/2491 (or close it) and then `master` can be deleted. Can you please do it? (I do not want to mess with your PR)

**Comment by nalimilan** [comment]
OK, changed.

**Comment by bkamins** [comment]
Thank you. I have removed `master`.
