### ISSUE TITLE
missing AsTable

### ISSUE THREAD

**Issue by jariji** [JuliaData/DataFrames.jl#3123]
```jl
transform(DataFrame(x=[(;a=1,b=2), missing]), :x => identity => AsTable)
MethodError: no method matching keys(::Missing)
```

I was expecting this to work. I can understand an argument that it shouldn't work though.

**Comment by bkamins** [comment]
In the current design all rows are expected to have the same keys, so this would work:
```
transform(DataFrame(x=[(;a=1,b=2), (;a=missing, b=missing)]), :x => identity => AsTable)
```

**Comment by jariji** [comment]
Annoying as this is, I don't think it should work.
