### ISSUE TITLE
Count nonmissing in `describe`

### ISSUE THREAD

**Issue by jariji** [JuliaData/DataFrames.jl#3126]
`describe` gives the number of missing values but not the number of observed values. I would like to have that too, since it is useful for understanding the data at a glance.

**Comment by jariji** [comment]
I tried `describe(d, count∘ByRow(!ismissing) => :count)` but it didn't work.

**Comment by bkamins** [comment]
Yes, this will be added. See https://github.com/JuliaData/DataFrames.jl/issues/3095
