### ISSUE TITLE
Programatically generate DataFrame vector from x DataFrames with varying x

### ISSUE THREAD

**Issue by YoshuaMoore1** [JuliaData/DataFrames.jl#3128]
Hi all,

I am relatively new to DataFrames.jl, and I think I am missing something with manipulating the DataFrames Type. I also have seen no examples in the documentation for my problem.

In my example I have 3 column matrix variables, each with 5 sets of 20 data values (20 rows). 
I want to generate a single excel file, with 5 sheets (for each dataset) containing the 20 row values for each of the 3 columns.

My approach is to generate a new DataFrame for each dataset programmatically, forming `df1, df2... df5` with a simple loop. This allows me to generate x DataFrames depending on the value of x (which will vary).

I then collect x DataFrames to form a DataFrame vector `dfs`, but this is hard-coded for each df requiring prior knowledge of x (Line 12).

My problem is that I do not know how to generate a DataFrame vector for x DataFrames programatically.
I have tried the methods I know that work with non-DataFrame Types but none of them work for the DataFrame Type.

Help is much appreciated!

Many thanks,
Yoshua

Example code below:

```
using DataFrames
col1_data = zeros(5,20)
col2_data = ones(5,20)
col3_data = rand(5,20)

sheet_names = ["sheet-1","sheet-2","sheet-3","sheet-4","sheet-5"]

for i = 1:length(sheet_names)
     @eval $(Symbol(:df, i)) = DataFrame(col1=col1_data[$i,:],col2=col2_data[$i,:],col3=col3_data[$i,:])
end

dfs = [df1,df2,df3,df4,df5]
```

Below is collecting the data from the DataFrames and splatting it into an excel document for completion of my desired result
```

using XLSX
nt = (;(Symbol(name) => (collect(eachcol(df)), names(df)) for (name, df) in zip(sheet_names, dfs))...)
XLSX.writetable("SingleExcel_nSheets.xlsx"; nt...)

```

**Comment by bkamins** [comment]
```
dfs = [DataFrame(col1=col1_data[i,:],col2=col2_data[i,:],col3=col3_data[i,:]) for i in 1:length(sheet_names)]
```
should do what you want.

Side comments:
1. never use `@eval` in your code - it is unsafe and fragile.
2. in general this type of Q&A is easier to handle in https://discourse.julialang.org/; Issues on GitHub are mostly used for feature requests or bug reports.

**Comment by YoshuaMoore1** [comment]
Thanks bkamins this works great.

Yes I will in the future. I suppose this forum is meant for issues with the package as opposed to "my" issues ;)
