### ISSUE TITLE
Tag a release? Downgrades Compat.jl

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaData/DataFrames.jl#3132]
Hi,

I'm not sure the line should be:

Compat = "3.46, 4.2"

Should 4.x, e.g. 4.1 be allowed too? Anyway, I was confused why adding a different package downgraded Compat, and it turned out b-to be because of its dependency on DataFrames, and newbies will not figure out installing the main branch.

I'm not sure if I need 4.x of Compat, but it's such a major package, that I suspect some package might (eventually).

**Comment by bkamins** [comment]
We are aware of this and I am pushing as fast as possible to make DataFrames.jl release.

CC @ronisbr + @nalimilan

**Comment by nalimilan** [comment]
What's the problem exactly? Did you try to install a package that only supported Compat 4.1?

Note that `Compat = "3.46, 4.2"` means that we allow 3.x and 4.y as long as x >= 46 and y >= 2.

**Comment by bkamins** [comment]
The problem is that in 1.3.4 release of DataFrames.jl we do not allow 4.x version of Compat.jl. So if users want to use Compat.jl they cannot install DataFrames.jl 1.3.4.

**Comment by bkamins** [comment]
I have tagged 1.3.5 release for the time being https://github.com/JuliaData/DataFrames.jl/commit/5709e79fdc27014a4dd6aaf3eacdd5ed3016d1c0
