### ISSUE TITLE
Two Type Warnings

### ISSUE THREAD

**Issue by George9000** [JuliaData/DataFrames.jl#3134]
During precompilation of a package where DataFrames is used, I suddenly received two warning that I'd not seen before about Types that were declared in DataFrames source but not used. What's remarkable is that the warnings did _not_ reappear the next time I launched julia during precompilation.

Unfortunately, I did not copy the entire warning, but it went something like this:
```
Warning: O<:Ordering is declared but not used
src/abstractdataframe/sort.jl, line 145

# get ordering function for the i-th column used for ordering
col_ordering(o::Ordering, i::Int) where {O<:Ordering} = o

Warning: T<:Type is declared but not used
src/dataframe/dataframe.jl, line 398

DataFrame(column_eltypes::AbstractVector{<:Type}, cnames::AbstractVector{<:AbstractString},
          nrows::Integer=0; makeunique::Bool=false) where T<:Type =

julia> versioninfo()
Julia Version 1.9.0-DEV.1305
Commit 305e2fb875 (2022-09-06 16:51 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.6.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = Emacs
```

Warning significance is unclear to me, but posting in case it is of use.

**Comment by bkamins** [comment]
I will check it. Thank you. Most likely this warning is not important, but it signals that we should clean-up some old code.

**Comment by bkamins** [comment]
I cannot reproduce, but I fixed it in https://github.com/JuliaData/DataFrames.jl/pull/3137
