### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by musvaage** [JuliaData/DataFrames.jl#3141]
```
$ date
Mon Sep 12 14:19:12 CDT 2022
$ git clone -q https://github.com/JuliaData/DataFrames.jl.git
$ 
```

grep -n Widnows DataFrames.jl/docs/src/man/basics.md
grep -n accidently DataFrames.jl/CONTRIBUTING.md
grep -n adressing DataFrames.jl/src/groupeddataframe/utils.jl
grep -n begining DataFrames.jl/src/other/utils.jl
grep -n beginng DataFrames.jl/src/other/utils.jl
grep -n convinience DataFrames.jl/src/abstractdataframe/selection.jl
grep -n countinous DataFrames.jl/src/other/utils.jl
grep -n desribe DataFrames.jl/docs/src/man/basics.md
grep -n dictionaly DataFrames.jl/src/abstractdataframe/selection.jl
grep -n earler DataFrames.jl/docs/src/man/basics.md
grep -n heterogenous DataFrames.jl/test/broadcasting.jl
grep -n homogenous DataFrames.jl/docs/src/index.md
grep -n homogenous DataFrames.jl/docs/src/man/reshaping_and_pivoting.md
grep -n retun DataFrames.jl/NEWS.md
grep -n therir DataFrames.jl/src/abstractdataframe/io.jl
grep -n thows DataFrames.jl/NEWS.md
grep -n tranformation DataFrames.jl/src/abstractdataframe/selection.jl
grep -n transorming DataFrames.jl/src/groupeddataframe/splitapplycombine.jl

**Comment by musvaage** [comment]
```sh
$ sed -n 806,808p DataFrames.jl/src/abstractdataframe/selection.jl
    # It is allowed to request a tranformation operation into a newname column
    # only once. This is ensured by the logic related to transformed_cols dictionaly
    # in _manipulate, therefore in select_transform! such a duplicate should not happen
$ 
```

I presume uncommenting the line is the correct fix.

```sh
sed -i 's/adressing/addressing/g' DataFrames.jl/src/groupeddataframe/utils.jl
sed -i 's/begining/beginning/g' DataFrames.jl/src/other/utils.jl
sed -i 's/beginng/beginning/g' DataFrames.jl/src/other/utils.jl
sed -i 's/convinience/convenience/g' DataFrames.jl/src/abstractdataframe/selection.jl
sed -i 's/countinous/continuous/g' DataFrames.jl/src/other/utils.jl
# sed -i 's/dictionaly/dictionary/g' DataFrames.jl/src/abstractdataframe/selection.jl
sed -i 's/heterogenous/heterogeneous/g' DataFrames.jl/test/broadcasting.jl
sed -i 's/therir/their/g' DataFrames.jl/src/abstractdataframe/io.jl
sed -i 's/tranformation/transformation/g' DataFrames.jl/src/abstractdataframe/selection.jl
sed -i 's/transorming/transforming/g' DataFrames.jl/src/groupeddataframe/splitapplycombine.jl
```

**Comment by bkamins** [comment]
Yes - it should be "dictionary"
