### ISSUE TITLE
Ancient version of DataFrames

### ISSUE THREAD

**Issue by lewisl** [JuliaData/DataFrames.jl#3152]
Why am I getting DataFrames 0.21.8 on MacOS ARM?

I have no project that specifies a dependency on DataFrames (that I've created) let alone a specific version of DataFrames.

I have 2 versions of Julia installed: MacOS Intel Julia 1.7.3 and MacOS ARM Julia 1.8.1.

The manifest for Julia 1.7.3 for MacOS Intel specifies this for DataFrames:
```
[[deps.DataFrames]]
deps = ["Compat", "DataAPI", "Future", "InvertedIndices", "IteratorInterfaceExtensions", "LinearAlgebra", "Markdown", "Missings", "PooledArrays", "PrettyTables", "Printf", "REPL", "Reexport", "SortingAlgorithms", "Statistics", "TableTraits", "Tables", "Unicode"]
git-tree-sha1 = "daa21eb85147f72e41f6352a57fccea377e310a9"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "1.3.4"
```

The manifest for Julia 1.8.1 for MacOS ARM specifies this for DataFrames:
```
[[deps.DataFrames]]
deps = ["CategoricalArrays", "Compat", "DataAPI", "Future", "InvertedIndices", "IteratorInterfaceExtensions", "Missings", "PooledArrays", "Printf", "REPL", "Reexport", "SortingAlgorithms", "Statistics", "TableTraits", "Tables", "Unicode"]
git-tree-sha1 = "ecd850f3d2b815431104252575e7307256121548"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.21.8"
```
Of course, I didn't specify this.  I assume it is in the download for this binary installer of Julia.  Is this a mistake?   I am not aware of binary dependencies/artifacts for DataFrames...?

What's worse is I don't even seen this release in this Repo.  The version history jumps from 0.22.7 to 1.0.0. Does it makes sense that this is an error in the creation of the Julia installer?

**Comment by bkamins** [comment]
Do:
1. `] add DataFrames@1.3.5` on both systems and tell me if you get any errors. Most likely you have other packages installed that require older version of DataFrames.jl. The error message will tell you where the conflict is.
2. having set working directory to an empty folder do `] activate .` and then `] add DataFrames` in this case on both systems 1.3.5 version should be installed

**Comment by lewisl** [comment]
Well, sometimes Pkg is a bit of a black box.

First time I did this on 1.7.3, it updated to 1.3.5 fine.  So, done.

First time I did this on 1.8.1 (ARM), several packages displayed in red (whatever that might mean—couldn’t find it in docs) and DataFrames didn’t update.

Quit Julia and iTerm.  Restart iTerm. Restart Julia 1.8.1.  Add DataFrames with explicit version.  It works.

So, done but still some mystery with Plots, which won’t update to latest. Not yours; I’ll try your solution to it.

From: Bogumił Kamiński ***@***.***>
Reply-To: "JuliaData/DataFrames.jl" ***@***.***>
Date: Thursday, September 15, 2022 at 2:11 PM
To: "JuliaData/DataFrames.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [JuliaData/DataFrames.jl] Ancient version of DataFrames (Issue #3152)


Do:
1.       ] add ***@***.*** on both systems and tell me if you get any errors. Most likely you have other packages installed that require older version of DataFrames.jl. The error message will tell you where the conflict is.
2.       having set working directory to an empty folder do ] activate . and then ] add DataFrames in this case on both systems 1.3.5 version should be installed

**Comment by bkamins** [comment]
So I am closing it here. I recommend you ask a general question about how Pkg works in https://discourse.julialang.org/ as there might be various sources of the problems.
