### ISSUE TITLE
CSV.read returned DataFrame is different?

### ISSUE THREAD

**Issue by liupgd** [JuliaData/DataFrames.jl#3154]
Hi there, I tried this code and got some exceptions:
```julia
using DataFrames, CSV
df = CSV.read("xxx.csv", DataFrame)
filter(:SomeColumn=>x->x>0, df)
```
which raised error:
> ERROR: MethodError: no method matching Int64(::SentinelArrays.ChainedVectorIndex{Vector{Bool}})
Closest candidates are:
  (::Type{T})(::T) where T<:Number at boot.jl:772
  (::Type{T})(::AbstractChar) where T<:Union{Int32, Int64} at char.jl:51
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  ...
Stacktrace:
 [1] nextind(#unused#::SentinelArrays.ChainedVector{Bool, Vector{Bool}}, i::SentinelArrays.ChainedVectorIndex{Vector{Bool}})
   @ Base ./abstractarray.jl:181
 [2] _copyto_bitarray!(B::BitVector, A::SentinelArrays.ChainedVector{Bool, Vector{Bool}})
   @ Base ./bitarray.jl:525
 [3] BitVector(A::SentinelArrays.ChainedVector{Bool, Vector{Bool}})
   @ Base ./bitarray.jl:509
 [4] convert(T::Type{BitVector}, a::SentinelArrays.ChainedVector{Bool, Vector{Bool}})
   @ Base ./bitarray.jl:580
 [5] _filter_helper(f::Function, cols::SentinelArrays.ChainedVector{String, Vector{String}})
   @ DataFrames ~/.julia/packages/DataFrames/a6np0/src/abstractdataframe/abstractdataframe.jl:1110
 [6] #filter#87
   @ ~/.julia/packages/DataFrames/a6np0/src/abstractdataframe/abstractdataframe.jl:1092 [inlined]
 [7] filter(::Pair{Symbol, var"#49#50"}, df::DataFrame)
   @ DataFrames ~/.julia/packages/DataFrames/a6np0/src/abstractdataframe/abstractdataframe.jl:1087

But, this code works well:
```julia
using DataFrames, CSV, Chain
df = @chain CSV.File("xxx.csv") DataFrame
filter(:SomeColumne=>x->x>0, df)
```
Version Info: 
- julia-1.8.0
- DataFrames v1.3.5
- CSV v0.10.4 

Is this a bug? Thx.

**Comment by bkamins** [comment]
This is a bug.
Fixed in https://github.com/JuliaData/DataFrames.jl/pull/3155

**Comment by bkamins** [comment]
For now - the recommendation is to use `ntasks=1` (i.e. disable multi-threading in `CSV.read`)

**Comment by quinnj** [comment]
This has been fixed and released upstream (in SentinelArrays.jl package); if you do `]up`, then it should bring in the fix.
