### ISSUE TITLE
Version incompatibility with PrettyTables.jl

### ISSUE THREAD

**Issue by Ezequiel92** [JuliaData/DataFrames.jl#3188]
If you create a new `Project.toml` and `Manifest.toml` in an empty folder, and just add DataFrames and PrettyTables, the version of DataFrames that get installed is very old:

```julia
(test) pkg> add DataFrames, PrettyTables
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/test/Project.toml`
⌃ [a93c6f00] + DataFrames v0.21.8
  [08abe8d2] + PrettyTables v2.1.2
```

I don't know if is an issue of DataFrames or PrettyTables.

My julia version is:
```julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69 (2022-09-06 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
Environment:
  JULIA_EDITOR = code
```

**Comment by bkamins** [comment]
This is an issue that DataFrames.jl 1.3 is compatible with PrettyTables.jl 1.x.

The DataFrames.jl 1.4 release (which will be soon) supports PrettyTables.jl 2.x.

So currently you cannot have both DataFrames.jl 1.3 and PrettyTables.jl 2.1.2 (this will change in a week most likely after the release). You need to choose which of the packages you want in the latest version.
