### ISSUE TITLE
Ignoring ENV["LINES"] in 1.4.x

### ISSUE THREAD

**Issue by gugatr0n1c** [JuliaData/DataFrames.jl#3203]
Hello,

working with Julia 1.8.2 and DataFrames 1.4.1 with jupyter ntb.
When I set ie:

ENV["LINES"] = 500
DataFrames ignore this setting and start to omitted rows from printing, even with ie 50 rows.

Is this bug? Is there any workaround? Thx

**Comment by bkamins** [comment]
The recommendation to set `ENV["LINES"]` is outated. Where have you found it? (so that we can clean it up and remove). The current rules how many lines should be printed are given in DataFrames.jl manual: https://dataframes.juliadata.org/stable/man/getting_started/#Installation

Quoting:

> By default DataFrames.jl limits the number of rows and columns when displaying a data frame in a Jupyter Notebook to 25 and 100, respectively. You can override this behavior by changing the values of the ENV["DATAFRAMES_COLUMNS"] and ENV["DATAFRAMES_ROWS"] variables to hold the maximum number of columns and rows of the output. All columns or rows will be printed if those numbers are equal or lower than 0.

**Comment by gugatr0n1c** [comment]
I just use it for "ages" and somehow googled it then before. Now cannot find it anymore. Thank you very much for this right notation. @bkamins

**Comment by bkamins** [comment]
In general - we believe that what we have now is better:
1. by default more columns are printed (so less often one needs to change this option)
2. user specifies how many columns to show (not how many characters to show) - which I believe is more a useful thing user would want to pass.

Thank you!
