### ISSUE TITLE
Allow `end` to select last column.

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#3209]
I was trying to `hcat` the last column of a data frame onto another data frame and was surprised that the `end` keyword does not work for selecting data frame columns. `df[:, end]`  selected the correct data, but it drops the column name. It would be convenient if `end` worked as an alias for the last integer index like it does for array indexing. (The `ncol(df)` workaround is easy enough if this is difficult to implement though.)

```julia
julia> df = DataFrame(rand(3,3), :auto)
3×3 DataFrame
 Row │ x1        x2        x3       
     │ Float64   Float64   Float64
─────┼──────────────────────────────
   1 │ 0.993444  0.609605  0.32879
   2 │ 0.195981  0.417102  0.843341
   3 │ 0.441776  0.205019  0.975706

julia> select(df, 1)
3×1 DataFrame
 Row │ x1       
     │ Float64
─────┼──────────
   1 │ 0.993444
   2 │ 0.195981
   3 │ 0.441776

julia> select(df, end)
ERROR: syntax: unexpected "end"
Stacktrace:
 [1] top-level scope
   @ none:1

julia> select(df, Cols([end]))
ERROR: syntax: unexpected "end"
Stacktrace:
 [1] top-level scope
   @ none:1

julia> select(df, ncol(df))
3×1 DataFrame
 Row │ x3       
     │ Float64
─────┼──────────
   1 │ 0.32879
   2 │ 0.843341
   3 │ 0.975706
```

**Comment by bkamins** [comment]
What you propose is syntactically not possible (this is disallowed by Julia). What you can do is `df[:, [end]]` instead.
