### ISSUE TITLE
sizeof() not working correctly with Dataframes

### ISSUE THREAD

**Issue by jdiaz97** [JuliaData/DataFrames.jl#3229]
sizeof() returns the size of a variable in bytes. This doesn't work with dataframes as it will return very small amounts that don't represent the actual size.

I have very normal 13312×5 DataFrame and sizeof() returns 48 bytes.

**Comment by bkamins** [comment]
`sizeof` returns the size of the object (and `DataFrame` itself is a small object, however, it can hold references to large objects).

You probably are looking for `Base.summarysize` which computes the amount of memory, in bytes, used by all unique objects reachable from the argument.
