### ISSUE TITLE
why `mixing strings with other selectors is not allowed`?

### ISSUE THREAD

**Issue by anandijain** [JuliaData/DataFrames.jl#3241]
`df[:, [:t, r"XYZ"]]` gave this error. it might be good to put a reason in the error message

**Comment by bkamins** [comment]
What exactly error message would you expect?
The message tells you the reason: you mix `Symbol` (`:t`) with `Regex` (`r"XYZ"`) which is not allowed.

Also the error message is:
```
ERROR: ArgumentError: mixing `Symbol`s with other selectors is not allowed
```
(so it is different from what you have in the title)

Here I assume you wanted: `df[:, Cols(:t, r"XYZ")]` but in general it could be something else so it is hard to tell what to suggest.

**Comment by anandijain** [comment]
Oh thanks! thats exactly what I'm looking for

**Comment by anandijain** [comment]
Yeah I see the issue. So improving the message is type-dependent. Maybe just a ref to Cols would be good

**Comment by bkamins** [comment]
OK - I will think what message would be better.

**Comment by bkamins** [comment]
Fixed in https://github.com/JuliaData/DataFrames.jl/pull/3242
