### ISSUE TITLE
Improve groupby sort

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3251]
Add an option to specify sort order in `groupby`.

**Comment by jkrumbiegel** [comment]
There's also the `by` keyword which has the separate job of transforming the sorted values before sorting them with the function passed in `lt`. For natural sort order, as an example, you'd only need `lt` and not `by`, but in other circumstances `by` might be useful as well. It's just not good to have `by` as a keyword in `groupby` when it doesn't relate to the grouping.

My suggestions would be either, add keywords `sort_lt` and `sort_by` and mirror the `sort` keywords there. Or optionally pass a `NamedTuple` to `sort` keyword like `sort = (; lt = func, by = ...)`.

**Comment by bkamins** [comment]
The challenge is the details. If `lt` and `by` should be "per column" or "per all grouping columns". Probably we should match what `sort` for `AbstractDataFrame` does.

**Comment by bkamins** [comment]
So, we would need to mimick the `sortperm` API. The changes would be:
* the `sort` kwarg apart from `nothing`, `false`, and `true` would accept a named tuple taking some or all of `alg`, `lt`, `by`, `rev`, `order`, with the same defaults as in `sortperm`; if such a named tuple were passed sorting would be performed.
* when passing grouping columns to `groupby` one could use `order` wrapper, e.g. `groupby(df, [:x, order(:y, rev=true)])`; if such `order` is passed then `sort=true` by default (passing `nothing` or `false` would error) (this is needed to allow for specifying sorting orders for grouping columns individually)

CC @nalimilan

**Comment by nalimilan** [comment]
Makes sense. That would just be a shorthand for `groupby(sort(df, ...), cols)` that avoids making a copy, right?

**Comment by bkamins** [comment]
This is what @jkrumbiegel wanted. Right?

**Comment by jkrumbiegel** [comment]
I think so, yes. It just seems natural to influence the sorting directly instead of splitting it out and doing `sort = false` on the `groupby` call.
