### ISSUE TITLE
Let DataFrame behave more like GroupedDataFrame with one zero-key group

### ISSUE THREAD

**Issue by jariji** [JuliaData/DataFrames.jl#3257]
`df::DataFrame` is conceptually similar to `groupby(df, [])`, so `keys(df)` could work but currently throws a `MethodError`. This change would simplify the mental model of using these objects.

**Comment by bkamins** [comment]
We cannot do it.

The contract for `keys` is:
```
  keys(iterator)

  For an iterator or collection that has keys and values (e.g. arrays and dictionaries), return an iterator over the
  keys.
```

`AbstractDataFrame` is not an iterator (as opposed to `GroupedDataFrame`). Also I do not think we want to make it an iterator with a single (or no) groups.

I initially was open to discuss it, but it seems to me that it is almost impossible that we will change this decision (people would be confused if we made `AbstractDataFrame` iterable this way), so I am closing the issue. But maybe @nalimilan will have another opinion.
