### ISSUE TITLE
`String` display quotation missing

### ISSUE THREAD

**Issue by Moelf** [JuliaData/DataFrames.jl#3261]
```julia
julia> DataFrame(Dict(:a=>["asd","asd"]))
2×1 DataFrame
 Row │ a
     │ String
─────┼────────
   1 │ asd
   2 │ asd

julia> ["asd","asd"]
2-element Vector{String}:
 "asd"
 "asd"
```

it feels like we should keep quotation marks

**Comment by bkamins** [comment]
Why do you think it is preferred?
If I understand the design correctly this is intended as it is more user friendly and uses less space. Also `$` is not escaped:
```
julia> x = ["\$"]
1-element Vector{String}:
 "\$"

julia> DataFrame(x=x)
1×1 DataFrame
 Row │ x
     │ String
─────┼────────
   1 │ $
```

CC @ronisbr

**Comment by Moelf** [comment]
```julia
julia> LazyTree(f, "ntuple", [r"vec"])
 Row │ vector_int32     vector_vector_i                                  vector_string                            vector_vector_s                              ⋯
     │ Vector{Int32}    Vector{Vector{I                                  Vector{String}                           Vector{Vector{S                              ⋯
─────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1   │ [1]              Vector{Int32}[Int32[1]]                          ["one"]                                  [["one"]]                                    ⋯
 2   │ [1, 2]           Vector{Int32}[Int32[1], Int32[2]]                ["one", "two"]                           [["one"], ["two"]]                           ⋯
 3   │ [1, 2, 3]        Vector{Int32}[Int32[1], Int32[2], Int32[3]]      ["one", "two", "three"]                  [["one"], ["two"], ["three"]]                ⋯
 4   │ [1, 2, 3, 4]     Vector{Int32}[Int32[1], Int32[2], Int32[3], Int  ["one", "two", "three", "four"]          [["one"], ["two"], ["three"], ["four"]]      ⋯
 5   │ [1, 2, 3, 4, 5]  Vector{Int32}[Int32[1], Int32[2], Int32[3], Int  ["one", "two", "three", "four", "five"]  [["one"], ["two"], ["three"], ["four"], ["fi ⋯
```

Because it's otherwise confusing and also it's about copy-ability- if I can past the display into REPL and get something back, of course, it's not a guarantee, but it's how Julia base does it too (for the same reason)

**Comment by bkamins** [comment]
I understand your point (and in production-related aspects of DataFrames.jl we follow it). However, for display the other aspect we need to consider is readability. Consider:
```
julia> [[[1]], [[1], [2]]]
2-element Vector{Vector{Vector{Int64}}}:
 [[1]]
 [[1], [2]]
```
and I would prefer such a display in DataFrames.jl since we provide element type information in the header.

Let us wait for @ronisbr to respond as he manages display for DataFrames.jl.

CC @nalimilan

**Comment by nalimilan** [comment]
Yeah, the way we print strings isn't completely orthodox, but as @bkamins says it takes less space and is less heavy. There's no ambiguity given that the type is printed in the header and tha columns are separated with vertical bars (which is not the case for arrays). FWIW, data frames and tibbles print the same way in R (which also differs from standard string printing there).

**Comment by ronisbr** [comment]
Hi @Moelf !

Sometime ago we decided to keep everything consistent with the output of `print` instead of `show`, which is used in REPL. This choice allowed a cleaner output as stated by @bkamins and @nalimilan.

However, if you prefer the REPL way, you can change the renderer as follows:

```julia
julia> df = DataFrame(Dict(:a=>["asd","asd"]));

julia> show(df, renderer = :show)
2×1 DataFrame
 Row │ a
     │ String
─────┼────────
   1 │ "asd"
   2 │ "asd"
julia> df = DataFrame(x = ["\$"]);

julia> show(df, renderer = :show)
1×1 DataFrame
 Row │ x
     │ String
─────┼────────
   1 │ "\$"
```

**Comment by bkamins** [comment]
@Moelf - does this resolve your issue?
