### ISSUE TITLE
`subseteq` convenience function

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaData/DataFrames.jl#3266]
I find it convenient to define the following function in my code:
```julia

"""
    subseteq(df; col1=val1, col2=val2, ...)

Return a subset of `df` where the values of the columns `col1`, `col2`, ..., 
are equal to `val1`, `val2`, ... .

# Examples

julia> df = DataFrame(a=[1,1,3,1], b=[4,5,6,4], c=[7,8,9,10])
4×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      4      7
   2 │     1      5      8
   3 │     3      6      9
   4 │     1      4     10

julia> subseteq(df, a=1, b=4)
2×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      4      7
   2 │     1      4     10

"""
subseteq(df; kws...) = DataFrames.subset(df, (k => x -> x .== v for (k, v) in kws)...)
```

Is there some interest in adding it to the library?

**Comment by bkamins** [comment]
It is in DataFramesMeta.jl:
```
@rsubset(df; :col1 == val1, :col2 == val2, ...)
```
or in DataFrames.jl (I know it is more typing that is why we also have the form above):
```
subset(df; :col1 => ByRow(==(val1)), :col2 => ByRow(==(val2)), ...)
```

What you propose will not work for column names that are not valid identifiers.

Would `@rsubset` from DataFramesMeta.jl be enough for you?

**Comment by CarloLucibello** [comment]
nice! I still find slightly more convenient the proposed function since it saves some typing and allows splatting named tuples but `@rsubset` is very close, much more flexible, and has a syntax coherent with the rest of the macros there.
