### ISSUE TITLE
Check CompatHelper setup

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3278]
@DilumAluthge

I have seen that https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml is significantly longer than what we have in DataFrames.jl https://github.com/JuliaData/DataFrames.jl/blob/main/.github/workflows/CompatHelper.yml.

Do you think we need to update it, or what we have is enough? Thank you!

**Comment by DilumAluthge** [comment]
It’s probably best to update, just to be safe.
