### ISSUE TITLE
Add `get` function for AbstractDataFrame

### ISSUE THREAD

**Issue by dgegen** [JuliaData/DataFrames.jl#3281]
Analogous to the syntax of the `df.get` [function in Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.get.html), I propose to add the following function in [src/abstractdataframe/iteration.jl](https://github.com/JuliaData/DataFrames.jl/blob/main/src/abstractdataframe/iteration.jl), which I syntactically consider a conventional and convenient way to deal with cases where the return of default values is desired.
```
"""
    get(df::AbstractDataFrame, col_ind, default=nothing)
Return the column with the index `col_ind`, or the given default value `default`
if the column of the given index is not present in the DataFrame `df`.
"""
function Base.get(df::AbstractDataFrame, col_ind::Union{Symbol,AbstractString},
                  default=nothing) 
    hasproperty(df, col_ind) ? df[:, col_ind] : default
end
```
Does anyone have additional suggestions, thoughts or opposing arguments?
Cheers!

**Comment by bkamins** [comment]
we could add:
```
get(df::DataFrameColumns, col_ind::ColumnIndex, default)
```
and
```
haskey(df::DataFrameColumns, col_ind::ColumnIndex)
```
so @dgegen could get the expected behavior, but with `eachcol(df)`.

@nalimilan - what do you think about it?

**Comment by nalimilan** [comment]
IIRC we had this a long time ago, but we dropped it because it goes against the idea that data frames are collections of rows. It would have to be called `getcols` if we wanted to add it.

**Comment by bkamins** [comment]
@nalimilan - that is why I do not want to add it to `DataFrame` but to `DataFrameColumns`. `DataFrameColumns` is a collection of columns so it could support `get` and `haskey`.

Note that we now support both `get` and `haskey` for `DataFrameRow` for the same reason (as it is a collection of columns).

**Comment by nalimilan** [comment]
Woops, sorry. Why not then. :-)

**Comment by bkamins** [comment]
Added in https://github.com/JuliaData/DataFrames.jl/pull/3282
