### ISSUE TITLE
More flexible `Not` column selector

### ISSUE THREAD

**Issue by adienes** [JuliaData/DataFrames.jl#3288]
w.r.t. https://julialang.slack.com/archives/C674VR0HH/p1676216308408839

Possibly `Not` could be expanded to take multiple column selectors such that
```
Not(args...; kwargs...)
```
Is equivalent to
```
Not(Cols(args...; kwargs...))
```

**Comment by bkamins** [comment]
This is reasonable. I need to think how to best design it.

**Comment by bkamins** [comment]
This is now added on `main`. The only limitation is that we do not support `kwarg` part, but I think it is sufficient so I am closing it. If you feel we should add something more please comment.

x-ref: https://github.com/JuliaData/DataFrames.jl/pull/3302
