### ISSUE TITLE
svd and eig on DataMatrix

### ISSUE THREAD

**Issue by ViralBShah** [JuliaData/DataFrames.jl#329]
What are the benefits of the `svd` and `eig` implementations for DataMatrix, over using the one from Base?

The comment in the code suggests that this one can handle `NA`. If not already done, this is a useful thing to document this, the algorithm used, and the citation.

This also makes me wonder on how to handle sparse datasets with missing data. Often people just use `svds` in matlab, where the missing data is treated as a 0, which is not what one wants.

**Comment by nalimilan** [comment]
DataArrays don't live here for a long time.
