### ISSUE TITLE
Question regarding the use `Symbol`s for column names

### ISSUE THREAD

**Issue by simsurace** [JuliaData/DataFrames.jl#3291]
I have been wondering whether the use of `Symbol`s for column names could create memory issues for really large tables with changing column names. For example, a microservice that is continuosly reading new (large) data tables and converting them to `DataFrames` could be creating many unique `Symbol`s, which are not being garbage collected according to [Julia docs](https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L1897-L1899), which may cause the service to eventually run out of memory. Cc @pdeffebach and @MasonProtter from a Slack thread. A simple MWE (due to @MasonProtter) illustrates the potential issue:
```julia
julia> using Random

julia> let v = rand(10)
           while true
               Symbol(rand!(v))
           end
       end
```
This leads to a linear increase in memory use.

**Comment by bkamins** [comment]
This is true. If you have a case like this use `Dict` with `String` as keys. Also make sure that your file reader does not use `Symbol` internally (as most readers would).

Does this answer your question?

**Comment by simsurace** [comment]
I guess this is sort of an open-ended discussion, others may chime in.
I suppose an immediate follow-up is: even if I pass a `Dict` with `String`s as keys, this will be internally transformed to `Symbol`s when building the `Index`, right?
https://github.com/JuliaData/DataFrames.jl/blob/0b3d620ef6acd287d5db74258972f470532029e3/src/other/index.jl#L21-L24

**Comment by bkamins** [comment]
Yes. I meant - in your use-case do not use `DataFrame` to store your data.

**Comment by bkamins** [comment]
Can this be closed or you have something more to clarify?

**Comment by simsurace** [comment]
@pdeffebach would you like to add something here?

**Comment by pdeffebach** [comment]
No, we can close this.
