### ISSUE TITLE
juliadata.org website pointing to random blog about martial arts?

### ISSUE THREAD

**Issue by ninjit** [JuliaData/DataFrames.jl#3296]
The documentation for Dataframes.jl is hosted at
https://dataframes.juliadata.org/stable/

and I assumed the juliadata.org website would be hosting more general information about related packages under the JuliaData umbrella; however it seems to point/redirect to a random blog about martial arts in indonesia.

This may be benign, i.e. blog belongs to a primary contributor - but it made me do a double take, and question whether I'm using a legitimate package.

Is there a landing page for JuliaData that this could be redirected to instead?
Or at least point to the main github org page:
github.com/JuliaData

**Comment by bkamins** [comment]
AFAICT the site seems to be owned by someone unrelated with Julia.

**Comment by bkamins** [comment]
Thank you for reporting.
