### ISSUE TITLE
sort(::GroupedDataFrame, ::Symbol)

### ISSUE THREAD

**Issue by jariji** [JuliaData/DataFrames.jl#3307]
```
MethodError: no method matching sort(::GroupedDataFrame{DataFrame}, ::Symbol)
```

Should this sort within each group?

**Comment by bkamins** [comment]
`GroupedDataFrame` does not support sorting currently. If we added `sort(::GroupedDataFrame{DataFrame}, ::Symbol)`.
If you want to get a `GroupedDataFrame` sorted by grouping columns then this is supported in `groupby`.

However, you seem to want to sort data within groups. This can be achieved by:
```
transform(gdf, sdf -> sort(sdf, :column_to_sort_on), ungroup=false)
```
Does this clarify what you wanted and the issue can be closed?
