### ISSUE TITLE
Accepting array element in rows specificed by named tuples, in `combine`

### ISSUE THREAD

**Issue by jonalm** [JuliaData/DataFrames.jl#3335]
Creating a DataFrame from a list of named tuple works fine, even when the nt elements contain arrays

```julia
DataFrame([
    (; foo="bar", boo=[1,2]),
    (; foo="baz", boo=[1,2])
]
)
```

But that is not the case if the DataFrame is created by a `combine` operations

```julia
combine(groupby(DataFrame(:group=>[1,1,2,2]), :group)) do g
    return (;
        foo="foo",
        boo=[1,2]
    )
end
```

gives
```
    nested task error: ArgumentError: mixing single values and vectors in a named tuple is not allowed
```

The above example would work as expected if one removes these two lines:
https://github.com/JuliaData/DataFrames.jl/blob/fcd98c6e883ef2dd6e6ba04a6a12e6eb8d7e5375/src/groupeddataframe/complextransforms.jl#L52 and
https://github.com/JuliaData/DataFrames.jl/blob/fcd98c6e883ef2dd6e6ba04a6a12e6eb8d7e5375/src/groupeddataframe/callprocessing.jl#L69

An obvious use-case for needing this is when you want some ordered indices or values from the group, in a single row for each group.

Would you be willing to reconsider these exceptions, and allow arrays as named tuple elements when using `combine`?

**Comment by bkamins** [comment]
> Would you be willing to reconsider these exceptions, and allow arrays as named tuple elements when using combine?

Please correct me if I am wrong, but this would imply that `(; x=[1, 2, 3], y=[2, 3, 4])` would be interpreted as a named tuple defining a single row. Whereas currently, it defines three rows.

**Comment by jonalm** [comment]
@bkamins I guess there are implicitly two suggestions here for the output of the function argument to `combine`:

1) **(Non breaking)** remove the above mentioned error, and allow named tuple outputs with a combinations of scalar and array values, and interpret those as rows in the resulting DataFrame.

2) **(Breaking)** change the behaviour such that named tuple output always produce a row in the resulting DataFrame.

The rational for 2 is that it is easy to explicitly wrap the output (of the function argument to `combine`) into a DataFrame, if you want the combined DataFrame to be a stack of DataFrames. But it is not clear (at least not to me) how to return a row with both scalar and array elements. It would be natural to achieve that with a named tuple output (always interpreted as a row). 1 would be a non-breaking quick fix to have this functionality for named tuples with mixed (scalar/array) elements, but may render the behaviour unexpected to some users.

**Comment by bkamins** [comment]
> But it is not clear (at least not to me) how to return a row with both scalar and array elements.

It was discussed on Slack.
If you have `f() = (; x=1, y=[1,2])`
You should return instead of:
```
julia> f()
(x = 1, y = [1, 2])
```
rather wrap all in additional vectors
```
julia> map(x -> [x], f())
(x = [1], y = [[1, 2]])
```
or equivalently:
```
julia> map(Base.vect, f())
(x = [1], y = [[1, 2]])
```
(or directly in definition of `f` wrap vectors in vectors)

I am aware that it is a bit inconvenient.

We will not make the option 2. (breaking change) because it is breaking.

Option 1. could be acceptable, but it is problematic as the rule determining how named tuple is handled would become even more complex than it is now (in general: users already find `combine` processing rule to have many cases)

Indeed in the code when have these two errors thrown because we wanted to leave the freedom in the future to decide what to do in that case (@nalimilan style 😄). So the conclusion is that we can discuss it, but we want to reach a consensus before making such a fundamental change. One of the reasons for this is that typically users could expect that `(; x=1, y=[1, 2])` should be expanded to `DataFrame(x=[1,1], y=[1,2])` instead (as discussed - this is what normally would `DataFrame` constructor do).

**Comment by jonalm** [comment]
So if I understand you correctly @bkamins: the best way of having a single row output from the combining function, which is robust against the potential content of that row (in the above mentioned case: arrays), is to wrap that row into a DataFrame with one single row, or to wrap it into a named tuple which would be expanded into a single rowed DataFrame in the DataFrame constructor?

If that is the case: wouldn't it be more natural to have a convention for explicitly returning a row? If named tuples are out of the question, could we have a `Row`-like type (`DataFrameRow`?) which acts like a named tuple?

**Comment by bkamins** [comment]
`DataFrameRow` - you can use it already. The only limitation is that it is not convenient to create it currently.

Indeed, though, it would be useful to add support for:

```
combine(gdf, src => Tables.Row ∘ fun => AsTable)
```
where your `fun` is returning a named tuple.

Do you think it would be useful to add something like this?

CC @nalimilan, @pdeffebach, @ararslan

The change it would require in the minilanguage is to add support for `Tables.AbstractRow`, just like we did it for pushing in https://github.com/JuliaData/DataFrames.jl/pull/3245.

I think it would be OK to add it.

**Comment by bkamins** [comment]
> doesn't check if something is `Tables.istable` and behave accordingly.

The reason is that `Tables.istable` is not a very reliable function. I prefer not to use it. Having said that, here we are talking about `Tables.AbstractRow` subtypes, which is a well defined interface.

> As for the current behavior, I think it's not a big deal to require the use of arrays

Still, I think recognizing `Tables.AbstractRow` is a simple fix that should not be problematic.

---

My question is, for 1.x release branch of DataFrames.jl if we feel that adding `Tables.AbstractRow` support is OK (and robust for 2.x release)?

**Comment by bkamins** [comment]
@pdeffebach - to expand. `Tables.istable` is trait based, which is fragile. `Tables.AbstractRow` rule is dispatch based, which makes it more robust.

**Comment by jonalm** [comment]
> Indeed, though, it would be useful to add support for:
> 
> ```
> combine(gdf, src => Tables.Row ∘ fun => AsTable)
> ```
> 
> where your `fun` is returning a named tuple.
> 
> Do you think it would be useful to add something like this?

@bkamins  I'm not sure I understand the implications of your suggestion. How I would use `combine` with the proposed solution?

Also, perhaps a bit tangential, why do you consider a trait based approach to be fragile?

**Comment by bkamins** [comment]
> How I would use combine with the proposed solution?

Just as I have written above:

```
combine(gdf, src => Tables.Row ∘ fun => AsTable)
```

passing return value of `fun` to `Tables.Row` forces the value returned by `fun` to be treated as one row.

> why do you consider a trait based approach to be fragile?

For two reasons:
* major: if `Tables.istable` returns `true` you are sure that you are working with a table; but if it returns `false` it does not mean that it is not a table (it only means that it might not be a table)
* minor: with type-based dispatch we are sure that the behavior cannot change dynamically; with trait based dispatch the behavior can be changed by the user (i.e. the user could define a method for `Tables.istable` and change the behavior of DataFrames.jl - indeed sometimes it could be useful, but in general I prefer to be able to determine statically how DataFrames.jl will evaluate some expression in cases it is possible)

**Comment by jonalm** [comment]
> > How I would use combine with the proposed solution?
> 
> Just as I have written above:
> 
> ```
> combine(gdf, src => Tables.Row ∘ fun => AsTable)
> ```

sorry for being an idiot, but I don't get what `src` would be in your example?

**Comment by bkamins** [comment]
`src` is a specification of source columns that should be passed to `fun`. See "Basic transformations" section in https://bkamins.github.io/julialang/2020/12/24/minilanguage.html.

**Comment by jonalm** [comment]
@bkamins  Thanks, and thanks for elaborating on the trait issue.

I think your proposal would be very useful.

**Comment by pdeffebach** [comment]
My only comment is that a DataFrames-specific singleton type, like `AsRow` might be more useful.

**Comment by bkamins** [comment]
What would be the benefit of `AsRow` over `Tables.Row` that is already defined in the ecosystem?

The definition would be `AsRow(fun) = Tables.Row ∘ fun`.

**Comment by bkamins** [comment]
>  I better understand why it's not good for the case.

OP wants `(; b="foo", c=[1,2])` to be interpreted as a single row not as a table that would expand `:b` value into two rows.

**Comment by sprmnt21** [comment]
I get that you're looking for this, isn't it?


```
julia> combine(groupby(DataFrame(:group=>[1,1,2,2]), :group)) do g
           DataFrame([(;
               foo="foo",
               boo=[1,2]
           )])
       end
2×3 DataFrame
 Row │ group  foo     boo    
     │ Int64  String  Array…
─────┼───────────────────────
   1 │     1  foo     [1, 2]
   2 │     2  foo     [1, 2]`
```

**Comment by jonalm** [comment]
@sprmnt21 : Yes. This issue is a request to avoid having to construct a full `DataFrame` to get a row.

**Comment by bkamins** [comment]
Ah - I missed `[` in @sprmnt21 proposal. This makes sense, so what currently works is:
```
julia> combine(groupby(DataFrame(:group=>[1,1,2,2]), :group), :group => (g ->
                  [(;
                      foo="foo",
                      boo=[1,2]
                  )]) => AsTable)
2×3 DataFrame
 Row │ group  foo     boo
     │ Int64  String  Array…
─────┼───────────────────────
   1 │     1  foo     [1, 2]
   2 │     2  foo     [1, 2]
```
and (this is a different output, but the same intention)
```
julia> combine(groupby(DataFrame(:group=>[1,1,2,2]), :group), :group => ByRow(g ->
                  (;
                      foo="foo",
                      boo=[1,2]
                  )) => AsTable)
4×3 DataFrame
 Row │ group  foo     boo
     │ Int64  String  Array…
─────┼───────────────────────
   1 │     1  foo     [1, 2]
   2 │     1  foo     [1, 2]
   3 │     2  foo     [1, 2]
   4 │     2  foo     [1, 2]
```

What we would need to change is the "legacy" syntax (i.e. taking a single function), where the current rule is that we only recognize:

> a data frame, a matrix, a NamedTuple, or a DataFrameRow

(and this is a closed list of recognized objects)

**Comment by sprmnt21** [comment]
If I'm not getting too off topic, I'd like to try to put the question in a more general way.
What I'd find easiest to follow as a mindset would be one in which the result of cols =>fun whatever is, is intended to occupy a "cell" without being implicitly "interpreted"  (expanded, flattened, ...).

Here are some fictitious examples:

```
julia> combine(groupby(DataFrame(:group=>[1,1,2,2]), :group)) do g
           (; foo="foo", boo=[1,2] )
       end
2×2 DataFrame
 Row │ group  x1
     │ Int64  NamedTup…
─────┼────────────────────────────────────
   1 │     1  (foo = "foo", boo = [1, 2])
   2 │     2  (foo = "foo", boo = [1, 2])



julia> combine(groupby(DataFrame(:group=>[1,1,2,2]), :group)) do g
           DataFrame([(;
               foo="foo",
               boo=[1,2]
           )])
       end
2×2 DataFrame
 Row │ group  x1
     │ Int64  DataFrame
─────┼──────────────────────
   1 │     1  1×2 DataFrame
   2 │     2  1×2 DataFrame


julia> combine(groupby(DataFrame(:group=>[1,1,2,2]), :group)) do g
           [
               (; foo="bar", boo=[1,2]),
               (; foo="baz", boo=[1,2])
           ]
       end
2×2 DataFrame
 Row │ group  x1
     │ Int64  Array…
─────┼──────────────────────────────────────────
   1 │     1  NamedTuple{(:foo, :boo), Tuple{S…
   2 │     2  NamedTuple{(:foo, :boo), Tuple{S…
```
The "expansion" of a NamedTuple or a DataFrame or any other "complex" structure should be explicitly required/constructed by the user.

**Comment by ararslan** [comment]
> What would be the benefit of `AsRow` over `Tables.Row` that is already defined in the ecosystem?
>
> The definition would be `AsRow(fun) = Tables.Row ∘ fun`. (so it would be a function not a type)

`AsRow(f)` permits the use of `do` blocks, e.g.
```julia
combine(gdf, src => AsRow() do x
            # some great stuff happens here
        end => AsTable)
```
With `Tables.Row ∘ fun`, the closest to this you can get is
```julia
combine(gdf, src => Tables.Row ∘ (x -> begin
            # some other stuff happens here
        end) => AsTable)
```
which is a bit more awkward to read and to write.

**Comment by nalimilan** [comment]
Adding support for `Tables.Row` seems uncontroversial. Maybe we can try that and see whether `AsRow(fun) = Tables.Row ∘ fun` is really needed? The fact that you would write `AsRow()` and `AsTable` in the same transformation sounds a bit weird to me. :-)
