### ISSUE TITLE
website: https://juliadata.org

### ISSUE THREAD

**Issue by cwpwd** [JuliaData/DataFrames.jl#3338]
Visiting https://juliadata.org was a surprise. There should be something, but not what's there.

**Comment by bkamins** [comment]
I do not own this domain and in general DataFrames.jl does not own JuliaData on GitHub think.

But I can ping @ViralBShah as maybe there is some general policy for such cases.

**Comment by bkamins** [comment]
@nalimilan - do you know the general policy (or whom to ask?)

**Comment by ViralBShah** [comment]
The domain is one of ours. However, this seems to be affected by some bug with github pages, where someone else has someone got it. We discussed this a few months ago and I thought it was fixed.

cc @aviks If you remember?

**Comment by nalimilan** [comment]
What do you see there? I just get a 404.

**Comment by ViralBShah** [comment]
I get:

```
Your connection is not private
Attackers might be trying to steal your information from juliadata.org (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by ViralBShah** [comment]
Ideally juliadata.org would point to - https://juliadata.github.io/ - but at the moment, that is a default Franklin page.
