### ISSUE TITLE
Dependency on DataStructures should be explicit and versioned

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataFrames.jl#3358]
https://github.com/JuliaData/DataFrames.jl/blob/453b4464b996d918f1dbce5034e739be16bad0aa/src/abstractdataframe/sort.jl#L17-L18 takes a dependency on `DataStructures` without declaring that in the `Project.toml`, and in particular without putting in proper version bounds.

I believe `FasterForward` was only added in v0.18.0 to `DataStructures`, so that line of code errors when combined with any older version of `DataStructures`. I think the immediate fix is very simple: add `DataStructures` to `Project.toml`, remove this indirection of importing via `SortingAlgorithms` and put a `DataStructures = 0.18` into the compat section.

The more complicated issue is that we now have a version in the general registry that looks to the package manager as working with `DataStructures` <v0.18, whereas it does. I think ideally that version would either be yanked, or maybe one can somehow modify the compat bounds in the registry for the existing tagged version?

**Comment by bkamins** [comment]
Fixed in https://github.com/JuliaData/DataFrames.jl/pull/3359 (hopefully cleanly)
