### ISSUE TITLE
Would adding support for JLD2.jl allow Type preservation?

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaData/DataFrames.jl#3364]
I use DataFrames pretty heavily in my workflows, saving and reading to Arrow file. One thing that I find a bit of a pain is that custom  types are lost on save. If DataFrames supported reading and writing to JLD2 could the Types be preserved?

**Comment by bkamins** [comment]
You can currently save and load dataframes using JLD2.jl. Can you please comment what feature are you missing?

**Comment by alex-s-gardner** [comment]
Apologies, I didn't realize that was already handled. It works fantastic and retains custom type information!

Should JLD2/H5 be added to the [list of supported formats](https://dataframes.juliadata.org/stable/man/importing_and_exporting/#Other-formats)?

**Comment by bkamins** [comment]
If you would think it is useful can you please open a PR?

**Comment by quinnj** [comment]
Custom type preservation should be fine in Arrow.jl as well; it does require defining the right ArrowTypes overloads, but should work.
