### ISSUE TITLE
ncol does not work on DataFrameRow, should it be made to?

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaData/DataFrames.jl#3367]
ncol does not work on DataFrameRow.

```julia
julia> df = DataFrame(A=1:3, B=5:7, fixed=1)

julia> ncol(first(df))
ERROR: MethodError: no method matching ncol(::DataFrameRow{DataFrame, DataFrames.Index})

Closest candidates are:
  ncol(::AbstractDataFrame)
   @ DataFrames ~/.julia/packages/DataFrames/dgZn3/src/abstractdataframe/abstractdataframe.jl:403
```

one can use length to get the number of columns
```julia 
julia> length(first(df))
3
```

but I'm wondering if expanding `ncol` to also work on `DataFrameRow` would be valuable for people living in DataFrames that might be thinking of the data in therms of rows and columns as appose to vector lengths?

**Comment by bkamins** [comment]
`nrow` does not work on `DataFrameRow`, because it is single dimensional. Technically it does not have columns, but has properties, just like a `NamedTuple`. That is why `length` works on it to get a number of properties exposed.

**Comment by alex-s-gardner** [comment]
I understand the thinking but I'm not sure it's intuitive. A single row in an Excel spreadsheet still has columns. Users will think of a `DataFrameRow`  simply as a single row of a column-row array, and therefor may want/try to use an operator like `ncol` (not my question was about `ncol` not 'nrow`)... but my suspicion is that I am blind to the downstream consequences of conceptually thinking of a `DataFrameRow` as a single row of multiple columns.

**Comment by bkamins** [comment]
I think we could add a fallback with an error pointing the user to use `length` instead of `ncol`.

Regarding your concerns. An intuitive understanding of a column is that it arranges data vertically. In this sense `DataFrameRow` has always one column and as many rows as there are fields. So technically `DataFrameRow` `dfr` has 1 column and `length(dfr)` rows.

Indeed we display it differently, but it is only because it is more convenient to display it horizontally.

**Comment by alex-s-gardner** [comment]
@bkamins I think all of this is a bit unintuitive. If  `DataFrameRow` has one column and it was extracted as a single row from the data frame then this operation essentially equates to a `transpose` of the row. I get that this has more to do with the internals of the operation but it does require the user to understand the mechanics than to rely on their intuition of row and column structures. It seems to me that in data frame space `ncol` should return the length of the dfr.

**Comment by bkamins** [comment]
This is unrelated to internal representation. It is a decision on conceptual level. Dropping one index drops one dimension.

There is a difference between dataframe with one row and a plain row. Consider the following example with matrices (which is equivalent to our discussion:

```
julia> mat = [1 2 3; 4 5 6]
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> size(mat) # two dimensions: 2 rows, 3 columns
(2, 3)

julia> row = mat[1, :] # selecting a row of a matrix
3-element Vector{Int64}:
 1
 2
 3

julia> size(row) # dimension dropped, 3 rows, 1 (implicit) column
(3,)

julia> mat1 = mat[1:1, :] # selecting a matrix having one row
1×3 Matrix{Int64}:
 1  2  3

julia> size(mat1) # dimension not dropped, 1 row, 3 columns
(1, 3)
```

**Comment by alex-s-gardner** [comment]
@bkaminsThanks for the explanations as to why the decision was made.   I get the logic but it does seem counterintuitive that a row slice has no columns but multiple rows. I guess it makes sense to me for a matrix since we're going from a Matrix to a vector... but for DataFrames we explicitly keep the row-column convention in the Type name `DataFrameRow`. This would be akin to calling a row-slice of a matrix a "HorizontalArray" that would contain a vertical vector. 

But I can see the compromise that was made in trying to have consistency with base julia. Thanks again.
