### ISSUE TITLE
error when unique! a empty dataframe

### ISSUE THREAD

**Issue by 1991jhf** [JuliaData/DataFrames.jl#3392]
I get inexact error trunc(Int64,Inf) when unique! an empty dataframes.

It track down to

function row_group_slots!(
...
    # if there are few rows per group limit the number of threads used
    nt = clamp(round(Int, (lg / 4) / ngroups - 2), 1, nt)
...

when ngroups=0.
However i cannot reproduce this in a minimal example.
Is it possible to short-circuit the unique! when the dataframe is empty?

Thank you

**Comment by bkamins** [comment]
fixed in #3393
