### ISSUE TITLE
Inconsistent Mean Calculation in Grouped DataFrame Compared to Overall DataFrame

### ISSUE THREAD

**Issue by sjkelly** [JuliaData/DataFrames.jl#3405]
We've encountered an inconsistency in DataFrames.jl related to calculating means on `GroupedDataFrames`, specifically with `Float32` data. The issue results in different mean values when calculated on a `GroupedDataFrame` compared to a `DataFrame`, which could lead to significant discrepancies in data analysis.

**MWE:**

```julia
using DataFrames
using Distributions
using Random

rng = MersenneTwister(630);

df = DataFrame(values = rand(rng, Normal(zero(Float32), one(Float32)), 1000), label = ones(Int, 1000));
grouped_mean = combine(groupby(df, :label), :values => mean => :mean).mean
ungrouped_mean = combine(df, :values => mean => :mean).mean

# The means are expected to be approximately equal, but they are not
@assert grouped_mean ≈ ungrouped_mean # This assertion fails
```

**Expected Behavior:**

The mean calculated on a `GroupedDataFrame` should be approximately the same as the mean calculated on an ungrouped `DataFrame`.

**Possible Relation to Other Issues:**

This issue seems to be related to a previously reported issue in the Julia repository: [JuliaLang/julia#28848](https://github.com/JuliaLang/julia/issues/28848). A similar example has been added to that thread.

**Comment by bkamins** [comment]
The behavior follows Julia Base behavior:

```
julia> Random.seed!(1);

julia> x = rand(Float32, 10^6);

julia> mean(x)
0.49974534f0

julia> mean(@view x[:])
0.49974534f0

julia> mean(@view x[collect(1:end)])
0.49974778f0

julia> x = rand(Float16, 10^6);

julia> mean(x)
NaN16

julia> mean(@view x[:])
NaN16

julia> mean(@view x[collect(1:end)])
Float16(0.0)
```

**Comment by sjkelly** [comment]
Thanks! I have reported this here: https://github.com/JuliaLang/julia/issues/52457
