### ISSUE TITLE
`DataFrame(x=Int[], y=Int)`

### ISSUE THREAD

**Issue by jariji** [JuliaData/DataFrames.jl#3414]
Shouldn't this be `DimensionMismatch`?

```jl

julia> DataFrame(x=Int[], y=Int)
0×2 DataFrame
 Row │ x      y        
     │ Int64  DataType 
─────┴─────────────────
```

Inspired by https://discourse.julialang.org/t/column-types-in-dataframes/108532

**Comment by bkamins** [comment]
You mean that if all passed vectors have length 0 then also passing non-vector values should error?

Indeed this is what R does.

**Comment by jariji** [comment]
I guess the result is harder to understand because the constructor uses implicit broadcasting, but if I think about it in terms of normal broadcasting rules there's no real reason for this to error. So maybe it's okay.
