### ISSUE TITLE
DataFrame(t::Table) converts PooledVector columns

### ISSUE THREAD

**Issue by behinger** [JuliaData/DataFrames.jl#3436]
potentially related to #3432 

```julia
using PooledArrays
using TypedTables
using DataFrames
t = Table(b = PooledArray([2,3,1]),a=PooledArray([1,2,3]))

DataFrame(t).a # returns Vector
DataFrame(columns(t)).a # returns PooledVector
```
I expected the DataFrame constructor to keep the Vector type intact. Not really sure why the `columns` helps that much - I dont understand the Tables.jl interface on that level.

Maybe this report helps someone, for me the solution with columns is fine

**Comment by bkamins** [comment]
The reason is that `t` to the "outside world" communicates that it is an iterator of rows, so `DataFrame` constructs a vectors from these rows.

**Comment by behinger** [comment]
ah I see, that makes sense. Thanks!!
