### ISSUE TITLE
Add Tidier.jl to docs/src/man/querying_frameworks.md

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#3446]
It would be nice to include Tidier.jl in the comparison of data manipulation frameworks [documentation](https://dataframes.juliadata.org/latest/man/querying_frameworks/), especially since [dplyr](https://dplyr.tidyverse.org/) is already linked at the top. I've not used Tidier.jl myself, but it seems to be quickly gaining popularity.

**Comment by bkamins** [comment]
Agreed

**Comment by bkamins** [comment]
Done
