### ISSUE TITLE
[POSSIBLE REGRESSION] DataFrames.jl Currently Failing on Nightly?

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaData/DataFrames.jl#3467]
Hello DataFrames.jl maintainers,

@jay-sanjay and I were working recently with DataFrames.jl and noticed a failing test suite within our CI pipeline. After scrutinizing the test suite, we realized that the suite was failing due to an error in DataFrames.jl on nightly. Here is some information about this problem -- has the been seen before and/or fixed yet?

**Version of DataFrames.jl:** v1.6.1
**Version of Julia:** Julia Version 1.12.0-DEV.1207
**Nightly Commit from Julia:** https://github.com/JuliaLang/julia/commit/4633607ce9b9f077f32f89f09a136e04389bbac2
**Build Architectures That Are Failing:** Windows-latest, Ubuntu-latest

Where the error occurred in our CI pipeline: https://github.com/JuliaHealth/OMOPCDMPathways.jl/actions/runs/10873471645/job/30169617952?pr=63#step:6:260

Error message in pipeline:

<details>
<summary>Copied Partial Error Message from CI Runner</summary>

```julia-repl
ERROR: LoadError: The following 3 direct dependencies failed to precompile:

DataFrames --code-coverage=@/home/runner/work/OMOPCDMPathways.jl/OMOPCDMPathways.jl --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=yes --inline=yes --startup-file=no --track-allocation=none --check-bounds=yes --compiled-modules=yes 

Failed to precompile DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0] to "/home/runner/.julia/compiled/v1.12/DataFrames/jl_umGyjP".
WARNING: Method definition formatdoc(Base.Docs.DocStr) in module REPL at /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/REPL/src/docview.jl:79 overwritten in module REPL at /cache/build/builder-amdci4-7/julialang/julia-master/usr/share/julia/stdlib/v1.12/REPL/src/docview.jl:79.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Error: Unexpected error (Review REPL precompilation with debug_output on):
│ 2004lERROR: Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
└ @ REPL.Precompile /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/REPL/src/precompile.jl:26
ERROR: LoadError: Failed to precompile REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] to "/home/runner/.julia/compiled/v1.12/REPL/jl_koUDLw".
```

</details>

**Comment by pdeffebach** [comment]
This should be fixed on master, #3459 removes the REPL dependency, which was causing precompilation issues.

**Comment by bkamins** [comment]
Is nightly working for you @TheCedarPrince ?

I plan to make a release soon.

**Comment by TheCedarPrince** [comment]
Hey @bkamins and @pdeffebach, as of testing on https://github.com/JuliaLang/julia/commit/44bef0df7a115334c10abac88aeba333b12cce2d, DataFrames.jl is back working again! Quickfix on the Julia side then!

**Comment by bkamins** [comment]
Thank you!
