### ISSUE TITLE
How to Get the DataFrames 1.7.0 User Manual in PDF

### ISSUE THREAD

**Issue by Jigyasu4indp** [JuliaData/DataFrames.jl#3471]
How can I get the user manual for the DataFrames.jl version 1.7.0 in PDF format, similar to the data.table package in R? Please provide a link or instructions on how to download it.

**Comment by bkamins** [comment]
We do not maintain PDF version of the manual as it was not very readable. If you wanted you could generate it using these instructions https://discourse.julialang.org/t/how-to-export-the-documentation-of-a-julia-package-to-pdf/115683/4
