### ISSUE TITLE
Metadata for columns and/or DataFrames

### ISSUE THREAD

**Issue by tshort** [JuliaData/DataFrames.jl#35]
Should we leave room for metadata on structures? Frank Harrell's Hmisc package allows units and labels to be attached to data.frame columns. 

People may want to attach other metadata like experimenter name or a DataFrame comment.

We could add a meta Dict to the DataFrame, the colindex, and/or at the DataVec level.

**Comment by quinnj** [comment]
Do we really want arbitrary metadata in the type? Seems like there are generally other ways to include metadata about your DataFrame w/o stuffing it into the type itself.

**Comment by nalimilan** [comment]
I think we something like that would be useful, even if that's not the highest priority. How could you store metadata about columns without support in `DataFrame` itself?

**Comment by pdeffebach** [comment]
I agree with the above. If the goal is to have easy plotting (automatic labels), and easy table creation, forcing a long list of packages to interact with a third labeling package would be far more difficult to maintain than incorporating metadata into dataframes.

**Comment by bkamins** [comment]
Closed with #3055
