### ISSUE TITLE
DOC: comparison between Datafeames.jl, pandas, and r data.fame objects

### ISSUE THREAD

**Issue by sglyon** [JuliaData/DataFrames.jl#392]
It seems like a lot of the functionality of this package is inspired by things in R data.frames or pandas. I think more users would be willing to give this package a try if in the documentation there was a section on the differences between dataframes and the others. Maybe even a table serving as a sort of cross reference between the three and how to perform common routines using each language.

This is somewhat reminiscent of the section on notable differences between julia and matlab, R, and python from the julia documentation and the old blog post about R and julia syntax from @johnmyleswhite .

**Comment by quinnj** [comment]
I'm not sure there's enough interest in this; anyone feel free to re-open if still desired.

**Comment by nalimilan** [comment]
I think that would be useful, and the number of comments by different people seems to confirm this.

**Comment by bkamins** [comment]
Closing this as we will soon have this (we already have it for dplyr and Stata)

**Comment by nalimilan** [comment]
Almost 7 years later at last! :-)

**Comment by bkamins** [comment]
Well - I would say that we are now finally ready for this 😄.

Just need to finish #2340 and I am ready for PyData Global 2020 tutorial how to port from pandas to DataFrames.jl that is upcoming in November this year.
