### ISSUE TITLE
Ideas for better static type inference

### ISSUE THREAD

**Issue by simonster** [JuliaData/DataFrames.jl#451]
I had a discussion with @malmaud today about type inference for DataFrames. The core problem is that when you index into a DataFrame, under the hood, we index into a `Vector{Any}` and so you get no type information about the result. Thus, if you want to iterate over one or more columns of a DataFrame, the only reasonably performant way to do so is to first pull out the columns with typeasserts (or pass them to a function) and then iterate over these columns, which is not really idiomatic.

Part of one potential solution would be to make the columns of a DataFrame a tuple instead of a `Vector{Any}`, and to parametrize the DataFrame by the type of this tuple. Then we'd have type information for the columns if referenced by index, and we'd at least have a type union for indexing by a string. The downside to this approach is that we wouldn't be able to add columns to an existing DataFrame, only create new DataFrames with more columns or re-ordered columns. Syntax like `df["newcol"] = x` wouldn't work.

This could make code that indexes a DataFrame as `df[i, 1]` nearly as fast as indexing a corresponding Array. However, ideally code that indexes a DataFrame as `df[i, "mycol"]` would also be as fast as indexing an Array. This doesn't seem to be possible without changes in Base. We'd have to push the process of looking up the column name in the Index to type inference time, so that 1) we don't have to perform the look up on each loop iteration and 2) type inference has information about the type of the column. We'd either need a way to hook into the type inference process or some kind of "named tuple" primitive that has type information for each member like a tuple but can be indexed with strings.

**Comment by nalimilan** [comment]
Closing in favor of https://github.com/JuliaData/DataFrames.jl/issues/1335.
