### ISSUE TITLE
Never print more characters from a field than fits on screen

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#460]
Right now a very long field will render in an unreadable way when calling `show(adf)` because we always print the whole field. If a field is longer than the number of characters available on screen, it should be truncated and an ellipsis printed out.

**Comment by quinnj** [comment]
Still relevant. I'l also note that we sometimes get some weirdness when showing fields that have unicode or control characters, which would probably not be too hard to handle at the same time.

**Comment by cjprybol** [comment]
Dup of https://github.com/JuliaData/DataFrames.jl/issues/760, which has been addressed
