### ISSUE TITLE
How should isequal work?

### ISSUE THREAD

**Issue by garborg** [JuliaData/DataFrames.jl#467]
This doesn't seem true to me: `isequal(DataFrame(p = @pdata(1:3)), DataFrame(d = @data(1:3)))`.

Should either of these be true?:
`isequal(DataFrame(d = @pdata(1:3)), DataFrame(d = @data(1:3)))`
`isequal(DataFrame(p = @data(1:3)), DataFrame(d = @data(1:3)))`

I opened a related issue: JuliaStats/DataArrays.jl#46

**Comment by quinnj** [comment]
Rendered irrelevant by switch to CategoricalArrays.jl

**Comment by nalimilan** [comment]
But there's also the question of how to handle the column names and order, right?

**Comment by quinnj** [comment]
I don't know; my natural inclination is that column names/order _would_ matter. I could _maybe_ get behind column _order_ not mattering, but I think it's just simpler overall to require names/order to match.

**Comment by garborg** [comment]
Definitely on the same page that column names matter.

Re: order, it'd be kind of nice if we didn't have integer indexing of columns in the public api, but since `df[1]` is still a thing, I guess our hands are tied -- I'd expect for two indexable isequal collections, that indexing into both returns isequal elements.

**Comment by nalimilan** [comment]
I think the consensus is that column names and their order should matter, as is currently the case.
