### ISSUE TITLE
A proposed select() that could achieve high-performance

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#504]
I've thought a lot about getting delayed evaluation like semantics in a sane way lately since I know that people really want them.

So I'd like to propose that we take SQL's lead when we return to those tricks and use the following ideas:

(1) Maintain a proper DSL that's passed in as strings. For precedent, see [Pandas' experimental eval function](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.eval.html).

(2) Interact with variables in the calling scope using placeholders: `query("select * from df where colA > ?", a)`.

We can make this sort of thing blaze if we adopt the `prepare`/`exec` distinction that most RDBMS's offer, where `prepare` compiles the clause and `exec` substitutes values for placeholders in tight loops.

I don't intend to work on this for a long time, but I think this proposal is truly viable. It involves writing some proper parsing code, but removes all the crazy mixed scope issues that made expression indexing hard.

**Comment by nalimilan** [comment]
We have DataFramesMeta now.
