### ISSUE TITLE
Generic performance problems

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#523]
The example below does a good job of capturing where our current interface is making things excessively difficult for type-inference to do its work:

```
using DataArrays, DataFrames

srand(1)
n = 5_000_000
a = rand(n)
b = rand(n)
da = data(a)
db = data(b)
df = DataFrame(a = da, b = db)

Base.values(da::DataArray) = da.data

function dot1(a::Vector, b::Vector)
    x = 0.0
    for i in 1:length(a)
        x += a[i] * b[i]
    end
    return x
end

function dot2(da::DataVector, db::DataVector)
    T = eltype(da)
    x = 0.0
    for i in 1:length(da)
        x += da[i]::T * db[i]::T
    end
    return x
end

function dot3(df::DataFrame)
    da, db = df[:a], df[:b]
    T = eltype(da)
    x = 0.0
    for i in 1:length(da)
        x += da[i]::T * db[i]::T
    end
    return x
end

function dot4(df::DataFrame)
    da, db = df[:a], df[:b]
    return dot2(da, db)
end

function dot5(da::DataVector, db::DataVector)
    x = 0.0
    for i in 1:length(da)
        x += da.data[i] * db.data[i]
    end
    return x
end

function dot6(da::DataVector, db::DataVector)
    x = 0.0
    for i in 1:length(da)
        x += values(da)[i] * values(db)[i]
    end
    return x
end

function dot7(da::DataVector, db::DataVector)
    x = 0.0
    for i in 1:length(da)
        if !(isna(da, i) || isna(da, i))
            x += values(da)[i] * values(db)[i]
        end
    end
    return x
end

function dot8(a::Vector, b::Vector)
    x = 0.0
    for i in 1:length(a)
        if !(isnan(a[i]) || isnan(a[i]))
            x += a[i] * b[i]
        end
    end
    return x
end

t1 = @elapsed dot1(a, b)
t2 = @elapsed dot2(da, db)
t3 = @elapsed dot3(df)
t4 = @elapsed dot4(df)
t5 = @elapsed dot5(da, db)
t6 = @elapsed dot6(da, db)
t7 = @elapsed dot7(da, db)
t8 = @elapsed dot8(a, b)

t1 = @elapsed dot1(a, b)
t2 = @elapsed dot2(da, db)
t3 = @elapsed dot3(df)
t4 = @elapsed dot4(df)
t5 = @elapsed dot5(da, db)
t6 = @elapsed dot6(da, db)
t7 = @elapsed dot7(da, db)
t8 = @elapsed dot8(a, b)

t1 = @elapsed dot1(a, b)
t2 = @elapsed dot2(da, db)
t3 = @elapsed dot3(df)
t4 = @elapsed dot4(df)
t5 = @elapsed dot5(da, db)
t6 = @elapsed dot6(da, db)
t7 = @elapsed dot7(da, db)
t8 = @elapsed dot8(a, b)

@printf "Vectors: %f\n" t1
@printf "DataVectors: %f\n" t2
@printf "DataVectors in DataFrame: %f\n" t3
@printf "DataVectors in DataFrame w/ Indirection: %f\n" t4
@printf "DataVectors w/ unsafe access: %f\n" t5
@printf "DataVectors w/ safish access: %f\n" t6
@printf "DataVectors w/ branch costs: %f\n" t7
@printf "Vectors w/ branch costs: %f\n" t8
```

This gives the following results, which are pretty representative of other runs on my laptop:
- Vectors: 0.008418
- DataVectors: 0.221481
- DataVectors in DataFrame: 1.747264
- DataVectors in DataFrame w/ Indirection: 0.214700
- DataVectors w/ unsafe access: 0.008278
- DataVectors w/ safish access: 0.007597
- DataVectors w/ branch costs: 0.039523
- Vectors w/ branch costs: 0.011451

Until we come up with something better, we might want to embrace the element-wise `isna` function I added as well as something like the `values` function I've defined here. (Which, like `isna`, was an idea that Tim Holy proposed.) That would at least get us to a sane place when using DataArrays.

If we follow my proposal to implement categorical data using an enum-type stored in a DataArray, we only need to optimize the performance of DataArrays going forward.

That still leaves a question above how to optimize the DataFrames case. Needing to introduce indirection to get proper type inference and good performance isn't a great long-term strategy.

**Comment by quinnj** [comment]
It would be valuable to re-run some of the original benchmarks here w/ the transition from DataArray to Vector{T}/Vector{Union{T, Null}}, particularly on 0.7 current master (9/7/2017) where performance optimizations have been implemented for Vector{Union{T, Null}} where `isbits(T) == true`.
