### ISSUE TITLE
Indexing and time series

### ISSUE THREAD

**Issue by filmackay** [JuliaData/DataFrames.jl#532]
Eagerly awaiting the indexing additions in the (hopefully) near future. How similar to Pandas will this implementation be?

Interested to see how this will intersect with time series functionality - will this just be left to `TimeSeries.jl` - or will there be embedded capability in `DataFrames.jl`? I found the Pandas model a bit restrictive - a single index column being a timestamp. It would be nice to have a bit more flexibility - such as multi-level indices that can use a time index amongst others.

**Comment by tbonza** [comment]
Just ran into this issue and resolved it with the following code:

```
hmm = filter(mydf) do x
    x.firstResponseDtYMD >= Date(2019,1,1) && x.firstResponseDtYMD < Date(2019,4,1)
end
size(hmm)
```

Do we agree that this is a reasonable approach? If so, how would you recommend including it? I'm new to Julia (v1.1); coming from Python

**Comment by bkamins** [comment]
You can also write:
```
hmm = filter(mydf) do x
    Date(2019,1,1) <= x.firstResponseDtYMD < Date(2019,4,1)
end
```
which is a bit shorter.

A more efficient code - if you would be in a performance critical part of code would be:
```
hmm = mydf[Date(2019,1,1) .<= x.firstResponseDtYMD .< Date(2019,4,1), :]
```
