### ISSUE TITLE
Codifying DataFrame design patterns

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#535]
In the past week, both @garborg and I implemented very similar functionality for working with the Cartesian product of vectors. See, #531 and https://github.com/johnmyleswhite/DataFrameUtils.jl/blob/master/test/DataFrameUtils.jl for two ways of working with the Cartesian product of vectors:
- Generate the product and store it in a DataFrame
- Generate the product, apply a function and store both product and function value in a DataFrame

In addition, the Iterators.jl package implements a `product` function that provides the Cartesian product as an iterable. One could therefore implement Cartesian product -> DataFrame in terms of a `collect2df` function and the existing `product` function.

In general, I suspect there's a small set of primitives like `collect2df` that would get us very far.

**Comment by quinnj** [comment]
Is this still desired?
