### ISSUE TITLE
Printing dataframe doesn't calculate col width correctly with escaped charaters

### ISSUE THREAD

**Issue by GlenHertz** [JuliaData/DataFrames.jl#551]
Hi,

I have a DF with a "$" that is in the CSV file and its column widths are not calculated correctly because Julia prints out "$" as "\$"...so the column is 1 character too narrow.  For example, `DataFrame(A=["\$4","spoon"], B=["cash", "kitchen"])` prints out as:

```
2x2 DataFrame
|-------|---------|-----------|
| Row # | A       | B         | 
| 1     | "\$4"    | "cash"    | # wider
| 2     | "spoon" | "kitchen" |
```

Not a big deal but I thought I would report it.

Glen

**Comment by cjprybol** [comment]
Fixed by @bkamins in https://github.com/JuliaData/DataFrames.jl/pull/1237
