### ISSUE TITLE
Provide convertion from dictionary to DataFrames

### ISSUE THREAD

**Issue by rominf** [JuliaData/DataFrames.jl#591]
Sometimes it's convenient to work with Arrays that starts from the zero (or from any other index).

I can use `OrderedDict` to achieve Array-like structures. The problem is that printing dictionaries is still ugly (https://github.com/JuliaLang/julia/issues/1759). But `DataFrames` give me better printing. I want to be able to convert `Dict` (or `OrderedDict`) to the `DataFrames` in one command.

This code works fine for me but I don't know whether is good or not and where should I put it (in the DataFrames or in the DataStructures code?)

``` julia
import Base.convert
function convert{K, V}(::Type{DataFrame}, d::Associative{K, V})
    DataFrame(collect(keys(d)), collect(values(d)))
end
```

or (I saw somewhere that `DataFrame` constructor without column names is deprecated):

``` julia
import Base.convert
function convert{K, V}(::Type{DataFrame}, d::Associative{K, V})
    DataFrame(keys=collect(keys(d)), values=collect(values(d)))
end
```

Example of usage:

``` julia
od = OrderedDict()
od[1] = 1.0
od[1.1] = 2.1
convert(DataFrame, od)
```

Output:

```
    x1  x2
1   1   1.0
2   1.1 2.1
```

UPD: I want to use `Dict` instead of `Array` because I want to be able to do those kind of stuff:

``` julia
od[1.5] = 42.0  # for storing values of non analytic function with one argument
```

or

``` julia
# Array like structure with negative indeces
od = OrderedDict()
for i = -5:5
    od[i] = 2*i
end
```

**Comment by NaelsonDouglas** [comment]
> function createdataframe(input::Dict)  
>   parsedinput = Dict()
>   for x in keys(input)
>     parsedinput[Symbol(x)] = [input[x]]
>   end
>   return DataFrame(parsedinput)
> end
