### ISSUE TITLE
Allow to hide row numbers

### ISSUE THREAD

**Issue by rominf** [JuliaData/DataFrames.jl#592]
Sometimes I don't need row numbers because I have my own numeration (see UPD in https://github.com/JuliaStats/DataFrames.jl/issues/591) as one of the columns, in this case row numbering only clutters.

**Comment by jayvn** [comment]
Any progress on this one ?

**Comment by bkamins** [comment]
@ronisbr - is this configurable in PrettyTables.jl? (i.e. can we disable printing row?)

**Comment by ronisbr** [comment]
Yes! Just pass the option `show_row_number = false`.

**Comment by bkamins** [comment]
Great! (probably a feature to show in the manual)
