### ISSUE TITLE
delete a row

### ISSUE THREAD

**Issue by XilinJia** [JuliaData/DataFrames.jl#595]
How can I do it?  I found deleterows, but it is not exported.  And the argument to deleterows is not straightforward - requiring rows to keep instead of rows to delete.  Can I have something simply like: deleterows(df, 3), which 3 is the row to delete?

**Comment by sylvaticus** [comment]
For those reading this with modern versions of Julia, the @milktrader approach is now:
`df[[1:2; 4:end],:]`

**Comment by Madhuri97** [comment]
Write the line of code to permanently delete rows three, five, nine from a DataFrame with the name df? 
can anyone tell what will be the answer?

**Comment by sylvaticus** [comment]
@Madhuri97 First congratulations for having reached this issue. You are close to obtain your answer, but this seems an exam question and the precise final answer to the specific question should be you to provide it. Good luck!

**Comment by Madhuri97** [comment]
> @Madhuri97 First congratulations for having reached this issue. You are close to obtain your answer, but this seems an exam question and the precise final answer to the specific question should be you to provide it. Good luck!

Yes, this is an exam question which I have attempted using many syntaxes but still, this shows error

My answer: 
df.deleterows!([3,5,9])
deleterows!(df,[3,5,9])
deleterows([3,5,9])

error Message: Make use of the bang form of the function and pass the row numbers as an array (inside the square bracket, separated by commas). Do not include any spaces in the code.

**Comment by bkamins** [comment]
@Madhuri97 the correct answer is:

if you want to do it in place:
```
delete!(df, [3,5,9])
```

if you want a new data frame:
```
df[Not[3,5,9], :]
```

if you want a view:
```
view(df, Not[3,5,9], :)
```

**Comment by Madhuri97** [comment]
> @Madhuri97 the correct answer is:
> 
> if you want to do it in place:
> 
> ```
> delete!(df, [3,5,9])
> ```
> 
> if you want a new data frame:
> 
> ```
> df[Not([3,5,9]), :]
> ```
> 
> if you want a view:
> 
> ```
> view(df, Not([3,5,9]), :)
> ```

Thank you very much it worked
