### ISSUE TITLE
Output format of reshape functions

### ISSUE THREAD

**Issue by garborg** [JuliaData/DataFrames.jl#645]
@tshort I got familiar with the reshape functions in #644, and had a couple questions about the output format:
1) Placing the id vars to the right of the measure vars -- seemed the opposite of what I'd used elsewhere -- what's the rationale?
2) Trivial: lowercase `variable` and `value` -- are they just from before the uppercasing idiom took hold, or is it a reducing clashes / purposely stand out thing?

```
julia> d = dataset("reshape2", "smiths")
julia> melt(d, [:Subject, :Time], [:Age, :Weight, :Height])
6x4 DataFrame
|-------|----------|-------|--------------|------|
| Row # | variable | value | Subject      | Time |
| 1     | Age      | 33.0  | "John Smith" | 1    |
| 2     | Age      | NA    | "Mary Smith" | 1    |
| 3     | Weight   | 90.0  | "John Smith" | 1    |
| 4     | Weight   | NA    | "Mary Smith" | 1    |
| 5     | Height   | 1.87  | "John Smith" | 1    |
| 6     | Height   | 1.54  | "Mary Smith" | 1    |
```

**Comment by bkamins** [comment]
We need to decide on this before 1.0 release

**Comment by bkamins** [comment]
@nalimilan - I would close it. These changes would be breaking and do not improve things significantly enough to justify it I think.

**Comment by nalimilan** [comment]
Maybe let's just add columns to the end instead of the beginning? That's what the tidyverse (both reshape2 and tidyr) and Pandas do, and it shouldn't break a lot of code anyway since names are more common to use than positions.

**Comment by bkamins** [comment]
So we switch to: id, variable, value order?

**Comment by bkamins** [comment]
If yes I will implement this after https://github.com/JuliaData/DataFrames.jl/pull/2140 is merged (because a lot of documentation will get updated)

**Comment by nalimilan** [comment]
Yes that sounds like the common order.
