### ISSUE TITLE
writecsv() issues

### ISSUE THREAD

**Issue by felixjung** [JuliaData/DataFrames.jl#727]
Hi I'm writing some data frames to disk using `writecsv()`. It works, but I get a deprecation warning:

```
julia> writecsv("../Tests/$intensity_type-dns-r-squared.csv", r2_stats)
WARNING: Default AbstractDataFrame iterator is deprecated, use eachcol(::AbstractDataFrame) instead
 in writedlm at datafmt.jl:535
 in anonymous at datafmt.jl:550
 in open at iostream.jl:137
 in writedlm at datafmt.jl:549
 in writecsv at datafmt.jl:555
```

Since this is a very simple call, I assume some code needs to be updated?

Best,

Felix

**Comment by maximsch2** [comment]
Is there a reason why we don't want `writecsv` to work on DataFrames as well?
We can have `writecsv(io, df::DataFrame) = writeable(io, df)`, no?

**Comment by johnmyleswhite** [comment]
I tend to dislike introducing strict aliasing since it, by definition, has no semantic value -- it's literally just a second name for something that should, ideally, have only one name.

**Comment by maximsch2** [comment]
I guess there is a point to that. How about something like this then:
```julia
writecsv(io, df::DataFrame) = error("Use writetable instead of writecsv to output a DataFrame")
```

**Comment by johnmyleswhite** [comment]
Sure, that works.

**Comment by nalimilan** [comment]
@maximsch2 Sounds like a good idea. Would you make a pull request to add this error message to `writecsv` and `writedlm` (with a test)?

I think we should change Julia Base to have a single function which would (like `readtable`) choose the separator based on the extension. That way, data frames could use the same function.
